### ISSUE TITLE
How to develop on this repo? (structural issue)

### ISSUE THREAD

**Issue by apsears** [TensorSpeech/TensorflowTTS#100]
Hi, this seems like a silly question, but what is the process for developing on a repo with this structure? It is very unlike others.

If I edit a file, say, tensorflow_tts/processor/ljspeech.py, the edits are not functional until I reinstall using "pip install --upgrade ."

Is there an easier way I'm missing? What would you call this structure?

[Edit: it was a silly question. You just work from the tensorflow_tts internal folder]

**Comment by dathudeptrai** [comment]
@apsears you can git clone and use 
```
pip install -e . 
```
Then u can modify tensorflow_tts folder :D without re-install
