### ISSUE TITLE
 NameError: name 'alignment_history' is not defined

### ISSUE THREAD

**Issue by MODAK27** [TensorSpeech/TensorflowTTS#106]
On running the End-2-End demo on colab Tacotron 2 model gets an error
NameError                                 Traceback (most recent call last)
<ipython-input-14-4e6782468b4a> in <module>()
----> 1 mels, alignment_history, audios = do_synthesis(input_text, tacotron2, melgan, "TACOTRON", "MELGAN")
      2 visualize_attention(alignment_history[0])
      3 visualize_mel_spectrogram(mels[0])
      4 ipd.Audio(audios, rate=22050)

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

NameError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_tts/models/tacotron2.py:910 inference  *
        return decoder_output, mel_outputs, stop_token_prediction, alignment_history

**Comment by dathudeptrai** [comment]
@MODAK27 fixed :))
