### ISSUE TITLE
Error when training fastspeech2

### ISSUE THREAD

**Issue by linhld0811** [TensorSpeech/TensorflowTTS#108]
After training some iteration, i get this 

> error:tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  ConcatOp : Dimensions of inputs should match: shape[0] = [2,1139,384] vs. shape[1] = [1,1140,384]
         [[{{node tf_fast_speech2/length_regulator/while/body/_1/concat}}]]
         [[tf_fast_speech2/mul_2/_160]]
  (1) Invalid argument:  ConcatOp : Dimensions of inputs should match: shape[0] = [2,1139,384] vs. shape[1] = [1,1140,384]
         [[{{node tf_fast_speech2/length_regulator/while/body/_1/concat}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference__one_step_fastspeech2_131786]

Anyone can help me to fix this error?! Thanks!

**Comment by l4zyf9x** [comment]
Following my guess, your dataset has some samples with total duration different from mel length, so when repeating it up, it does not match real Mel-spectrogram. You should check over your dataset and ensure that all samples have total duration equal to mel length.
