### ISSUE TITLE
FastSpeech2 saved_model fails

### ISSUE THREAD

**Issue by sujeendran** [TensorSpeech/TensorflowTTS#109]
Hi @dathudeptrai,
I am trying to save fastspeech2 same as fastspeech and it always fails.
Here is my code:
![image](https://user-images.githubusercontent.com/30560413/87169883-e178d500-c2d0-11ea-9baf-cfe3f3f2d794.png)

And this is the error I'm getting:
![image](https://user-images.githubusercontent.com/30560413/87170061-2270e980-c2d1-11ea-89bc-47705b531d26.png)

I tried passing a concrete function with arguments too. Still can't get it done. I faced similar issue when working on newer versions of tensorflow. But I am using tf2.2 now and I am able to save fs1. Only issue is with FastSpeech2

**Comment by dathudeptrai** [comment]
@sujeendran fix #109
