### ISSUE TITLE
preprocess question

### ISSUE THREAD

**Issue by unparalleled-ysj** [TensorSpeech/TensorflowTTS#110]
After I modify the preprocessing process, do I need to reinstall TensorflowTTS?

**Comment by dathudeptrai** [comment]
@unparalleled-ysj you can use:
```
pip install -e .
```
so you can edit everything without re-install.

**Comment by unparalleled-ysj** [comment]
> @unparalleled-ysj you can use:
> 
> ```
> pip install -e .
> ```
> 
> so you can edit everything without re-install.

Thanks
