### ISSUE TITLE
Does TFLite support on-device training?

### ISSUE THREAD

**Issue by jun-danieloh** [TensorSpeech/TensorflowTTS#111]
I just noticed that TFLite colab was released so am trying to follow that. Is on-device training also possible with TFLite?

**Comment by dathudeptrai** [comment]
@jun-danieloh you mean training on mobile or training to optimize for mobile ?

**Comment by jun-danieloh** [comment]
@dathudeptrai training on mobile!

**Comment by dathudeptrai** [comment]
@jun-danieloh not yet i think :)). it's very hard :v. I don't think in the near future tflite can support this :))

**Comment by dathudeptrai** [comment]
feel free to re-open :))
