### ISSUE TITLE
[Run melgan.stft] TypeError: Unexpected keyword argument passed to optimizer: lr_fn

### ISSUE THREAD

**Issue by ZhaoZeqing** [TensorSpeech/TensorflowTTS#114]
My environment:

- Tensorflow 2.2.0
- cuda 10.1
- cudnn 7.6.4

When I run **melgan.stft** with own 22.05k dataset, all conf files are same to LJSpeech, this error occurred:

Traceback (most recent call last):
  File "examples/melgan/train_melgan.py", line 628, in <module>
    main()
  File "examples/melgan/train_melgan.py", line 608, in main
    gen_optimizer=tf.keras.optimizers.Adam(**config["generator_optimizer_params"]),
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/adam.py", line 144, in __init__
    super(Adam, self).__init__(name, **kwargs)
  File "anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 269, in __init__
    "passed to optimizer: " + str(k))
TypeError: Unexpected keyword argument passed to optimizer: lr_fn

**Comment by dathudeptrai** [comment]
@ZhaoZeqing seems u are running train_melgan script rather than train_melgan_stft :)

**Comment by ZhaoZeqing** [comment]
Oh!! Thanks! Maybe there is a mistake in README file of melgan.stft :D

Also puzzled about upsample_scale and downsample_scale in **multiband_melgan**, why need 8*4*2*4==hopsize? If [8 4 2] can be anything like [4 4 4] or [1 8 8] ?

**Comment by dathudeptrai** [comment]
@ZhaoZeqing we know that we use hop_size = 256, that mean 1 mel == 256 audio values (for example, if ur audio is = 8192 values (~8192/22050=0.37s) ->> len(mels) == 8192 / 256 = 32 frame.). For melgan/melgan.stft, we upsample the mel-spectrogram to 256x so we need upsample_scales = [8, 4, 2] (4, 4, 4 or 2, 4, 8 also ok). For multiband melgan, we have 4 subband, each subbands audio has length = 1/4 original audio so we just need to upsample 256/4 = 64 times.

**Comment by dathudeptrai** [comment]
fell free to re-open if you are still confuse :D

**Comment by ZhaoZeqing** [comment]
@dathudeptrai Many thanks! :)
