### ISSUE TITLE
Using model without Tensorflow or TensorflowTTS?

### ISSUE THREAD

**Issue by MegaPanchamZ** [TensorSpeech/TensorflowTTS#124]
Is it possible to output the trained model, into a form where it can be loaded without TensorFlow on the system? For example, using the model on a system without AVX instructions (Like an Intel Pentium or android system).

**Comment by machineko** [comment]
https://www.tensorflow.org/xla/tfcompile

**Comment by MegaPanchamZ** [comment]
> https://www.tensorflow.org/xla/tfcompile
> also
> https://tvm.apache.org/docs/tutorials/relay_quick_start.html

I understand that there are ways to compile the graph, but have no idea where to start. I am using a slightly modified version of the jupyter notebook.

Thanks for the help!

**Comment by dathudeptrai** [comment]
@MegaPanchamZ I don't know :D, i think atleast we need tensorflow dependency ?

**Comment by MegaPanchamZ** [comment]
Tensorflow models can be used on android (with a dependency) and that should be fine. My real problem is how? I don't understand much of what is going on. Really, I'm looking for some guidance.

**Comment by dathudeptrai** [comment]
@MegaPanchamZ see this PR https://github.com/TensorSpeech/TensorflowTTS/pull/123

**Comment by MegaPanchamZ** [comment]
Thank you so much. Just realised I am an actual spoon. The inference without TensorFlow begins with needing the .pb which you guys have graciously created notebooks for.
