### ISSUE TITLE
preprocess

### ISSUE THREAD

**Issue by yanglu1994** [TensorSpeech/TensorflowTTS#129]
hello, I am confused about where is the preprocess code?[tensorflow-tts-preprocess, tensorflow-tts-compute-statistics, tensorflow-tts-normalize]

tensorflow-tts-preprocess --rootdir ./datasets/ --outdir ./dump/ --conf preprocess/ljspeech_preprocess.yaml
tensorflow-tts-compute-statistics --rootdir ./dump/train/ --outdir ./dump --config preprocess/ljspeech_preprocess.yaml
tensorflow-tts-normalize --rootdir ./dump --outdir ./dump --stats ./dump/stats.npy --config preprocess/ljspeech_preprocess.yaml

**Comment by dathudeptrai** [comment]
all of them :v

**Comment by tekinek** [comment]
@yanglu1994  I did have same confusion I guess. They are here:
TensorflowTTS/tensorflow_tts/bin/
 -- preprocess.py 
 -- compute_statistics.py
 -- normalize.py

so you can run prepossessing this way too:
python tensorflow_tts/bin/preprocess.py --rootdir ./datasets/ --outdir ./dump/ --conf preprocess/ljspeech_preprocess.yaml
...

**Comment by yanglu1994** [comment]
OK, I see it ,think you!
