### ISSUE TITLE
NaNs in FS2 posnet

### ISSUE THREAD

**Issue by machineko** [TensorSpeech/TensorflowTTS#133]
So i've trained Fastespeech2 on my dataset using phones based on MFA extraction (pull request incoming later tomorrow).
But I meet weird NaNs in eval postnet after ~50k steps postnet is only producing nans. 
I'm not an expert using tensorflow (last 2.5 years i've use mainly pytorch) so I have question if it is possible that it's caused by fp16 training [later i'll train fp32 model to confirm this but it needs a lot more time] and how to do training more stable on fp16 (maybe some tricks how to debug nans in tensorflow)?

![image](https://user-images.githubusercontent.com/42299606/88171261-4dd3cc80-cc1f-11ea-8194-7beff286cc17.png)

![image](https://user-images.githubusercontent.com/42299606/88171965-888a3480-cc20-11ea-9a56-20abc6c49697.png)

**Comment by dathudeptrai** [comment]
@machineko mixed precision is still on experimental module of tensorflow so it is not stable yet. In my case it ălways fine in my private dataset and ljspeech. If you get nan, you can training float32, the training speed is still very fast even it is float32. You just need < 1 day to train fastspeech. But if you still want to use float16, you can try this trick: resume training float32 at the step you get nan for around 5k steps. Then resume again with float16 :))

**Comment by tekinek** [comment]
Same problem #125 with tacotron2 training at 53.5k steps (1080ti, tensorflow 2.2). Restart training from 50k solved my problem so far.

**Comment by machineko** [comment]
Sure I'll try both of ur solutions later and post updates here :)

**Comment by machineko** [comment]
It's looks like fp16 stability turning off and retraining on 32precision didn't have any nans problem. (probably we can fix it excluding some layers from fp16 training and i'll test it in next week)
