### ISSUE TITLE
no duration file error

### ISSUE THREAD

**Issue by yanglu1994** [TensorSpeech/TensorFlowTTS#135]
after  data preprocessing,  I run train_fastspeech2.py but there is no duration file in /dump/train

**Comment by dathudeptrai** [comment]
@yanglu1994 can you read the step 1 carefully :)). https://github.com/TensorSpeech/TensorflowTTS/tree/master/examples/fastspeech2#step-1-create-tensorflow-based-dataloader-tfdataset

**Comment by yanglu1994** [comment]
I need a pretrained tacotron2 model to extract duration for fastspeech?

> CUDA_VISIBLE_DEVICES=0 python examples/tacotron2/extract_duration.py \
  --rootdir ./dump/valid/ \
  --outdir ./dump/valid/durations/ \
  --checkpoint ./examples/tacotron2/exp/train.tracotron2.v1/checkpoints/model-65000.h5 \
  --use-norm 1 \
  --config ./examples/tacotron2/conf/tacotron2.v1.yaml \
  --batch-size 32
  --win-front 3 \
  --win-back 3

**Comment by dathudeptrai** [comment]
@yanglu1994 ofc, you need to train ur own tacotron-2 to extract Duration at the momement or u can use MFA to extract :v

**Comment by yanglu1994** [comment]
can you give me a example of duration file?
Does duration means the total time of wave file and every phoneme start and end time? there is a interval file in my data. like this.can I abstract duration directly from interval file?

> Filetype="ooTextFile"
Objectclass="TextGrid"
0
2.66
<exists>
1
"IntervalTier"
"000001.interval"
0
2.66
17
0
0.27958612055419324
"sil"
0.27958612055419324
0.406291189066745
"k"
0.406291189066745
0.5165142974475827
"a2"
...

Does the alignments file in this code is the same with your duration file?

`def process_utterance(in_dir, out_dir, basename):
    wav_path = os.path.join(in_dir, 'Wave', basename)
    seg_bn = basename.strip().split('.')[0]
    _tg_name = '{}.interval'.format(seg_bn)
    tg_path = os.path.join(in_dir, 'PhoneLabeling', _tg_name) 
    
    # Get alignments
    textgrid = tgt.io.read_textgrid(tg_path)
    phone, duration, start, end = get_alignment(textgrid.get_tier_by_name(_tg_name))
    text = '{'+ '}{'.join(phone) + '}' # '{A}{B}{$}{C}', $ represents silent phones
    text = text.replace('{$}', ' ')    # '{A}{B} {C}'
    text = text.replace('}{', ' ')     # '{A B} {C}'

    if start >= end:
        return None

    # Read and trim wav files
    _, wav = read(wav_path)
    wav = wav[int(hp.sampling_rate*start):int(hp.sampling_rate*end)].astype(np.float32)
    
    # Compute fundamental frequency
    f0, _ = pw.dio(wav.astype(np.float64), hp.sampling_rate, frame_period=hp.hop_length/hp.sampling_rate*1000)
    f0 = f0[:sum(duration)]

    # Compute mel-scale spectrogram and energy
    mel_spectrogram, energy = Audio.tools.get_mel_from_wav(torch.FloatTensor(wav))
    mel_spectrogram = mel_spectrogram.numpy().astype(np.float32)[:, :sum(duration)]
    energy = energy.numpy().astype(np.float32)[:sum(duration)]
    if mel_spectrogram.shape[1] >= hp.max_seq_len:
        return None

    # Save alignment
    ali_filename = '{}-ali-{}.npy'.format(hp.dataset, basename)
    np.save(os.path.join(out_dir, 'alignment', ali_filename), duration, allow_pickle=False)

    # Save fundamental prequency
    f0_filename = '{}-f0-{}.npy'.format(hp.dataset, basename)
    np.save(os.path.join(out_dir, 'f0', f0_filename), f0, allow_pickle=False)

    # Save energy
    energy_filename = '{}-energy-{}.npy'.format(hp.dataset, basename)
    np.save(os.path.join(out_dir, 'energy', energy_filename), energy, allow_pickle=False)

    # Save spectrogram
    mel_filename = '{}-mel-{}.npy'.format(hp.dataset, basename)
    np.save(os.path.join(out_dir, 'mel', mel_filename), mel_spectrogram.T, allow_pickle=False)
    
    return '|'.join([basename, text]), max(f0), min([f for f in f0 if f != 0]), max(energy), min(energy), mel_spectrogram.shape[1]
`

**Comment by dathudeptrai** [comment]
@yanglu1994 the duration file is a 1D vector and len(duration) = len(charactor/phoneme) and sum(durations) = len(mel).

**Comment by tekinek** [comment]
@yanglu1994  to me, your file looks like an alignment between phonemes and their durations (in second).

> "k"
> 0.406291189066745
> 0.5165142974475827

likely indicate that the phoneme "k" starts at 0.406291189066745 sec and ends at 0.5165142974475827. "sil" represent  silence -- break in utterance.

The duration needed by FastSpeech is something slightly different. It is, for your case, the alignment between phonemes and mel spectrogram which is kind of processed representation of raw sound. Duration file is a simple list of integers in which index matchs a phoneme in sentence and value represents number of mels aligned with that phoneme. A mel is  roughly 11ms long, but it depends on how it is generated, and there is a formula.
