### ISSUE TITLE
Error on inference of multi band melgan models

### ISSUE THREAD

**Issue by MegaPanchamZ** [TensorSpeech/TensorflowTTS#136]
Dropping the error below.

`
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * Tensor("mels:0", shape=(1, 789, 80), dtype=float32)
  Keyword arguments: {}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (1 total):
    * TensorSpec(shape=(None, 256, 80), dtype=tf.float32, name='mels')
  Keyword arguments: {'training': True}

Option 2:
  Positional arguments (1 total):
    * TensorSpec(shape=(None, 256, 80), dtype=tf.float32, name='input_1')
  Keyword arguments: {'training': True}

Option 3:
  Positional arguments (1 total):
    * TensorSpec(shape=(None, 256, 80), dtype=tf.float32, name='input_1')
  Keyword arguments: {'training': False}

Option 4:
  Positional arguments (1 total):
    * TensorSpec(shape=(None, 256, 80), dtype=tf.float32, name='mels')
  Keyword arguments: {'training': False}
`

In trying to use inference of mb_melgan models, I get an error ( using colab notebook ). Using identical code from the inference example in the ./examples folder. For the mels, I used mels generated from inference of a fastspeech2 model.

Is there  a change required in the ipynb?

Thanks.

**Comment by dathudeptrai** [comment]
@MegaPanchamZ can you provide colab or the full code to reproduce ?

**Comment by MegaPanchamZ** [comment]
Sure, https://colab.research.google.com/drive/1wjEpn6-VoOCRrHN21NenEsX7XusRw0Ew?usp=sharing

**Comment by dathudeptrai** [comment]
@MegaPanchamZ https://colab.research.google.com/drive/1EuXRO1Asl6YK1W0UFQWcPhFCUMf4oD2B?usp=sharing. You should saved mb_melgan by mb_melgan._inference function though signatures as fastspeech2 does.

**Comment by MegaPanchamZ** [comment]
Oh, thanks. I had no idea.

**Comment by dathudeptrai** [comment]
@MegaPanchamZ glad to see it help you. If you see our framework helpful, let give it a star and share our work with ur friends :)).

**Comment by MegaPanchamZ** [comment]
I already did :) they are having fun experimenting with the framework.

**Comment by dathudeptrai** [comment]
@MegaPanchamZ :)) do not forget give us a star so the repo will become more popular :))
