### ISSUE TITLE
Problems with TFlite inference.

### ISSUE THREAD

**Issue by MegaPanchamZ** [TensorSpeech/TensorflowTTS#138]
Hello, I am having a few issues with the inference of **fastspeech,** **fastspeech2** and **mb_melgan.** 
``
Input shape: [1, 19] , interpreter shape: [1 1]
Warning: Latency might be affected due to change in input shape
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-07343f1be630> in <module>()
      1 start = time.time()
----> 2 mel_output_tflite = fastspeechlite.infer(sentences[3])
      3 end = time.time()
      4 print(f"TFLite inference time: {end-start}s")
      5 mel_after = tf.reshape(mel_output_tflite, [-1, 80]).numpy()

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in set_tensor(self, tensor_index, value)
    406       ValueError: If the interpreter could not set the tensor.
    407     """
--> 408     self._interpreter.SetTensor(tensor_index, value)
    409 
    410   def resize_tensor_input(self, input_index, tensor_size, strict=False):

ValueError: Cannot set tensor: Got value of type **BOOL** but expected type INT32 for input 1, name: speaker_ids 
``

Colab Notebook provided:
https://colab.research.google.com/drive/1pxaVpLq6a9Dk4i-JbFsvsUnMP2BIF5WG?usp=sharing

Thanks.

**Comment by manmay-nakhashi** [comment]
@MegaPanchamZ i think tflite inference input signature is different 
int FastSpeechLite inference test
try calling with this
input_ids = tf.expand_dims(tf.convert_to_tensor(input_ids, dtype=tf.int32), 0)
    return (input_ids,
            tf.convert_to_tensor([0], tf.int32),
            tf.convert_to_tensor([1.0], dtype=tf.float32))

**Comment by MegaPanchamZ** [comment]
Will test soon! and let you know.

**Comment by MegaPanchamZ** [comment]
@manmay-nakhashi Unfortunately that did not work :(

**Comment by dathudeptrai** [comment]
@MegaPanchamZ you should git pull the newest code and do converts tflite again.

**Comment by MegaPanchamZ** [comment]
Actually using this repository found @ https://github.com/sujeendran/TensorflowTTS seemed to fix the issue.

Currently, I have a working ipynb at colab  which anyone can copy, found @ https://colab.research.google.com/drive/14_mJCfDyxSLCfsintOiWSatIlZ0B1FmT?usp=sharing

I will try to pull the newest code once I finish learning the new tflite system.

**Comment by MegaPanchamZ** [comment]
Problem was solved, closing issue. :)
