### ISSUE TITLE
When  I inference,how to change the tone?

### ISSUE THREAD

**Issue by learnerkun** [TensorSpeech/TensorflowTTS#141]
I do not find any param for tone change,if there are params for tone change in inferencing?

**Comment by dathudeptrai** [comment]
@learnerkun For fastspeech2, you can change `f0_ratios`, `energy_ratios`, let see the code here https://github.com/TensorSpeech/TensorflowTTS/blob/master/tensorflow_tts/models/fastspeech2.py#L218-L220.

**Comment by learnerkun** [comment]
Ok，Thanks！
