### ISSUE TITLE
issue while running android app 

### ISSUE THREAD

**Issue by manmay-nakhashi** [TensorSpeech/TensorflowTTS#144]
pushed uploaded model which is in assets folder.
not able load model from given path
W/System.err: java.lang.IllegalArgumentException: Contents of /storage/self/primary/fastspeech2_quant.tflite does not encode a valid TensorFlow Lite model: Could not open '/storage/self/primary/fastspeech2_quant.tflite'.

**Comment by manmay-nakhashi** [comment]
@mapledxf

**Comment by dathudeptrai** [comment]
@manmay-nakhashi you should change the path in the code to relative path or absolute path :)).
