### ISSUE TITLE
Way to mitigate using tensorflow when inferencing .tflite

### ISSUE THREAD

**Issue by MegaPanchamZ** [TensorSpeech/TensorFlowTTS#149]
Currently, after trying to create a way to inference the fastspeech2 model the need for tf to still exist is a nuisance.

```python
  def prepare_input(self,input_ids):
    input_ids = tf.expand_dims(tf.convert_to_tensor(input_ids, dtype=tf.int32), 0)
    return (input_ids,
            tf.math.not_equal(input_ids, 0),
            tf.convert_to_tensor([0], tf.int32),
            tf.convert_to_tensor([1.0], dtype=tf.float32),
            tf.convert_to_tensor([1.0], dtype=tf.float32),
            tf.convert_to_tensor([1.0], dtype=tf.float32))
```
Any way to remove the need for tf.(whatever)  when conferencing? Also is there anyone who has used the tflite binary instead of nightly for fastspeech2 ?

**Comment by dathudeptrai** [comment]
I don't if there is a way to do that, inferencing by python with tflite is just to check output.

**Comment by MegaPanchamZ** [comment]
Should there be a way to use java or js to run the tflite ?

**Comment by dathudeptrai** [comment]
@MegaPanchamZ you mean server side or low end divices?. For mobile we can use C or java to inferencing tflite. For server we use saved model instead.

**Comment by MegaPanchamZ** [comment]
I need to use the model on a Xeon CPU, no AVX instructions and can't run the tf-nightly build. I am hoping that there is a way to run the tflite model without the AVX instruction set. :/

**Comment by dathudeptrai** [comment]
@MegaPanchamZ i do not know if there is a relation between tflite and avx. My laptop computer do not have avx also but can run tflite

**Comment by MegaPanchamZ** [comment]
How did you create the tflite file? When I created it with tf-nightly I get an error trying to run it. I assume you used colab to create, train and export the model.

**Comment by dathudeptrai** [comment]
close because inactivity.
