### ISSUE TITLE
FastSpeech2s

### ISSUE THREAD

**Issue by WhiteFu** [TensorSpeech/TensorFlowTTS#155]
hello, Great Job. Have you implemented fastSpeech2s?  How's the audio's quality generated by fastSpeech2s?  
if you finished it, Could you give some examples?   Thanks a lot!

**Comment by dathudeptrai** [comment]
@WhiteFu the audio quality generated by FastSpeech2s is the same as fastspeech2. The inference speed is slightly faster but it's not important. Now, I don't see any benefit of FastSpeec2 except it can train with single-stage rather than 2 stages. And it requires multi-gpu to train :)).
