### ISSUE TITLE
Training on Multispeaker Dataset

### ISSUE THREAD

**Issue by sjainlucky** [TensorSpeech/TensorFlowTTS#158]
Currently i am trying to train my model with Multispeaker dataset. What are the changes I need to apply in the model for training it on fastspeech2?

**Comment by dathudeptrai** [comment]
@sjainlucky you just need return speaker_id in generator function in dataset loader.

**Comment by ZDisket** [comment]
@dathudeptrai Do you see anything wrong in my implementation? https://github.com/ZDisket/TensorflowTTS/commit/59d546130c81b08d4f6cebe9309b915a1010d7ba#diff-d9ec9f8dbf92ba0ced95db127ecdafd1 I can't get my multispeaker models (249 speakers 15 hours of audio) to generate coherent speech after 50k steps even when I augment them with 160 LibriTTS (downsampled to 22KHz) speakers.
Every speakerid file contains a NumPy array with 1 integer element containing the speaker ID (ex: `[5]`)

**Comment by dathudeptrai** [comment]
@ZDisket i don't see anything wrong in ur change. We just need return speaker_id in generator function and change n_speakers in config. It worked in my private muti speaker dataset. Do you think a problem is about ur dataset have so many speaker but the total durations of dataset is too small ?.

**Comment by ZDisket** [comment]
@dathudeptrai Then it's probably my dataset, although I'm not too sure why adding LibriTTS speakers didn't work since I heard of someone doing a similar trick training Tacotron2

**Comment by dathudeptrai** [comment]
@ZDisket let wait the pull request for LibriTTS.

**Comment by dathudeptrai** [comment]
close because inactivity, fell free to re-open or create new issue.
