### ISSUE TITLE
More problems with MFA

### ISSUE THREAD

**Issue by adfost** [TensorSpeech/TensorflowTTS#159]
Apparently the command ./montreal-forced-aligner/bin/mfa_align ./datasets/wavs ./montreal-forced-aligner/pretrained_models/librispeech-lexicon.txt ./montreal-forced-aligner/pretrained_models/english.zip ./TextGrids -j 8 isn't filling the TextGrids file

**Comment by dathudeptrai** [comment]
@weird, everything is fine for me. It runs a bit slow :)). For Ljspeech, it took around 20-30m to fill TextGrid directory.

**Comment by adfost** [comment]
It worked before, but I decided to get rid of some data, and deleted the TextGrids file. I can't fill it up again.

**Comment by dathudeptrai** [comment]
@adfost maybe just delete the folder then run the script again -_-.
