### ISSUE TITLE
TensorFlow Serving

### ISSUE THREAD

**Issue by unparalleled-ysj** [TensorSpeech/TensorFlowTTS#163]
Hi, I want to use tensorflow-serving to deploy the fastspeech2 model. I successfully converted the model to saved_model format and used the tf.saved_model.load() API to verify that the model can be called correctly, but I use tensorflow-serving to deploy the model and use the RESTful API. Way to access, the following error occurred：

{'error': '[_Derived_]{{function_node __inference__inference_5663}} {{function_node __inference__inference_5663}} Input to reshape is a tensor with 21504 values, but the requested shape has 84\n\t [[{{node encoder/layer_._0/attention/self/query/Tensordot/Reshape}}]]\n\t [[StatefulPartitionedCall/StatefulPartitionedCall]]'}
{'error': '[_Derived_]{{function_node __inference__inference_5663}} {{function_node __inference__inference_5663}} Input to reshape is a tensor with 52992 values, but the requested shape has 207\n\t [[{{node encoder/layer_._0/attention/self/query/Tensordot/Reshape}}]]\n\t [[StatefulPartitionedCall/StatefulPartitionedCall]]'}
{'error': '[_Derived_]{{function_node __inference__inference_5663}} {{function_node __inference__inference_5663}} Input to reshape is a tensor with 6656 values, but the requested shape has 26\n\t [[{{node encoder/layer_._0/attention/self/query/Tensordot/Reshape}}]]\n\t [[StatefulPartitionedCall/StatefulPartitionedCall]]'}

This is the 3 test texts in the for loop statement. I noticed that the multiple relationship between the values is 256. If anyone has relevant experience, please help me

**Comment by dathudeptrai** [comment]
@unparalleled-ysj sorry, I didn't use tf-serving, I just load the model by tf.saved_model.load then inferencing it as normal:v.

**Comment by ZDisket** [comment]
@unparalleled-ysj 
> I successfully converted the model to saved_model format

How?

**Comment by unparalleled-ysj** [comment]
> @unparalleled-ysj
> 
> > I successfully converted the model to saved_model format
> 
> How?

Just using tf.saved_model.save() like notebooks

**Comment by dathudeptrai** [comment]
I will close this issue :D

**Comment by meowtech** [comment]
@unparalleled-ysj Would you mind share your solution with us? I come across the same situation recently.
