### ISSUE TITLE
Possibility of using normal tensorflow= 2.2.0 to run inference on tflite models.

### ISSUE THREAD

**Issue by MegaPanchamZ** [TensorSpeech/TensorFlowTTS#164]
After doing some investigative work regarding tflilte, I found a python package on pypi 'tflite' which is compatible with tensorflow 2.2.0  not the nightly build. I was wondering if it was still possible to use tf 2.2.0  to 'convert' the model to tflite so I can run inference on the tflite model(s). I have a colab notebook and was trying to convert the model and came across this error:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-dd82e1dab2c8> in <module>()
     29 converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
     30                                        tf.lite.OpsSet.SELECT_TF_OPS]
---> 31 tflite_model = converter.convert()
     32 # Save the TF Lite model.
     33 with open('fastspeech2_quant.tflite', 'wb') as f:

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in convert(self)
    481               "None is only supported in the 1st dimension. Tensor '{0}' has "
    482               "invalid shape '{1}'.".format(
--> 483                   _get_tensor_name(tensor), shape_list))
    484         elif shape_list and shape_list[0] is None:
    485           # Set the batch size to 1 if undefined.

ValueError: None is only supported in the 1st dimension. Tensor 'input_ids' has invalid shape '[1, None]'.
```

Any help would be appreciated. 

Colab notebook here:
https://colab.research.google.com/drive/14_mJCfDyxSLCfsintOiWSatIlZ0B1FmT?usp=sharing

**Comment by dathudeptrai** [comment]
@MegaPanchamZ no, for tflite you should use tf-nightly.

**Comment by ZDisket** [comment]
@dathudeptrai Will tflite C++ API compiled from this branch: https://github.com/tensorflow/tensorflow/tree/r2.3 work for inference?

**Comment by dathudeptrai** [comment]
@ZDisket i always use tf-nightly for TFlite

**Comment by MegaPanchamZ** [comment]
> @ZDisket i always use tf-nightly for TFlite

With TFlite technology existing pre the nightly build, is there a way to still inference with the TFlite package and regular TensorFlow. I would like to use the model in another project, but I have qualms with conferencing. @dathudeptrai  you mentioned using it on a non-avx system, how did you still manage to run inference.

**Comment by dathudeptrai** [comment]
@MegaPanchamZ i don't know everything about avx, i just saw that my laptop is non-avx system and it can run tflite ?

**Comment by ZDisket** [comment]
@MegaPanchamZ You can use tensorflow==2.3.0, I managed to convert a model and almost run inference from C++ (need to recompile tflite with flux delegate)

**Comment by MegaPanchamZ** [comment]
@ZDisket seems interesting. I will look into compiling it soon.

**Comment by dathudeptrai** [comment]
closed issue :D. feel free to re-open
