### ISSUE TITLE
multi-band melgan question

### ISSUE THREAD

**Issue by unparalleled-ysj** [TensorSpeech/TensorFlowTTS#169]
Hi, When I converted mb_melgan to saved_models format and used a for loop to generate 10 audios, I encountered the following warning:

WARNING:tensorflow:6 out of the last 11 calls to <function recreate_function.<locals>.restored_function_body at 0x7fb36059bc20> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

Is there a shape problem with tf.function in mb_melgan ?

**Comment by dathudeptrai** [comment]
@unparalleled-ysj can you try the nestwest code :)) and follow the notebook here (https://github.com/TensorSpeech/TensorflowTTS/blob/master/notebooks/multiband_melgan_inference.ipynb). In the newest code, i use input_signature for mb_melgan on inference function so everything about shape related should be fine :D (https://github.com/TensorSpeech/TensorflowTTS/blob/master/tensorflow_tts/models/mb_melgan.py#L175-L180)

**Comment by unparalleled-ysj** [comment]
@dathudeptrai Suppose I trained an mb-melgan with 16k sampling rate data, can I generate 8k sampling rate speech through parameter settings instead of post-processing ?

**Comment by dathudeptrai** [comment]
can't use parameter settings to do that :D

**Comment by unparalleled-ysj** [comment]
> @unparalleled-ysj can you try the nestwest code :)) and follow the notebook here (https://github.com/TensorSpeech/TensorflowTTS/blob/master/notebooks/multiband_melgan_inference.ipynb). In the newest code, i use input_signature for mb_melgan on inference function so everything about shape related should be fine :D (https://github.com/TensorSpeech/TensorflowTTS/blob/master/tensorflow_tts/models/mb_melgan.py#L175-L180)

@dathudeptrai Hi, after I update this change, mbmelgan output shape is (1, 38250, 4) ,   the original version is (1, 153000, 1)

**Comment by dathudeptrai** [comment]
@unparalleled-ysj that mean the output of mb_melgan should pass to pqmf to generate a final audios. 38250 * 4 = 153000. :D

**Comment by unparalleled-ysj** [comment]
@dathudeptrai But the pqmf.synthesis function has been called in mbmelgan's inference, isn't it? Why is the output dimension still (1, 38250, 4)?

**Comment by dathudeptrai** [comment]
@unparalleled-ysj i do not know, maybe you did something wrong ?. Pls see the notebook (https://github.com/TensorSpeech/TensorflowTTS/blob/master/notebooks/multiband_melgan_inference.ipynb), everything is fine

**Comment by unparalleled-ysj** [comment]
I did it based on this notebooks. By the way, my model was trained before updating the auto_model code. Is the problem here?

**Comment by dathudeptrai** [comment]
@unparalleled-ysj yes :)) that is the problem :D

**Comment by unparalleled-ysj** [comment]
@dathudeptrai Okay, thanks, let me find the problem, so should I retrain a model?

**Comment by dathudeptrai** [comment]
@unparalleled-ysj no need to retrain :D just pull the newest code and everything will be fine

**Comment by unparalleled-ysj** [comment]
@dathudeptrai My current code is the latest, but the model was trained before updating the auto_model code. According to the notebooks steps, the model conversion and use are no problem, but the output dimension becomes (1, 38250, 4)

**Comment by dathudeptrai** [comment]
@unparalleled-ysj i do not know what you did wrong but if the outshape is (1, 38250, 4) so let use pqmf.synthesize(ur_output) to get final audio first.

**Comment by unparalleled-ysj** [comment]
@dathudeptrai I just tried it and the voice is ok

**Comment by dathudeptrai** [comment]
@unparalleled-ysj hi, i know the problem, pls pull request the latest master :D. I just fixed :D.
