### ISSUE TITLE
problem with f0 outliers?

### ISSUE THREAD

**Issue by abylouw** [TensorSpeech/TensorFlowTTS#170]
Hi,

What is the idea of the `remove_outlier` function in tensorflow_tts/utils/outliers.py?
Is it to filter for pitch halving and doubling issues?

The reason I am asking is that I have one corpus with some utterances with very few and short voiced regions. Now the `np.percentile` function in `remove_outlier` calculates `p75` as `0` because the utterance is mostly unvoiced. This then makes that all voiced regions are "outliers" and then further up in the pre-processing breaks the StandardScaler due to `f0[f0!=0]` in:

https://github.com/TensorSpeech/TensorflowTTS/blob/ddd3caf20bb0032852f04296f9192be6e80f3caf/tensorflow_tts/bin/preprocess.py#L317

being an empty array.

If `remove_outlier` is for detection and filtering of pitch halving and doubling issues then I can make a different plan.

**Comment by dathudeptrai** [comment]
Hi, the `remove_outlier` function aim to filter the outlier pitch, let see the figure bellow:

1. output of pw.dio:
![before](https://user-images.githubusercontent.com/43868663/88992747-59ee1700-d30e-11ea-8057-3addf504495c.png)


2. output of remove_outlier:
![after](https://user-images.githubusercontent.com/43868663/88992741-58245380-d30e-11ea-99a0-1fee33a59669.png)

The problem you are mentioning here is the case that i didn't expect :)). But we can easy solve this problem by using `pw.stonemask`, i'm not sure if it solve the problem but let try :D. Just replace the remove_outlier and use pw.stonemask instead (https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder)

3. output of pw.stonemask:
![stonemask](https://user-images.githubusercontent.com/43868663/88992851-9457b400-d30e-11ea-9aad-463e66fa4b06.png)

cc: @mapledxf it may related with ur problem.

**Comment by abylouw** [comment]
Thanks, I'll try stonemask. I don't really mind if it is slower, it is just pre-processing.

**Comment by abylouw** [comment]
I can confirm that stonemask has fixed my issue and I cannot see much difference in processing speed, although I have not tested it with  /usr/bin/time.

**Comment by dathudeptrai** [comment]
@abylouw can you report here if the training process work fine or even better :)))

**Comment by Zak-SA** [comment]
> I can confirm that stonemask has fixed my issue and I cannot see much difference in processing speed, although I have not tested it with /usr/bin/time.

Can you please post the changes you made to switch from remove_outlier to stonemask?
