### ISSUE TITLE
any plan to implement parallelWavegan?

### ISSUE THREAD

**Issue by superhg2012** [TensorSpeech/TensorFlowTTS#171]

**Comment by dathudeptrai** [comment]
@superhg2012 yes, but i need make the framework clearer and simpler + support more language first :)).

**Comment by dathudeptrai** [comment]
@superhg2012 https://github.com/TensorSpeech/TensorFlowTTS/pull/197. I just finish implement pwgan model/config, you can use it to train :)) write ur trainer. I will write trainer code when i have free time.
