### ISSUE TITLE
Cannot save FastSpeech2 model to .pb

### ISSUE THREAD

**Issue by ZDisket** [TensorSpeech/TensorFlowTTS#172]
When I load a FastSpeech2 model to save to a SavedModel .pb (for inference with C++), as it says here: https://www.tensorflow.org/guide/keras/save_and_serialize#export_to_savedmodel doing `fastspeech2.save("fs2mdl")`, I get this error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-9-90e4c45d79d3> in <module>()
      1 import tensorflow as tf
----> 2 fastspeech2.save("saved_model")
      3 
      4 # Concrete Function
      5 #fastspeech2_concrete_function = fastspeech2.inference_tflite.get_concrete_function()

24 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    300   def wrapper(*args, **kwargs):
    301     with ag_ctx.ControlStatusCtx(status=ag_ctx.Status.DISABLED):
--> 302       return func(*args, **kwargs)
    303 
    304   if inspect.isfunction(func) or inspect.ismethod(func):

TypeError: call() missing 4 required positional arguments: 'speaker_ids', 'duration_gts', 'f0_gts', and 'energy_gts'
```
Full error log in attached text file
[allframes.txt](https://github.com/TensorSpeech/TensorFlowTTS/files/5013307/allframes.txt)

**Comment by dathudeptrai** [comment]
@ZDisket pls follow the instruction in this notebook (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/notebooks/fastspeech2_inference.ipynb).

**Comment by ZDisket** [comment]
@dathudeptrai Oh, didn't know that notebook had that function. Thanks!

**Comment by tongtianchedi** [comment]
hello, I met the same question, but  did not solve it  with https://github.com/TensorSpeech/TensorFlowTTS/blob/master/notebooks/fastspeech2_inference.ipynb
can you tell me how to solve it in detail? Thank you.
