### ISSUE TITLE
Fastspeech2 model bad with shorter vocab size ?

### ISSUE THREAD

**Issue by ZhaoZeqing** [TensorSpeech/TensorFlowTTS#180]
I run preprocessor with my own symbols which is shorter than LJSpeech symbols, and trained Fastspeech2 model with this new symbols, but the audios synthesized by this model are not good. 
If I didn't change this [line](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/configs/fastspeech.py#L19), just use LJSpeech symbols' length,  the audios are great.
A little puzzled about this.

**Comment by dathudeptrai** [comment]
:))))))))))))) @ZhaoZeqing you make me puzzle also :)). BTW, chinese will be support tonight, or tmr :))). A quality is great :)).

**Comment by ZhaoZeqing** [comment]
@dathudeptrai  Thanks! I tried to get duration from 15w steps tacotron2, then both ljspeech symbols' length or my own symbols' length are great :)   Maybe the model I used to get duration is not so good before ?

**Comment by dathudeptrai** [comment]
close because inactivity, fell free to re-open or create new issue.
