### ISSUE TITLE
Switching from outlier to pw.stonemask

### ISSUE THREAD

**Issue by Zak-SA** [TensorSpeech/TensorFlowTTS#185]
Hi,
I am having the error:

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by StandardScaler.

according to issue #170 discussion replacing the remove_outlier with pw.stonemask should solve this error. 

Can anyone help with sharing the changes needed and the modified preprocess.py after the change?
Highly appreciate the help.

Thanks

**Comment by Zak-SA** [comment]
And I have one more question,  can someone explain why the remove_outlier causing this error? Is it related to something with the audio files? Is there something we can do to avoid this error before preprocessing the data? 
Thanks

**Comment by dathudeptrai** [comment]
the problem with the remove_outlier is because:

```
the np.percentile function in remove_outlier calculates p75 as 0 because the utterance is mostly unvoiced. This then makes that all voiced regions are "outliers" and then further up in the pre-processing breaks the StandardScaler due to f0[f0!=0]
```
I will push commit to fix that :D

**Comment by Zak-SA** [comment]
> the problem with the remove_outlier is because:
> 
> ```
> the np.percentile function in remove_outlier calculates p75 as 0 because the utterance is mostly unvoiced. This then makes that all voiced regions are "outliers" and then further up in the pre-processing breaks the StandardScaler due to f0[f0!=0]
> ```
> 
> I will push commit to fix that :D

thanks

**Comment by dathudeptrai** [comment]
@Zak-SA i just commit the fix :)) let try again :D

**Comment by Zak-SA** [comment]
> @Zak-SA i just commit the fix :)) let try again :D

I am applying the fix you committed, will let you know in few minutes. It usually crash at 31% .
Thank you

**Comment by Zak-SA** [comment]
> @Zak-SA i just commit the fix :)) let try again :D

Awesome,  it worked! And it didn't take long.
Thank you so much.
