### ISSUE TITLE
FastSpeech2 model implementation and alignments

### ISSUE THREAD

**Issue by superhg2012** [TensorSpeech/TensorFlowTTS#189]
Hi,  I see that your  implementation of VariantPredictor is different from source paper's  description.  

1  the inputs of  pitch predictor and energy predictor is outputs from  length regulator which is different with this repo. I am not sure whtether it will affect the quality of synthesis.

2 about the alignments, this repo still use alignments from Tacotron2 or TransformerTTS, not MFA.

**Comment by dathudeptrai** [comment]
@superhg2012 

1. I implemented exactly paper said but got bad performance then i changed a model a bit :)). You can train and see the performance :D.

2. We are working for MFA, there are some problem now :)) hope will finish soon.

**Comment by superhg2012** [comment]
@dathudeptrai  get it! I will try that. For mandarin, there are prodody tags line #1, #2, #3 and #4 ,  it seemed that  these tags can not be aligned with MFA alignment tools.

**Comment by dathudeptrai** [comment]
@superhg2012 i don't know mandarin. @candlewill @azraelkuan can you guys help ?

**Comment by azraelkuan** [comment]
yes, mfa can only align sp1, so if u want more prosody tags, u need to train a prosody predictor @superhg2012

**Comment by superhg2012** [comment]
@azraelkuan thanks !!! by the way, The prosody predictor mentioned here is frontend models like lstm + crf?  or backend model?

**Comment by azraelkuan** [comment]
@superhg2012 you can check this https://arxiv.org/pdf/1911.04111.pdf

**Comment by superhg2012** [comment]
@azraelkuan  thanks a lot!
