### ISSUE TITLE
Data Sets How to Use?

### ISSUE THREAD

**Issue by wanfuse123** [TensorSpeech/TensorFlowTTS#193]
Hi! Thank you all for your hard work. I dont understand how to proceed from data sets to training the models . That is how to prepair and layout the datasets. It seems like from whats written you only support one dataset that being the LibriSpeech. But perhaps I am getting confused. Can you write more about using the different datasets, and also recommend which one is best to provide the most human like voices? Seems like all voice projects that are available to public are still in the creepy stage. It also seemed like this project might be an exception if I can manage to get it working. On many projects that are less than a week since last updated for the Jupyter - Python - Notebooks also seem to always be broken and puke up errors. Is there an updated one for this project as  of Aug 8, 2020?

**Comment by dathudeptrai** [comment]
@wanfuse123 i will write more about using other datasets in wiki soon. what you mean "creepy stage" ?.

**Comment by machineko** [comment]
If u are using multispeaker dataset u can check https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2_multispeaker

just split train.txt file into and run all comands everything should works without changes (if u got 24k sampling_rate dataset else u'll need to change config)

train.txt
wav_path|text|speaker_name

**Comment by wanfuse123** [comment]
creepy stage. See this link!

Also, if one were to take two inputs, human spoken versions of output (with good orator) and two input from the other side of computer spoken version . And run them through a GAN it would likely improve the outputs (not sure of outputs of  this project, haven't seen the samples yet) but generally creepy stage is where most projects are at...

https://ibb.co/kDhjg72

**Comment by dathudeptrai** [comment]
close because inactivity.
