### ISSUE TITLE
how to train multi-speaker tacotron2 model

### ISSUE THREAD

**Issue by xgate1** [TensorSpeech/TensorFlowTTS#195]
hi. i have multi speaker dataset. and try to multi-speaker model training
and i check this issue [https://github.com/TensorSpeech/TensorFlowTTS/issues/158](url).
i have err `tf.Tensor` as a Python `bool` is not allowed 
in compute_per_example_losses 

i don't know where i change to train multi-speaker for tacotron2

**Comment by dathudeptrai** [comment]
can you make the fork and update ur code so i can easy to help you :)), if you want training multi-speaker, the only thing you need is set n_speakers in config and return speaker id in the dataloader (tacotron2_dataset.py)

**Comment by dathudeptrai** [comment]
close because inactivity.
