### ISSUE TITLE
Tacotron2: mels are not getting aligned properly.

### ISSUE THREAD

**Issue by najmuzsakib11** [TensorSpeech/TensorFlowTTS#196]
Hi, I am new in this field. I trained Tacotron2 from scratch with a different dataset. I am using same config as TensorflowTTS/examples/tacotron2/conf/tacotron2.v1.yaml. But it is not aligning properly for short sentences. There is noice at the end the audio. Can you think of anything that i might have done wrong. Thank you.
![1](https://user-images.githubusercontent.com/47039457/89854279-53d12380-dbb5-11ea-8894-e9ff4282c438.png)
![1_alignment](https://user-images.githubusercontent.com/47039457/89854295-5e8bb880-dbb5-11ea-8a71-c9fae5aff04e.png)

**Comment by dathudeptrai** [comment]
@najmuzsakib11 do you mean the yellow line ?

**Comment by najmuzsakib11** [comment]
Yes. Here is another example.
![Screenshot 2020-08-11 at 9 49 11 AM](https://user-images.githubusercontent.com/47039457/89855410-394c7980-dbb8-11ea-86de-226970965adb.png)
Text: As he crossed toward the pharmacy at the corner he involuntarily turned his head because of a burst.
The audio sounds like this 
https://drive.google.com/file/d/1tkc5l9YDrkozWRi4Qv7jrwUGCJcUTmpr/view?usp=sharing

**Comment by dathudeptrai** [comment]
@najmuzsakib11 that is normal :D, in training, we evaluation it by "batch" :)) so the charactor  and the mel will be padded to the longest sample in the batch :)) everything is ok :D

**Comment by najmuzsakib11** [comment]
Ok got it. Thank you. 
I added eos symbols in the end like you said. But there is still a noice at the end at inference time. Yes i am using your notebook for inference.  I have trained more then 250K iters and still getting the noice. For long sentences the noice is shorter and for short sentences noice is longer. What is causing that any guess.

**Comment by dathudeptrai** [comment]
@najmuzsakib11 can you share ur tensorboard. Actually, we have some problem about `eos` symbols in the code that is a hard code for ljspeech eos in the tacotron daloader, when we change the symbols, that cause some problem :)). see here (https://github.com/TensorSpeech/TensorFlowTTS/issues/188).

**Comment by najmuzsakib11** [comment]
Here is my tensorboard
![Screenshot 2020-08-11 at 11 00 30 AM](https://user-images.githubusercontent.com/47039457/89859090-fee7da00-dbc1-11ea-9b19-77875ea2d0a0.png)

**Comment by dathudeptrai** [comment]
@najmuzsakib11 seem you are not monitor the training process frequently :)) at around 37-38k steps you got nan problem. The solution is disble guided attention loss and retrain :)). see (https://github.com/TensorSpeech/TensorFlowTTS/issues/125).

**Comment by najmuzsakib11** [comment]
Got it. Thanks for the help.
