### ISSUE TITLE
Duration Format

### ISSUE THREAD

**Issue by mapledxf** [TensorSpeech/TensorFlowTTS#200]
@dathudeptrai  Hi, the Chinese baker dataset comes with text grid files already.
```
File type = "ooTextFile short"
"TextGrid"

0
1.995
<exists>
1
"IntervalTier"
"009875.interval"
0
1.995
13
0
0.2778364775809071
"sil"
0.2778364775809071
0.34081735068878827
"m"
0.34081735068878827
0.5832143244989526
"a1"
0.5832143244989526
0.7599737056904039
"sp1"
0.7599737056904039
0.8801136905264462
"s"
0.8801136905264462
0.9621476008770476
"ii1"
0.9621476008770476
1.0590005401942093
"q"
1.0590005401942093
1.1860207884790117
"ing2"
1.1860207884790117
1.2722887071057731
"sh"
1.2722887071057731
1.395
"u1"
1.395
1.4585746076124073
"n"
1.4585746076124073
1.6962083221118915
"e5"
1.6962083221118915
1.995
"sil"
```
I am trying to convert these files into duration files.
So could you explain a little bit about duration file's structure?
What is in the duration file exactly?
An example is appreciated. :)

**Comment by machineko** [comment]
phoneme and time (start-end)

```
1.6962083221118915
1.995
"sil"
```
1.69 start of silence token
1.995 end of silence token

**Comment by mapledxf** [comment]
I understand the text grid. I just don't know how to conver text grid to the duration used for training.
The format is different from the example. What do you save in the durations.npy file?

**Comment by dathudeptrai** [comment]
@mapledxf ref [here](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/mfa_extraction/txt_grid_parser.py#L72-L102)

**Comment by mapledxf** [comment]
got it
thx
