### ISSUE TITLE
MFA txtgrid parser error

### ISSUE THREAD

**Issue by mataym** [TensorSpeech/TensorFlowTTS#202]
[testuser@localhost TensorflowTTS]$ python examples/mfa_extraction/txt_grid_parser.py \
>   --yaml_path examples/fastspeech2/conf/fastspeech2.v1.yaml \
>   --dataset_path ./corpus \
>   --text_grid_path ./mfa/parsed \
>   --output_durations_path ./durations \
>   --sample_rate 22050
  File "examples/mfa_extraction/txt_grid_parser.py", line 39
    sample_rate: int
               ^
SyntaxError: invalid syntax

this same error also occurred when i ran the run_mfa.py:
[testuser@localhost TensorflowTTS]$ python examples/mfa_extraction/run_mfa.py
  File "examples/mfa_extraction/run_mfa.py", line 31
    mfa_path:str,
            ^
SyntaxError: invalid syntax
i cannot find any problem in this these *.py files, how do i solve this problem?thanks

**Comment by machineko** [comment]
Python version?

**Comment by mataym** [comment]
> Python version?
> Looks like typing problem and typing was added in python 3.5
> https://docs.python.org/3/library/typing.html
my python version is 3.7.7 with conda env. i did not modify source code. i just ran the script.

**Comment by machineko** [comment]
run python --version from terminal to be sure

**Comment by mataym** [comment]
> @mataym run` python --version` from terminal to be sure

thanks a lot, it is just python version, after activated my conda env, it running with no error.
