### ISSUE TITLE
debug tensorflow-tts-preprocess with pycharm

### ISSUE THREAD

**Issue by mataym** [TensorSpeech/TensorFlowTTS#205]
i want to debug fastspeech2 preprocessing script with pycharm, the script is as follows:
tensorflow-tts-preprocess --rootdir tensorflow_tts/datasets --outdir ./dump --config preprocess/ljspeech_preprocess.yaml 

can anyone tell me how to run above script with pycharm, i don't like debug by using ipdb. thanks

**Comment by tekinek** [comment]
@mataym  I have no idea with Pycharm, but an easy way to "debug" preprocessing is to use logging.debug("message") at wherever you wish to monitor, then run the script with an additional argument --verbose 1.

**Comment by machineko** [comment]
Add flags to pycharm run config that's all it's needed for that :)
