### ISSUE TITLE
how to generate acoustic model for a corpus(or for a language) in order to using mfa-aligner

### ISSUE THREAD

**Issue by mataym** [TensorSpeech/TensorFlowTTS#206]
when i want to generate TextGrid files for corpus with MFA, it needs a acoustic model for training. the mfa-align script as follows:
bin/mfa_align corpus_directory dictionary_path **acoustic_model_path** output_directory

there is no acoustic model for my language in [pretrained acoustic model] list(https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html#pretrained-acoustic-models).
i want create a acoustic model for my language, then use it for mfa-align to generate textgrids.
can anyone give me some instructions that how to generate acoustic_model? 
another question is what is the deference between bin/mfa_align and bin/mfa_train_and_align in MFA? thanks

**Comment by machineko** [comment]
https://montreal-forced-aligner.readthedocs.io/en/latest/example.html#example-3-train-mandarin-g2p-model

**Comment by mataym** [comment]
> https://montreal-forced-aligner.readthedocs.io/en/latest/example.html#example-3-train-mandarin-g2p-model
> 
> https://montreal-forced-aligner.readthedocs.io/en/latest/alignment_techniques.html
> 
> @dathudeptrai This isn't question on our implementation but for MFA git u can close it :D

i think the link you provided is used to generate G2P model, not acoustic model. i downloaded english G2P and  acoustic model from the given link, the contents of the two model is different.

**Comment by machineko** [comment]
G2P is just example u should contact MFA authors if u want tutorial.

Also second link is full alignment tutorial so if u want to train ur model follow that
