### ISSUE TITLE
Transfer learning using the pre-trained model

### ISSUE THREAD

**Issue by jesinj** [TensorSpeech/TensorFlowTTS#213]
Thanks a lot for providing these pre-trained models.
I have a variant of English and a small database of it - with 1000 sentences.
Do you have any ideas on how I can use transfer learning using your pre-trained model, and develop a voice for this language?
Thanks a lot

**Comment by ZDisket** [comment]
@jesinj You add a call to `load_weights("model_name.h5")` for whatever model(s) you want to load after said model is built in the code. For example, this is my transfer learning snippet for FastSpeech2:
https://github.com/ZDisket/TensorflowTTS/blob/7ec3bdcf5097bd33aa869a0f7bd829406ec11069/examples/fastspeech2/train_fastspeech2.py#L355-L361
If you're basing a mel generation model on one that uses another dictionary, add `by_name=True,skip_mismatch=True`

**Comment by jesinj** [comment]
Thanks a lot for this information. I will try this out and keep you updated. Would the same be applicable for Tacotron2 as well?

**Comment by ZDisket** [comment]
@jesinj Yes, see this for information: https://github.com/ZDisket/TensorflowTTS/commit/366b3f1d617bab5632efb731aae3ce53747f2bbc

**Comment by dathudeptrai** [comment]
close in #231
