### ISSUE TITLE
'StandardScaler' object has no attribute 'mean_'

### ISSUE THREAD

**Issue by tienanh-1999** [TensorSpeech/TensorFlowTTS#217]
- When I try to save statistics to file in the preprocessing step, I got an error: AttributeError: 'StandardScaler' object has no attribute 'mean_'. 
- I find some answers in the Internet and it said that "starting from Scikit-Learn version 0.17, the attribute "mean_" and “std_”are no longer present as StandardScaler objects."
- But in the setup file, we need to use scikit-learn>=0.22.0.
Thank you for your support, Anh.

**Comment by tekinek** [comment]
I saw this error when I tried to use this repo at the begging, but forgot how it was solved exactly. It is not a versioning problem. I suggest you to make a python virtual environment and conduct setup inside; or put the followings into a text file req.txt, then run  $pip3 install -r req.txt 

tensorflow-gpu==2.3.0
tensorflow-addons>=0.10.0
setuptools>=38.5.1
librosa>=0.7.0
soundfile>=0.10.2
matplotlib>=3.1.0
PyYAML>=3.12
tqdm>=4.26.1
h5py>=2.10.0
unidecode>=1.1.1
inflect>=4.1.0
scikit-learn>=0.22.0
pyworld>=0.2.10
numba<=0.48
jamo>=0.4.1
pypinyin
g2pM
textgrid
click
g2p_en

then do preprocessing with TensorFlowTTS/tensorflow_tts/bin/preprocess.py. Make sure that 
$export PYTHONPATH=/path/to/TensorFlowTTS
