### ISSUE TITLE
Preprocessing on Mobile

### ISSUE THREAD

**Issue by abhijeetchauhan** [TensorSpeech/TensorFlowTTS#223]
In the colab notebook for tflite for tacotron 2 it is written.
The TFLite file doesn't have LJSpeechProcessor. So you need to run it before feeding input vectors.

Is there a way to invoke LJSpeechProcessor in Android to get on device inference?

**Comment by dathudeptrai** [comment]
@abhijeetchauhan write it by naitive java is much simpler :)). You can see our anrdroid example, it is implemented :)). (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/utils/Processor.java)

**Comment by abhijeetchauhan** [comment]
Thank you :))
