### ISSUE TITLE
multiprocess.pool.MaybeEncodingError : Error sending result 

### ISSUE THREAD

**Issue by ayush9096** [TensorSpeech/TensorFlowTTS#225]
2020-08-25 08:10:15.795375: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:00<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:00<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:01<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:01<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:01<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:02<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:02<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:02<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:03<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:03<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:03<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:03<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:04<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:04<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:05<?, ?it/s]
[Preprocessing]:   0%|                                                                                                                                                            | 0/23223 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/ayush/.local/bin/tensorflow-tts-preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/ayush/.local/lib/python3.7/site-packages/tensorflow_tts/bin/preprocess.py", line 313, in main
    p.map(save_to_file, range(len(processor.items)))
  File "/home/ayush/.local/lib/python3.7/site-packages/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/home/ayush/.local/lib/python3.7/site-packages/multiprocess/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ayush/.local/lib/python3.7/site-packages/multiprocess/pool.py", line 657, in get
    raise self._value
multiprocess.pool.MaybeEncodingError: Error sending result: '<multiprocess.pool.ExceptionWithTraceback object at 0x7f3e50b88190>'. Reason: 'PicklingError("Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError")'

**Comment by dathudeptrai** [comment]
> p.map(save_to_file

seems you didn't use master code, can you pull the newest code then:

```
pip install -e .
```

and do preprocessing again ?

**Comment by ayush9096** [comment]
`Traceback (most recent call last):
  File "/home/ayush/TTS/tensorTTS/bin/tensorflow-tts-preprocess", line 11, in <module>
    load_entry_point('TensorFlowTTS', 'console_scripts', 'tensorflow-tts-preprocess')()
  File "/home/ayush/TTS/TensorFlowTTS/tensorflow_tts/bin/preprocess.py", line 438, in preprocess
    for result, mel, energy, f0, features in train_map:
  File "/home/ayush/anaconda3/lib/python3.7/multiprocessing/pool.py", line 354, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/ayush/anaconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f905a21bb90>'. Reason: 'PicklingError("Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError")'
`

Again pulled the code, and getting this in pre-processing step.

**Comment by dathudeptrai** [comment]
@ayush9096  at line https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/bin/preprocess.py#L437. Can you print (result, mel, energy, f0, features) and its dtype for me ?

**Comment by ayush9096** [comment]
`2020-08-25 09:06:00.998772: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-08-25 09:06:03,131 (preprocess:364) INFO: Selected 'ljspeech' processor.
2020-08-25 09:06:03,182 (preprocess:403) INFO: Training items: 12445
2020-08-25 09:06:03,182 (preprocess:404) INFO: Validation items: 655
[Preprocessing train]:   0%|                                                                                                                                                      | 0/12445 [00:00<?, ?it/s]("I don't recall the exact date. It was about a week prior. End quote.", '/data2u/lj_speech/wavs/LJ047-0223.wav', 'ljspeech')
{'raw_text': "I don't recall the exact date. It was about a week prior. End quote.", 'text_ids': array([ 46,  11,  41,  52,  51,   3,  57,  11,  55,  42,  40,  38,  49,
        49,  11,  57,  45,  42,  11,  42,  61,  38,  40,  57,  11,  41,
        38,  57,  42,   7,  11,  46,  57,  11,  60,  38,  56,  11,  38,
        39,  52,  58,  57,  11,  38,  11,  60,  42,  42,  48,  11,  53,
        55,  46,  52,  55,   7,  11,  42,  51,  41,  11,  54,  58,  52,
        57,  42,   7, 148], dtype=int32), 'audio': array([-0.00024414, -0.00012207,  0.00021362, ...,  0.00021362,
        0.00027466,  0.00042725], dtype=float32), 'utt_id': 'LJ047-0223', 'speaker_name': 'ljspeech', 'rate': 22050}
("They could not deny that the latter was the truth, and were forthwith stigmatized by Mr. Chapman, Overend and Gurney's representative, as rogues.", '/data2u/lj_speech/wavs/LJ014-0340.wav', 'ljspeech')
{'raw_text': "They could not deny that the latter was the truth, and were forthwith stigmatized by Mr. Chapman, Overend and Gurney's representative, as rogues.", 'text_ids': array([ 57,  45,  42,  62,  11,  40,  52,  58,  49,  41,  11,  51,  52,
        57,  11,  41,  42,  51,  62,  11,  57,  45,  38,  57,  11,  57,
        45,  42,  11,  49,  38,  57,  57,  42,  55,  11,  60,  38,  56,
        11,  57,  45,  42,  11,  57,  55,  58,  57,  45,   6,  11,  38,
        51,  41,  11,  60,  42,  55,  42,  11,  43,  52,  55,  57,  45,
        60,  46,  57,  45,  11,  56,  57,  46,  44,  50,  38,  57,  46,
        63,  42,  41,  11,  39,  62,  11,  50,  46,  56,  57,  42,  55,
        11,  40,  45,  38,  53,  50,  38,  51,   6,  11,  52,  59,  42,
        55,  42,  51,  41,  11,  38,  51,  41,  11,  44,  58,  55,  51,
        42,  62,   3,  56,  11,  55,  42,  53,  55,  42,  56,  42,  51,
        57,  38,  57,  46,  59,  42,   6,  11,  38,  56,  11,  55,  52,
        44,  58,  42,  56,   7, 148], dtype=int32), 'audio': array([-0.00268555, -0.00457764, -0.00360107, ..., -0.00024414,
       -0.00024414, -0.00021362], dtype=float32), 'utt_id': 'LJ014-0340', 'speaker_name': 'ljspeech', 'rate': 22050}
`
Inside the loop at #L437, it was printing nothing, so I printed it ljspeech.py at line No. 180 print(sample)

It processing 29 files, and in between it giving this also and breaking
`raceback (most recent call last):
  File "/home/ayush/TTS/tensorTTS/bin/tensorflow-tts-preprocess", line 8, in <module>
    sys.exit(preprocess())
  File "/home/ayush/TTS/tensorTTS/lib/python3.7/site-packages/tensorflow_tts/bin/preprocess.py", line 438, in preprocess
    for result, mel, energy, f0, features in train_map:
  File "/home/ayush/anaconda3/lib/python3.7/multiprocessing/pool.py", line 354, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/ayush/anaconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f6c5384a810>'. Reason: 'PicklingError("Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError")'
`

**Comment by dathudeptrai** [comment]
@ayush9096 weird, i just re-run the ljspeech preprocessing and everything is fine so far. Did you use `pip install -e .` ?. I think there is a mismatch version. My numpy version is `1.18.5`

**Comment by ayush9096** [comment]
@dathudeptrai  Yes, my numpy version are also same. I was setting fmin  " " and fmax " " , in lj_speech_processor.yaml, that's why it was coming. It worked after giving a pre-defined value.

**Comment by ayush9096** [comment]
@dathudeptrai How should I re-consider the global gain scale, if using some other dataset ?

**Comment by dathudeptrai** [comment]
> @dathudeptrai  Yes, my numpy version are also same. I was setting fmin  " " and fmax " " , in lj_speech_processor.yaml, that's why it was coming. It worked after giving a pre-defined value. 

Can you give me ur setting so i can find the reason

**Comment by ayush9096** [comment]
@dathudeptrai  I was using null values for fmin and fmax. 

`###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
sampling_rate: 22050     # Sampling rate.
fft_size: 1024           # FFT size.
hop_size: 256            # Hop size. (fixed value, don't change)
win_length: null         # Window length.
                         # If set to null, it will be the same as fft_size.
window: "hann"           # Window function.
num_mels: 80             # Number of mel basis.
fmin: ""                 # Minimum freq in mel basis calculation.
fmax: ""               # Maximum frequency in mel basis calculation.
global_gain_scale: 1.0   # Will be multiplied to all of waveform.
trim_silence: true       # Whether to trim the start and end of silence.
trim_threshold_in_db: 60 # Need to tune carefully if the recording is not good.
trim_frame_size: 2048    # Frame size in trimming.
trim_hop_size: 512       # Hop size in trimming.
format: "npy"            # Feature file format. Only "npy" is supported.

~            `

**Comment by dathudeptrai** [comment]
i think it's not a bug, fmin, fmax must be pre-define.
