### ISSUE TITLE
Android example using Tacotron2 and mb-melgan

### ISSUE THREAD

**Issue by Zak-SA** [TensorSpeech/TensorFlowTTS#228]
Will you share  android Example using Tacotron2 and MB-Melgan anytime soon?

Thanks

**Comment by dathudeptrai** [comment]
@Zak-SA tacotron-2 so slow, can you try fastspeech ?

**Comment by Zak-SA** [comment]
@dathudeptrai 
I will try fastSpeech. But it would be good to have the android example for tacotron2

**Comment by Zak-SA** [comment]
@dathudeptrai 
When I tried to train Fastspeech2 I am getting this error:
Traceback (most recent call last):
  File "examples/fastspeech2/train_fastspeech2.py", line 400, in <module>
    main()
  File "examples/fastspeech2/train_fastspeech2.py", line 307, in main
    train_dataset = CharactorDurationF0EnergyMelDataset(
  File "./examples/fastspeech2/fastspeech2_dataset.py", line 98, in __init__
    assert (
AssertionError: Number of charactor, mel, duration, f0 and energy files are different
 

can you help?

Thanks

**Comment by kau1992** [comment]
@Zak-SA 
Did you extract duration using MFA  or Tacotron-2  ?   For fastspeech training duration required.

Please check below link -
Extract duration from MFA  - 
https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/mfa_extraction

Extract duration from Tacotron-2
https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/tacotron2#step-4-extract-duration-from-alignments-for-fastspeech

**Comment by dathudeptrai** [comment]
@Zak-SA did you read a tutorial carefully ?, did you extract duration from tacotron2 ?, the error is very clear `AssertionError: Number of charactor, mel, duration, f0 and energy files are different`, can you check it by urself ?

**Comment by Zak-SA** [comment]
@dathudeptrai I will check it again, Thanks for the links

**Comment by Zak-SA** [comment]
@dathudeptrai 
I did extract duration when I was training using the old gpu but I didn't use the same folder, I thought it was already there but I didn't use it. thanks

and I can extract duration from any checkpoint right? I don't need the final tacotron2 model, correct?

**Comment by Zak-SA** [comment]
@dathudeptrai i did extract the duration but the path was different. 
I did read the tutorial carefully but after replacing the gpu I preprocessed the data again and it added the speaker name on the dump folder while the duration where in the old dump folder. That's why i got confused because i know I did extract the duration. 
Thanks again for the help.

**Comment by tekinek** [comment]
@Zak-SA I think the safest and first try for duration extraction should go with Tactroton2. It needs you to train Tactron2 model first until around 60k steps:
https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/tacotron2#step-4-extract-duration-from-alignments-for-fastspeech

**Comment by Zak-SA** [comment]
@tekinek thanks for your reply.  I extracted the duration earlier when I got to step 54k. I may redo it again if you believe that 60k is better. I thought it would be ok for 50k+ step.

**Comment by tekinek** [comment]
@Zak-SA 54k should be enough. If the durations were extracted using Tacotron2, then your problem is more of man-made. Just double check your commands and their parameters.

**Comment by Zak-SA** [comment]
@tekinek 
Yes I explained above the problem. When I extracted the duration I was using my old gpu. So the folder name that contains the preprocessed data is "dump"
When i installed new gpu i decided to preprocess again but the updates added the speaker name for the dump folder, so I had two folders.  One had the old preprocessed data with duration extracted and the second one without it. 

The problem is solved now. Thank you for your help.

**Comment by Zak-SA** [comment]
When I tried to convert fastspeech2 to Tflite, I got this error:

from tensorflow_tts.processor.ZAKspeech import symbols, _symbol_to_id
ImportError: cannot import name 'symbols' from 'tensorflow_tts.processor.ZAKspeech' (/home/zak/venv/lib/python3.8/site-packages/tensorflow_tts/processor/ZAKspeech.py)

any ideas?

thanks
