### ISSUE TITLE
how to  fine tune model from .h5 file

### ISSUE THREAD

**Issue by billy800413** [TensorSpeech/TensorFlowTTS#229]
Hi, I want to tune model from .h5 file. But I find  --resume command should input ckpt file. So do I need to transfer  .h5 to ckpt first?

**Comment by ZDisket** [comment]
@billy800413 Please see https://github.com/TensorSpeech/TensorFlowTTS/issues/213#issuecomment-676857909

**Comment by dathudeptrai** [comment]
close in #231
