### ISSUE TITLE
The Dimension of durations obtained by MFA is not equal to the Dimension of ids?How to solve it?

### ISSUE THREAD

**Issue by Hymnhyz** [TensorSpeech/TensorFlowTTS#230]
Thank the author for u excellent work. When I trained my data set on fastspeeh2, I used MFA to get the durations, but when I trained the model, I found :
The Dimension of durations obtained by MFA is not equal to the Dimension of ids?
How to solve it?

**Comment by machineko** [comment]
len of durations array or sum of durations?
If its sum of durations then just run last step from [mfa_example](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/mfa_extraction)

**Comment by machineko** [comment]
Are you where following [mfa_example](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/mfa_extraction) tutorial?

**Comment by Hymnhyz** [comment]
Thanks for the reply, I solved this problem by commenting out TensorFlowTTS/preprocess/XXX_preprocess.yaml # trim_mfa: true

**Comment by dathudeptrai** [comment]
@Hymnhyz let close if the issue is solved.
