### ISSUE TITLE
Plans to implement Fast Speech 2S?

### ISSUE THREAD

**Issue by DanBigioi** [TensorSpeech/TensorFlowTTS#239]
Hey guys,

Just wondering whether you are planning on implementing the fully end to end Fast Speech 2S version of the model as detailed in the paper: https://arxiv.org/pdf/2006.04558.pdf

**Comment by dathudeptrai** [comment]
@DanBigioi  i implemented it before and saw the performance is the same as 2 stages FastSpeech + mb-melgan but hard to training so i do not want to public it.

**Comment by manmay-nakhashi** [comment]
@dathudeptrai shouldn't it be easy as it is direct text to waveform generation ?

**Comment by machineko** [comment]
@manmay-nakhashi Why should it be easy to train, its 2 models converted to one ofc. It would be harder to train you can look at 3.2.3 Ablation Study and see 2s version is very fragile and changes in energy and pitch can decrease quality very easily compared to 2 stage version.

**Comment by dathudeptrai** [comment]
as i said, i do not see any improvement when my fastspeech2s convergence (interms of both speed and quality) but i saw that it's very hard to training (hardest model i have ever trained). i won't public it in the near future.
