### ISSUE TITLE
How to export .h5 to .pb ？

### ISSUE THREAD

**Issue by MachineLP** [TensorSpeech/TensorFlowTTS#241]

**Comment by MariaMsu** [comment]
Maybe [this jupyter](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/notebooks/fastspeech2_inference.ipynb) [Save to Pb] will be helpfull

**Comment by dathudeptrai** [comment]
@MachineLP https://github.com/TensorSpeech/TensorFlowTTS/tree/master/notebooks

**Comment by MachineLP** [comment]
> Maybe [this jupyter](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/notebooks/fastspeech2_inference.ipynb) [Save to Pb] will be helpfull

Thanks

**Comment by MachineLP** [comment]
> @MachineLP https://github.com/TensorSpeech/TensorFlowTTS/tree/master/notebooks

Thanks
