### ISSUE TITLE
How should the text be processed during fastspeech2 inference?

### ISSUE THREAD

**Issue by Hymnhyz** [TensorSpeech/TensorFlowTTS#243]
Thank you for your excellent work. I am facing a problem that is how to deal with the text when fastspeech2 reasoning. I think that g2p is used in the code to give the result directly, but the pause of the phoneme obtained by MFA is different from that obtained by g2p. How to get the input similar to the training set during inference?

**Comment by machineko** [comment]
I mean g2p shouldn't add any pauses its just in my example code i add pause to end of every word for test purposes.
If you want to don't have SIL tokens after every word just change ->

```python
    def clean_g2p(self, g2p_text: list):
        data = []
        for i, txt in enumerate(g2p_text):
            if i == len(g2p_text) - 1:
                if txt != " " and txt != "SIL":
                    data.append("@" + txt)
                else:
                    data.append(
                        "@END"
                    )  # TODO try learning without end token and compare results
                break
            data.append("@" + txt) if txt != " " else data.append(
                "@SIL"
            )  # TODO change it in inference
        return data
```

to
```python
    def clean_g2p(self, g2p_text: list):
        data = []
        for i, txt in enumerate(g2p_text):
            if i == len(g2p_text) - 1:
                if txt != " " and txt != "SIL":
                    data.append("@" + txt)
                else:
                    data.append(
                        "@END"
                    )  # TODO try learning without end token and compare results
                break
            if txt != " ":
               data.append("@" + txt)
        return data
```

**Comment by machineko** [comment]
And for MFA phonemes and durations -> Silence is extracted from audio not from tokens so you can't follow that up in your code just from text you can mimic it using averages if you wanna.

**Comment by tekinek** [comment]
@Hymnhyz  Have you already trained a Fastspeech2 or just have done MFA alignment?

>> How to get the input similar to the training set during inference?

It is difficult to do an exact match, because what MFA thinks is a SIL might not be a SIL in your text or vice verse. But you can keep punctuation (such as ", : ; ?") in your text as a SIL during g2p for inference, so that the model possibly generates a short break accordingly.

**Comment by ZDisket** [comment]
@Hymnhyz You go through the g2p output and build a new array, replacing punctuation with silence like this:
https://github.com/ZDisket/TensorflowTTS/blob/3471204ceca2ca823f319e50b4dea696ec381d31/tensorflow_tts/processor/ljspeech.py#L235-L252

**Comment by Hymnhyz** [comment]
@tekinek  Ihave already trained a Fastspeech2 with MFA. When inferring, I used custom rules to segment the input text. I processed punctuation and some conjunctions. Am I doing this right? But this kind of rule needs to be carefully compiled, otherwise it may be very different from the input of MFA.

**Comment by Hymnhyz** [comment]
@ZDisket Thank you for your suggestion!

**Comment by Hymnhyz** [comment]
@machineko Can fastspeech2 be improved for each speaker, the model knows where to segment the input text? MFA changed the input of fastspeeh2 into an unpunctuated but silent phoneme style. The reasoning uses plain text with punctuation marks, and only uses punctuation marks as @SIL. Will the intonation and prosody model be learned automatically?
