### ISSUE TITLE
Error when inference FastSpeech 2

### ISSUE THREAD

**Issue by tienanh-1999** [TensorSpeech/TensorFlowTTS#245]
When I run these following code
![image](https://user-images.githubusercontent.com/47650134/92196859-6845ca80-ee9a-11ea-8e0b-a353a8a22eb1.png)

I got an error
![image](https://user-images.githubusercontent.com/47650134/92196906-7f84b800-ee9a-11ea-8aaf-be249aec746e.png)

The config is unchanged when training and inference.
Thank you !

**Comment by dathudeptrai** [comment]
if you want to load weight you need set is_build=True. If you set is_build=false then you need inference the model by passing fake input then load_weight.

**Comment by tienanh-1999** [comment]
Thank you !

**Comment by dathudeptrai** [comment]
I will close since this is not a bug. BTW, since you are a vietnamese, i need you read license before decide use this framework :)). (https://github.com/TensorSpeech/TensorFlowTTS#license)
