### ISSUE TITLE
Building TensorflowTTS C++ Inference on mac osx

### ISSUE THREAD

**Issue by aitalk** [TensorSpeech/TensorFlowTTS#248]
does anyone have instruction on how to build TensorflowTTS C++ Inference on mac machine? Thanks.

**Comment by ZDisket** [comment]
@aitalk I certainly don't, other than the fact that all libraries should be cross-platform, so you'll have to compile everything from scratch.

**Comment by aitalk** [comment]
I tried. but i was able to build the required libfst and Phonetisaurus . But when compiling then cppwin, I get following errors:

In file included from TensorflowTTSCppInference/EnglishPhoneticProcessor.cpp:1:
In file included from TensorflowTTSCppInference/EnglishPhoneticProcessor.h:6:
In file included from ../../../Phonetisaurus/src/include/PhonetisaurusScript.h:39:
In file included from ../../../Phonetisaurus/src/include/PhonetisaurusRex.h:47:
../../../Phonetisaurus/src/include/loadclusters.h:8:44: error: unknown type name 'SymbolMap12M'
int LoadClusters (const SymbolTable* syms, SymbolMap12M* clusters,
                                           ^
../../../Phonetisaurus/src/include/loadclusters.h:9:19: error: unknown type name 'SymbolMapM21'
                  SymbolMapM21* invclusters);
                  ^
In file included from TensorflowTTSCppInference/EnglishPhoneticProcessor.cpp:1:
                                           ^
