### ISSUE TITLE
Parameters for MB MelGAN for 24 kHz

### ISSUE THREAD

**Issue by mikus** [TensorSpeech/TensorFlowTTS#249]
Hi, I wanted to ask what should be the correct parameters for MB MelGAN with following inputs:
* sampling rate: 24 kHz
* frame shift: 12.5 ms
* frame length: 50 ms

Should I change only `sampling_rate` and `hop_size` in training configuration and `sampling_rate`, `fft_size`, `hop_size` and `win_length` in preprocessing config, or should I also tweak network parameters like `fft_lengths` in `stft_loss_params`?

Moreover, could you also help me to investigate why the generated audio is shorter than the reference one. It contains only 273 frames whereas 320 in reference.
![generated audio is shorter than the reference one](https://user-images.githubusercontent.com/834701/92250518-de165a00-eecb-11ea-9e3d-e12ca02b05aa.png)

Here are my configs:
* [preprocessing](https://gist.github.com/mikus/e971ba63101d98ae774b9acacd39a43a)
* [training](https://gist.github.com/mikus/34717fe4db82a425f0ca9c08b83d9cc3)

**Comment by dathudeptrai** [comment]
@mikus ur preprocessing and training cofig should follow baker config (this dataset is also 24K). ur preprocesisng config is ok but wrong in training config. Let see ur `upsample_scales` (https://gist.github.com/mikus/34717fe4db82a425f0ca9c08b83d9cc3#file-mbmelgan_training-yaml-L24), that is wrong. Let say multiple(upsample_scales) should equal hop_size. See baker training config here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/multiband_melgan/conf/multiband_melgan.baker.v1.yaml#L24) and you can see 3*5*5 = 300 while ur config is 8 * 4 * 2 = 256 :).

**Comment by mikus** [comment]
Thx @dathudeptrai, it totally makes sense. :)
Other network parameters should stay as they are? In particular the size of FFT in the STFT loss?

**Comment by dathudeptrai** [comment]
@mikus let use the same baker config first and see the performance :)
