### ISSUE TITLE
Multi-speaker audio samples for FastSpeech/FastSpeech 2

### ISSUE THREAD

**Issue by ming024** [TensorSpeech/TensorFlowTTS#250]
It is really an astonishing large project.

I have seen that there is multi-speaker support in the preprocessing scripts and model configs. It will be great if anyone can share the multi-speaker audio samples generated with the non-autoregressive models such as FastSpeech and FastSpeech2.

**Comment by dathudeptrai** [comment]
[multi-lingual-multi-speaker.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5177535/multi-lingual-multi-speaker.zip)

This is a result of my model trained on M-ailab dataset (partly) with other datasets, let say this is an audio generated by multi-lingual-multi-speaker dataset, the model is modify a bit to work with multi lingual, i also tested the public code here for multi speaker and it work fine.

**Comment by dathudeptrai** [comment]
@ming024 if you don't have any question, pls close issue :D

**Comment by ming024** [comment]
I think the audio quality is very good. How many speakers are there in your datasets?

**Comment by dathudeptrai** [comment]
> I think the audio quality is very good. How many speakers are there in your datasets?

Sorry, that is private infomation :D.

**Comment by ZDisket** [comment]
I have some too from MFA-aligned FS2. This is 11 speaker samples, total 18 hours of audio distributed over 136 speakers (distribution not uniform, some have as little as 20 seconds while others 50 minutes)
[11samples-50ks.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5212413/11samples-50ks.zip)

**Comment by ming024** [comment]
@dathudeptrai @ZDisket Thanks a lot, I will close this issue #250
