### ISSUE TITLE
Loading pb model error

### ISSUE THREAD

**Issue by unparalleled-ysj** [TensorSpeech/TensorFlowTTS#251]
Hi, use the latest code to train the fastspeech2 model, which can be converted to pb format correctly, but an error occurs when loading the pb model

File "test_scripts/inference.py", line 61, in LoadModelFromPB
    model = tf.saved_model.load(model_path)
  File "/root/anaconda3/envs/pb/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 578, in load
    return load_internal(export_dir, tags)
  File "/root/anaconda3/envs/pb/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 604, in load_internal
    export_dir)
  File "/root/anaconda3/envs/pb/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 116, in __init__
    meta_graph.graph_def.library))
  File "/root/anaconda3/envs/pb/lib/python3.7/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 311, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(copy)
  File "/root/anaconda3/envs/pb/lib/python3.7/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 63, in function_def_to_graph
    importer.import_graph_def_for_function(graph_def, name="")
  File "/root/anaconda3/envs/pb/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 412, in import_graph_def_for_function
    graph_def, validate_colocation_constraints=False, name=name)
  File "/root/anaconda3/envs/pb/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: indices.shape[-1] must be <= params.rank, but saw indices shape: [1,?,1] and params shape: [] for '{{node embeddings/position_embeddings/GatherNd}} = ResourceGatherNd[Tindices=DT_INT32, _output_shapes=[[1,?,256]], dtype=DT_FLOAT](embeddings_position_embeddings_gathernd_resource:0, embeddings/position_embeddings/ExpandDims:0)' with input shapes: [], [1,?,1].

It seems that there is a problem with the updated embedding code

**Comment by dathudeptrai** [comment]
hi, i just ran a notebook (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/notebooks/fastspeech2_inference.ipynb) and everything fine.

**Comment by unparalleled-ysj** [comment]
The model trained in the previous version is fine using this notebook, but the model trained with the latest code will have the above problems，are you running with the latest model

**Comment by dathudeptrai** [comment]
@unparalleled-ysj the logic of model didn't change in newest version, that's why the old pretrained can be load into the newest code.

**Comment by unparalleled-ysj** [comment]
@dathudeptrai  No, I trained a single-speaker mode, the model in .h5 format can be loaded and used correctly, and it can also be converted to a model in .pb format, but the converted model in .pb format cannot be loaded correctly

**Comment by ZhaoZeqing** [comment]
@dathudeptrai I trained a multispeaker Tacotron2 model (modified **n_speakers** in config file), then converted it from .h5 to pb sucessfully, but loaded the pb model with the following error:

ValueError: indices.shape[-1] must be <= params.rank, but saw indices shape: [?,1] and params shape: [] for '{{node encoder/embeddings/speaker_embeddings/GatherNd}} = ResourceGatherNd[Tindices=DT_INT32, _output_shapes=[[?,512]], dtype=DT_FLOAT](encoder_embeddings_speaker_embeddings_gathernd_resource:0, encoder/embeddings/speaker_embeddings/ExpandDims:0)' with input shapes: [], [?,1].

**Comment by ZhaoZeqing** [comment]
@dathudeptrai It's OK when I fixed it the same to fastspeech2 at https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/models/tacotron2.py#L79-L80 :)

**Comment by engineergun** [comment]
> @dathudeptrai It's OK when I fixed it the same to fastspeech2 at https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/models/tacotron2.py#L79-L80 :)

@ZhaoZeqing i have same problem can u share more info, i couldnt understand.

**Comment by engineergun** [comment]
> > > @dathudeptrai It's OK when I fixed it the same to fastspeech2 at https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/models/tacotron2.py#L79-L80 :)
> > 
> > 
> > @ZhaoZeqing i have same problem can u share more info, i couldnt understand.
> 
> @engineergun Sorry, I forget it. Maybe try this [30d7bcc](https://github.com/TensorSpeech/TensorFlowTTS/commit/30d7bcc186b0bff9ef1bfc5c512ba5e28b96b841)

thank you for your reply. i tried it but just first speaker's voice was understandable other speakers were generating pure noise. by the way in the evaluation steps genereted sounds were very good.

**Comment by ZhaoZeqing** [comment]
> > > > @dathudeptrai It's OK when I fixed it the same to fastspeech2 at https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/models/tacotron2.py#L79-L80 :)
> > > 
> > > 
> > > @ZhaoZeqing i have same problem can u share more info, i couldnt understand.
> > 
> > 
> > @engineergun Sorry, I forget it. Maybe try this [30d7bcc](https://github.com/TensorSpeech/TensorFlowTTS/commit/30d7bcc186b0bff9ef1bfc5c512ba5e28b96b841)
> 
> thank you for your reply. i tried it but just first speaker's voice was understandable other speakers were generating pure noise. by the way in the evaluation steps genereted sounds were very good.

@engineergun If you give the correct speaker id in when processing dataset? like this https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech2_libritts/fastspeech2_dataset.py#L121
