### ISSUE TITLE
fastspeech2 data 

### ISSUE THREAD

**Issue by fly2mun** [TensorSpeech/TensorFlowTTS#254]
hello.
i try to make the fastspeech2 model used by Ljspeech data set.
but i can not train any more.

1. try to ljspeech dataset.
tensorflow-tts-preprocess
tensorflow-tts-normalize
2. I can train tacotron2 by ljspeech.

But fastspeech2 train fail.

Traceback (most recent call last):
  File "examples/fastspeech2/train_fastspeech2.py", line 412, in <module>
    main()
  File "examples/fastspeech2/train_fastspeech2.py", line 325, in main
    mel_length_threshold=mel_length_threshold,
  File "./examples/fastspeech2/fastspeech2_dataset.py", line 101, in __init__
    ), f"Number of charactor, mel, duration, f0 and energy files are different"
AssertionError: Number of charactor, mel, duration, f0 and energy files are different

please help me.

**Comment by dathudeptrai** [comment]
you need extract duration before training FastSpeech2, you can use tacotron2 or MFA to do that.

**Comment by fly2mun** [comment]
I see, Thank you for your cooperation.
