### ISSUE TITLE
How to speed up inference using tensorrt？

### ISSUE THREAD

**Issue by MachineLP** [TensorSpeech/TensorFlowTTS#255]

**Comment by dathudeptrai** [comment]
i will let you try tenssort and if you see any speed-up pls let me know :D

**Comment by machineko** [comment]
@MachineLP https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html There is full tutorial I was using it to get ~20-30% speed-up for Fast speech on fp16

**Comment by MachineLP** [comment]
> @MachineLP https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html There is full tutorial I was using it to get ~20-30% speed-up for Fastspeech2 on fp16



> @MachineLP https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html There is full tutorial I was using it to get ~20-30% speed-up for Fastspeech2 on fp16

thanks

**Comment by MachineLP** [comment]
> i will let you try tenssort and if you see any speed-up pls let me know :D

ok

**Comment by MachineLP** [comment]
> @MachineLP https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html There is full tutorial I was using it to get ~20-30% speed-up for Fastspeech2 on fp16

thanks，have you ever tried it？  can you share your code？

**Comment by machineko** [comment]
> > @MachineLP https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html There is full tutorial I was using it to get ~20-30% speed-up for Fastspeech2 on fp16
> 
> thanks，have you ever tried it？ can you share your code？

I dont have code right now but I was using slightly modified code from this tutorial and as i said it give ~20-30% speed up using fp16

**Comment by MachineLP** [comment]
> > > @MachineLP https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html There is full tutorial I was using it to get ~20-30% speed-up for Fastspeech2 on fp16
> > 
> > 
> > thanks，have you ever tried it？ can you share your code？
> 
> I dont have code right now but I was using slightly modified code from this tutorial and as i said it give ~20-30% speed up using fp16

Follow the tutorial with an error：
converter.convert()
  File "/home/suser/anaconda3/envs/machinelp/lib/python3.7/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1087, in convert
    frozen_func = convert_to_constants.convert_variables_to_constants_v2(func)
  File "/home/suser/anaconda3/envs/machinelp/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 679, in convert_variables_to_constants_v2
    func, lower_control_flow, aggressive_inlining)
  File "/home/suser/anaconda3/envs/machinelp/lib/python3.7/site-packages/tensorflow/python/framework/convert_to_constants.py", line 526, in _convert_variables_to_constants_v2_impl
    raise ValueError("Cannot find the Placeholder op that is an input "
ValueError: Cannot find the Placeholder op that is an input to the ReadVariableOp.


```
from tensorflow.python.compiler.tensorrt import trt_convert as trt
converter = trt.TrtGraphConverterV2(input_saved_model_dir='tf_savedmodel')
converter.convert()
converter.save('trt_savedmodel')
```

**Comment by MachineLP** [comment]
> https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html

Tensorflow version 2.2/2.3, tutorial only for Tensorflow2.0?

**Comment by machineko** [comment]
> > https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html
> 
> Tensorflow version 2.2/2.3, the tutorial only for Tensorflow2.0?

I was using TF 2.2 also u can check [tf-trt](https://www.tensorflow.org/api_docs/python/tf/experimental/tensorrt/Converter)

**Comment by ahmedalbahnasawy** [comment]
@machineko sorry for reopening the issue. 
My tensorflow-gpu version is 2.3.1.  I want to ask about the Input for a single inference call, for a network that has 5 input tensors as fastspeech2 for generating corresponding TRT engines and save it. 
`converter.build(input_fn=my_input_fn)`

**Comment by machineko** [comment]
> @machineko sorry for reopening the issue.
> My tensorflow-gpu version is 2.3.1. I just wanted to ask about the Input for a single inference call, for a network that has 5 input tensors as fastspeech2 for generating corresponding TRT engines and save it.
> `converter.build(input_fn=my_input_fn)`

I was using multiple inputs but I don't remember if this was just dict or tuple passed to an input method call or smth else but it should be easily found in TRT or TF-TRT docs.

**Comment by ahmedalbahnasawy** [comment]
@machineko from the TRT docs, converter.build expects you to send it a tuple containing the inputs .

` 
def build_trt():
    for _ in range(10):
         input_ids= [46, 11, 49, 52, 59, 42, 11, 62, 52, 58, 11, 56, 52, 11, 50, 58, 40, 45, 7, 148]      
         input_ids=tf.expand_dims(tf.convert_to_tensor(input_ids, dtype=tf.int32), 0)
         speaker_ids=tf.convert_to_tensor([0], dtype=tf.int32)
         speed_ratios=tf.convert_to_tensor([1.0], dtype=tf.float32)
         f0_ratios =tf.convert_to_tensor([1.0], dtype=tf.float32)
         energy_ratios =tf.convert_to_tensor([1.0], dtype=tf.float32)
         yield (input_ids,speaker_ids,speed_ratios,f0_ratios,energy_ratios)

converter.build(input_fn=build_trt)
`
but i'm getting :
TypeError: pruned(energy_ratios, f0_ratios, input_ids, speaker_ids, speed_ratios, unknown, unknown_0, unknown_1, unknown_10, unknown_100, unknown_101, unknown_102, unknown_103, unknown_104, unknown_105, unknown_106, unknown_107, unknown_108, unknown_109, unknown_11,............)
