### ISSUE TITLE
Colab Tflite convertion code is not workig.

### ISSUE THREAD

**Issue by fly2mun** [TensorSpeech/TensorFlowTTS#257]
Thank you greate tensorflow tts 
I try to working test for tensorflow tts examples. But i can find working failed. 

2020/07/05 Support Convert Tacotron-2, FastSpeech to Tflite. Pls see the colab. Thank @jaeyoo from TFlite team for his support.

Please check it colab code. 

Thanks moon

**Comment by dathudeptrai** [comment]
Fixed it. There is a bug on tf-nightly, but the old version is ok. I will report the bug to tensorflow.

**Comment by fly2mun** [comment]
Hello i checked now.
It's work perfect.
Thanks


2020년 9월 10일 (목) 오후 12:05, dathudeptrai <notifications@github.com>님이 작성:
