### ISSUE TITLE
train fastspeech2.v1 error：train_mel_loss_before = nan  & train_mel_loss_after = nan

### ISSUE THREAD

**Issue by MachineLP** [TensorSpeech/TensorFlowTTS#258]
[train]:  48%|████▊     | 95400/200000 [02:45<7:39:06,  3.80it/s]2020-09-10 11:52:14,447 (base_trainer:831) INFO: (Step: 95400) train_duration_loss = 0.0353.
2020-09-10 11:52:14,448 (base_trainer:831) INFO: (Step: 95400) train_f0_loss = 0.0659.
2020-09-10 11:52:14,448 (base_trainer:831) INFO: (Step: 95400) train_energy_loss = 0.0505.
2020-09-10 11:52:14,449 (base_trainer:831) INFO: (Step: 95400) train_mel_loss_before = nan.
2020-09-10 11:52:14,449 (base_trainer:831) INFO: (Step: 95400) train_mel_loss_after = nan.

**Comment by dathudeptrai** [comment]
> [train]: 48%|████▊ | 95400/200000 [02:45<7:39:06, 3.80it/s]2020-09-10 11:52:14,447 (base_trainer:831) INFO: (Step: 95400) train_duration_loss = 0.0353.
> 2020-09-10 11:52:14,448 (base_trainer:831) INFO: (Step: 95400) train_f0_loss = 0.0659.
> 2020-09-10 11:52:14,448 (base_trainer:831) INFO: (Step: 95400) train_energy_loss = 0.0505.
> 2020-09-10 11:52:14,449 (base_trainer:831) INFO: (Step: 95400) train_mel_loss_before = nan.
> 2020-09-10 11:52:14,449 (base_trainer:831) INFO: (Step: 95400) train_mel_loss_after = nan.

stop training, load pretrained and continue training without `mixed_precision`.

**Comment by MachineLP** [comment]
> > [train]: 48%|████▊ | 95400/200000 [02:45<7:39:06, 3.80it/s]2020-09-10 11:52:14,447 (base_trainer:831) INFO: (Step: 95400) train_duration_loss = 0.0353.
> > 2020-09-10 11:52:14,448 (base_trainer:831) INFO: (Step: 95400) train_f0_loss = 0.0659.
> > 2020-09-10 11:52:14,448 (base_trainer:831) INFO: (Step: 95400) train_energy_loss = 0.0505.
> > 2020-09-10 11:52:14,449 (base_trainer:831) INFO: (Step: 95400) train_mel_loss_before = nan.
> > 2020-09-10 11:52:14,449 (base_trainer:831) INFO: (Step: 95400) train_mel_loss_after = nan.
> 
> stop training, load pretrained and continue training without `mixed_precision`.

ok
