### ISSUE TITLE
The  inference process in on GPU or CPU

### ISSUE THREAD

**Issue by peter05010402** [TensorSpeech/TensorFlowTTS#259]

**Comment by dathudeptrai** [comment]
what do you mean ?

**Comment by peter05010402** [comment]
Is possible inference on CPU？

**Comment by ZDisket** [comment]
@peter05010402 Yes, CPU inference is possible and very fast. I have about 0.243 RTF FastSpeech2 + Multi-Band MelGAN with LJSpeech settings when doing C++ inference on an Athlon x4 860k.

**Comment by peter05010402** [comment]
@ZDisket thank you for your reply. I'll try it.

**Comment by peter05010402** [comment]
> @peter05010402 Yes, CPU inference is possible and very fast. I have about 0.243 RTF FastSpeech2 + Multi-Band MelGAN with LJSpeech settings when doing C++ inference on an Athlon x4 860k.
Hi @ZDisket , I run C++ inference on CPU, it cost more than 500ms for inference "hello", detail as follow:
![image](https://user-images.githubusercontent.com/42974031/93348539-eb86f900-f868-11ea-8327-7ebd8f248f7f.png)
