### ISSUE TITLE
Convert Multiband MelGAN to TFlite

### ISSUE THREAD

**Issue by tienanh-1999** [TensorSpeech/TensorFlowTTS#260]
I got a problem when convert MBmelgan to TFlite. The tf-nightly is _2.4.0-dev20200913_. 

The code is captured as below:

![image](https://user-images.githubusercontent.com/47650134/93036134-320e0500-f669-11ea-8c25-a983a73ad3a9.png)

Then I got an _ConverterError_:

![image](https://user-images.githubusercontent.com/47650134/93036185-5a95ff00-f669-11ea-9651-ba400b10cc41.png)

Thank you in advance.

**Comment by dathudeptrai** [comment]
seem you use weightnorm :))

**Comment by tienanh-1999** [comment]
yes :D using weightnorm cannot convert to TFlite ?

**Comment by dathudeptrai** [comment]
@tienanh-1999 i can :)) but need some trick :)), i think you need finetune ur model without weightnorm :))>

**Comment by tienanh-1999** [comment]
successful :)) thank you !
