### ISSUE TITLE
pwg vs. mb-melgan quality?

### ISSUE THREAD

**Issue by LLianJJun** [TensorSpeech/TensorFlowTTS#263]
hi.

Generally, Which of the best quality is pwg or mb-melgan?

In my experiment, pwg showed better performance, but I wonder it is a proper experiment.

**Comment by Hongpeng1992** [comment]
same results

**Comment by dathudeptrai** [comment]
pwg is sightly better than mb-melgan but do not forget that mb-melgan is 1x faster than pwgan :)).

**Comment by LLianJJun** [comment]
@Hongpeng1992 
If so, my mb-melgan training is wrong.

**Comment by LLianJJun** [comment]
@dathudeptrai 
I trained pwg and mb-melgan in the kan-bayashi git...
Is there any difference between the code of kan-bayashi git and yours?

Could it be less convergent? (kan-bayashi code)
There is a significant difference in quality.

I am training your mb-melgan code with the same data.

**Comment by dathudeptrai** [comment]
the implementation is same so you can convert the weight from kan's repo to mine. About convergence speed, i think my TF implementation convergence faster. Before create this repo, i also use kan's code.

**Comment by LLianJJun** [comment]
@dathudeptrai 
thanks.
But, in my memory,  you implemented 'mb-melgan' before kan's repo. Is that correct?

**Comment by alexdemartos** [comment]
Hi @dathudeptrai . Any advice on training PWG/MB-MelGAN on "difficult" (large number of speakers) dataset? What are the config parameters that better trade off audio quality vs. speed (i.e. making the models bigger and slower, but better quality)?

Related question: has anyone tried to include learnt speaker embeddings from the FastSpeech/Taco2 models as vocoder inputs?
