### ISSUE TITLE
Quick question regarding data structure.

### ISSUE THREAD

**Issue by jun-danieloh** [TensorSpeech/TensorFlowTTS#267]
```
|   |- stats.npy
|   |- stats_f0.npy
|   |- stats_energy.npy
|   |- train_utt_ids.npy
|   |- valid_utt_ids.npy
```

I am looking at code but not able to find these files usages. Are these files are used while training?

**Comment by dathudeptrai** [comment]
@jun-danieloh stats is mel_stat and it will use to normalize the mel, you can see a folder named `norm-feats`. `stats_f0` and `stats_energy` will use to normalize f0/energy in FastSpeech2.

**Comment by jun-danieloh** [comment]
@dathudeptrai `stats.npy` is used for normalizing `*-raw-feats.npy` to `*-norm-feats.npy`, right?

**Comment by dathudeptrai** [comment]
Yes

Vào Th 6, 18 thg 9, 2020 lúc 12:12 Daniel Oh <notifications@github.com> đã
viết:
