### ISSUE TITLE
Synthesize tacotron2 with gl

### ISSUE THREAD

**Issue by ethanstan** [TensorSpeech/TensorFlowTTS#268]
Hello. I fine tuned a tacotron2 model with my own dataset. I would like to synthesize some audio using Griffin lim before proceeding to vocoder. Is this possible? I see the tensorflow gl notebook but it doesn’t have a place for input text and I’m not sure how to piece it together.

Also would be great if it could save synthesized audio during training under tensorboard :)

Thanks!!!

**Comment by machineko** [comment]
Here you have example how to use gl in training [gl](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech2_libritts/train_fastspeech2.py#L171)
