### ISSUE TITLE
Cannot get the tensorboard for training

### ISSUE THREAD

**Issue by sabby993** [TensorSpeech/TensorFlowTTS#270]
Hi there, I am training the tacotron 2 model for a TTS for New Zealand English and I wanted to examine my training graphs with tensorboard. However, I can't get the tensorboard to work with the train_tacotron2.py file as there is some attribute error that I am getting when I am adding the callback attribute to the trainer.fit function. Since I am new to tensorflow and tensorboard, I just wanted to know what code to use and which logs to use in this case to obtain the different tensorboard graphs. This is the changes I did to the code of the train_tacotron2.py --->

![Capture](https://user-images.githubusercontent.com/68219507/93852131-91bd7d80-fd05-11ea-82d7-f15a7d57e774.JPG)

Please can you let me know what I am doing wrong as I am getting an error --  TypeError: fit() got an unexpected keyword argument 'callbacks'.

**Comment by ZDisket** [comment]
@sabby993 Can you state what you want to do more specifically? Because the training scripts already output Tensorboard logs with charts to the `outdir`.

**Comment by sabby993** [comment]
@ZDisket I am not training to the complete 200k steps because I am interrupting the execution in between 4k steps. Then I am not getting the tensorboard after interrupting. So I wanted to get the tensorboard for 4k steps only.

**Comment by ZDisket** [comment]
@sabby993 That's unusual, even when interrupting I still get logs.

**Comment by dathudeptrai** [comment]
@sabby993 Trainer is our designed Class not Model so Trainer.fit is not Model.fit then it does not include callbacks here.

**Comment by sabby993** [comment]
@dathudeptrai Ok...so to get the tensorboard, I just need to refer to the logs saved at outdir?

**Comment by dathudeptrai** [comment]
> @dathudeptrai Ok...so to get the tensorboard, I just need to refer to the logs saved at outdir?

yes, the tensorboard in outdir :))

**Comment by sabby993** [comment]
Ok thank you for clearing that up. Much appreciated. 👍🏼
