### ISSUE TITLE
How do I prepare a dataset in another language?

### ISSUE THREAD

**Issue by Nistrian** [TensorSpeech/TensorFlowTTS#277]
I have a normalized dataset in Russian that follows the ljspeech format. How can I skip the text normalization step? When I run `tensorflow-tts-preprocess --rootdir ./dataset --outdir ./dump --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech `following the instructions, I get the error:

> Traceback (most recent call last):
>   File "/usr/local/bin/tensorflow-tts-preprocess", line 8, in <module>
>     sys.exit(preprocess())
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/bin/preprocess.py", line 371, in preprocess
>     cleaner_names=dataset_cleaner[config["dataset"]],
>   File "<string>", line 14, in __init__
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/processor/base_processor.py", line 63, in __post_init__
>     self.create_items()
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/processor/ljspeech.py", line 148, in create_items
>     self.items = [self.split_line(self.data_dir, line, "|") for line in f]
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/processor/ljspeech.py", line 148, in <listcomp>
>     self.items = [self.split_line(self.data_dir, line, "|") for line in f]
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_tts/processor/ljspeech.py", line 153, in split_line
>     text_norm = parts[self.positions["text_norm"]]
> IndexError: list index out of range

**Comment by dathudeptrai** [comment]
@Nistrian you should write your own Processor. Pls refer all supported processor here (https://github.com/TensorSpeech/TensorFlowTTS/tree/master/tensorflow_tts/processor).
