### ISSUE TITLE
Training melgan Error

### ISSUE THREAD

**Issue by peter05010402** [TensorSpeech/TensorFlowTTS#281]
Hi
I have finished: 
"tensorflow-tts-preprocess --rootdir ./[ljspeech/kss/baker/libritts] --outdir ./dump_[ljspeech/kss/baker/libritts] --config preprocess/[ljspeech/kss/baker]_preprocess.yaml --dataset [ljspeech/kss/baker/libritts]
tensorflow-tts-normalize --rootdir ./dump_[ljspeech/kss/baker/libritts] --outdir ./dump_[ljspeech/kss/baker/libritts] --config preprocess/[ljspeech/kss/baker/libritts]_preprocess.yaml --dataset [ljspeech/kss/baker/libritts]"

when I run "CUDA_VISIBLE_DEVICES=0 python examples/melgan/train_melgan.py \
  --train-dir ./dump/train/ \
  --dev-dir ./dump/valid/ \
  --outdir ./examples/melgan/exp/train.melgan.v1/ \
  --config ./examples/melgan/conf/melgan.v1.yaml \
  --use-norm 1
  --generator_mixed_precision 0 \
  --resume ""   "

got error:

![image](https://user-images.githubusercontent.com/42974031/94396229-1429bf80-0194-11eb-8210-694f4412dd54.png)
![image](https://user-images.githubusercontent.com/42974031/94396271-27d52600-0194-11eb-992e-d7b497b6fa30.png)

**Comment by dathudeptrai** [comment]
@peter05010402 can you run Mb-melgan instead, BtW, can you share me ur preprocess config and training config ?
