### ISSUE TITLE
Tensorflow TTS requires TF 2.3 minimum??

### ISSUE THREAD

**Issue by Tetsujinfr** [TensorSpeech/TensorFlowTTS#282]
hi

in the readme it says that TF TTS requires TF 2.2/2.3 (it recommends the latest 2.3 etc sure). I have TF2.2 installed with GPU support, and I cannot upgrade to 2.3, but I assume TTS should still work.

Now, when I install from source, I have the following error message:
> ERROR: Could not find a version that satisfies the requirement tensorflow-gpu>=2.2.0 (from TensorFlowTTS==0.0) (from versions: none)
> ERROR: No matching distribution found for tensorflow-gpu>=2.2.0 (from TensorFlowTTS==0.0)

Am I supposed to tweak the install process manually to authorize it to continue with my TF 2.2 install ?

Am I stuck? I am under Jetson NX with Jetpack 4.4 (Cuda 10.2, Cudnn 8.02) on ARM64, so I am trying to avoid re-installing my TF 2.2 NVidia distrib here.

Thanks for our help on this.

**Comment by dathudeptrai** [comment]
@Tetsujinfr you can comment out this line https://github.com/TensorSpeech/TensorFlowTTS/blob/master/setup.py#L25 to avoid re-install TF

**Comment by Tetsujinfr** [comment]
thanks , yes what I did for TF and for TFA too since I did install it from source separately.
battling with the llvmlite install now, but that is a classical pain on the jetson, hopefuly i will get through it.
Closing this issue for now given I have passed the initial struggle.

Thanks for your helpful quick reply
