### ISSUE TITLE
does robotic sound like voice come from small network or alignment issues ? (in fastspeech2 plus mb-melgan) 

### ISSUE THREAD

**Issue by manmay-nakhashi** [TensorSpeech/TensorFlowTTS#284]

**Comment by dathudeptrai** [comment]
i do not know :D. Maybe both :d

**Comment by manmay-nakhashi** [comment]
@dathudeptrai can it be something other then this two ? :sweat_smile:

**Comment by dathudeptrai** [comment]
@manmay-nakhashi dataset quality :))). FastSpeech is limitted, i still not better than Autoregressive model as Tacotron2 in all datasets :D.
