### ISSUE TITLE
Can it run in eager excution mode?

### ISSUE THREAD

**Issue by lukewys** [TensorSpeech/TensorFlowTTS#285]
Hi, thanks very much for your project. I am playing around and want to do some changes to the model. However, it seems that the base_trainer basically wrapped everything in tf.function. I want to get the shape of the tensor in the forward pass as int, i.e. `last_decoder_hidden_states.shape[1]`. 

In eager execution, things would be a lot easier as `last_decoder_hidden_states.shape[1].numpy()`

It seems impossible in graph mode. Is there any way to get the shape or change the running mode to eager execution? Thanks very much in advance!

**Comment by dathudeptrai** [comment]
@lukewys tf.config.run_functions_eagerly

**Comment by lukewys** [comment]
Hi @dathudeptrai , thanks very much for that!
