### ISSUE TITLE
TFLite models requires TF >=2.3?

### ISSUE THREAD

**Issue by Tetsujinfr** [TensorSpeech/TensorFlowTTS#288]
hi

I managed to get Tensorflow TTS infer properly the fastspeech model on Jetson NX, with Jetpack 4.4 (Cuda 10.2, Cudnn 8, Tensorflow 2.2 using GPU). So far so good.

Now, the full model is memory hungry and slow to run on the Jetson so I am trying to convert the fastspeech model (120mb) into a tflite optimized model.
In did leverage the colab notebook which I tweaked a bit to get that done, but I have the following error:
> 
> cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-01 23:34:23.227043: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
> 2020-10-01 23:34:23.228054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 656 MB memory) -> physical GPU (device: 0, name: Xavier, pci bus id: 0000:00:00.0, compute capability: 7.2)
> 2020-10-01 23:34:42.198966: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:824] Optimization results for grappler item: graph_to_optimize
> 2020-10-01 23:34:43.836437: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:826]   constant_folding: Graph size after: 2125 nodes (-224), 2510 edges (-222), time = 12833.0518ms.
> 2020-10-01 23:34:43.836598: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:826]   constant_folding: Graph size after: 2125 nodes (0), 2510 edges (0), time = 494.191ms.
> Traceback (most recent call last):
>   File "tflite_conv.py", line 39, in <module>
>     tflite_model = converter.convert()
>   File "/media/tetsfr/SSD/tf2/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 483, in convert
>     _get_tensor_name(tensor), shape_list))
> ValueError: None is only supported in the 1st dimension. Tensor 'input_ids' has invalid shape '[1, None]'.

**=> Does someone have an idea? Help please ?**
(when I run the colab notebook the coversion works well, but it seems I can not use the tflite model obtained from the colab instance, likely due to optimisations specific to the colab server GPU which is different from the Volta I have on the Jetson NX)

Here is the conversion code I am using and which through the error above:
```
import tensorflow as tf
import yaml
import numpy as np
import matplotlib.pyplot as plt
from tensorflow_tts.processor import LJSpeechProcessor
from tensorflow_tts.processor.ljspeech import LJSPEECH_SYMBOLS

# Load model - FastSpeech
from tensorflow_tts.configs import FastSpeechConfig
from tensorflow_tts.models import TFFastSpeech

with open('fastspeech_config.yml') as f:
    config = yaml.load(f, Loader=yaml.Loader)
config = FastSpeechConfig(**config["fastspeech_params"])
fastspeech = TFFastSpeech(config=config, enable_tflite_convertible=True, name="fastspeech")
fastspeech._build()
fastspeech.load_weights("fastspeech-150k.h5")

## Convert to TF Lite
fastspeech_concrete_function = fastspeech.inference_tflite.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_functions(
    [fastspeech_concrete_function]
)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

# Save the TF Lite model.
with open('fastspeech_quant.tflite', 'wb') as f:
  f.write(tflite_model)
print('Model size is %f MBs.' % (len(tflite_model) / 1024 / 1024.0) )

```

thanks

**Comment by dathudeptrai** [comment]
@Tetsujinfr you should install tf-nightly==2.4.0-dev20200630. See colab here (https://colab.research.google.com/drive/1HudLLpT9CQdh2k04c06bHUwLubhGTWxA?usp=sharing#scrollTo=mvLDbeJzQFeh). TF 2.3 not yet support dynamic shape.

**Comment by Tetsujinfr** [comment]
ok thanks that is very useful. Unfortunately it means I have to build it from source on the Jetson (only 2.2 has a package available), that might be quite tricky but I will give it a try. I am closing this issue given the root cause is identified and clear.
thanks again
