### ISSUE TITLE
tacotron2/extract_duration.py  Error

### ISSUE THREAD

**Issue by peter05010402** [TensorSpeech/TensorFlowTTS#289]
After finish "tacotron2/train_tacotron2.py",  I run "tacotron2/extract_duration.py", got error as follow:

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/42974031/95003962-baa01580-0617-11eb-8021-87c99e0ddce2.png">

**Comment by dathudeptrai** [comment]
@peter05010402 can you print(d) after (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/extract_duration.py#L181). Seem your `real_char_length` is not correct, and can you give me a alignment figure of ur tacotron2 ?

**Comment by qianhui-wan** [comment]
Hey @dathudeptrai I had the same error when extracting durations.

```
Traceback (most recent call last):
  File "extract_duration.py", line 228, in <module>
    main()
  File "extract_duration.py", line 189, in main
    assert d[-1] > 0 and d[0] > 0, f'{d}, {np.sum(d)}, {real_mel_length}'
AssertionError: [ 1  8  0  8  0  4  2  4  2  4  2  6  6  4  4  4  4  4  2  4  0  6  4  6
  4  4  4  2  4  6  2  4  4  4  4  4  2  4  4  4  2 10  4  4  4  4  6  4
  4  4  4  6  6  4  6  4  2  4  2  6  4  4  4  4  6  2  4  6  4  4  6  4
  2  8  0  4  6  8  0  2 10  2  8  6  6 10  8  6  0  0  0  0], 377, 377
```

print(d) after `d = get_duration_from_alignment(alignment)`, I used `reduction_factor=2` for training.
```
[1 4 0 4 0 2 1 2 1 2 1 3 3 2 2 2 2 2 1 2 0 3 2 3 2 2 2 1 2 3 1 2 2 2 2 2 1
 2 2 2 1 5 2 2 2 2 3 2 2 2 2 3 3 2 3 2 1 2 1 3 2 2 2 2 3 1 2 3 2 2 3 2 1 4
 0 2 3 4 0 1 5 1 4 3 3 5 4 3 0 0 0 0]
```

And here is a pic of alignment:
![30_alignment](https://user-images.githubusercontent.com/58607002/99300819-11099200-281b-11eb-8f5a-66ba39af27e8.png)

**Comment by dathudeptrai** [comment]
@qianhui-wan can you try comment out this code (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/extract_duration.py#L184-L198)

**Comment by qianhui-wan** [comment]
> @qianhui-wan can you try comment out this code (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/extract_duration.py#L184-L198)

then there's a length mismatch at

```
Traceback (most recent call last):
  File "extract_duration.py", line 227, in <module>
    main()
  File "extract_duration.py", line 199, in main
    ), f"different between sum_durations and len_mel, {np.sum(d)} and {real_mel_length}"
AssertionError: different between sum_durations and len_mel, 404 and 403
```

**Comment by zcy618** [comment]
Please try:
assert d[-1] >= 0 and d[0] >= 0, f'{d}, {np.sum(d)}, {real_mel_length}'

**Comment by qianhui-wan** [comment]
> Please try:
> assert d[-1] >= 0 and d[0] >= 0, f'{d}, {np.sum(d)}, {real_mel_length}'

Yes this would run, thanks! 
When tacotron2 outputs some zeros in the alignments/durations, does it mean the tacotron itself is not good enough?

**Comment by dathudeptrai** [comment]
> > Please try:
> > assert d[-1] >= 0 and d[0] >= 0, f'{d}, {np.sum(d)}, {real_mel_length}'
> 
> Yes this would run, thanks!
> When tacotron2 outputs some zeros in the alignments/durations, does it mean the tacotron itself is not good enough?

that means that phoneme is silent
