### ISSUE TITLE
_ref is different from ground truth

### ISSUE THREAD

**Issue by theAayushbajaj** [TensorSpeech/TensorFlowTTS#291]
Is there any preprocessing been done on the audio before its fed through _pqmf_ synthesis in Multiband Melgan? I'm using my own mels generated from a different method. _ref files sound different from the ground truth. I couldn't find any preprocessing step in the pipeline.

**Comment by dathudeptrai** [comment]
@theAayushbajaj here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/processor/ljspeech.py#L165). Just load audio by soundfile.
