### ISSUE TITLE
"End-to-end example" from the front page meant to be working?

### ISSUE THREAD

**Issue by NekiMedo** [TensorSpeech/TensorFlowTTS#293]
Hi, is the "End-to-end examples" Python script meant to be working without modfications? It references a few `*.h5` files and there are no such files in the repo:

    ...
    OSError: Unable to open file (unable to open file: name = './examples/fastspeech/pretrained/model-195000.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

What am i missing here?

**Comment by dathudeptrai** [comment]
you need to download it :))) for example here (https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2#pretrained-models-and-audio-samples)

**Comment by NekiMedo** [comment]
Thanks for the link.
At the URL pointed to by the above i can find `model-150000.h5` and when the script is modified for the file name change the error message becomes:

    ValueError: You are trying to load a weight file containing 10 layers into a model with 6 layers.

And that's before the script attempts to read `generator-1500000.h5` - which i don't know where to find either.
So i guess the answer is - "no, it does not run out of the box".

**Comment by dathudeptrai** [comment]
@NekiMedo i think you use wrong config :))). Seems you are using config V2 rather V1 :)). BTW, if you want to run and try, you can use our colab :)) (https://colab.research.google.com/drive/1akxtrLZHKuMiQup00tzO2olCaN-y3KiD?usp=sharing). Generator checkpoint here (https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/multiband_melgan#pretrained-models-and-audio-samples).

**Comment by NekiMedo** [comment]
you are probably right although i'm only guessing that *'wrong config'* refers to this line in the code:

    fs_config = AutoConfig.from_pretrained('./examples/fastspeech/conf/fastspeech.v1.yaml')
Yeah, colab is a funny beast, Google is rather hostile towards Firefox and the page doesn't render at all; not sure that i want to install Chrome on my PC so i might revisit this later from a different box.
Thanks for your prompt responses.
