### ISSUE TITLE
The ids length does not match the length of the other npy arrays

### ISSUE THREAD

**Issue by Nistrian** [TensorSpeech/TensorFlowTTS#295]
I am trying to run fastspeech2 using ljspeech dataset, which is referenced at [here](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2)
I have gone through all the steps outlined in mfa_extraction. Before trying to run fastspeech2, I decided to look at the length of the arrays contained in the dump. All arrays except **ids** have the same length. And for **all** samples. This raises the error `Number of charactor, mel, duration, f0 and energy files are different`. Can you please tell me how to fix this?

![image](https://user-images.githubusercontent.com/69087388/95652701-a9657600-0afb-11eb-8dad-7fbec8ddcaa1.png)

**Comment by dathudeptrai** [comment]
@Nistrian it mean the number of files, not the length of each file :D
