### ISSUE TITLE
How to inference on CPU?

### ISSUE THREAD

**Issue by yg1031** [TensorSpeech/TensorFlowTTS#297]
I followed the example below and it worked well on Ubuntu 16.04:
https://github.com/TensorSpeech/TensorFlowTTS#end-to-end-examples
But I want to get it work on my robot without GPU, so how to inference model on CPU, is there any example?

**Comment by dathudeptrai** [comment]
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
```

Add above code in the head of the runing script.

**Comment by yg1031** [comment]
> os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

It worked!
Thank you for your quick reply!
