### ISSUE TITLE
Bad inference result but normal result in train/evaluate stage of Tacotron2

### ISSUE THREAD

**Issue by taylorlu** [TensorSpeech/TensorFlowTTS#303]
Hi, thanks for your job.
But I encountered a trouble shot when inferred a sample using trained *.pth file.
This was the mel spectrum in evaluate stage when training.
![企业微信截图_20201014071408](https://user-images.githubusercontent.com/5125756/95926074-f2fcdc00-0ded-11eb-8ea1-1fe0e2d61656.png)
and this was the mel output using `decode_tacotron2.py`
![企业微信截图_20201014071241](https://user-images.githubusercontent.com/5125756/95926159-293a5b80-0dee-11eb-8efa-6e15598c4f3b.png)
It seemed the mel spectrum generating was not work after a short timestep, what's the reason or some parameters were in wrong settings when I running?

**Comment by dathudeptrai** [comment]
@taylorlu the model is not good enough to inference without teacher forcing mode in 30k :D. maybe 60k-80k is ok :D.

**Comment by taylorlu** [comment]
thanks for your suggestion, I am trying it, it seems better then before.
