### ISSUE TITLE
Dockerfile does not install dataclasses dependency

### ISSUE THREAD

**Issue by OscarVanL** [TensorSpeech/TensorFlowTTS#305]
Hi,

I'm following the readme [here](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2_libritts).

I created and started the docker container as follows:

`bash examples/fastspeech2_libritts/scripts/build.sh`

`bash examples/fastspeech2_libritts/scripts/interactive.sh`

Now when running 

```
tensorflow-tts-preprocess --rootdir ./libritts \
  --outdir ./dump_libritts \
  --config preprocess/libritts_preprocess.yaml \
  --dataset libritts
```

I get the error: `ModuleNotFoundError: No module named 'dataclasses'`

This is installed by manually running `pip install dataclasses`. 

I assume this dependency is missing from the Dockerfile :)

**Comment by dathudeptrai** [comment]
seems python3.7 have dataclasses by default :D.

**Comment by OscarVanL** [comment]
In this case, the problem is the docker image `tensorflow/tensorflow:2.2.0-gpu` includes Python 3.6.9, not Python 3.7.

Either the docker image should be upgraded, or dataclasses should be added to the dependencies.

**Comment by dathudeptrai** [comment]
> dependencies

got it, i will add it as dependencies :D
