### ISSUE TITLE
Compare models

### ISSUE THREAD

**Issue by lalimili6** [TensorSpeech/TensorFlowTTS#314]
Hi, Dears
At this time, you support 6 models. Could you compare them? How can I decide to start training a model?
Pleas, list models by training time, data need for training, synthesizing voice quality, synthesizing time, synthesizing  resource, in whole which one prefer and etc.

best regards

**Comment by ZDisket** [comment]
@lalimili6 I'll craft a spreadsheet for such comparisons in a bit, but in the meanwhile, here's one comparing GAN vocoders I made a while ago: https://docs.google.com/spreadsheets/d/1rCIlzDdTnE-VMaA9d7D09wPjeA79y4Q_zRPIh4Bp8XI/edit?usp=sharing

**Comment by lalimili6** [comment]
@ZDisket Thanks for share that sheet and explain them in details.
I look forward to more sheet however, Take it easy, In your implements and experiments can you compare models in ballpark figure?
