### ISSUE TITLE
how to change mb-melgan yaml config to train  8khz data

### ISSUE THREAD

**Issue by jackiegeek** [TensorSpeech/TensorFlowTTS#316]
I have change hop_size to 100 (8000/num-mels) and upsample_scales [8 4 2]

**Comment by ZDisket** [comment]
@jackiegeek All left is to change the upsample scales so that `hop_size/result of multiplication between upsample scales = 4` (n of out_channels). For 32KHz (hop_size 400), I did `[5, 5, 4] `

**Comment by tts-nlp** [comment]
@jackiegeek You should make the following changes：
`hop_size=100, windows_size=4000, upsample_scales=[5,5]` 
for multiband=4 mode

**Comment by jackiegeek** [comment]
thx very much!! As far as I know,  the parameter

fmin: 80 (if speaker is male, should be set to 55 because male voice have a low frequence)
fmax: <= sample rate / 2 
hop_size = sample rate(sr) / num_mels
hop_size = out_channels * (multiplication between upsample scales  ) ( hop_size:100 = out_channels 4 * [5 * 5]

**Comment by jackiegeek** [comment]
I find a reference 8k config file, it seems that set hop_size to 200 rather than 100 is better 

https://github.com/kan-bayashi/ParallelWaveGAN/blob/d3b2b7b6b54a66a4e62b6533f8f990564258dabf/egs/yesno/voc1/conf/multi_band_melgan.v1.debug.yaml

**Comment by jackiegeek** [comment]
@dathudeptrai if I use 16k data with hop_size 200, what is the difference if I set upsample_scales to [2, 5, 5] and [5, 5, 2] ? thx

**Comment by dathudeptrai** [comment]
> @dathudeptrai if I use 16k data with hop_size 200, what is the difference if I set upsample_scales to [2, 5, 5] and [5, 5, 2] ? thx

let try :)) i think 2 5 5 is better :D

**Comment by OnceJune** [comment]
Will odd upsample scale lead to checkerboard artifacts?

**Comment by jackiegeek** [comment]
in my case, no

**Comment by Moonmore** [comment]
hello, I am using fastspeech2 and mb_melgan's scheme to train 8k data. I use 8k data with hop_size 100, and I set upsample_scales to [2, 5, 5]. by the way,my data is obtained by down-sampling data with high sampling rate. The problem  is that the voice synthesized by the gl algorithm is fine, but the voice through the mb_melgan model becomes very slow, and the configuration has not been improved after several modifications. How can I improve on this basis?

**Comment by OnceJune** [comment]
@Moonmore make sure product of upsample_scales and bind_nums equals to hop_size, in your case, 2*5*5*4(mbmelgan uses 4 bands, so here bind_nums is 4)=200, which is not your hop_size 100.
maybe try using upsample_scales [5, 5] to see if it will help.
