### ISSUE TITLE
Convert Multi-band MelGAN pretrained model to TFLite

### ISSUE THREAD

**Issue by OscarVanL** [TensorSpeech/TensorFlowTTS#318]
Hi,

I'm looking to convert the [pretrained universal vocoder for Multi-band MelGAN ](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/multiband_melgan#pretrained-models-and-audio-samples)into a TensorFlow Lite `.tflite` file for use on Android.

I'm trying to convert `multiband_melgan.v1_24k` (universal vocoder) to be a drop-in replacement for the `mbmelgan.tflite` (not a universal vocoder) file in the Android example, found [here](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/android/app/src/main/assets).

As this is a `.h5` file, my understanding is I need to go `.h5` -> `.pb` -> `.tflite`

The problem is, once it reaches `load_model`, I get the error `ValueError: No model found in config file.`

Some research says this is because the model was exported with `model.save_weights`, this way the architecture information is not saved.

Is there any way I can load the architecture information so I can make this conversion? I believe this model was added by @ZDisket

**Comment by OscarVanL** [comment]
Hi, apologies, I worked this out on my own.

I needed to use the MultiBangMelGANGeneratorConfig to load the `.yaml` config that comes with the model.

**Comment by OscarVanL** [comment]
And now I see there's already a PR to add this functionality, lol.

**Comment by OscarVanL** [comment]
So using my code to generate the `.tflite`, when I replace `mbmelgan.tflite` in the Android example I get the error.

`java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/reshape.cc:69 num_input_elements != num_output_elements (13760 != 8480)`

Any ideas why I might be getting that error?

**Comment by dathudeptrai** [comment]
> So using my code to generate the `.tflite`, when I replace `mbmelgan.tflite` in the Android example I get the error.
> 
> `java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/reshape.cc:69 num_input_elements != num_output_elements (13760 != 8480)`
> 
> Full error log
> I have also tried generating the `tflite` file with the Colab in #104, but this results in the same outcome.
> 
> Any ideas why I might be getting that error?
> 
> @mapledxf When you created the `tflite` models used in the Android example, did you do anything special to generate them?

can you run python API for tflite successfully?

**Comment by mapledxf** [comment]
@OscarVanL 
Something wrong with this line:
https://github.com/TensorSpeech/TensorFlowTTS/blob/1dae63feca9259d64b1a3d6a9eeb7fe8f158eeb6/examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/MBMelGan.java#L50

You should check the shape of the input which is generated from here:
https://github.com/TensorSpeech/TensorFlowTTS/blob/1dae63feca9259d64b1a3d6a9eeb7fe8f158eeb6/examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/tts/InputWorker.java#L86

**Comment by OscarVanL** [comment]
> @OscarVanL 
> Something wrong with this line:
> https://github.com/TensorSpeech/TensorFlowTTS/blob/1dae63feca9259d64b1a3d6a9eeb7fe8f158eeb6/examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/MBMelGan.java#L50
> 
> You should check the shape of the input which is generated from here:
> https://github.com/TensorSpeech/TensorFlowTTS/blob/1dae63feca9259d64b1a3d6a9eeb7fe8f158eeb6/examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/tts/InputWorker.java#L86

Thank you, I will check this later :)

**Comment by OscarVanL** [comment]
@mapledxf 

I made some changes to print the shapes:
1.
```java
System.out.println("getAudio() input Shape: " + Arrays.toString(input.getShape()));
mModule.resizeInput(0, input.getShape());
System.out.println("Input shape after resizeInput: " + Arrays.toString(mModule.getInputTensor(0).shape()));
```

2.                
```java
TensorBuffer output = mFastSpeech2.getMelSpectrogram(inputIds, SPEED);
System.out.println("InputWorker TensorBuffer output size: " + Arrays.toString(output.getShape()));
```

The console output says:

```java
I/System.out: InputWorker TensorBuffer output size: [1, 63, 80]
I/System.out: getAudio() input Shape: [1, 63, 80]
    Input shape after resizeInput: [1, 63, 80]
```

When I use the example MelGAN model (`mbmelgan.tflite`) the output looks similar, the shapes all match.

So it seems the sizes have been set correctly in the app.

One difference I see is when the app starts and prints the input/output shapes:

Your working model:
```
D/FastSpeech2: input:0 name:input_ids shape:[1, 1] dtype:INT32
    input:1 name:attention_mask shape:[1, 1] dtype:INT32
    input:2 name:speaker_ids shape:[1] dtype:INT32
    input:3 name:speed_ratios shape:[1] dtype:FLOAT32
    input:4 name:f0_ratios shape:[1] dtype:FLOAT32
    input:5 name:energy_ratios shape:[1] dtype:FLOAT32
    output:0 name:Identity shape:[1, 1, 80] dtype:FLOAT32
    output:1 name:Identity_1 shape:[1, 1, 80] dtype:FLOAT32
    output:2 name:Identity_2 shape:[1, 1] dtype:INT32
    output:3 name:Identity_3 shape:[1, 1] dtype:FLOAT32
    output:4 name:Identity_4 shape:[1, 1] dtype:FLOAT32
    successfully init
D/MBMelGan: input:0 name:mels shape:[1, 1, 80] dtype:FLOAT32
    output:0 name:Identity shape:[1, 1, 1] dtype:FLOAT32
    successfully init
```


My broken model:
```
D/FastSpeech2: input:0 name:input_ids shape:[1, 1] dtype:INT32
    input:1 name:attention_mask shape:[1, 1] dtype:INT32
    input:2 name:speaker_ids shape:[1] dtype:INT32
    input:3 name:speed_ratios shape:[1] dtype:FLOAT32
    input:4 name:f0_ratios shape:[1] dtype:FLOAT32
    input:5 name:energy_ratios shape:[1] dtype:FLOAT32
    output:0 name:Identity shape:[1, 1, 80] dtype:FLOAT32
    output:1 name:Identity_1 shape:[1, 1, 80] dtype:FLOAT32
    output:2 name:Identity_2 shape:[1, 1] dtype:INT32
D/FastSpeech2: output:3 name:Identity_3 shape:[1, 1] dtype:FLOAT32
    output:4 name:Identity_4 shape:[1, 1] dtype:FLOAT32
    successfully init
W/Gralloc3: mapper 3.x is not supported
D/MBMelGan: input:0 name:input_1 shape:[1, 100, 80] dtype:FLOAT32
    output:0 name:Identity shape:[1, 30000, 1] dtype:FLOAT32
    successfully init
```

Notice the differencece in MBMelGan's input and output shapes.

**Comment by mapledxf** [comment]
@dathudeptrai could you explain why his mb model has different shapes?
@OscarVanL Have you test your mb model by python api?

**Comment by dathudeptrai** [comment]
> @dathudeptrai could you explain why his mb model has different shapes?
> @OscarVanL Have you test your mb model by python api?

i will make a pull request for MB_melgan converter. They way you convert to tflite seem wrong so the shape is fixed by 100 (hop_size is 300 then the output shape is 300000).

**Comment by OscarVanL** [comment]
> @OscarVanL Have you test your mb model by python api?

I haven't yet, I will do that later today

**Comment by manmay-nakhashi** [comment]
@OscarVanL 
```
with open('../examples/multiband_melgan/conf/multiband_melgan.german.yaml') as f:
    config = yaml.load(f, Loader=yaml.Loader)
config = MultiBandMelGANGeneratorConfig(**config["multiband_melgan_generator_params"])
class TFMBMelGANGenerator(TFMelGANGenerator):
    def __init__(self, config, **kwargs):
        super().__init__(config, **kwargs)
        self.pqmf = TFPQMF(config=config, name='pqmf')
        
    def build(self, input_shape):
        self.pqmf.build(input_shape)
        self.built = True
    @tf.function(input_signature=[tf.TensorSpec(shape=[1, None, 40], dtype=tf.float32)])
    def call(self, mels):
        mb_audios = super().call(mels)
        audios = self.pqmf.synthesis(mb_audios)
        return audios
mb_melgan = TFMBMelGANGenerator(config, name="mb_melgan")
fake_mels = tf.random.uniform(shape=[1, 256, 40], dtype=tf.float32)
audios = mb_melgan(fake_mels)
mb_melgan.summary()
mb_melgan.load_weights("../generator-620000.h5", by_name=True)
mb_melgan_concrete_function = mb_melgan.call.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_functions(
    [mb_melgan_concrete_function]
)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model_mb_mel = converter.convert()
with open('mbmelgan_GE_1.tflite', 'wb') as f:
  f.write(tflite_model_mb_mel)
print('Model size is %f MBs.' % (len(tflite_model_mb_mel) / 1024 / 1024.0) )
```

**Comment by OscarVanL** [comment]
@manmay-nakhashi

When running that script I get the error:
```
   ValueError: Python inputs incompatible with input_signature:
      inputs: (
        Tensor("mels:0", shape=(1, None, 40), dtype=float32))
      input_signature: (
        TensorSpec(shape=(None, None, 80), dtype=tf.float32, name='mels'))
```

After changing the shapes from 40 to 80, the code runs and generates a `.tflite` file without errors, I tried this on the Android example, and it works!

Thank you!

**Comment by tingyang01** [comment]
Let me know how I can test the flight model of the Multi-band Mel-GAN model.
    config_file = "./multiband_melgan.v1.yaml"
    model_path = "./mbMelgan_generator-2560000.h5"
    with open(config_file) as conf:
        config = yaml.load(conf, Loader=yaml.Loader)
    config = MultiBandMelGANGeneratorConfig(**config['multiband_melgan_generator_params'])
    mblemgan = TFMBMelGANGenerator(config=config, name='MBMelGAN')
    mblemgan._build()
    # Load weights from file
    mblemgan.load_weights(model_path)
    fake_mels = tf.random.uniform(shape=[4, 256, 80], dtype=tf.float32)
    audios = mblemgan.inference(fake_mels)
    mb_melgan_concrete_function = mblemgan.inference_tflite.get_concrete_function()
    converter = tf.lite.TFLiteConverter.from_concrete_functions(
        [mb_melgan_concrete_function]
    )
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.SELECT_TF_OPS]

    # Convert the model.
    tflite_model = converter.convert()
    with open('./mbMelgan_generator-2560000_1.tflite', 'wb') as t_f:
      t_f.write(tflite_model)

**Comment by OscarVanL** [comment]
Did you try the code from @manmay-nakhashi ? That worked for me. I can use the saved tflite for MB MelGAN on the Android example.

**Comment by tingyang01** [comment]
Hello @OscarVanL 
Thanks for your reply.
I did not get any code.
Could you share the code with me?

**Comment by OscarVanL** [comment]
It is the comment on this issue from 8 days ago, you can see it above. This worked for me.

**Comment by tingyang01** [comment]
I see, 
Let me know also which TensorFlow and Tf-nightly version you will use.

**Comment by OscarVanL** [comment]
I think I used Tensorflow 2.3.1 for this with success, but I cannot remember for sure.

**Comment by tingyang01** [comment]
Thank you let me try.
you dont use Tf-nightly?

**Comment by OscarVanL** [comment]
No, in the colab it used the nightly, but I could not get this to work, so used TF 2.3.1 instead and it worked.

**Comment by tingyang01** [comment]
Hello @OscarVanL
I just converted the model into Tf-light and tested it on Android.
Thanks again

**Comment by OscarVanL** [comment]
Nice, glad you got it to work :) did you use TF 2.3.1 or TF nightly?
