### ISSUE TITLE
What differentiates your approach from commercial approaches?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [TensorSpeech/TensorFlowTTS#319]
Each time a new ML TTS comes out in github, it's not quite there yet.

In part it sounds robotic and unnatural.

That besomes less with each release, but it's still there.

Compare that to commercial TTS based on ML, you notice, that there is a big difference.

My question is: do they achieve this by having more data to have their algorithm practise on or are their algorithms better?

**Comment by seicaratteri** [comment]
Following! :)

**Comment by dathudeptrai** [comment]
@ErfolgreichCharismatisch mostly because more clean data rather than their algorithms :)).

**Comment by ErfolgreichCharismatisch** [comment]
@dathudeptrai I have a dataset of high quality recordings. They are not converted to text, recordings only. Which framework would work as a good stt engine to use the combination with TensorFlowTTS?
