### ISSUE TITLE
MBMelGAN resume training correctly?

### ISSUE THREAD

**Issue by abylouw** [TensorSpeech/TensorFlowTTS#321]
I am fine tuning an MBMelGAN model and it stopped just after 100k steps. 

I resumed the training at 100k with the model that was saved there and noticed that the error metrics do not continue in the same range as has been my experience with training FS2, but rather jump up a lot and then quickly start converging to the trend where the 100k errors were. 

I stopped training after 105k just to check this and the same happened when I resumed from 105k steps.

Attached are my training graphs, is this the expected behaviour?

![train2](https://user-images.githubusercontent.com/22814737/96680403-b98c1980-1375-11eb-9d27-d6e714851735.png)
![train1](https://user-images.githubusercontent.com/22814737/96680410-bbee7380-1375-11eb-887d-dd7c0e959aa5.png)

**Comment by dathudeptrai** [comment]
@abylouw i think it's ok, when u resume the dataset is shuffled so maybe this behaviour is normal :)).
