### ISSUE TITLE
Unsupported Ops for TFLite inference in C++

### ISSUE THREAD

**Issue by brendanxwhitaker** [TensorSpeech/TensorFlowTTS#322]
Why is tf.while_loop used in utils/decoder.py instead of an ordinary while loop? I'm trying to compile a C++ program to run a converted version of this model in TFLite, and it looks like this OP requires the flex delegate, which makes the binary size way bigger. Is it possible to modify the model minimally to make it so it only uses ops that are natively supported by TFLite, so no select tensorflow operators (https://www.tensorflow.org/lite/guide/ops_select)?

**Comment by dathudeptrai** [comment]
> Why is tf.while_loop used in utils/decoder.py instead of an ordinary while loop? I'm trying to compile a C++ program to run a converted version of this model in TFLite, and it looks like this OP requires the flex delegate, which makes the binary size way bigger. Is it possible to modify the model minimally to make it so it only uses ops that are natively supported by TFLite, so no select tensorflow operators (https://www.tensorflow.org/lite/guide/ops_select)?

I do not know :D, i just know that we need flex delegate to run tf.while_loop :D. tf.function will convert ordinary while loop to tf.while_loop automatically.

**Comment by jackiegeek** [comment]
I assume this is the same problem when I convert fastspeech2 to tflite model ?

when I only import `tflite_runtime`
```
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 370 (FlexRandomUniform) failed to prepare.
```

when I import tensorflow as well, it won't show error above
