### ISSUE TITLE
multiband_melgan inference wav is not voice

### ISSUE THREAD

**Issue by peter05010402** [TensorSpeech/TensorFlowTTS#323]
After train 4000k steps,  multiband_melgan inference wav is not voice
the wav file as follow
[2fdb2415-5b3a-49f9-9aba-29b0a87d7967.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5419707/2fdb2415-5b3a-49f9-9aba-29b0a87d7967.zip)

**Comment by ZDisket** [comment]
@peter05010402 What about previous checkpoints? I train my mb-melgans for 2.5M steps at most with elevated sample rates.

**Comment by peter05010402** [comment]
@ZDisket  Sorry, i don't understand what you said
Could you describe in detail？

**Comment by ZDisket** [comment]
@peter05010402 How do the audio samples sound like at previous stages in training (900k, 1M, 1.5M)?

**Comment by peter05010402** [comment]
@ZDisket  From 20k ,100k, 1M to 4M  ， it ‘s the same

**Comment by ZDisket** [comment]
@peter05010402 Then something must've gone wrong.

**Comment by peter05010402** [comment]
@ZDisket   yes.
With the same config.py,  Training in anoter dataset.  From 20k steps, the inderence wav is voice.

**Comment by peter05010402** [comment]
@ZDisket  my training mb_gan instruction is as follow.    Do you think it is right?

1.  tensorflow-tts-preprocess --rootdir ./[ljspeech/kss/baker/libritts] --outdir ./dump_[ljspeech/kss/baker/libritts] --config preprocess/[ljspeech/kss/baker]_preprocess.yaml --dataset [ljspeech/kss/baker/libritts]

2.  tensorflow-tts-normalize --rootdir ./dump_[ljspeech/kss/baker/libritts] --outdir ./dump_[ljspeech/kss/baker/libritts] --config preprocess/[ljspeech/kss/baker/libritts]_preprocess.yaml --dataset [ljspeech/kss/baker/libritts]

3 . CUDA_VISIBLE_DEVICES=0 python examples/multiband_melgan/train_multiband_melgan.py \
  --train-dir ./dump/train/ \
  --dev-dir ./dump/valid/ \
  --outdir ./examples/multiband_melgan/exp/train.multiband_melgan.v1/ \
  --config ./examples/multiband_melgan/conf/multiband_melgan.v1.yaml \
  --use-norm 1 \
  --generator_mixed_precision 1 \
  --resume ""

**Comment by dathudeptrai** [comment]
> @ZDisket my training mb_gan instruction is as follow. Do you think it is right?
> 
> 1. tensorflow-tts-preprocess --rootdir ./[ljspeech/kss/baker/libritts] --outdir ./dump_[ljspeech/kss/baker/libritts] --config preprocess/[ljspeech/kss/baker]_preprocess.yaml --dataset [ljspeech/kss/baker/libritts]
> 2. tensorflow-tts-normalize --rootdir ./dump_[ljspeech/kss/baker/libritts] --outdir ./dump_[ljspeech/kss/baker/libritts] --config preprocess/[ljspeech/kss/baker/libritts]_preprocess.yaml --dataset [ljspeech/kss/baker/libritts]
> 
> 3 . CUDA_VISIBLE_DEVICES=0 python examples/multiband_melgan/train_multiband_melgan.py 
> --train-dir ./dump/train/ 
> --dev-dir ./dump/valid/ 
> --outdir ./examples/multiband_melgan/exp/train.multiband_melgan.v1/ 
> --config ./examples/multiband_melgan/conf/multiband_melgan.v1.yaml 
> --use-norm 1 
> --generator_mixed_precision 1 
> --resume ""

pls share ur tensorboard

**Comment by peter05010402** [comment]
![image](https://user-images.githubusercontent.com/42974031/96863410-6b703680-1499-11eb-994e-9f76bd52e450.png)
![image](https://user-images.githubusercontent.com/42974031/96863473-817df700-1499-11eb-8449-a98207c752a3.png)
@dathudeptrai   Thank you

**Comment by dathudeptrai** [comment]
> ![image](https://user-images.githubusercontent.com/42974031/96863410-6b703680-1499-11eb-994e-9f76bd52e450.png)
> ![image](https://user-images.githubusercontent.com/42974031/96863473-817df700-1499-11eb-8449-a98207c752a3.png)
> @dathudeptrai Thank you

https://github.com/TensorSpeech/TensorFlowTTS/issues/247

**Comment by peter05010402** [comment]
@dathudeptrai  Thank you!
