### ISSUE TITLE
Character-level processor for multispeaker fastspeech2 model.

### ISSUE THREAD

**Issue by ronggong** [TensorSpeech/TensorFlowTTS#326]
Hi,

As far as I know, the libritts fastspeech2 recipe takes phoneme-level symbols as input, which requires a g2p processor, and ljspeech recipe takes character-level input, which is independent of the g2p processor and seems to be more straightforward. I would like to know what is the reason to choose a phoneme-level input for libritts recipe, and what are pros and cons for both input types?

To me, the g2p processor makes itself an obstacle to port from python to other platforms, e.g. c++, which requires a good native g2p library. The Phonetisaurus used in cppwin example doesn't always give a correct g2p result.

I would like to explore the possibility to train a multispeaker fastspeech2 model with character-level input, and first to have opinions from more experienced guys. What would be the potential issue? @dathudeptrai @ZDisket

**Comment by ZDisket** [comment]
@ronggong 

> I would like to know what is the reason to choose a phoneme-level input for libritts recipe

You can align phoneme-level inputs with Montreal Forced Aligner, which eliminates the need for a teacher model.

>The Phonetisaurus used in cppwin example doesn't always give a correct g2p result.

The cppwin example is extremely outdated. My https://github.com/ZDisket/TensorVox uses mixed dictionary lookup & TFG2P.

**Comment by dathudeptrai** [comment]
@ronggong charactor is easy to deploy and you do not need any G2P model but you should training teacher model to get alignment (here we use Tacotron-2) :D.

**Comment by ronggong** [comment]
@dathudeptrai Is the teacher model hard to train for the libritts data? Is the teacher model's training script included in the example https://github.com/tensorspeech/TensorFlowTTS/tree/master/examples/fastspeech2 ?

**Comment by ronggong** [comment]
@ZDisket Thanks, I am going to test TensorVox. I see you have two speaker models, Jordan Peterson and LJspeech, may I ask why didn't you train a multispeaker model?

**Comment by ZDisket** [comment]
@ronggong I did train several multispeaker (+ multi-emotion, which the program itself supports), but they're on semi-private datasets. Also, the demo available is extremely outdated too.

**Comment by ronggong** [comment]
@ZDisket I want to give it try your TensorVox, however, I can't compile it because of some dependencies missing, eg. rnnnoise. I removed this dependency from the source code and compiled it, but then some runtime dll is missing, e.g. Qt5WinExtras.dll. Could you update the compiling dependencies and runtime dll in gdrive?

**Comment by ZDisket** [comment]
@ronggong Here's an updated version with LJSpeech and another model: https://drive.google.com/file/d/1Ce8Ruvd-90qcTOJu4N_-eE8S0hD2cSAe/view?usp=sharing

**Comment by ronggong** [comment]
@ZDisket Nice demo, congratulations!  just curious, the g2p dictionary has different phoneme spellings for some words. e.g. 
abbreviated	AH0 B R IY1 V IY0 EY2 T AH0 D
abbreviated	AH0 B R IY1 V IY0 EY2 T IH0 D

In such cases, how do you decide which one to use? I see the g2p does 
> first it does a dictionary lookup (semi-optimized with bucketed string search) then if not found, uses the model.

I can contribute to include the multispeaker libritts model in your demo if you haven't train it. The data itself is CC BY license.

**Comment by ZDisket** [comment]
@ronggong 

> In such cases, how do you decide which one to use? 

There's no explicit mechanism for that. My guess is that it uses the first one.

**Comment by tekinek** [comment]
In my experience, phoneme-based model produces more natural sound than character level, as it has more symbols to represent variances in speech ( eg, 48 standard phonemes vs 26 characters in English).  If your datasets is small in size character-based training might be better. However, with a larger dataset and good MFA alignment phoneme-based training is worth a try.

**Comment by ronggong** [comment]
@tekinek One thing needs to bring about is we need a good g2p model to convert text to phonemes. Do you aware a good g2p implementation trained for English language and better to have a c++ implementation.

**Comment by tekinek** [comment]
@ronggong  Sorry, for English g2p I just use https://github.com/bootphon/phonemizer; never searched beyond that.
