### ISSUE TITLE
Running training from checkpoint

### ISSUE THREAD

**Issue by RuslanSel** [TensorSpeech/TensorFlowTTS#327]
I've got an error:
20-10-25 07:54:06.897975: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./examples/tacotron2/exp/train.tacotron2.v1/checkpoints/ckpt-94000.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Resume option:
  --resume "./examples/tacotron2/exp/train.tacotron2.v1/checkpoints/ckpt-94000.data-00000-of-00001"
If I run
  --resume "./examples/tacotron2/exp/train.tacotron2.v1/checkpoints/ckpt-94000.index"
I've got
OSError: Unable to open file (unable to open file: name = './examples/tacotron2/exp/train.tacotron2.v1/checkpoints/model-1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
But I want to resume from model-94000.h5.

Thanks in advance.

**Comment by dathudeptrai** [comment]
@RuslanSel i think you didn't read readme carefully :D. you should resume .../ckpt-94000

**Comment by RuslanSel** [comment]
Thank you! :-)
