### ISSUE TITLE
Could you give me some examples in this file?

### ISSUE THREAD

**Issue by xinbingzhe** [TensorSpeech/TensorFlowTTS#329]
https://github.com/TensorSpeech/TensorFlowTTS/blob/9c33ebffebfb3fac5bdc0afa2d858e6dd9a1ed0c/tensorflow_tts/processor/baker.py#L559

**Comment by dathudeptrai** [comment]
[Uploading 000001-010000.txt…]()

**Comment by dathudeptrai** [comment]
[Uploading 000001-010000.zip…]()

**Comment by dathudeptrai** [comment]
[000001-010000.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5437224/000001-010000.zip)

**Comment by xinbingzhe** [comment]
> [000001-010000.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5437224/000001-010000.zip)
thank you !!!
