### ISSUE TITLE
prepare_libri Notebook does not filter clips exceeding max_file_len

### ISSUE THREAD

**Issue by OscarVanL** [TensorSpeech/TensorFlowTTS#331]
I ran `examples/fastspeech2_libritts/libri_experiment/prepare_libri.ipynb` to prepare the LibriTTS dataset, but have noticed clips that exceed 11 seconds (I have `max_file_len` set as 11 seconds) in the re-formatted dataset. I assume these should be filtered out.

For example, this is just one speaker's file which I assume should have been filtered out.
![image](https://user-images.githubusercontent.com/7999692/97194753-6ca7a900-17a2-11eb-996a-8e85c2f68113.png)

Is this the intended behaviour of this script?

**Comment by ronggong** [comment]
Is this a bug of the ipynb script?
```
if max_file_len < dur < min_file_len:
                        print(dur)
                        continue
```

I guess it actually wanted to say `if max_file_len < dur or dur < min_file_len`

**Comment by OscarVanL** [comment]
Yes, looks like that's it.

**Comment by OscarVanL** [comment]
Wanna make a PR or shall I?
