### ISSUE TITLE
Model should raise an error if n_speakers does not match the number of speakers in dataset

### ISSUE THREAD

**Issue by OscarVanL** [TensorSpeech/TensorFlowTTS#333]
There was a transfer error when I was copying my dataset to the server I'm doing training with. As a result, only 18 of my 21 speakers transferred, but I did not notice this mistake.

Maybe an error/warning should display if the number of speakers in the training dataset does not match the `n_speakers` option in the hyperparameter configuration? This could help avoid human errors like this resulting in wasted time training poor models :)

**Comment by machineko** [comment]
Good idea u can implement it :)

**Comment by dathudeptrai** [comment]
i will implement it :D
