### ISSUE TITLE
Got err, When Training with 16k hz  data

### ISSUE THREAD

**Issue by zhangsanfeng86** [TensorSpeech/TensorFlowTTS#334]
Hi, 
1.my preprocess16k.yaml  as follow:
![image](https://user-images.githubusercontent.com/73547638/97331121-f85d2a80-18b3-11eb-97a3-833602e5aa95.png)

2.When I run "tensorflow-tts-preprocess --rootdir ./baker/ --outdir ./dump_baker --config ./TensorFlowTTS/preprocess/baker_preprocess16k.yaml --dataset baker"
Err as follow:
![image](https://user-images.githubusercontent.com/73547638/97331234-1aef4380-18b4-11eb-8aa3-6e21bad10709.png)

**Comment by zhangsanfeng86** [comment]
I got another Err

![image](https://user-images.githubusercontent.com/73547638/97342832-af13d780-18c1-11eb-878e-20d3bb484895.png)

**Comment by dathudeptrai** [comment]
can you give me ur folder structure :))

**Comment by zhangsanfeng86** [comment]
![image](https://user-images.githubusercontent.com/73547638/97395557-2a0bdb00-1920-11eb-9de5-b75e5011c0f3.png)
@dathudeptrai  thank you for ur reply!

**Comment by zhangsanfeng86** [comment]
The first question i have solved.  Because special character in training txt.
