### ISSUE TITLE
Any plan to implement GMM Attention + Tacotron2 ?

### ISSUE THREAD

**Issue by joan126** [TensorSpeech/TensorFlowTTS#336]
Hi,  is there any plan to try GMM Attention with Tacotron2?

**Comment by dathudeptrai** [comment]
no plan for it :)), i do not see any benefit of GMM for now. :D.

**Comment by joan126** [comment]
> no plan for it :)), i do not see any benefit of GMM for now. :D.

1 compared with LSA, no performance improved? 
2  then or long sentence synthesis?
3 what about Graves Attention?

**Comment by dathudeptrai** [comment]
> > no plan for it :)), i do not see any benefit of GMM for now. :D.
> 
> 1 compared with LSA, no performance improved?
> 2 then or long sentence synthesis?
> 3 what about Graves Attention?

1. Yes, LSA is better in terms of quality.
2. The model right now can synthesize very long sentences.
3. GravesAttention is GMM attention.

**Comment by joan126** [comment]
> > > no plan for it :)), i do not see any benefit of GMM for now. :D.
> > 
> > 
> > 1 compared with LSA, no performance improved?
> > 2 then or long sentence synthesis?
> > 3 what about Graves Attention?
> 
> 1. Yes, LSA is better in terms of quality.
> 2. The model right now can synthesize very long sentences.
> 3. GravesAttention is GMM attention.
Thanks， I am reading papers of Blizzard Challenge 2020 for Chinese Synthesis Task, at least three teams used GMM Attention instead of LSA and achieved good ranks!

**Comment by xiaoyangnihao** [comment]
> no plan for it :)), i do not see any benefit of GMM for now. :D.

Hope plan to implement GMM Attention + Tacotron2, too.
