### ISSUE TITLE
Convert multi-band melgan model into Tflight

### ISSUE THREAD

**Issue by tingyang01** [TensorSpeech/TensorFlowTTS#339]
I am converting the multiband-Mel gan model into Tf-light with this code.

    config_file = "./multiband_melgan.v1.yaml"
    model_path = "./mbMelgan_generator-2560000.h5"
    with open(config_file) as conf:
        config = yaml.load(conf, Loader=yaml.Loader)
    config = MultiBandMelGANGeneratorConfig(**config['multiband_melgan_generator_params'])
    mblemgan = TFMBMelGANGenerator(config=config, name='MBMelGAN')
    mblemgan._build()
    # Load weights from file
    mblemgan.load_weights(model_path)
    fake_mels = tf.random.uniform(shape=[4, 256, 80], dtype=tf.float32)
    audios = mblemgan.inference(fake_mels)
    mb_melgan_concrete_function = mblemgan.inference_tflite.get_concrete_function()
    converter = tf.lite.TFLiteConverter.from_concrete_functions(
        [mb_melgan_concrete_function]
    )
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.SELECT_TF_OPS]

    # Convert the model.
    tflite_model = converter.convert()
    with open('./mbMelgan_generator-2560000_1.tflite', 'wb') as t_f:
      t_f.write(tflite_model)

But I am not getting the valid model.
And the correct test method.
I hope to get your help.
Thank you.

**Comment by OscarVanL** [comment]
Hi, based on your comments on this issue, you have fixed this now? https://github.com/TensorSpeech/TensorFlowTTS/issues/318

**Comment by tingyang01** [comment]
Yes, fixed it in TensorFlow 2.3.1.
Thank you
