### ISSUE TITLE
can you please provide the tf-nightly==2.4.0-dev20200630 whl file?

### ISSUE THREAD

**Issue by cookingbear** [TensorSpeech/TensorFlowTTS#342]
I want to reproduce the tflite model according to the colab for fastspeech.
However, the tf-nightly==2.4.0-dev20200630 whl file has been gone for a while
I also tested the newest tf-nightly==2.5.0-dev20201029, the tf.repeat function would cause the errors below:

tensorflow.lite.python.convert.ConverterError: ...../lib/python3.6/site-packages/tensorflow/python/saved_model/load.py:890:0: error: 'tf.Reshape' op requires 'shape' to have at most one dynamic dimension, but got multiple dynamic dimensions at indices 1 and 2

........

Exception ignored in: <bound method Buckets.del of <tensorflow.python.eager.monitoring.ExponentialBuckets object at 0x7f6e852aa4c8>>
Traceback (most recent call last):
File "......./lib/python3.6/site-packages/tensorflow/python/eager/monitoring.py", line 407, in del
AttributeError: 'NoneType' object has no attribute 'TFE_MonitoringDeleteBuckets'

**Comment by dathudeptrai** [comment]
@cookingbear tensorflow 2.3.1 is ok.
