### ISSUE TITLE
Reusing duration from pretrained model for finetuning fastspeech2 on new speaker

### ISSUE THREAD

**Issue by charlie-codes-choi** [TensorSpeech/TensorFlowTTS#343]
I'm currently trying to finetune fastspeech2 on a new speaker using the pretrained LJspeech model. Might be a stupid question but, would I also have to finetune the tacotron2 model to get the duration, or can I just use pretrained tacotron2 model to get the duration?

**Comment by dathudeptrai** [comment]
@charlie-codes-choi you need fine-tune :D
