### ISSUE TITLE
Changing Processor in Android Example from Character to Phoneme Symbols

### ISSUE THREAD

**Issue by OscarVanL** [TensorSpeech/TensorFlowTTS#345]
Hi,

Sorry to ask your help once again @mapledxf 

I am trying to customise the Android example to use a custom FastSpeech2 model with the MB-MelGan Universal Vocoder. 
The problem is, speech is different when using these models on Android compared to on my PC with Python inference...

With the input text: "hello world this is a test of the voice text to speech"

1. In a notebook...

This is converted to phoneme symbol IDs: 
[37, 10, 46, 51, 74, 70, 30, 46, 24, 74, 25, 39, 58, 74, 39, 72, 74, 10, 74, 60, 27, 58, 60, 74, 11, 69, 74, 25, 10, 74, 69, 54, 58, 74, 60, 27, 45, 58, 60, 74, 60, 67, 74, 58, 56, 42, 23]

It sounds [like this](https://drive.google.com/file/d/1eQxgIAOYLuzo2Awj-SX2NWYnEapHAN13/view?usp=sharing)

2. On the Android example...

`symbolsToSequence()` processes the same text into character IDs: 
[45, 42, 49, 49, 52, 11, 60, 52, 55, 49, 41, 11, 57, 45, 46, 56, 11, 46, 56, 11, 38, 11, 57, 42, 56, 57, 11, 52, 43, 11, 57, 45, 42, 11, 59, 52, 46, 40, 42, 11, 57, 42, 61, 57, 11, 57, 52, 11, 56, 53, 42, 42, 40, 45]
https://github.com/TensorSpeech/TensorFlowTTS/blob/e42595abbf21208c81e0fabaa0b1eaeaca2c4053/examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/utils/Processor.java#L176-L189

[This sounds messed up using a Phoneme-trained FS2 model...](https://drive.google.com/file/d/1Rl7LnhFyep2w7-9KH3-MMy0pJ1OJpzUH/view?usp=sharing)

The Processor in the Android example is designed for a character symbol set. I'm asking for advice on how to modify the Android example to use the correct phoneme symbols for Libritts...

If I am correct, I should just need to rewrite the same logic in the [Libritts processor](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/processor/libritts.py) into Java using a Java G2P library. Would this work?

**Comment by OscarVanL** [comment]
On this topic, do you have any recommendations for lightweight G2P Java libraries?

**Comment by ronggong** [comment]
If you found a good G2P and tested please let me know, I am looking for a good G2P in c++. But if there is a Java version, maybe I can port it.

**Comment by OscarVanL** [comment]
I tried the Sphinx G2P and it works, but it gives different results to the Python G2P because it's using a different set of phonemes...

Input text = 'hello world this is a test of the voice text to speech'

```
Python: [@HH, @AH0, @L, @OW1, @SIL, @W, @ER1, @L, @D, @SIL, @DH, @IH1, @S, @SIL, @IH1, @Z, @SIL, @AH0, @SIL, @T, @EH1, @S, @T, @SIL, @AH1, @V, @SIL, @DH, @AH0, @SIL, @V, @OY1, @S, @SIL, @T, @EH1, @K, @S, @T, @SIL, @T, @UW1, @SIL, @S, @P, @IY1, @CH]
```

```
Sphinx Java: [@HH, @EH, @L, @OW, @SIL, @W, @ER, @L, @D, @SIL, @TH, @IH, @S, @SIL, @IH, @S, @SIL, @AH, @SIL, @T, @EH, @S, @T, @SIL, @AH, @V, @SIL, @TH, @IY, @SIL, @V, @OY, @S, @SIL, @T, @EH, @K, @S, @T, @SIL, @T, @OW, @SIL, @S, @P, @IY, @CH]
```

Ideally, I would use the same G2P library as used by TensorFlowTTS to get the same outcome, but this seems unlikely.



This does complicate things... Perhaps it's possible to use Python within the App for this sole feature (there are ways to run Python code within Java), but I doubt this is good for performance...

**Comment by mapledxf** [comment]
@OscarVanL 
unfortunately, i didn't find any java version g2p. :(

**Comment by OscarVanL** [comment]
Ok, thank you for checking :)

**Comment by ronggong** [comment]
Those are different phoneme sets, the G2P library gives more varieties with stress.

**Comment by dathudeptrai** [comment]
@OscarVanL @ronggong I'm also finding the G2P library that works on both java and python =))). I tried to train Tensorflow Seq2Seq for G2P and convert it to tflite. It worked but somehow my TF implementation has poor performance :D

**Comment by dathudeptrai** [comment]
@OscarVanL @ronggong this is a code for training G2p (https://github.com/Kyubyong/nlp_made_easy/blob/master/PyTorch%20seq2seq%20template%20based%20on%20the%20g2p%20task.ipynb) on pytorch :)). we can port it into tensorflow or we can re-implement it by TF and convert to tflite ^^.

**Comment by ZDisket** [comment]
@OscarVanL You can find the code for training TensorVox's RNN-G2p here: https://github.com/ZDisket/TensorVox/tree/master/g2p_train
Converting it to TFLite shouldn't be a problem as the model itself (my program uses dict lookup + model like g2p_en) is very simple. You also want to use very low temperature (0.01). You can see its usage [here](https://github.com/ZDisket/TensorVox/blob/2459b8b438ceb1293a4b684d2d6ff60e2ffb4007/phonemizer.cpp#L175)

**Comment by ronggong** [comment]
Kyubyong's g2p also use dict lookup and NN, however, it has the dependency of nltk to give the POS to distinguish the homographs.

**Comment by manmay-nakhashi** [comment]
@ronggong @OscarVanL i am using https://github.com/AdolfVonKleist/Phonetisaurus for g2p. have build it for arm.

**Comment by ronggong** [comment]
@manmay-nakhashi Thanks, tried Phonetisaurus, but it seems me there obvious parsing mistakes.

**Comment by OscarVanL** [comment]
@manmay-nakhashi 
Unless I am mistaken, there isn't any way to use this on Android / Java.

**Comment by manmay-nakhashi** [comment]
@OscarVanL @ronggong you can compile it using swig

**Comment by ronggong** [comment]
Tried to use Phonetisaurus, if I input "It should be like that.". It returns the phoneme sequence:
IH2 T SH UH1 D B L AY1 K DH AE1 T

obviously, the vowel of "be" is missing.

**Comment by OscarVanL** [comment]
Thanks for investigating this. 
My temporary "workaround" is for my Android app to send the text to a remote Python server using the normal g2p-en library, which then returns the phoneme symbol IDs as a protocol buffer serialised array. (But this obviously is not very practical as it adds an internet connection constraint!)

It adds ~30ms of latency if the TCP socket is already open, so it's not terrible.

**Comment by ronggong** [comment]
@OscarVanL As @dathudeptrai suggested, we can port g2p-en into java or c++ with the help of tensorflow, I think it will be a good practice.

**Comment by OscarVanL** [comment]
@ronggong If you are still looking for a C++ implementation of g2p, it looks like @ZDisket has done it!

**Comment by ronggong** [comment]
@OscarVanL Thanks, it's good to know :)
