### ISSUE TITLE
[question] training chinese tacotron2 model with my own wavs

### ISSUE THREAD

**Issue by hudsonx1123** [TensorSpeech/TensorFlowTTS#347]
Hi,
I try to train chinese tacotron2 model with baker. 
I replaced the wav files with my own wav files and re-define 000001-010000.txt following original format.
It's ok in preprocess and traing progress, but something is wrong when I copy  the model to sample baker colab for test.
Input is about 20 chinese-words sentence. 
It is just about 6 sec sentnece but  Tacotron2 + MB-MelGAN generate 1:39 wav(as attachated image). 
It can correctly speak the sentence in the  first 6 sec but strange sound in the other duration.
any suggestion about this problem?? 
Thanks a lot!!
![ScreenHunter 51](https://user-images.githubusercontent.com/45844949/98065922-904cac80-1e90-11eb-926f-b94a9e069b35.png)

**Comment by azraelkuan** [comment]
@hudsonx1123 seems you train a bad tacotron, can u share me you Groud Truth Align mels or Train result using tacotron.
u can check it in your log dir

**Comment by hudsonx1123** [comment]
> @hudsonx1123 seems you train a bad tacotron, can u share me you Groud Truth Align mels or Train result using tacotron.
> u can check it in your log dir

@azraelkuan ,here are image and event data of my train result(I trained 80k steps this time). Thanks for your reply and help.

![taco2_train_01](https://user-images.githubusercontent.com/45844949/98185741-36a7b900-1f48-11eb-83a5-4833a766855e.png)
[events.out.tfevents.1604042982.ND6TensorFlowAndCaldi.24689.505.v2.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5491334/events.out.tfevents.1604042982.ND6TensorFlowAndCaldi.24689.505.v2.zip)

**Comment by azraelkuan** [comment]
it seems that your have some bad data in you dataset, u need to filter it out, or add grad norm to handle this.

**Comment by ahmedalbahnasawy** [comment]
@hudsonx1123 It might be data issue. What is your batch_size and ngpus ?

**Comment by hudsonx1123** [comment]
> it seems that your have some bad data in you dataset, u need to filter it out, or add grad norm to handle this.

@azraelkuan  I tried to remove all the Chinese period symbol in the metadata file (000001-010000.txt) and train again.
for example: 
000001	卡尔普#2陪外孙#1玩滑梯#4。
to
000001	卡尔普#2陪外孙#1玩滑梯#4

Then the issue was fixed and I get good result. 
Thanks for your help!!

![ScreenHunter 52](https://user-images.githubusercontent.com/45844949/98624952-c33be800-2349-11eb-91bc-e38af883b284.png)

**Comment by hudsonx1123** [comment]
> @hudsonx1123 It might be data issue. What is your batch_size and ngpus ?

@ahmedalbahnasawy I just use default baker conf(tacotron2.baker.v1.yaml)  to do training.
