### ISSUE TITLE
stream tts for mbmelgan

### ISSUE THREAD

**Issue by jackiegeek** [TensorSpeech/TensorFlowTTS#348]
I want to use mbmelgan as stream tts (send parts of mel to mbmelgan to get parts of audio), but when I concatenate parts of audio, there are obvious noise at concat position, how can I solve it? thx in advanced!

**Comment by manmay-nakhashi** [comment]
@jackiegeek 1. popping noise can come if your chunks going to audio players are not consistent or 
2. some times mb-melgan  models have an edge effect that can cause this problem.
for a solution you can apply overlapping windowing with queue implementation.

**Comment by jackiegeek** [comment]
thx, I will try

**Comment by tts-nlp** [comment]
@manmay-nakhashi ！ Has this problem been solved？

**Comment by jackiegeek** [comment]
I comment out padding when inference,  "apply overlapping windowing with queue implementation". overlapping window size depend on your upsample scaler.

**Comment by tts-nlp** [comment]
@jackiegeek If my upsample scaler is [4,4,4,4], how do I set the  overlapping window size? thanks!
