### ISSUE TITLE
How to control pitch ,when inference wav?

### ISSUE THREAD

**Issue by zhangsanfeng86** [TensorSpeech/TensorFlowTTS#349]
Is it possible control pitch, When inference wav?

**Comment by dathudeptrai** [comment]
yes, you can contry it by adjust `f0_ratios`, `energy_ratios`,

**Comment by zhangsanfeng86** [comment]
@dathudeptrai  Thank you！！！

**Comment by zheng-xing** [comment]
Hi @dathudeptrai , I used ljspeech dataset and tried varying the f0_ratios and energy_rations with numbers 1.3 and 0.7 but the results seem the same as those using number 1.0. Do you know what possible reasons for these? BTW, I also change the speed_ratios with 1.3 and 0.7 and this has a clear effect on the results.

Thanks!
