### ISSUE TITLE
custom symbols

### ISSUE THREAD

**Issue by lalimili6** [TensorSpeech/TensorFlowTTS#350]
How can I set my own symbols in preproces?
I want to train a model on own dataset.
as describe in readme I change my dataset as librispeech format.
also I change symbols and letters in `tensorflow_tts/processor/ljspeech.py` .
and run preprocess as in readme: 
`tensorflow-tts-preprocess --rootdir ./ljspeech--outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech`
but `dump_ljspeech/ljspeech_mapper.json` dont change and the same `tensorflow_tts/processor/pretrained/ljspeech_mapper.json`.

best regrds

**Comment by machineko** [comment]
You need to reinstall the package to take effect of ur changes (as its build in this way) => https://github.com/TensorSpeech/TensorFlowTTS/blob/e42595abbf21208c81e0fabaa0b1eaeaca2c4053/setup.py#L55

This should be added to readme :P @dathudeptrai
