### ISSUE TITLE
How to create my own dataset?

### ISSUE THREAD

**Issue by seicaratteri** [TensorSpeech/TensorFlowTTS#351]
Hello all! First of all, thanks for the great work - it is incredible! 🥇 

I have contacted a friend who has a very great voice and we are able to do around 12h of studio recordings. I was thinking as a first approach to recreate the LJSPEECH datset with her voice - basically using the same text, but with a different voice. Is there a better way to create a dataset for training? and what are the general recommendation for it? I read some papers and they all say to keep the same base frequency, to speak at the same velocity rate and with the same intonation. Is there anything else I should know?

Thank you in advance, I really appreciate it! :) if the results are good I can also share the model with the voice here!

**Comment by seicaratteri** [comment]
Up! :)

**Comment by OscarVanL** [comment]
Some recommendations based on my experience creating my own voice recordings and merging them with LibriTTS:

1. Recordings should not exceed 15 seconds. I recommend splitting them where you would have logical splits in your speech, for example at sentence fullstops, commas, and semicolons. Recordings that are long will result in you running out of memory in training.

2. Keep a consistent sampling rate. If you intend to merge the speech with another dataset (as I did with LibriTTS), match the sampling rate.

3. Recordings should be mono.

Ultimately you should aim to copy the structure that some of the dataset processing stages leave those datasets in.

I've had good results using LibriTTS, which is based on people reading audiobooks. These often have differences in velocity, intonation, etc, to make the book interesting to listen to, yet the model still sounds good!

In my experience, the things that made the biggest difference were to have a large quantity of data, and to match the fastspeech2 hop_size to the vocoder's hop_size.

**Comment by seicaratteri** [comment]
Hello @OscarVanL! Thank you so much for sharing your insights, it's precious and I really appreciate it! :) Could you elaborate a little bit more on "match the fastspeech2 hop_size to the vocoder's hop_size"? As the vocoder is already pre-trained, you mean simply adapting the hop_size hyperparameter of fast speech2 to be equal to the one that was used to train the vocoder?

Thank you again! 🥇

**Comment by OscarVanL** [comment]
Exactly!

**Comment by seicaratteri** [comment]
Thanks a lot! :) one last question: hop_size aside, did you change any of the hyperparameters in the config files when you trained fast speech2 or did you stick with the default ones?

**Comment by OscarVanL** [comment]
I stuck with the hyperparameters in `TensorFlowTTS\examples\fastspeech2_libritts\conf\fastspeech2libritts.yaml`. The only parameter I changed was `n_speakers` to match the number of speakers in my dataset, and `batch_size` from 32 to 16 because I was running out of VRAM on my GPU.

**Comment by seicaratteri** [comment]
Awesome! Thank you so much it's really helpful! 🥇 Just out of curiosity, on which GPU did you train and how long did it take?

**Comment by OscarVanL** [comment]
I trained on a 2070. My FastSpeech2 models take 80-110k steps to be optimal, 8-11 hours typically. This is with 34 hours of speaker data.

**Comment by seicaratteri** [comment]
Very good to know! Thanks a lot again! :)

**Comment by seicaratteri** [comment]
Hello @OscarVanL! :) I have a question for you: I am trying to train fastspeech2 on a custom dataset - to do it, should I first extract the durations using tacotron? if yes, does this mean that I have to train tacotron before I train fastspeech2? How was your experience in this case?

Thank you a lot in advance! :)
