### ISSUE TITLE
About the variant_predictor in FastSpeech2

### ISSUE THREAD

**Issue by TiramisuJ** [TensorSpeech/TensorFlowTTS#352]
Hi, When I read the code of fastspeech 2, I was a little confused about the output of variant_predictor. The shape of the energy_outputs is [batch_size, character_length, feature], while the shape of the ground truth is  [barch_size, mel_length, feature]. Different shapes seem to represent different meanings, one in character dimension and the other in time dimension.Is there a problem with this training?

**Comment by dathudeptrai** [comment]
the `energy_outputs` is `per_charactor_energy`, you can see the code here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech2/fastspeech2_dataset.py#L170-L171) that we calculate `per_charactor_energy` by its duration :D.

**Comment by TiramisuJ** [comment]
I see. Thank you very much for your answer :D
