### ISSUE TITLE
Illegal memory access when training fastspeech2libritts

### ISSUE THREAD

**Issue by GavinStein1** [TensorSpeech/TensorFlowTTS#356]
Hi there,

I'm trying to train fastspeech2libritts based off the 150K pretrained ljspeech model. When I am training, very early (within the first 10 mins), I hit the following illegal memory access error:
<img width="1202" alt="Screen Shot 2020-11-05 at 3 12 20 pm" src="https://user-images.githubusercontent.com/46909879/98334504-b91aa080-204e-11eb-858d-f7a859e7d476.png">

I am using Cuda 10.1 amd CudNN 7.6.5.

While the error is reproduceable, it doesn't always happen at the same number of iterations. 

Any ideas as to why?

**Comment by machineko** [comment]
TF_FORCE_GPU_ALLOW_GROWTH=true can cause this error u can try to turn it off.

You can also try => https://github.com/NVIDIA/framework-determinism as its not tensorflowTTS error you should consider heading here => https://github.com/tensorflow/tensorflow/issues

**Comment by GavinStein1** [comment]
Thanks! this seemed to fix it
