### ISSUE TITLE
tacotron2 synthesize wave

### ISSUE THREAD

**Issue by lalimili6** [TensorSpeech/TensorFlowTTS#360]
Hi Dears,
Is it possible to synthesize waves from only tacotron2 models (or FastSpecch2)? or we must train a vocoder?
best regards

**Comment by OscarVanL** [comment]
I am not sure about Tacotron, but if you look at the [FastSpeech2 paper](hhttps://arxiv.org/abs/2006.04558) it designed FastSpeech2**s**, which generates the speech waveform directly, so is an end-to-end model.

However, this repository only includes normal FastSpeech2, not FastSpeech2s. People have asked about this before (https://github.com/TensorSpeech/TensorFlowTTS/issues/155, and https://github.com/TensorSpeech/TensorFlowTTS/issues/239), the answer from dathudeptrai may interest you. He says it's very hard to train.

**Comment by lalimili6** [comment]
Thank, In e.g. Mozilla tts repo, tacotron2 generates the waveform in wav format directly and they add vocoder to improve wave quality.
but in this repo, I think we **must** train a vocoder to get a wave, is it true?
Can we use English vocoder for other languages?

**Comment by OnceJune** [comment]
Try griffin-lim if you don't want a neural vocoder.

> Can we use English vocoder for other languages?
Depends on the vocoder you're using. If it is speaker independent, yes, speaker dependent, you might get strange sound, DSP, yes.
