### ISSUE TITLE
ERROR: LeakSanitizer: detected memory leaks

### ISSUE THREAD

**Issue by zhangsanfeng86** [TensorSpeech/TensorFlowTTS#361]
Hi all
when inference in C++, LeakSanitizer detected memory leaks, as follow:
![image](https://user-images.githubusercontent.com/73547638/98551139-f180df80-22d7-11eb-9d8e-b0d07fa0e683.png)

**Comment by dathudeptrai** [comment]
@ZDisket

**Comment by ZDisket** [comment]
@zhangsanfeng86 That's Tensorflow C API related and I can't really do much about it. Besides, it's a small, one-time memory leak of the device definition when the model is created for the first time, and it's not really that concerning as the OS frees memory when the program closes. I'll see if I can do anything about it, if not then oh well, 24 bytes one time which is later taken care of by the OS is hardly a tragedy.

**Comment by zhangsanfeng86** [comment]
@ZDisket  Thank you for ur quick and clear reply ：）
