### ISSUE TITLE
MelGan train on baker dataset got error

### ISSUE THREAD

**Issue by jinfagang** [TensorSpeech/TensorFlowTTS#364]
```
Traceback (most recent call last):
  File "examples/multiband_melgan/train_multiband_melgan.py", line 507, in <module>
    main()
  File "examples/multiband_melgan/train_multiband_melgan.py", line 446, in main
    MultiBandMelGANDiscriminatorConfig(**config["multiband_melgan_discriminator_params"]),
KeyError: 'multiband_melgan_discriminator_params'

```

Does this params delete or miss in baker's config file? It says doesn't have this params in config.

**Comment by dathudeptrai** [comment]
@jinfagang https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/multiband_melgan/conf/multiband_melgan.baker.v1.yaml#L32. I think you are using an old version of this repo

**Comment by jinfagang** [comment]
@dathudeptrai OK, I will pull it this night, poor me copied that params from multiband_melgan.v1 and trained it for a long time...
