### ISSUE TITLE
fastspeech2 crushed on multi-gpu training

### ISSUE THREAD

**Issue by zhufengyun** [TensorSpeech/TensorFlowTTS#368]
for the same dataset and same config
training is ok on [1, 2, 4] gpus
but chrushed on [8, 10] gpus

2020-11-13 04:48:49.761847: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at constant_op.cc:185 : Invalid argument: Dimension -2147483648 must be >= 0
Traceback (most recent call last):
  File "workspace/scripts/train_fastspeech2.py", line 462, in <module>
    main()
  File "workspace/scripts/train_fastspeech2.py", line 454, in main
    resume=args.resume,
  File "./tensorflow_tts/trainers/base_trainer.py", line 870, in fit
    self.run()
  File "./tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "./tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "./tensorflow_tts/trainers/base_trainer.py", line 686, in _train_step
    self.one_step_forward(batch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 11 root error(s) found.
  (0) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_4/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
         [[replica_4/tf_fast_speech2/length_regulator/while/LoopCond/_1932/_1454]]
  (1) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_9/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
  (2) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_8/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
  (3) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_4/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
         [[replica_2/tf_fast_speech2/embeddings/strided_slice_1/_331]]
  (4) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_4/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
         [[AdamWeightDecay/concat_21/_324]]
  (5) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_4/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
         [[Func/replica_5/cond_3/else/_2468/input/_6959/_4710]]
  (6) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_4/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
         [[GroupCrossDeviceControlEdges_0/AdamWeightDecay/AdamWeightDecay/update_0/Const/_6301]]
  (7) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_4/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
  (8) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_4/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
         [[GroupCrossDeviceControlEdges_4/AdamWeightDecay/AdamWeightDecay/update_0/Const/_6237]]
  (9) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_4/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
         [[gradient_tape/replica_9/cond_1/StatelessIf/pivot_f/_4394/_2963]]
  (10) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_4/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:656) ]]
         [[GroupCrossDeviceControlEdges_2/AdamWeightDecay/AdamWeightDecay/update_0/Const/_6445]]
0 successful operations.
0 derived errors ignored. [Op:__inference__one_step_forward_277825]

**Comment by zhufengyun** [comment]
after adding some print functions to fastspeech.py:

sum_durations = tf.reduce_sum(durations_gt, axis=-1)  # [batch_size]
max_durations = tf.reduce_max(sum_durations)
tf.print("sum_durations", sum_durations)
tf.print("max_durations", max_durations)

tf.print("max_durations before tf.zeros", max_durations)
encoder_masks = tf.zeros(shape=[0, max_durations], dtype=tf.int32)

logs:
[train]:   0%|▏                                                                                                                             | 506/500000 [16:11<97:21:58,  1.43it/s]sum_durations [1680 1440 417 1199 1963 244]
max_durations 1963
max_durations before tf.zeros 1963
sum_durations [488 792 661 521 369 492]
max_durations 792
max_durations before tf.zeros 792
sum_durations [279 359 640 320 959 1639]
max_durations 1639
max_durations before tf.zeros 1639
sum_durations [1080 406 1183 811 1318 1399]
max_durations 1399
max_durations before tf.zeros 1399
sum_durations [782 379 166 1479 1600 519]
max_durations 1600
max_durations before tf.zeros 1600
sum_durations [377 425 1093 623 760 319]
max_durations 1093
max_durations before tf.zeros 1093
sum_durations [667 1195 671 359 799 1218]
max_durations 1218
max_durations before tf.zeros 1218
sum_durations [480 359 1199 1999 296 542]
max_durations 1999
max_durations before tf.zeros 1999
sum_durations [262 1719 359 838 240 805]
max_durations 1719
max_durations before tf.zeros 1719
sum_durations [824 411 359 199 840 640]
max_durations 840
max_durations before tf.zeros 840
[train]:   0%|▏                                                                                                                            | 507/500000 [16:12<101:59:48,  1.36it/s]2020-11-13 06:02:45.325105: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at constant_op.cc:185 : Invalid argument: Dimension -2147483648 must be >= 0
2020-11-13 06:02:45.325644: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at constant_op.cc:185 : Invalid argument: Dimension -2147483648 must be >= 0
2020-11-13 06:02:45.326324: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at constant_op.cc:185 : Invalid argument: Dimension -2147483648 must be >= 0
2020-11-13 06:02:45.326728: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at constant_op.cc:185 : Invalid argument: Dimension -2147483648 must be >= 0
2020-11-13 06:02:45.329176: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at constant_op.cc:185 : Invalid argument: Dimension -2147483648 must be >= 0
Traceback (most recent call last):
  File "lbworkspace/scripts/train_fastspeech2.py", line 462, in <module>
    main()
  File "lbworkspace/scripts/train_fastspeech2.py", line 454, in main
    resume=args.resume,
  File "./tensorflow_tts/trainers/base_trainer.py", line 870, in fit
    self.run()
  File "./tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "./tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "./tensorflow_tts/trainers/base_trainer.py", line 686, in _train_step
    self.one_step_forward(batch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 11 root error(s) found.
  (0) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_2/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
  (1) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_7/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
         [[tf_fast_speech2/length_regulator/Sum/_290]]
  (2) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_7/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
         [[GroupCrossDeviceControlEdges_5/AdamWeightDecay/AdamWeightDecay/update_0/Const/_6197]]
  (3) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_7/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
         [[replica_4/Add/_261]]
  (4) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_7/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
         [[AdamWeightDecay/concat_21/_364]]
  (5) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_7/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
         [[AdamWeightDecay/Cast_16/ReadVariableOp/_144]]
  (6) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_7/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
  (7) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_7/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
         [[AdamWeightDecay/Cast/ReadVariableOp/_156]]
  (8) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_7/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
         [[GroupCrossDeviceControlEdges_1/AdamWeightDecay/AdamWeightDecay/update_0/Const/_6425]]
  (9) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_7/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
         [[AdamWeightDecay/concat_21/_354]]
  (10) Invalid argument:  Dimension -2147483648 must be >= 0
         [[node replica_7/tf_fast_speech2/length_regulator/zeros_1 (defined at ./tensorflow_tts/models/fastspeech.py:660) ]]
         [[AdamWeightDecay/adam_weight_decay_rate_9/_512]]
0 successful operations.
0 derived errors ignored. [Op:__inference__one_step_forward_277888]

**Comment by dathudeptrai** [comment]
@zhufengyun sorry for reply late :(. Can you try the newest code ?

**Comment by zhufengyun** [comment]
@dathudeptrai i found that the same bug appears when i use grad accumulation for, say, 8+ steps, with one gpu. 
the debug log shows (batchsize=6, code in the second post):

sum_durations [820 359 847 665 1039 1440]
max_durations 1440
max_durations before tf.zeros 1440
sum_durations [879 160 1262]
max_durations 1262
max_durations before tf.zeros 1262
sum_durations []
max_durations -2147483648
max_durations before tf.zeros -2147483648

i guess this is related to incomplete batch data.
after adding drop_remainder=True to datasets.padded_batch in fastspeech2_dataset.py, the problem is gone.

**Comment by dathudeptrai** [comment]
> @dathudeptrai i found that the same bug appears when i use grad accumulation for, say, 8+ steps, with one gpu.
> the debug log shows (batchsize=6, code in the second post):
> 
> sum_durations [820 359 847 665 1039 1440]
> max_durations 1440
> max_durations before tf.zeros 1440
> sum_durations [879 160 1262]
> max_durations 1262
> max_durations before tf.zeros 1262
> sum_durations []
> max_durations -2147483648
> max_durations before tf.zeros -2147483648
> 
> i guess this is related to incomplete batch data.
> after adding drop_remainder=True to datasets.padded_batch in fastspeech2_dataset.py, the problem is gone.

yes, you are right, the problem comes from an incomplete batch that I fixed in the private library :))).

**Comment by zhufengyun** [comment]
cool 👍
