### ISSUE TITLE
The Gaussian noise vector at the generator input in Multi-band MelGAN implementation

### ISSUE THREAD

**Issue by dipjyoti92** [TensorSpeech/TensorFlowTTS#375]
First of all, I would like to thank for this wonderful repo. I have a small query regarding the Multi-band MelGAN. 

According to the Multi-band MelGAN paper, they use Gaussian noise vector at the generator input along with mels in the loss (equation 1 and equation 8 in the original paper). Although, the noise vector is not used in the Generator while calculating multi-resolution  STFT  loss. However, I do not see the Gaussian noise vector at the generator input in the Multi-band MelGAN implementation. Can anyone please suggest the reason for that?

**Comment by dathudeptrai** [comment]
> First of all, I would like to thank for this wonderful repo. I have a small query regarding the Multi-band MelGAN.
> 
> According to the Multi-band MelGAN paper, they use Gaussian noise vector at the generator input along with mels in the loss (equation 1 and equation 8 in the original paper). Although, the noise vector is not used in the Generator while calculating multi-resolution STFT loss. However, I do not see the Gaussian noise vector at the generator input in the Multi-band MelGAN implementation. Can anyone please suggest the reason for that?

i did not use Gaussian noise for simplicity :)).
