### ISSUE TITLE
How to conver baker.py to java file?

### ISSUE THREAD

**Issue by sszhangpengfei** [TensorSpeech/TensorFlowTTS#376]
I want to use Chinese TTS on android,but i found just only python sripte to conver text to id , i need a java file.
please help me.

**Comment by X-CCS** [comment]
Hello! @sszhangpengfei   Has this been solved?

**Comment by zhpnp** [comment]
you can see this simple [demo](https://github.com/tatans-coder/TensorflowTTS_chinese)
