### ISSUE TITLE
About using eos in different corpora

### ISSUE THREAD

**Issue by xsr6064** [TensorSpeech/TensorFlowTTS#378]
First of all, thank you very much for the excellent implementations. 

I am currently reading parts of the code, and found the use of eos symbol is different for some corpora, specifically for libritts: while other processors append "eos" to the end of each sentence, libritts processor doesn't seem to do that (setup_eos_token() returns None). Could you please explain why libritts doesn't use "eos" to help me to get the intuition of the design choice?

Thanks a lot again.

**Comment by l4zyf9x** [comment]
I think EOS purpose is for training Tacotron, to let the model know when stop. Move on to FastSpeech, we have duration predictor, so we don't need EOS any more.

**Comment by xsr6064** [comment]
Ahh, I see, I thought the libritts processor can also be used to train tacotron. Thank you very much for the clarification.
