### ISSUE TITLE
Killed training with Tacotron2

### ISSUE THREAD

**Issue by luis-vera** [TensorSpeech/TensorFlowTTS#384]
Hi. I am training my dataset with Tacotron 2 in 2 different machines. In the first one I am using Windows 10 and I haven't problem until now. But in the second one I am using ubuntu 20.04 and the training process always has ended in the epoch 506 of 200.000. The message is:
[train] 0% | 506/200000
Terminado (killed)

Could you tell me what would be the problem with Ubuntu because Ubuntu machine has GPU but Windows 10 machine don't

Thanks a lot for your help

**Comment by dathudeptrai** [comment]
@luis-vera not sure what is the problem.

**Comment by NeonBohdan** [comment]
The same thing 
While thaining tacotron2 after ~10K epochs killed with PAM usage constanly increasing
Nothing changed even after 
```
allow_cache: false
is_shuffle: false
```
