### ISSUE TITLE
I want to create organization repo and need enroll more member :D

### ISSUE THREAD

**Issue by dathudeptrai** [TensorSpeech/TensorFlowTTS#39]
after an open source time, I see a lot of things to do sụch as support more model like flow/glow, GAN, tensorrt, ...  but 1 or 2 people may not be enough to do that. I am thinking about creating a organization repo and enroll more members with us to develop. In the future, I want to change the repo name to TensorSpeech and support speech-related problems like voice conversion, speech recognition, ... Does anyone want to join?: D.

**Comment by ZDisket** [comment]
I'm primarily a C++/Qt app developer so all I can offer is GUI front ends like [this ](https://drive.google.com/file/d/11XqKbg4aSAuU5fmgorS4I7ImuQSGEN8j/view?usp=sharing)for now but I can join.

**Comment by manmay-nakhashi** [comment]
you can count me in

**Comment by rgzn-aiyun** [comment]
Hi, I am also interested in this!

**Comment by Yablon** [comment]
I am also interested in this. I am a speech engineer in China, I only have time  on weekday nights and weekends.

**Comment by abylouw** [comment]
I am also interested

**Comment by azraelkuan** [comment]
I am interested too.

**Comment by dathudeptrai** [comment]
I'll wait for a while longer :)), i will create organization soon :D.

**Comment by jcphong** [comment]
Can i join with u guys in tensorrt session :dancing_men:

**Comment by sourangshupal** [comment]
I am interested too

**Comment by candlewill** [comment]
Count me in. I can make some contribute in Taco and melgan if you like.

**Comment by ayush9096** [comment]
I am also interested. You can count me in.

**Comment by MachineLP** [comment]
I am interested too.

**Comment by dathudeptrai** [comment]
if anyone want to joint, please email me (nguyenquananhminh@gmail.com) and give me some infomations about urself, what will you contribute to the repo, ur everyday job, ...
