### ISSUE TITLE
use of _build for dummy input 

### ISSUE THREAD

**Issue by wsr692** [TensorSpeech/TensorFlowTTS#390]
https://github.com/TensorSpeech/TensorFlowTTS/blob/ea72bab6cef40dff68b0b619ecf0d7c9cce3e3f0/tensorflow_tts/models/fastspeech2.py#L123

https://github.com/TensorSpeech/TensorFlowTTS/blob/ea72bab6cef40dff68b0b619ecf0d7c9cce3e3f0/tensorflow_tts/models/fastspeech2.py#L134

Hi, I thanks for keeping up this great work. 
May I ask why you chose to make  _build execute  __call__(by self) by feeding the fake input ? 
I see this in tacotron2, melgan & fastspeech1&2, I wonder why this was necessary. Is it to check if model call succeeds?

**Comment by dathudeptrai** [comment]
Hi, we need to feed a fake input to the call function to build a model so make it able to load_weights :D.

**Comment by wsr692** [comment]
Oh, so that was for loading pretrained model. Thanks!
