### ISSUE TITLE
Is it possible to use MFA on LJSpeech?

### ISSUE THREAD

**Issue by seicaratteri** [TensorSpeech/TensorFlowTTS#392]
Hello all! First of all thanks for the repo, the work is incredible! 🥇 

I am trying to train FastSpeech2 on LJSpeech, but I am finding this blocking error when extracting the durations using MFA. What I have run is:

`!python examples/mfa_extraction/run_mfa.py \
  --corpus_directory ./ljspeech/ \
  --output_directory ./mfa/parsed \
  --jobs 1`

And the output I get is:

`Setting up corpus information...
WARNING: Some issues parsing the corpus were detected. Please run the validator to get more information.
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 224, in <module>
  File "aligner/command_line/align.py", line 181, in validate_args
  File "aligner/command_line/align.py", line 117, in align_corpus
  File "aligner/corpus.py", line 500, in speaker_utterance_info
ZeroDivisionError: division by zero
[833] Failed to execute script align`

Am I missing something? Is it possible to use MFA on a single speaker dataset?

Thank you in advance! :)

**Comment by machineko** [comment]
Your folder structure should be changed to this => dataset/**LJ**/lj-000.wav etc. cause MFA is searching speakers inside ur dataset foders.

For example => Dataset/speaker_id/speaker_001.wav

**Comment by seicaratteri** [comment]
Hello @machineko! Thank you so much for your answer and help :)

I am a bit confused. The structure of my current folder is:

LJSpeech-1.1
|___wavs

Shouldn't MFA consider the folder wavs as the speaker id? Anyway, I also tried to rename it to LJ, like this:

LJSpeech-1.1
|___LJ

And as well to rename the parent directory like this:

Dataset
|___wavs

Dataset
|___LJ

But none of this worked, I always get the same error as in the OP. What I run is:

`!python examples/mfa_extraction/run_mfa.py \
  --corpus_directory /content/TensorFlowTTS/Dataset \
  --output_directory ./mfa/parsed \
  --jobs 8`

Of course, I changed the corpus directory path with the right name of the parent folder when I renamed it. There must be something very little I am missing because this shouldn't be complicated! Do maybe you see my mistake? :)

Thank you so much in advance! I really appreciate the help! 🌻

**Comment by machineko** [comment]
It should looks like this =>
![image](https://user-images.githubusercontent.com/42299606/100449663-97906000-30b4-11eb-80a3-1903aee1115d.png)

**Comment by seicaratteri** [comment]
I see! Then maybe what I am missing are the .txt file, because I only have the .wavs

Does the .txt files need to have the transcription for the related .wav file?

Thanks a lot again for your help! Is much appreciated! :)

**Comment by machineko** [comment]
Yup they need to be transcription for .wav files you can check more here https://montreal-forced-aligner.readthedocs.io/en/latest/data_prep.html

**Comment by seicaratteri** [comment]
Thank you so much! By adding the transcript, now it works!

Nonetheless, I am still stuck: when i try to train fastspeech2, i get the following error:

`AssertionError: Number of charactor, mel, duration, f0 and energy files are different`

What could be the cause of this?

**Comment by machineko** [comment]
Open new issue for this problem :P (u can also check older issues for this error)

**Comment by seicaratteri** [comment]
Make sense! Thanks a lot for your help! :)

**Comment by CrossEntropy** [comment]
Hi @seicaratteri   @machineko  
When I run this for ljspeech, do i need to change the `--yaml_path` ? Thanks
```python
python examples/mfa_extraction/txt_grid_parser.py \
  --yaml_path examples/fastspeech2_libritts/conf/fastspeech2libritts.yaml \
  --dataset_path ./ljspeech \
  --text_grid_path ./mfa/parsed \
  --output_durations_path ./ljspeech/durations \
  --sample_rate 24000 
```
