### ISSUE TITLE
hifigan tensorflow trained slowly

### ISSUE THREAD

**Issue by hdmjdp** [TensorSpeech/TensorFlowTTS#393]
I found the tf version is slower than the torch version of hifigan during training. Is that normal?

`[train]:   0%|          | 1901/2000000 [1:56:07<432417:49:49, 779.09s/it]2020-11-27 14:50:45,035 (base_trainer:140) INFO: (Steps: 1901) Finished 1 epoch training (1901 steps per epoch).
[train]:   0%|          | 1988/2000000 [1:57:26<477:51:38,  1.16it/s] `

**Comment by dathudeptrai** [comment]
> I found the tf version is slower than the torch version of hifigan during training. Is that normal?
> 
> `[train]: 0%| | 1901/2000000 [1:56:07<432417:49:49, 779.09s/it]2020-11-27 14:50:45,035 (base_trainer:140) INFO: (Steps: 1901) Finished 1 epoch training (1901 steps per epoch). [train]: 0%| | 1988/2000000 [1:57:26<477:51:38, 1.16it/s]`

Share ur cỏnfig and ur command line, it should run much faster than ur report.

**Comment by machineko** [comment]
> I found the tf version is slower than the torch version of hifigan during training. Is that normal?
> 
> `[train]: 0%| | 1901/2000000 [1:56:07<432417:49:49, 779.09s/it]2020-11-27 14:50:45,035 (base_trainer:140) INFO: (Steps: 1901) Finished 1 epoch training (1901 steps per epoch). [train]: 0%| | 1988/2000000 [1:57:26<477:51:38, 1.16it/s] `

It looks like cpu training 🍡

**Comment by hdmjdp** [comment]
@machineko @dathudeptrai It trained used gpu.

**Comment by dathudeptrai** [comment]
> @machineko @dathudeptrai It trained used gpu.

pls share ur config and ur command line.

**Comment by hdmjdp** [comment]
> pls share ur config and ur command line.

CUDA_VISIBLE_DEVICES=1 python /home/user/work/gan_vocoder/TensorFlowTTS/examples/hifigan/train_hifigan_mel.py 



hifigan_generator_params:
    out_channels: 1
    kernel_size: 7
    filters: 512
    use_bias: true
    upsample_scales: [10, 5, 3, 2, 2]
    stacks: 3
    stack_kernel_size: [3, 7, 11]
    stack_dilation_rate: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
    use_final_nolinear_activation: true
    nonlinear_activation: "LeakyReLU" # Nonlinear activation function.
    nonlinear_activation_params:      # Parameters of nonlinear activation function.
        alpha: 0.1
    is_weight_norm: false

**Comment by dathudeptrai** [comment]
> > pls share ur config and ur command line.
> 
> CUDA_VISIBLE_DEVICES=1 python /home/user/work/gan_vocoder/TensorFlowTTS/examples/hifigan/train_hifigan_mel.py
> 
> hifigan_generator_params:
> out_channels: 1
> kernel_size: 7
> filters: 512
> use_bias: true
> upsample_scales: [10, 5, 3, 2, 2]
> stacks: 3
> stack_kernel_size: [3, 7, 11]
> stack_dilation_rate: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
> use_final_nolinear_activation: true
> nonlinear_activation: "LeakyReLU" # Nonlinear activation function.
> nonlinear_activation_params: # Parameters of nonlinear activation function.
> alpha: 0.1
> is_weight_norm: false

pls copy full command line and full config json.
