### ISSUE TITLE
tensorflow profiler

### ISSUE THREAD

**Issue by jun-danieloh** [TensorSpeech/TensorFlowTTS#394]
Does anyone try tensorflow profiler? I have trouble running it :(

**Comment by dathudeptrai** [comment]
@jun-danieloh what is ur bug :)). i never try to use tfprofiler because i don't have permission in my server :))).

**Comment by jun-danieloh** [comment]
@dathudeptrai Not sure yet :) Tensorflow documentations from Google are not clear to understand :(
