### ISSUE TITLE
What are the following steps after training

### ISSUE THREAD

**Issue by luis-vera** [TensorSpeech/TensorFlowTTS#398]
Hi everybody. I am training a dataset with Tacotron2.  I understand the following steps are executing Step 3 and Step 4 according th e corresponding  README file.  

In Step 3 and Step 4 you mention model-120000.h5 but in directory checkpoint I have only model-2000.h5 and model-4000.h5 but I can't find this file in my downloaded repository. 

Next, in case I completed Step 3 and 4 how can I enter a text to TensorflowTTS if I want to synthesize it to a wav file?

Thanks a lot
Luis Vera

**Comment by dathudeptrai** [comment]
@luis-vera how many steps did you train for tacotron2 now ? 4k ?

**Comment by luis-vera** [comment]
Hi. I will use model-4000.h5 What is the difference with model-2000.h5?

**Comment by dathudeptrai** [comment]
> Hi. I will use model-4000.h5 What is the difference with model-2000.h5?

4000 mean 4k steps, 2000 mean 2k steps. You should run around 80k steps for tacotron2.

**Comment by luis-vera** [comment]
Ok thanks. Could you tell me where I can find model-80000.h5 to download it please? 

Sorry but I am new in this area and I make many questions abut this. At this moment I am executing epoch 3728/200000 in training stage in Windows 10. I tried to execute the same code in Ubuntu 20.04 but this operating system didn't recognize Cuda (10.1 nor 11.1)

**Comment by dathudeptrai** [comment]
@luis-vera https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/tacotron2#pretrained-models-and-audio-samples here :D

**Comment by luis-vera** [comment]
Hi again. Well, I tried to train dataset with tacotron2 (I entered another issue about this) and I couldn't. After that I tried to train using another model, fastspeech using extract_duration.py as you said in README with model-65000.h5 and model-120000 and I had problems because Windows message was the same:

Traceback (most recent call last):
  File "examples/fastspeech/train_fastspeech.py", line 390, in <module>
    main()
  File "examples/fastspeech/train_fastspeech.py", line 292, in main
    train_dataset = CharactorDurationMelDataset(
  File ".\examples\fastspeech\fastspeech_dataset.py", line 64, in __init__
    assert (
AssertionError: Number of charactor, mel and duration files are different                 (7018 vs 7018 vs 0).


Thanks a lot for your help

**Comment by dathudeptrai** [comment]
> Hi again. Well, I tried to train dataset with tacotron2 (I entered another issue about this) and I couldn't. After that I tried to train using another model, fastspeech using extract_duration.py as you said in README with model-65000.h5 and model-120000 and I had problems because Windows message was the same:
> 
> Traceback (most recent call last):
> File "examples/fastspeech/train_fastspeech.py", line 390, in 
> main()
> File "examples/fastspeech/train_fastspeech.py", line 292, in main
> train_dataset = CharactorDurationMelDataset(
> File ".\examples\fastspeech\fastspeech_dataset.py", line 64, in **init**
> assert (
> AssertionError: Number of charactor, mel and duration files are different (7018 vs 7018 vs 0).
> 
> Thanks a lot for your help

The assertion is clear, there is no duration file in ur folder. You should check this line (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech/fastspeech_dataset.py#L60)
