### ISSUE TITLE
fastspeech2-melgan error

### ISSUE THREAD

**Issue by augustfr** [TensorSpeech/TensorFlowTTS#399]
Not sure what's going on here. I had tacotron2-melgan and fastspeech-melgan running perfectly. But when I switched over to fastspeech2-melgan I'm getting this error:   
File "fastspeech2-melgan.py", line 79, in <module>
    mels, audios = do_synthesis(input_text, fastspeech2, melgan, "FASTSPEECH2", "MELGAN")
TypeError: cannot unpack non-iterable NoneType object

**Comment by dathudeptrai** [comment]
not sure what is a bug, can you give me a google colab to reproduce this bug ?
