### ISSUE TITLE
fastspeech embeddings - layers.Embedding & layers.Layer 

### ISSUE THREAD

**Issue by wsr692** [TensorSpeech/TensorFlowTTS#400]
Hi! 
Thanks for your passion spent on keeping this project amazingly alive!

I have another question regarding embedding implementation in your fastspeech.
Below, I see that `TFEmbedding` is subclassing  `layers.Embedding`, which implicitly does `add_weight` in `build`. May I ask why you chose to subclass embedding for positional and speaker embeddings?

https://github.com/TensorSpeech/TensorFlowTTS/blob/23d9ac3567b58825715ff9bae1784b53dea162de/tensorflow_tts/models/fastspeech.py#L66

And In comparison,  in `TFFastSpeechEmbeddings`,  layers.Layer is the superclass and  `add_weights` is being explicitly called in `build`. What is the reason for this difference?

https://github.com/TensorSpeech/TensorFlowTTS/blob/23d9ac3567b58825715ff9bae1784b53dea162de/tensorflow_tts/models/fastspeech.py#L78

I figure that layers.embedding is not trainable, and is thus used for positional and speaker embedding only - since these aren't updated, while character_embedding must be trained?

Thank you for your time!

**Comment by dathudeptrai** [comment]
@wsr692 all embedding layer in `TFFastSpeechEmbeddings` is trainable except `positional_embedding`. `TFEmbedding` layer is a replacement of `tf.keras.layers.Embedding` that fix this slow bug (https://github.com/tensorflow/tensorflow/issues/38287).

**Comment by wsr692** [comment]
got it, thanks!
