### ISSUE TITLE
hifigan uses more cpu then mb_melgan even though it is smaller model then mb_melgan !!! why ?

### ISSUE THREAD

**Issue by manmay-nakhashi** [TensorSpeech/TensorFlowTTS#402]

**Comment by dathudeptrai** [comment]
@manmay-nakhashi hifigan v1 is much larger. Hifigan v2 is smaller but discriminator is much larger :)))

**Comment by manmay-nakhashi** [comment]
@dathudeptrai i trained Hifigan v2 , it's params are lesser then mb_melgan and while deploying we use only generator , will bigger discriminator will affect in inference time ?

**Comment by dathudeptrai** [comment]
@manmay-nakhashi it affects training tỉme :)))

**Comment by manmay-nakhashi** [comment]
@dathudeptrai is there any paper on that ? , or is it like i use hifigan to give 4 subband output ?

**Comment by dathudeptrai** [comment]
We do not need any paper about mb_hifigan :))) just implement it like mb_melgan

**Comment by manmay-nakhashi** [comment]
@dathudeptrai ok i'll try that , i managed to train hifigan with only Trainable params: 232,113 , which gives a decent output , but it still takes more cpu then my mb_melgan model.

**Comment by manmay-nakhashi** [comment]
@dathudeptrai in paper they claim that v3 is much faster have you implemented that ?

**Comment by dathudeptrai** [comment]
> @dathudeptrai in paper they claim that v3 is much faster have you implemented that ?

i will.

**Comment by manmay-nakhashi** [comment]
@dathudeptrai  i have made a change for v3 i am training it , let's see what is the result
