### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by augustfr** [TensorSpeech/TensorFlowTTS#406]
What do I need to do to get the TTS to run in realtime? I've attached the python file I'm using to get the output. It takes about 15 seconds until it prompts the user for the text input. Then takes about 7 seconds to make the .wav file after receiving the text input. I'm running it on an EC2 instance with a Tesla K80 gpu. Is there a way to make this much faster without upgrading the computer I'm running it on?
[tacotron2.pdf](https://github.com/TensorSpeech/TensorFlowTTS/files/5632924/tacotron2.pdf)

**Comment by crux153** [comment]
Tacotron2 is slow. Use FastSpeech2 with MB-MelGAN :)

**Comment by augustfr** [comment]
I'm using FastSpeech2 with MB-MelGAN now, it definitely is faster than Tacotron2, but still doesn't feel like it could be used in realtime. It takes about 7 seconds for mine to run the do_synthesis function and output the .wav file. Has anyone been able to increase that speed without upgrading computer hardware?

**Comment by ZDisket** [comment]
@augustfr What do you mean? FS2 + MB-MelGAN can run about 2.5x faster than realtime on the average consumer PC (CPU).

**Comment by augustfr** [comment]
I've attached the code I'm running. If anyone could let me know why it takes about 7 seconds to process after the text is inputted that would be great. I'm running it on Ubuntu p2.xlarge instance. 



[fastspeech2-mb_melgan copy.txt](https://github.com/TensorSpeech/TensorFlowTTS/files/5663128/fastspeech2-mb_melgan.copy.txt)

**Comment by dathudeptrai** [comment]
@augustfr what is ur text :)) and what is ur CPU ?

**Comment by augustfr** [comment]
@dathudeptrai I was just doing one or two sentences. Something like "This is the new version of text to speech. Testing to see how it works" 

I'm running it on a p2.xlarge ec2 instance which has 4 vCPU's.

**Comment by dtx525942103** [comment]
@augustfr Time taken to initialize the model is long ,but speech synthesis just need 200ms

**Comment by augustfr** [comment]
@dtx525942103 is there a way to initialize the model ahead of time?
