### ISSUE TITLE
extra_duration problem

### ISSUE THREAD

**Issue by Zegalryang** [TensorSpeech/TensorFlowTTS#407]
I tried to extract duration follow command

python examples/tacotron2/extract_duration.py   --rootdir ./dump_kss/train/   --outdir ./dump_kss/train/durations/   --checkpoint tacotron2-100k.h5  --use-norm 1   --config ./examples/tacotron2/conf/tacotron2.kss.v1.yaml   --batch-size 32

after done, durations had different file count

(base) [root@f5238eaec1ac durations]# ls -al *npy | wc -l
12192

(base) [root@f5238eaec1ac ids]# ls -al *npy | wc -l
12209

what should I do?

**Comment by dathudeptrai** [comment]
@Zegalryang try to set to False (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/tacotron_dataset.py#L241)

**Comment by Zegalryang** [comment]
@dathudeptrai It works!! thanks
