### ISSUE TITLE
Error at train GAN on resume from checkpoint

### ISSUE THREAD

**Issue by r7sa** [TensorSpeech/TensorFlowTTS#409]
Resume training of GAN (in my case - HiFiGAN) from 900k step (far beyond the discriminator_train_start_steps) lead to great increasing fm_loss and decreasing real/fake_loss. I think this is due to incorrect step of descriminator that restored in line https://github.com/TensorSpeech/TensorFlowTTS/blob/26f9e0096b90e0f79c7893495e4bb75978dbf778/tensorflow_tts/trainers/base_trainer.py#L617
It seems that right code is 
`self.steps - discriminator_train_start_steps`

**Comment by dathudeptrai** [comment]
@r7sa you are right, i will fix it .
