### ISSUE TITLE
Running path problem

### ISSUE THREAD

**Issue by UNPARALLELE** [TensorSpeech/TensorflowTTS#41]
[root@localhost TensorflowTTS]# CUDA_VISIBLE_DEVICES=0 python examples/tacotron2/train_tacotron2.py --train-dir ./dump/train/ --dev-dir ./dump/valid/ --outdir ./examples/tacotron2/exp/train.tacotron2.v1/ --config ./examples/tacotron2/conf/tacotron2.v1.yaml --use-norm 1 --mix_precision 0 --resume ""
Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 31, in <module>
    from examples.tacotron2.tacotron_dataset import CharactorMelDataset
ModuleNotFoundError: No module named 'examples'

Why do I get this error when running in the root directory ?

**Comment by jun-danieloh** [comment]
This is happening to me as well. I am using Docker environment...

**Comment by MokkeMeguru** [comment]
We should use 
```python
from tensorflow_tts.examples ...
```
instead of 
```python
from examples ...
```

in whole example script.

**Comment by MokkeMeguru** [comment]
Sorry, my mistake. We should use 

```python
import sys
sys.path.append(".")

import ...
```

**Comment by xxoospring** [comment]
> Sorry, my mistake. We should use
> 
> ```python
> import sys
> sys.path.append(".")
> 
> import ...
> ```

still not work...

**Comment by MokkeMeguru** [comment]
We now solve the problem I think.
Can you try below code

```
git clone https://github.com/TensorSpeech/TensorflowTTS TTTS
cd TTTS
docker-compose build
docker-compose up -d
docker-compose exec tensoflowtts /bin/bash
python examples/tacotron2/train_tacotron2.py 
# ...
```

**Comment by dathudeptrai** [comment]
i closed since it solved
