### ISSUE TITLE
max_position_embeddings for pretrained model.

### ISSUE THREAD

**Issue by Freddy-pp** [TensorSpeech/TensorFlowTTS#410]
Hi, @dathudeptrai. First, I want to thank you for the great TTS project.

I have a noob question. When I try to synthesize a long (>450 characters) sentence with FS2 LJSpeech pretrained model, I got error similar to https://github.com/TensorSpeech/TensorFlowTTS/issues/142 . As I understand it's caused by long input that is greater than **max_position_embeddings** from config file.
In the issue thread you wrote:

> yes :)), 2048 is maximum, you can adjust it in the config file :))). replace 2048 to 10000 for example :D.

But when I'm changing the **max_position_embeddings** in config I get the following error:

Traceback (most recent call last):
  File "./infen.py", line 22, in <module>
    name="fastspeech2"
  File "/home/ubuntu/tts/TensorFlowTTS/tensorflow_tts/inference/auto_model.py", line 72, in from_pretrained
    model.load_weights(pretrained_path)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2211, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 708, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3576, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 858, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (4097, 384) and (2049, 384) are incompatible

Do I understand correctly that I can change the value **max_position_embeddings** only with a new training? Or this could be done somehow for a pretrained model? Or maybe there are any other possible ways to increase the maximum input size for a pretrained model?

**Comment by dathudeptrai** [comment]
> Hi, @dathudeptrai. First, I want to thank you for the great TTS project.
> 
> I have a noob question. When I try to synthesize a long (>450 characters) sentence with FS2 LJSpeech pretrained model, I got error similar to #142 . As I understand it's caused by long input that is greater than **max_position_embeddings** from config file.
> In the issue thread you wrote:
> 
> > yes :)), 2048 is maximum, you can adjust it in the config file :))). replace 2048 to 10000 for example :D.
> 
> But when I'm changing the **max_position_embeddings** in config I get the following error:
> 
> Traceback (most recent call last):
> File "./infen.py", line 22, in 
> name="fastspeech2"
> File "/home/ubuntu/tts/TensorFlowTTS/tensorflow_tts/inference/auto_model.py", line 72, in from_pretrained
> model.load_weights(pretrained_path)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2211, in load_weights
> hdf5_format.load_weights_from_hdf5_group(f, self.layers)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 708, in load_weights_from_hdf5_group
> K.batch_set_value(weight_value_tuples)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
> return target(*args, **kwargs)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3576, in batch_set_value
> x.assign(np.asarray(value, dtype=dtype(x)))
> File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 858, in assign
> self._shape.assert_is_compatible_with(value_tensor.shape)
> File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
> raise ValueError("Shapes %s and %s are incompatible" % (self, other))
> ValueError: Shapes (4097, 384) and (2049, 384) are incompatible
> 
> Do I understand correctly that I can change the value **max_position_embeddings** only with a new training? Or this could be done somehow for a pretrained model? Or maybe there are any other possible ways to increase the maximum input size for a pretrained model?

i will implement the method that allows you to change the `max_position_embeddings` value in the inference but don't you think 400 characters is so long and it's not present in the real-world problems?

**Comment by Freddy-pp** [comment]
> i will implement the method that allows you to change the `max_position_embeddings` value in the inference but don't you think 400 characters is so long and it's not present in the real-world problems?

Thank you for quick reply.Yes, probably such tasks will not often occur in the real world. At least for English. At the same time, in Slavic languages, sentences can sometimes be so long that two consecutive sentences may well exceed the limit of 400 characters. And sometimes even one. Therefore, it is possible that someone will train a model with a 2048 limitation on the mel length and then face the task of using longer segments. Therefore, it is possible that it would be useful to be able to change this parameter in the inference.

**Comment by dathudeptrai** [comment]
> > i will implement the method that allows you to change the `max_position_embeddings` value in the inference but don't you think 400 characters is so long and it's not present in the real-world problems?
> 
> Thank you for quick reply.
> Yes, probably such tasks will not often occur in the real world. At least for English. At the same time, in Slavic languages, sentences can sometimes be so long that two consecutive sentences may well exceed the limit of 400 characters. And sometimes even one. Therefore, it is possible that someone will train a model with a 2048 limitation on the mel length and then face the task of using longer segments. So it may be useful to be able to change this parameter in the inference.
> Thanks in advance.

did you know that almost TTS system now use **streaming** ?

**Comment by Freddy-pp** [comment]
Yes, I understand that.

**Comment by dathudeptrai** [comment]
@Freddy-pp 

```
fastspeech2.resize_positional_embeddings(3000)
fastspeech2.load_weights(..., by_name=True, skip_mismatch=True)
```

**Comment by Freddy-pp** [comment]
Hi @dathudeptrai . Thanks for your updates.

But looks that something goes wrong when I use latest commit. I update my code to latest version (d3b1bc5a52f095dac9855d789d27b8cfc0ee4856) and update installation with "pip install ." After that all sound that I could generate with the following code
```
fs2_config = AutoConfig.from_pretrained('./examples/fastspeech2/conf/fastspeech2.v1.yaml')

fastspeech2 = TFAutoModel.from_pretrained(
    config=fs2_config,
    pretrained_path="./model-150000.h5",
    name="fastspeech2"
)

mb_melgan_config = AutoConfig.from_pretrained(./examples/multiband_melgan/conf/multiband_melgan.v1.yaml')

mb_melgan = TFAutoModel.from_pretrained(
    config=mb_melgan_config,
    pretrained_path="./tftts_model.h5",
    name="mb_melgan"
)

# inference
processor = AutoProcessor.from_pretrained(pretrained_path="./test/files/ljspeech_mapper.json")
ids = processor.text_to_sequence("Hello.")

(
    masked_mel_before,
    masked_mel_after,
    duration_outputs,
    _,
    _,
) = fastspeech2.inference(
    input_ids=tf.expand_dims(tf.convert_to_tensor(ids, dtype=tf.int32), 0),
    speaker_ids=tf.convert_to_tensor([0], dtype=tf.int32),
    speed_ratios=tf.convert_to_tensor([1.0], dtype=tf.float32),
    f0_ratios =tf.convert_to_tensor([1.0], dtype=tf.float32),
    energy_ratios =tf.convert_to_tensor([1.0], dtype=tf.float32)
)

audio_after = mb_melgan.inference(masked_mel_after)[0, :, 0]

sf.write('./audio_after.wav', audio_after, 22050, "PCM_16")
```
using your pretrained model from https://drive.google.com/drive/folders/158vFyC2pxw9xKdxp-C5WPEtgtUiWZYE0 all synthesized files contains only loud noise no matter what text I use as input.

When I reset to previous commit (3fed1e8b824c581155d16d4b696e7b8255d3ad1d) all goes well and I can synthesize normal speech.

**Comment by dathudeptrai** [comment]
> Hi @dathudeptrai . Thanks for your updates.
> 
> But looks that something goes wrong when I use latest commit. I update my code to latest version ([d3b1bc5](https://github.com/TensorSpeech/TensorFlowTTS/commit/d3b1bc5a52f095dac9855d789d27b8cfc0ee4856)) and update installation with "pip install ." After that all sound that I could generate with the following code
> 
> ```
> fs2_config = AutoConfig.from_pretrained('./examples/fastspeech2/conf/fastspeech2.v1.yaml')
> 
> fastspeech2 = TFAutoModel.from_pretrained(
>     config=fs2_config,
>     pretrained_path="./model-150000.h5",
>     name="fastspeech2"
> )
> 
> mb_melgan_config = AutoConfig.from_pretrained(./examples/multiband_melgan/conf/multiband_melgan.v1.yaml')
> 
> mb_melgan = TFAutoModel.from_pretrained(
>     config=mb_melgan_config,
>     pretrained_path="./tftts_model.h5",
>     name="mb_melgan"
> )
> 
> # inference
> processor = AutoProcessor.from_pretrained(pretrained_path="./test/files/ljspeech_mapper.json")
> ids = processor.text_to_sequence("Hello.")
> 
> (
>     masked_mel_before,
>     masked_mel_after,
>     duration_outputs,
>     _,
>     _,
> ) = fastspeech2.inference(
>     input_ids=tf.expand_dims(tf.convert_to_tensor(ids, dtype=tf.int32), 0),
>     speaker_ids=tf.convert_to_tensor([0], dtype=tf.int32),
>     speed_ratios=tf.convert_to_tensor([1.0], dtype=tf.float32),
>     f0_ratios =tf.convert_to_tensor([1.0], dtype=tf.float32),
>     energy_ratios =tf.convert_to_tensor([1.0], dtype=tf.float32)
> )
> 
> audio_after = mb_melgan.inference(masked_mel_after)[0, :, 0]
> 
> sf.write('./audio_after.wav', audio_after, 22050, "PCM_16")
> ```
> 
> using your pretrained model from https://drive.google.com/drive/folders/158vFyC2pxw9xKdxp-C5WPEtgtUiWZYE0 all synthesized files contains only loud noise no matter what text I use as input.
> 
> When I reset to previous commit ([3fed1e8](https://github.com/TensorSpeech/TensorFlowTTS/commit/3fed1e8b824c581155d16d4b696e7b8255d3ad1d)) all goes well and I can synthesize normal speech.

i will fix it.
