### ISSUE TITLE
background noise in multi-band melgan

### ISSUE THREAD

**Issue by xiaoyangnihao** [TensorSpeech/TensorFlowTTS#423]
Hi, I train the multi-band melgan with my own CN datasets, which is similar with baker. So  I use the dafauat config as baker. But there is some backgroud noise in the synthesized audio. Any ideas to solve this problems ?

**Comment by dathudeptrai** [comment]
> Hi, I train the multi-band melgan with my own CN datasets, which is similar with baker. So I use the dafauat config as baker. But there is some backgroud noise in the synthesized audio. Any ideas to solve this problems ?

share tensorboard and audio samples, pls.

**Comment by xiaoyangnihao** [comment]
![image](https://user-images.githubusercontent.com/14233490/101740927-6a0bd380-3b04-11eb-88eb-679b3293b30c.png)

here is my audio samples. I use the true mel as the test input. [test.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5671266/test.zip)

**Comment by dathudeptrai** [comment]
> ![image](https://user-images.githubusercontent.com/14233490/101740927-6a0bd380-3b04-11eb-88eb-679b3293b30c.png)
> 
> here is my audio samples. I use the true mel as the test input. [test.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5671266/test.zip)

the tensorboard is very good interns of loss value. Ur synthesize audio is good based on my non-native ear :))

**Comment by xiaoyangnihao** [comment]
thx, I will try some other checkpoints.

**Comment by xiaoyangnihao** [comment]
> > ![image](https://user-images.githubusercontent.com/14233490/101740927-6a0bd380-3b04-11eb-88eb-679b3293b30c.png)
> > here is my audio samples. I use the true mel as the test input. [test.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5671266/test.zip)
> 
> the tensorboard is very good interns of loss value. Ur synthesize audio is good based on my non-native ear :)). You can try the other checkpoints (around 1M-1.5M steps)

By the way, which loss value is not so good you think ? What should be the normal loss value?

**Comment by dathudeptrai** [comment]
@xiaoyangnihao all ur loss value is very good :))).
