### ISSUE TITLE
background noise in multi-band melgan, MY custom Datasets

### ISSUE THREAD

**Issue by chanyong-owl** [TensorSpeech/TensorFlowTTS#424]
Hi, I train the multi-band melgan with my custom datasets, 

it's small datasts about 5,000 for test

so i used multiband_melgan.v1.yaml  

and changed  unsample rate [2,4,8]  beacuse it's small datasets

I train about 700,000 iters. 

but there is some background noise in multi-band melgan with my custom Datasets

the noise exists in 300,000 iters already. T.T

If i train more than 1M, 2M ..... , the noise can be removed??

I put the log for your [help.T,T]
![eval](https://user-images.githubusercontent.com/57178312/101849675-89a20b00-3b9b-11eb-9194-3a81cf9a64d3.png)
![train](https://user-images.githubusercontent.com/57178312/101849689-91fa4600-3b9b-11eb-8021-57b25649a006.png)

**Comment by ZDisket** [comment]
It would help a lot for you to include audio samples.

**Comment by chanyong-owl** [comment]
test for AWS POLLY Datasets (KOREAN)

custom is the result for training
aws is original voice

Thank you

[voice.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/5676631/voice.zip)

**Comment by ronggong** [comment]
There seems the same kind of noise in the English colab demo https://colab.research.google.com/drive/1akxtrLZHKuMiQup00tzO2olCaN-y3KiD?usp=sharing#scrollTo=_ChvXMc8mF7K
The MB-melgan is 940k steps there. I am also curious if the noise will disappear by training more steps.
