### ISSUE TITLE
Indian accent English voice cloning 

### ISSUE THREAD

**Issue by ajay01994** [TensorSpeech/TensorFlowTTS#428]
Hi team,

Thanks for your efforts to build this repo, i am looking for voice cloning over Indian English accent and other local languages. Can you please tell me they steps how to do that, i have the speech data of the mentioned accents but are not trained. 

Thanks 

Ajay sahu

**Comment by dathudeptrai** [comment]
@ajay01994 maybe you need to read this discussion (https://github.com/TensorSpeech/TensorFlowTTS/issues/296). 

@OscarVanL can you help him ?

**Comment by OscarVanL** [comment]
Hi ajay, as dathudeptrai suggested you can read that long thread where I tried to do the same with British accents with FastSpeech2 acoustic model and MB-MelGAN vocoder. My [final summary reply](https://github.com/TensorSpeech/TensorFlowTTS/issues/296#issuecomment-741850534) might save you some time if you don't want to read it all.

Here's what I did:

1. I took the existing LJSpeech [fastspeech2.v1](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2) pre-trained model. This model is trained on English American speakers, but we can finetune it to any accent we want.

2. I found a dataset with the accent I wanted, in my case I wanted Southern British accents, so I found a dataset with this.

* Unfortunately, this dataset wasn't large enough to train on this alone.
* So I merged this dataset as a 50:50 split with LibriTTS (mostly American speakers), giving me a total of 35 hours of speech with 100 speakers.

3. I modified the [dataset preparation steps](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2_libritts) for FastSpeech2 LibriTTS to my needs, then trained using the `--pretrained` argument as explained [here](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2) to fine-tune the LJSpeech `fastspeech2.v1` model.

4. Finally, at inference, you need to pass in a speaker ID from your Indian accent dataset (if you merge two accents together as I did, you want to avoid using an American speaker ID or your model will make American speech). You should check `libritts_mapper.json`, which is a file generated that has a mapping from your dataset's speaker IDs to the IDs you need to use in inference.

To get good sounding speech, I also fine-tuned a MBMelgan vocoder, which removed a lot of the buzzing and artefacts. This was quite simple and I just used the same dataset I used for training FS2. But you should work on training your acoustic model first :)


I'm not sure how to train for the local Indian languages you mentioned, but I found the "Microsoft Speech Corpus (Indian languages)" dataset [here](https://github.com/JRMeyer/open-speech-corpora), which could be helpful.

Hope this helps you get started.

**Comment by ajay01994** [comment]
Hi @OscarVanL, Thanks for your steps and suggestions, I'll try this out and see how it performs.. @dathudeptrai  highly appreciate your efforts to look into this issue and put forward help.. 

Thanks!

Ajay

**Comment by amrahsmaytas** [comment]
Hi @OscarVanL @dathudeptrai , 

Very thanks for the steps and details, 
But, being a beginner in fields like tts and voice synthesis, I am quite confused regarding few terms like tts, voice cloning, 

For eg: by reading above details, I understand that, if we train on Indian dataset, we can get tts in Indian accent (which does not include my voice),

But, not voice cloning, that is my voice cloned, am I right? 

Did I miss anything? 

Can you please guide me, how can I achieve my voice clone (I am an Indian) once I train the tensorflow tts on Indian dataset? 

How long, I need to wait to get my voice clone reading some 200-300 words? 

Will it be real time? 

Thanks 🙂

**Comment by ariG23498** [comment]
Hey @OscarVanL 
I have been trying to poke around on a similar topic. I have tried emulating the steps that you have taken. I have limited data, and am training just the `embedding` layer of the FS2 model for a mere 5k epochs.

I am not able to fathom the `speaker_id` part in inference step.
```python
mel_before, mel_outputs, duration_outputs, _, _ = text2mel_model.inference(
  tf.expand_dims(tf.convert_to_tensor(input_ids, dtype=tf.int32), 0),
  speaker_ids=tf.convert_to_tensor([1], dtype=tf.int32), # have changed the 0 to a 1, as the speaker_id I have provided is 1.
  speed_ratios=tf.convert_to_tensor([1.0], dtype=tf.float32),
  f0_ratios=tf.convert_to_tensor([1.0], dtype=tf.float32),
  energy_ratios=tf.convert_to_tensor([1.0], dtype=tf.float32),
)
```
This just so happens that providing any value in `speaker_ids=tf.convert_to_tensor([1], dtype=tf.int32)` produces the same voice in the inference step.
I did notice that in the `./dump/libritts_mapper.json` I have the speaker ids
```json
"speakers_map":{
      "6209":0,
      "1088":1,
      "3830":2,
      "1":3,
      "6147":4,
      "8088":5
   },
```
But I can literally provide any other value, the model still runs and provides the same voice. Am I doing anything wrong here?
