### ISSUE TITLE
Can I getTacotron2 inference reference?

### ISSUE THREAD

**Issue by Zegalryang** [TensorSpeech/TensorFlowTTS#431]
I'd like to check my trained model in tacotron2 step(with melgan)

Inference sample in the main page didnt work..

so, can i get or refer to something about inference tacotoron2?

**Comment by dathudeptrai** [comment]
pls follow the inference colab (https://colab.research.google.com/drive/1akxtrLZHKuMiQup00tzO2olCaN-y3KiD?usp=sharing)

**Comment by Zegalryang** [comment]
@dathudeptrai Thanks!!
