### ISSUE TITLE
Train Multinband melgan

### ISSUE THREAD

**Issue by Zegalryang** [TensorSpeech/TensorFlowTTS#433]
I'd like to train multiband melgan

and i first, i trained stft losses and i want to train start training generator + discriminator 
using instruction 

```
CUDA_VISIBLE_DEVICES=0 python examples/multiband_melgan/train_multiband_melgan.py \
  --train-dir ./dump/train/ \
  --dev-dir ./dump/valid/ \
  --outdir ./examples/multiband_melgan/exp/train.multiband_melgan.v1/ \
  --config ./examples/multiband_melgan/conf/multiband_melgan.v1.yaml \
  --use-norm 1 \
  --resume ./examples/multiband_melgan/exp/train.multiband_melgan.v1/checkpoints/ckpt-200000
```

but.. I cannot find resume checkpoint
in the folder of checkpoints like that.

<img width="835" alt="스크린샷 2020-12-18 오후 3 31 27" src="https://user-images.githubusercontent.com/2080839/102582613-5127a180-4146-11eb-9501-53f993b38fd5.png">

what file should i use?

**Comment by Liofang** [comment]
you config is:  --resume ./examples/multiband_melgan/exp/train.multiband_melgan.v1/checkpoints/ckpt-200000
but the path you show in the fig is '/multiband_melgan/train.mb_melgan.kss.v1'
