### ISSUE TITLE
Multi-speaker is slower than single speaker on Tacotron2 training

### ISSUE THREAD

**Issue by ZhaoZeqing** [TensorSpeech/TensorFlowTTS#434]
I used a multi-speaker dataset with 101 speakers and I added speaker id in tacotron_dataset, but found that multi-speaker is slower than single speaker when training Tacotron2 on one P100:

**Multi-speaker**
n_speakers: 101
batch_size: 8
about 12s/it

**Single speaker**
n_speakers: 1
batch_size: 16
about 3s/it

I added these code at tacotron_dataset:
`
datasets = datasets.filter(
            lambda x: x["mel_lengths"] <= 800
        )
`

**Comment by dathudeptrai** [comment]
@ZhaoZeqing is this problem still exist ?

**Comment by ZhaoZeqing** [comment]
@dathudeptrai Yes, it still exists.

**Comment by dathudeptrai** [comment]
> @dathudeptrai Yes, it still exists.

how about 2,3,4,5,6 speakers ? did you test it ?

**Comment by ZhaoZeqing** [comment]
@dathudeptrai I'll try it, many thanks!

**Comment by ZhaoZeqing** [comment]
@dathudeptrai  I tried different number of speakers, it seems ok when use 101 speakers with 12s/it

batch size: 8
n_speakers:
  2   5.7s/it
  4   6.2s/it
  10  9.4s/it
  101 12s/it

**Comment by ZhaoZeqing** [comment]
@dathudeptrai This issue is ok now. I found that the speed was slow because of the long audios in my dataset.

**Comment by dathudeptrai** [comment]
@ZhaoZeqing oh, good to know that :D.
