### ISSUE TITLE
Have you considered adding DeviceTTS code?

### ISSUE THREAD

**Issue by CrossEntropy** [TensorSpeech/TensorFlowTTS#444]
Hi @dathudeptrai Good job! 

Have you considered adding DeviceTTS code? It seems that this [article](https://arxiv.org/abs/2010.15311) is quite interesting.Thanks

**Comment by dathudeptrai** [comment]
@CrossEntropy let me see.

**Comment by monatis** [comment]
I was also interested in this paper, but the closed Chinese dataset they're using already has prosody annotations and phone-level timestamps (see 3.1 Speech corpus in the paper), so it may be hard to reproduce with public datasets.

**Comment by CrossEntropy** [comment]
@monatis  This article cleverly embeds the autoregressive into the hidden layer of the encoder and uses a simple module to replace the FFT (feed forward transformer). However, not using the self-attention mechanism still makes me confused.

**Comment by monatis** [comment]
@CrossEntropy Yes, the proposed DFSMN architecture comes from [this paper (PDF)](https://arxiv.org/pdf/1803.05030.pdf) by the same authors. Unfortunately there are not many uses of this architecture in the literature and end-to-end implementations in the public domain. So the results remain questionable until we actually implement and train it from scratch.

**Comment by CrossEntropy** [comment]
@CrossEntropy Thank you for your interpretation. I found this article (DFSMN) published in ICASSP 2018. I think the most magical part of DeviceTTS is DFSMN, which greatly reduces the amount of network calculations (0.099G FLOPs/ second in the result of paper). It would be better if the author could provide more details of model construction :)
