### ISSUE TITLE
Trills and jitters in Chinese TTS demo wav

### ISSUE THREAD

**Issue by xiaoyangnihao** [TensorSpeech/TensorFlowTTS#445]
In Chinese TTS demo: https://colab.research.google.com/drive/1YpSHRBRPBI7cnTkQn1UcVTWEQVbsUm1S?usp=sharing#scrollTo=BcrLl7j_fbE2.

The wavs in the colab demo seems to have distinct trills and jitters，no matter the model is tacotron or fastspeech. I think it is caused by mb-melgan, so any ideas to slove this probem?  I also try databaker dataset by myself, there are same problems, even I train the mb-melgan model a bit longer steps.

**Comment by dathudeptrai** [comment]
cc: @candlewill @azraelkuan

**Comment by azraelkuan** [comment]
@xiaoyangnihao maybe cayse by the mismatch between predicted mels and groundtruth mels. can u try to refine the mbmelgan using tacotron's gta mels?

**Comment by xiaoyangnihao** [comment]
> @xiaoyangnihao maybe cayse by the mismatch between predicted mels and groundtruth mels. can u try to refine the mbmelgan using tacotron's gta mels?

there is still same problem in gta mode

**Comment by OnceJune** [comment]
try:
1. norm your wav files, avoid clip
2. adjust fmax in audio process config

**Comment by xiaoyangnihao** [comment]
> try:
> 
> 1. norm your wav files, avoid clip
> 2. adjust fmax in audio process config

thanks, I will try and reply later.

**Comment by xxoospring** [comment]
Hi, how about your result?

**Comment by xiaoyangnihao** [comment]
> Hi, how about your result?

I try to norm wav files, but the synthed audios sound even worse, I don't know why.

**Comment by xxoospring** [comment]
> > Hi, how about your result?
> 
> I try to norm wav files, but the synthed audios sound even worse, I don't know why.
I also encountered this problem with LJSpeech

**Comment by xxoospring** [comment]
I also check the [demo page](https://drive.google.com/drive/u/0/folders/1NG7oOfNuXSh7WyAoM1hI8P5BxDALY_mU),  LJ002-0303.wav also have this problem

**Comment by xiaoyangnihao** [comment]
> I also check the [demo page](https://drive.google.com/drive/u/0/folders/1NG7oOfNuXSh7WyAoM1hI8P5BxDALY_mU), LJ002-0303.wav also have this problem

Someone says this is caused by GAN network itself. So have you try to do some optimazations to solve this probems ?
By the way, have you try to set  is_weight_norm=true, I tried, but the error curve does not converge. @dathudeptrai@candlewill @azraelkuan

**Comment by xxoospring** [comment]
> > I also check the [demo page](https://drive.google.com/drive/u/0/folders/1NG7oOfNuXSh7WyAoM1hI8P5BxDALY_mU), LJ002-0303.wav also have this problem
> 
> Someone says this is caused by GAN network itself. So have you try to do some optimazations to solve this probems ?
> By the way, have you try to set is_weight_norm=true, I tried, but the error curve does not converge. @dathudeptrai @candlewill @azraelkuan

No, I didn't do optimizations, maybe its just because of the "GAN", not about the model, I have also encountered this on melgan last year

**Comment by xiaoyangnihao** [comment]
> > > I also check the [demo page](https://drive.google.com/drive/u/0/folders/1NG7oOfNuXSh7WyAoM1hI8P5BxDALY_mU), LJ002-0303.wav also have this problem
> > 
> > 
> > Someone says this is caused by GAN network itself. So have you try to do some optimazations to solve this probems ?
> > By the way, have you try to set is_weight_norm=true, I tried, but the error curve does not converge. @dathudeptrai @candlewill @azraelkuan
> 
> No, I didn't do optimizations, maybe its just because of the "GAN", not about the model, I have also encountered this on melgan last year

So what is your choice for vocoder now?

**Comment by xxoospring** [comment]
> > > > I also check the [demo page](https://drive.google.com/drive/u/0/folders/1NG7oOfNuXSh7WyAoM1hI8P5BxDALY_mU), LJ002-0303.wav also have this problem
> > > 
> > > 
> > > Someone says this is caused by GAN network itself. So have you try to do some optimazations to solve this probems ?
> > > By the way, have you try to set is_weight_norm=true, I tried, but the error curve does not converge. @dathudeptrai @candlewill @azraelkuan
> > 
> > 
> > No, I didn't do optimizations, maybe its just because of the "GAN", not about the model, I have also encountered this on melgan last year
> 
> So what is your choice for vocoder now?

I am choosing right now, not decided yet:smile:
