### ISSUE TITLE
Hifi GAN pre-trained model

### ISSUE THREAD

**Issue by tulasiram58827** [TensorSpeech/TensorFlowTTS#447]
Can you provide the pre-trained model of Hifi GAN trained on LJSpeech dataset.

@dathudeptrai

**Comment by dathudeptrai** [comment]
i have no time to train it on a Public dataset but it's ok in my private dataset :D, need community contribution :D.

**Comment by ZDisket** [comment]
@dathudeptrai Did you try both v1 and v2? I couldn't get v2 to even sound similar.

**Comment by monatis** [comment]
hi @dathudeptrai I can give it a go with your dataset, plus with Thorsten dataset in German 🙂
