### ISSUE TITLE
MFA on LJSpeech

### ISSUE THREAD

**Issue by CrossEntropy** [TensorSpeech/TensorFlowTTS#448]
Hi @machineko @dathudeptrai @ZDisket  I have two questions.

Q1: I cleaned the text in ljspeech using `english_cleaners`, but when I run:

```python
python examples/mfa_extraction/run_mfa.py \
--corpus_directory ./ljspeech \
--output_directory ./mfa/parsed \
--jobs 8
```

the result is very poor:
`
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 12828.0
Creating dictionary information...
Done with setup.
There were 3275 segments/files not aligned. Please see ./mfa/parsed/unaligned.txt for more details on why alignment failed for these files.
Done! Everything took 2419.595493555069 seconds
`

Did I do something wrong?

Q2: When I run this for ljspeech, do i need to change the `--yaml_path` ? 
```python
python examples/mfa_extraction/txt_grid_parser.py \
--yaml_path examples/fastspeech2_libritts/conf/fastspeech2libritts.yaml \
--dataset_path ./ljspeech \
--text_grid_path ./mfa/parsed \
--output_durations_path ./ljspeech/durations \
--sample_rate 16000
```

Thanks!

**Comment by machineko** [comment]
Hey @CrossEntropy MFA is package build not by us but not aligned can happen by multiple reasons mostly failing of beam search and not enough phonemes in dictionary.

Questions related to MFA u should make here => [MFA_REPO](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues)

About second question => 
Yes u should point to config based on ljspeech not libritts this are 2 different dataset (single and multispeakers)

**Comment by CrossEntropy** [comment]
Thank you for your reply @machineko  One step further, can I train a tacotron2 that uses phonemes to get better alignment?

**Comment by machineko** [comment]
Yup u can very easy train Tacotron2 using phonemes just swap characters to phonemes in ur input files :).
but still MFA give better alignment in most cases :)

**Comment by CrossEntropy** [comment]
Thanks @machineko
