### ISSUE TITLE
WebGL / in-browser synthetisation opportunity?

### ISSUE THREAD

**Issue by miohtama** [TensorSpeech/TensorFlowTTS#451]
The latest WebGL supports TensorFlow:

https://www.tensorflow.org/js/guide/platform_environment

My question is that are there any technical limitations, like model sizes or specific used TensorFlow features, which would prevent running TensorFlowTTS within a web browser using WebAssembly and WebGL. As this would open a door dor dynamic dubbing and would be a huge accessibility win in many uses. Are there any other considerations one should think when embedding TensowFlowTTS into a web page?

Myself, I consider CDN cached 100 MB - 500 MB download size for the model as the reasonable expectation what users would be willing to download to get the text-to-speech within a web page or web app.

**Comment by dathudeptrai** [comment]
i never try to use webGL :)))

**Comment by StoneCypher** [comment]
> Myself, I consider CDN cached 100 MB - 500 MB download size for the model as the reasonable expectation

[so, ... half a cent per page view](https://aws.amazon.com/cloudfront/pricing/)?

This isn't realistic.

**Comment by miohtama** [comment]
There are open source-oriented CDNs like [KeyCDN](https://www.keycdn.com/open-source-cdn and others. These CDN services are happy to absorb the distribution cost if the service for the public good in the exchange of brand and promotion value. The internal price of delivery is way lower than half a cent per user, so it is not unrealistic. You do not need to load the set for every page view.
