### ISSUE TITLE
duration from lab files

### ISSUE THREAD

**Issue by altangerelc** [TensorSpeech/TensorFlowTTS#456]
Hi all,

I have a question about duration alignment import from HTS aligned phoneme data.
I wanna elude the step to get durations with Tacotron2 and/or MFA.
How should I import from .lab file? Is there any script developed?
If no, how should I convert the aligned .lab file millisecond to mel ?
I am using "ljspeech" dataset.

**Comment by machineko** [comment]
For mfa https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/mfa_extraction

**Comment by altangerelc** [comment]
@machineko Thanks for the pointer.
Does this mean mel_duration = second_duration * ( sample_rate / hop_size) ?
I checked it on 4.52 second speech but the sum of the phonemes length comes as 313 which should be about 389 mels.
It is not so precise. Is there any problem or am I wrong ?

**Comment by machineko** [comment]
Not sure if u have problem with that u need to give me sample file to check it myself

**Comment by altangerelc** [comment]
@machineko Sample rate is 22050 hz, and hop size is 256. a sample wav file length is 5.28 seconds long and after preprocessing step its corresponding raw-feats length is 443. How should I send you the sample, by email?

**Comment by machineko** [comment]
upload to google drive/dropbox

**Comment by altangerelc** [comment]
@machineko Here are the sample files. I would like to create a duration file for this. 
 https://drive.google.com/file/d/1ojIynYmfHP6ZWbXLoqB7C8e1bVcO7Rvj/view?usp=sharing 
I got this
 https://drive.google.com/file/d/1PdmuK_2hbZXN4Mt2_QhK1IFCyOGHifG0/view?usp=sharing

**Comment by altangerelc** [comment]
Dear all, Thanks for the help. I got the clue from the issue #461. 
The issue was the trimming silences.
