### ISSUE TITLE
Parallel WaveGAN TFLite

### ISSUE THREAD

**Issue by tulasiram58827** [TensorSpeech/TensorFlowTTS#458]
Hi @dathudeptrai,

We(@sayakpaul)  successfully converted the PyTorch pre-trained model(from the [repository](https://github.com/kan-bayashi/ParallelWaveGAN)) to TFLite Format with the help of [Notebook](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/parallel_wavegan/convert_pwgan_from_pytorch_to_tensorflow.ipynb) from this repository.

You can find the conversion notebook [here](https://github.com/tulasiram58827/TTS_TFLite/blob/main/Parallel_WaveGAN_TFLite.ipynb).

As this repository contains a lot of collections of other models also I would like to add this [Notebook](https://github.com/tulasiram58827/TTS_TFLite/blob/main/Parallel_WaveGAN_TFLite.ipynb) to this repository so that many people get benefitted.  If you would like me to add I will go ahead and open PR.

Also, I would like to publish the Parallel WaveGAN model to TF Hub. As I used the code from this repository to convert PyTorch Weights to TensorFlow so I need your permission to publish it to TFHub. Let me know if I can go ahead and publish.

You can refer to this [Repository](https://github.com/tulasiram58827/TTS_TFLite) for other TFLite models like HiFi-GAN and for [benchmarks comparison](https://github.com/tulasiram58827/TTS_TFLite#model-benchmarks) of all other available models.

**Comment by dathudeptrai** [comment]
@tulasiram58827 great works, let creat a PR then I can review and merge it :D. It's good if you can publish TTS model to tfhub, i also tried it before but the tfhub-team answered too slowly:))))

**Comment by tulasiram58827** [comment]
Sure then I will proceed with PR and TFHub. Do you want me to publish models like Tacotron2, Fastspeech2, MelGAN also to TFHub?

**Comment by dathudeptrai** [comment]
> Sure then I will proceed with PR and TFHub. Do you want me to publish models like Tacotron2, Fastspeech2, MelGAN also to TFHub?

that would be great :)).

**Comment by tulasiram58827** [comment]
Created [PR](https://github.com/tensorflow/tfhub.dev/pull/37) to publish to TFHub. Will inform you once they are published.

**Comment by tulasiram58827** [comment]
@dathudeptrai Models are now available on TFHub. You can find [here](https://tfhub.dev/tulasiram58827)
