### ISSUE TITLE
Feature Request Thread

### ISSUE THREAD

**Issue by dathudeptrai** [TensorSpeech/TensorFlowTTS#467]
Don't hesitate to tell me what features you want in this repo :)))

**Comment by unparalleled-ysj** [comment]
@dathudeptrai What do you think of voice cloning

**Comment by mikus** [comment]
I would like to see better componentization. There are similar blocks (groups of layers) implemented multiple times, like positional encoding, speaker encoding or postnet. Others relates on configuration specific just for one particular network like self-attention block used in FastSpeech. With a little rework, making those block more generic it would be easier to create new network types. Similarly with losses, e.g. training for hifigan contains many duplicated code from mb-melgan. Moreover, most of the training and inference scripts looks quite similar and I believe they can be refactored too to, once again, compose the final solution from more generic components.

And BTW, I really appreciate your work and think you did a great job! :)

**Comment by dathudeptrai** [comment]
> training for hifigan contains many duplicated code from mb-melgan

Hmm, in this case, users just need to read and understand hifigan without reading mb-melgan.

**Comment by ZDisket** [comment]
@unparalleled-ysj What do you mean by voice cloning? You mean zero-shot?

**Comment by unparalleled-ysj** [comment]
> @unparalleled-ysj What do you mean by voice cloning? You mean zero-shot?
For example, given a short segment of the target person’s voice, the model does not need to be retrained to synthesize the voice of the speaker’s timbre, such as using voiceprint technology to extract speaker embedding to train a multi-speaker TTS model

**Comment by ZDisket** [comment]
@unparalleled-ysj That's what I was thinking about. Relevantly, @dathudeptrai I saw https://github.com/dipjyoti92/SC-WaveRNN, could SC-MB-MelGAN be possible?

**Comment by lr2582858** [comment]
@unparalleled-ysj @ZDisket That is also what I’m doing. I'm trying to train a multi-speaker fastspeech2 model replacing current hardcoding speaker-ID with bottleneck feature extracted by a voiceprint model.  The bottleneck feature of continuous softcoding represents a speaker-related space. If the unknown voice is similar to a voice in the training space, voice cloning may be realized. But judging from the results of current open source projects, it is a difficult problem and certainly not as simple as I described. Do you have any good ideas?

**Comment by mikus** [comment]
One of the options for better support for multiple speakers or styles could be an adding of Variable Auto-Encoder which automatically extracts this voice/style "fingerprint".

**Comment by abylouw** [comment]
LightSpeech https://arxiv.org/abs/2102.04040

**Comment by nmfisher** [comment]
@abylouw Here's an early version of LightSpeech here https://github.com/nmfisher/TensorFlowTTS/tree/lightspeech

Training pretty well on a Mandarin dataset so far (~30k steps) but haven't validated formally against LJSpeech (to be honest, I don't think I'll get time, so would prefer someone else to help out).

This is just the final architecture mentioned in the paper (so I haven't implemented any NAS). 

Also the paper only mentioned the final per-layer SeparableConvolution kernel sizes, not the number of attention heads, so I've emailed one of the authors to ask if he can provide that too.

**Comment by dathudeptrai** [comment]
> @abylouw early version of LightSpeech here https://github.com/nmfisher/TensorFlowTTS/tree/lightspeech
> 
> Training pretty well on a Mandarin dataset so far (~30k steps) but haven't validated formally against LJSpeech (to be honest, I don't think I'll get time, so would prefer someone else to help out).
> 
> This is just the final architecture mentioned in the paper (so I haven't implemented any NAS).
> 
> Also the paper only mentioned the final per-layer SeparableConvolution kernel sizes, not the number of attention heads, so I've emailed one of the authors to ask if he can provide that too.

great! :D. how about a number of parameters in LightSpeech ?

**Comment by nmfisher** [comment]
My early version of LightSpeech is:
![image](https://user-images.githubusercontent.com/7238578/109444672-df4acd00-7a91-11eb-8129-c9ff42b95b1f.png)

By comparison, FastSpeech 2 (v1) is:

![image](https://user-images.githubusercontent.com/7238578/109444718-f7225100-7a91-11eb-9289-ab9f049956a8.png)

But given the paper claims 1.8M parameters for LightSpeech (vs 27M for FastSpeech 2), my implementation obviously still isn't 100% accurate. Feedback from the authors will help clarify the number of attention heads (and also the hidden size of each head).

Also I think the paper didn't implement PostNet, so removing that layer immediately eliminates ~4.3M parameters.

**Comment by luan78zaoha** [comment]
@dathudeptrai @nmfisher I also tried to reduce the model size of FastSpeech2 (but not include PostNet modular) with a parameter order: Encoder Dim > 1d_CNN > Attention = Stacks_Num. Reducing encoder-dim is the most effective way to reduce the model size. For the config of fastspeech2.baker.v2.yaml, the model size reduced from 64M to 28M, and the proportion of Postnet modules in the total model size increased from 27% to 62%. Interestingly, the effect does not get worse after deleting Postnet during inference, for Baker Dataset. Thus, the final model size is only 10M. Based on the above experiments, the model size may have the potential to be further reduced.

**Comment by dathudeptrai** [comment]
> @dathudeptrai @nmfisher I also tried to reduce the model size of FastSpeech2 (but not include PostNet modular) with a parameter order: Encoder Dim > 1d_CNN > Attention = Stacks_Num. Reducing encoder-dim is the most effective way to reduce the model size. For the config of fastspeech2.baker.v2.yaml, the model size reduced from 64M to 28M, and the proportion of Postnet modules in the total model size increased from 27% to 62%. Interestingly, the effect does not get worse after deleting Postnet during inference, for Baker Dataset. Thus, the final model size is only 10M. Based on the above experiments, the model size may have the potential to be further reduced.

yeah, Postnet is only for faster convergence, we can ignore it after the training process.

**Comment by dathudeptrai** [comment]
@nmfisher 6M params is small enough, did you get a good result with lighspeech ? . how fast is it ?

**Comment by luan78zaoha** [comment]
> > @dathudeptrai @nmfisher I also tried to reduce the model size of FastSpeech2 (but not include PostNet modular) with a parameter order: Encoder Dim > 1d_CNN > Attention = Stacks_Num. Reducing encoder-dim is the most effective way to reduce the model size. For the config of fastspeech2.baker.v2.yaml, the model size reduced from 64M to 28M, and the proportion of Postnet modules in the total model size increased from 27% to 62%. Interestingly, the effect does not get worse after deleting Postnet during inference, for Baker Dataset. Thus, the final model size is only 10M. Based on the above experiments, the model size may have the potential to be further reduced.
> 
> yeah, Postnet is only for faster convergence, we can ignore it after the training process.

I'm sorry that I haven't studied lightspeech in detail, and I have a question: what's the difference in details between the small-size FastSpeech and lightspeech. @nmfisher

**Comment by dathudeptrai** [comment]
> I'm sorry that I haven't studied lightspeech in detail, and I have a question: what's the difference in details between the small-size FastSpeech and lightspeech. @nmfisher

@luan78zaoha lightspeech use separableConvolution :D.

**Comment by luan78zaoha** [comment]
@dathudeptrai  I used TF-LITE to inferencing on x86-linux platform. The result is that: RTF of 45M and 10M models were 55.6 and 98.0, respectively.

**Comment by dathudeptrai** [comment]
> @dathudeptrai I used TF-LITE to inferencing on x86-linux platform. The result is that: RTF of 45M and 10M models were 55.6 and 98.0, respectively.

let wait @luan78zaoha reports lightspeech RTF :D.

**Comment by nmfisher** [comment]
> > > @dathudeptrai @nmfisher I also tried to reduce the model size of FastSpeech2 (but not include PostNet modular) with a parameter order: Encoder Dim > 1d_CNN > Attention = Stacks_Num. Reducing encoder-dim is the most effective way to reduce the model size. For the config of fastspeech2.baker.v2.yaml, the model size reduced from 64M to 28M, and the proportion of Postnet modules in the total model size increased from 27% to 62%. Interestingly, the effect does not get worse after deleting Postnet during inference, for Baker Dataset. Thus, the final model size is only 10M. Based on the above experiments, the model size may have the potential to be further reduced.
> > 
> > 
> > yeah, Postnet is only for faster convergence, we can ignore it after the training process.
> 
> I'm sorry that I haven't studied lightspeech in detail, and I have a question: what's the difference in details between the small-size FastSpeech and lightspeech. @nmfisher

As @dathudeptrai mentioned, LightSpeech uses SeparableConvolution in place of regular Convolution, but then also passes various FastSpeech2 configurations through neural architecture search to determine the best configuration of kernel sizes/attention heads/attention dimensions. Basically they use NAS to find the smallest configuration that performs as well as FastSpeech2.

**Comment by debasish-mihup** [comment]
@dathudeptrai Can you help me implement Higan with fastspeech2 on android? I have tried to implement the same by using https://github.com/tulasiram58827/TTS_TFLite/tree/main/models pretrained model and changing the line  
https://github.com/TensorSpeech/TensorFlowTTS/blob/9a107d98bd20e8030c07e03a5857f62f36d69270/examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/FastSpeech2.java#L73 to handle the input model data shape. But the output is pure noise.

**Comment by StuartIanNaylor** [comment]
Note really a request but just wondering about the use of Librosa.
I have been playing around with https://github.com/google-research/google-research/tree/master/kws_streaming which uses internal methods for MFCC.
The one it uses is the pyhon.ops one but the tf.signal was also quite a perf boost on using librosa.

Is there any reason for librosa over say tf.signal.stft and tf.signal.linear_to_mel_weight_matrix as they seem extremely performant?

**Comment by Collin-Budrick** [comment]
> @dathudeptrai What do you think of voice cloning

I have no doubt this project would work wonders on Voice cloning.

**Comment by StuartIanNaylor** [comment]
With the fastspeech tflite model is it possible to covert to run on a Edge TPU?
If so any examples how?

**Comment by zero15** [comment]
Will tacotron2 support full integer quantization in tflite?
Current model use full interger quantization failed with "pybind11::init(): factory function returned nullptr."  It's likely because the model has multi subgraphs

**Comment by ZDisket** [comment]
@dathudeptrai Can you help with implementing forced alignment attention loss for Tacotron2 like in [this paper](https://ieeexplore.ieee.org/document/8703406)? I've managed to turn MFA durations into alignments and put them in the dataloader, but replacing the regular guided attention loss only makes the attention learning worse, at least when finetuning a regular model.

**Comment by dathudeptrai** [comment]
@ZDisket let me read the paper first :D.

**Comment by ZDisket** [comment]
@dathudeptrai Since that post I discovered that MAE between the generated and forced attention works to guide it, but it's so strong that it ends up hurting performance, which could be fixed with a low enough multiplier like 0.01, although I haven't tested it extensively as I abandoned it in favor of training a universal vocoder with a trick.

**Comment by alexdemartos** [comment]
This looks really interesting:

https://arxiv.org/pdf/2106.03167v2.pdf

**Comment by tts-nlp** [comment]
I have implemented algorithm 3, but the effect is not good, my implementation is as follows
  
from numpy.lib.stride_tricks import as_strided
import numpy as np
from scipy import fftpack


def xcorr_offset(x1, x2):
    """
    Under MSR-LA License
    Based on MATLAB implementation from Spectrogram Inversion Toolbox
    References
    ----------
    D. Griffin and J. Lim. Signal estimation from modified
    short-time Fourier transform. IEEE Trans. Acoust. Speech
    Signal Process., 32(2):236-243, 1984.
    Malcolm Slaney, Daniel Naar and Richard F. Lyon. Auditory
    Model Inversion for Sound Separation. Proc. IEEE-ICASSP,
    Adelaide, 1994, II.77-80.
    Xinglei Zhu, G. Beauregard, L. Wyse. Real-Time Signal
    Estimation from Modified Short-Time Fourier Transform
    Magnitude Spectra. IEEE Transactions on Audio Speech and
    Language Processing, 08/2007.
    """
    x1 = x1 - x1.mean()
    x2 = x2 - x2.mean()
    frame_size = len(x2)
    half = frame_size // 2
    corrs = np.convolve(x1.astype('float32'), x2[::-1].astype('float32'))
    corrs[:half] = -1E30
    corrs[-half:] = -1E30
    offset = corrs.argmax() - len(x1)
    return offset


def invert_halfoverlap(X_strided):
    """
    Invert ``halfoverlap`` function to reconstruct X
    Parameters
    ----------
    X_strided : ndarray, shape=(n_windows, window_size)
        X as overlapped windows
    Returns
    -------
    X : ndarray, shape=(n_samples,)
        Reconstructed version of X
    """
    # Hardcoded 50% overlap! Can generalize later...
    n_rows, n_cols = X_strided.shape
    X = np.zeros((((int(n_rows // 2) + 1) * n_cols),)).astype(X_strided.dtype)
    start_index = 0
    end_index = n_cols
    window_step = n_cols // 2
    for row in range(X_strided.shape[0]):
        X[start_index:end_index] += X_strided[row]
        start_index += window_step
        end_index += window_step
    return X


def overlap_add(X_strided, window_step, wsola=False):
    """
    overlap add to reconstruct X
    Parameters
    ----------
    X_strided : ndarray, shape=(n_windows, window_size)
        X as overlapped windows
    window_step : int
       step size for overlap add
    Returns
    -------
    X : ndarray, shape=(n_samples,)
        Reconstructed version of X
    """
    n_rows, window_size = X_strided.shape

    # Start with largest size (no overlap) then truncate after we finish
    # +2 for one window on each side
    X = np.zeros(((n_rows + 2) * window_size,)).astype(X_strided.dtype)
    start_index = 0

    total_windowing_sum = np.zeros((X.shape[0]))
    win = 0.54 - .46 * np.cos(2 * np.pi * np.arange(window_size) / (
            window_size - 1))
    for i in range(n_rows):
        end_index = start_index + window_size
        if wsola:
            offset_size = window_size - window_step
            offset = xcorr_offset(X[start_index:start_index + offset_size],
                                  X_strided[i, :offset_size])
            ss = start_index - offset
            st = end_index - offset
            if start_index - offset < 0:
                ss = 0
                st = 0 + (end_index - start_index)
            X[ss:st] += X_strided[i]
            total_windowing_sum[ss:st] += win
            start_index = start_index + window_step
        else:
            X[start_index:end_index] += X_strided[i]
            total_windowing_sum[start_index:end_index] += win
            start_index += window_step
    X = X[:end_index]
    return X


def overlap(X, window_size, window_step):
    """
    Create an overlapped version of X
    Parameters
    ----------
    X : ndarray, shape=(n_samples,)
        Input signal to window and overlap
    window_size : int
        Size of windows to take
    window_step : int
        Step size between windows
    Returns
    -------
    X_strided : shape=(n_windows, window_size)
        2D array of overlapped X
    """
    if window_size % 2 != 0:
        raise ValueError("Window size must be even!")
    # Make sure there are an even number of windows before stridetricks
    append = np.zeros((window_size - len(X) % window_size))
    X = np.hstack((X, append))
    overlap_sz = window_size - window_step
    new_shape = X.shape[:-1] + ((X.shape[-1] - overlap_sz) // window_step, window_size)
    new_strides = X.strides[:-1] + (window_step * X.strides[-1],) + X.strides[-1:]
    X_strided = as_strided(X, shape=new_shape, strides=new_strides)
    return X_strided


def halfoverlap(X, window_size):
    """
    Create an overlapped version of X using 50% of window_size as overlap.
    Parameters
    ----------
    X : ndarray, shape=(n_samples,)
        Input signal to window and overlap
    window_size : int
        Size of windows to take
    Returns
    -------
    X_strided : shape=(n_windows, window_size)
        2D array of overlapped X
    """
    if window_size % 2 != 0:
        raise ValueError("Window size must be even!")
    window_step = window_size // 2
    # Make sure there are an even number of windows before stridetricks
    append = np.zeros((window_size - len(X) % window_size))
    X = np.hstack((X, append))
    num_frames = len(X) // window_step - 1
    row_stride = X.itemsize * window_step
    col_stride = X.itemsize
    X_strided = as_strided(X, shape=(num_frames, window_size),
                           strides=(row_stride, col_stride))
    return X_strided


def stft(X, fftsize=128, step="half", mean_normalize=True, real=False,
         compute_onesided=True):
    """
    Compute STFT for 1D real valued input X
    """
    if real:
        local_fft = fftpack.rfft
        cut = -1
    else:
        local_fft = fftpack.fft
        cut = None
    if compute_onesided:
        cut = fftsize // 2 + 1
    if mean_normalize:
        X -= X.mean()
    if step == "half":
        X = halfoverlap(X, fftsize)
    else:
        X = overlap(X, fftsize, step)
    size = fftsize
    win = 0.54 - .46 * np.cos(2 * np.pi * np.arange(size) / (size - 1))
    X = X * win[None]
    X = local_fft(X)[:, :cut]
    return X


def istft(X, fftsize=128, step="half", wsola=False, mean_normalize=True,
          real=False, compute_onesided=True):
    """
    Compute ISTFT for STFT transformed X
    """
    if real:
        local_ifft = fftpack.irfft
        X_pad = np.zeros((X.shape[0], X.shape[1] + 1)) + 0j
        X_pad[:, :-1] = X
        X = X_pad
    else:
        local_ifft = fftpack.ifft
    if compute_onesided:
        X_pad = np.zeros((X.shape[0], 2 * X.shape[1])) + 0j
        X_pad[:, :fftsize // 2 + 1] = X
        X_pad[:, fftsize // 2 + 1:] = 0
        X = X_pad
    X = local_ifft(X).astype("float64")
    if step == "half":
        X = invert_halfoverlap(X)
    else:
        X = overlap_add(X, step, wsola=wsola)
    if mean_normalize:
        X -= np.mean(X)
    return X


if __name__ == '__main__':
    import librosa

    audio, sr = librosa.load("000001.wav", sr=16000)
    # print(audio)
    audio_stft = stft(audio, fftsize=1024, step=200, compute_onesided=False)
    audio_real = np.real(audio_stft)
    wave_output = istft(audio_real, fftsize=1024, step=200, compute_onesided=False)

    librosa.output.write_wav("1.wav", wave_output, sr=16000)

Please help to see what the problem?

**Comment by ZDisket** [comment]
@tts-nlp That looks like an implementation of Algorithm 1. For the 2nd and third, they mention a shift time transform

> In order to obtain the shift time transform, the convolution technique was applied after
> obtaining a DFT matrix or a fourier basis matrix in most implementations. OLA was applied to obtain the inverse transform

**Comment by rgzn-aiyun** [comment]
> @dathudeptrai What do you think of voice cloning

Hey, I've seen a project about voice cloning recently.

**Comment by rgzn-aiyun** [comment]
This looks really interesting:

https://github.com/KuangDD/zhrtvc

**Comment by abylouw** [comment]
Anybody working on VQTTS?

**Comment by qxde01** [comment]
I have tried [fastspeech2  voice cloning](https://github.com/qxde01/CTTS/tree/main/fastspeech2-vc/fastspeech2_vc) base on aishell3 and other data, total 200 speakers,But it didn't work well。Maybe  I couldn't train a good speaker embedding model，then I use a [wenet-wespeaker](https://github.com/wenet-e2e/wespeaker) pretrained Model(chinese) to  extract the speaker embedding vector,But it also works badly。Has anyone tried it?

**In addition, TensorFlowTTS project is not very active, not updated for more than a year.**

**Comment by StuartIanNaylor** [comment]
> I have tried [fastspeech2 voice cloning](https://github.com/qxde01/CTTS/tree/main/fastspeech2-vc/fastspeech2_vc) base on aishell3 and other data, total 200 speakers,But it didn't work well。Maybe I couldn't train a good speaker embedding model，then I use a [wenet-wespeaker](https://github.com/wenet-e2e/wespeaker) pretrained Model(chinese) to extract the speaker embedding vector,But it also works badly。Has anyone tried it?
> 
> **In addition, TensorFlowTTS project is not very active, not updated for more than a year.**

Just been looking at wenet but haven't really made an appraisal but so far seems 'very kaldi' :)
