### ISSUE TITLE
cross sentence prosody discontinourity 

### ISSUE THREAD

**Issue by MMingabc** [TensorSpeech/TensorFlowTTS#471]
Hi, 

I am using FastSpeech v2 and MB-MelGAN for a Chinese TTS task. The training set is the Open Acess Biaobei BZNSYP. 

The result of a single sentence with medium length is pretty satisfying, but there are notable discontinourities cross sentences in a long text. 

I cut a long text into short sentences accroding to punctuations. As for a single sentence, the result is good enough, but the prosodies of prevous and latter sentences do not match. For example, the first sentence is expressed in a formal broadcasting tone, while the latter one is expressed in a casual conversational way.

How do I fix this problem? Or is there any literature I can read about?

Thanks!

**Comment by dathudeptrai** [comment]
@MMingabc you may need to use the overlap technique to fix this problem. For example, ur sentence length is 30s. In the first sentence you can split it from 0 -> 10s, a second sentence from 8s -> 18s, a third sentence from 16s -> 26s ,... So we have 2s overlaps. Everything you need to do is merge those sentence (do not forget to remove an overlaps segment :D)

**Comment by lr2582858** [comment]
@MMingabc The existing models all have the problem of pronunciation errors due to the long input sentences. I think this is due to the input length mismatch between inferencing and training. But Fastspeech2 is still the best I test. In addition to the split sentence you said, I think of two ways:
1. Adding long sentences data in the training set. 
2. The global attention of fastspeed2 for a sentence is converted to the local attention across several adjacent words or punctuations. A sliding window with a certain overlap can be used in model inferencing.

**Comment by MMingabc** [comment]
@dathudeptrai @lr2582858 Thank you both so much for your valuable advices. I tried the overlap strategy, and it eased this problem to a great extent. I found that a 10-phoneme-length overlap helps improve the consistency of long text. But because overlapping increases the length of a sentence I noticed that the performance on longer sentences degraded. So the ultimate sulotion as @lr2582858 had said would be adding long sentences to the dataset. I haven't tried constraining attention to adjacent words. What effects will this cause? Any experimental results? Thank you!

**Comment by lr2582858** [comment]
@MMingabc You can refer this [paper](https://arxiv.org/abs/1910.10288). It is purely location-based attention mechanism and allowing it to generalize to very long utterances as well. 
The method of splitting sentences has a certain risk of deteriorating the effect: If you don't have a good sentence splitting strategy, the split sentence is likely not in line with human speaking habits (For example, "There’s a way to measure the acute emotional intelligence that has never gone out of style." -> "There’s a way to measure the" + "the acute emotional intelligence that" + "that has never gone out of style."). This means that the input features will dismatch with the training data‘ feature space, which may cause an exception at the junction of the synthesized speech.
