### ISSUE TITLE
Does the batch size need to be divisible by the number of training data?

### ISSUE THREAD

**Issue by ZhaoZeqing** [TensorSpeech/TensorFlowTTS#473]
Hi~ I used the latest code with TF2.3.1, when I wanted to extract duration from a Tacotron2 model, it seems that the batch size need to be divisible by the number of training/valid data, otherwise, the total number of durations is less than other feats.
This error also occurred when using multi-gpu to train Tacotron2 model sometimes, a little puzzled about this :(

**Comment by dathudeptrai** [comment]
@ZhaoZeqing  i think I fixed it a long time ago (https://github.com/TensorSpeech/TensorFlowTTS/issues/407).

**Comment by ZhaoZeqing** [comment]
@dathudeptrai Many thanks! It worked! :)
