### ISSUE TITLE
Are there any techniques to improve pronunciation of short one-word texts?

### ISSUE THREAD

**Issue by OscarVanL** [TensorSpeech/TensorFlowTTS#474]
Hi,

I am using FastSpeech2 with MB-MelGAN. When passing a short input text, like "Yes" into the model, this sounds very robotic and noisy/buzzy.

Someone explained to me in the past that these models prefer sentences to short input texts.

I have two questions:

1. Why do these models perform worse for short texts than longer ones?
2. Is there anything I can do to improve the model's quality for short text?

Thanks! :)

**Comment by dathudeptrai** [comment]
@OscarVanL try seq2seq model such as Tacotron2, if tacotron2 can generate good sound for short one-word texts, let use its generates audio as soft-ground-truth for FastSpeech2 training :))), you can generate as many as you want :D .

**Comment by OscarVanL** [comment]
I see, so if FS2 is trained with short one-word utterances then it will generate better ones too?

**Comment by dathudeptrai** [comment]
> I see, so if FS2 is trained with short one-word utterances then it will generate better ones too?

Sure :))

**Comment by OscarVanL** [comment]
Thanks!
