### ISSUE TITLE
training custom fastspeech2 model

### ISSUE THREAD

**Issue by PedroDKE** [TensorSpeech/TensorFlowTTS#478]
Hi all! Let me start by saying thank you for this amazing github repo.

As the title says I want to train a custom fastspeech2 model.
My problem is that I already get stuck at the first step / preprocessing (https://github.com/tensorspeech/TensorFlowTTS/tree/master/examples/fastspeech2)

My data consists out of simple audio,sentence pairs and i'm unsure on how to do all the steps such that i can get the format necessary to train fastspeech2.

i get that i need to extract the charactor_ids, duration, f0, energy and mel-spectograms but how do iIuse the Dataloader mentioned in the readme in the link? 

am i missing a step here? and what should i do? is there maybe another example/documentation on how to do this?

thank you!

**Comment by dathudeptrai** [comment]
@PedroDKE what is ur bug now ?

**Comment by PedroDKE** [comment]
Well, it isnt really a bug, i'm just lost on which preprocessing steps and toold i have to take/use to train a FastSpeech2 model on a custom dataset. I saw that there is support for some datasets but i just get lost on how to do it for a custom dataset (audio,transcript pairs)

**Comment by dathudeptrai** [comment]
> i'm just lost on which preprocessing steps and toold i have to take/use to train a FastSpeech2 model on a custom dataset. I saw that there is support for some datasets but i just get lost on how to do it for a custom dataset

you need extract duration first :D. You can use tacotron2 or MFA.

**Comment by PedroDKE** [comment]
okay, thank you! But i assume that i also need f0 and energy, how would i extract those?

**Comment by dathudeptrai** [comment]
you should ran tensorflow-tts-preprocess, the code to extract f0/energy here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/bin/preprocess.py#L266-L285)

**Comment by PedroDKE** [comment]
okay, but the readme says that only ljspeech, kss, baker, libritts and thorsten are supported datasets arguments? Should i take one of the .yaml files and adapt it to fit my dataset or would this not work?

also i tried to look for the file that does the normalization (tensorflow-tts-normalize) but i can't seem to find it, is it the same file as the preprocessing one?

**Comment by dathudeptrai** [comment]
for the preprocessing code you can see here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/setup.py#L56-L62) to know :D

**Comment by PedroDKE** [comment]
okay i will look into it, thank you! :D

**Comment by vinamramunot-tech** [comment]
@PedroDKE were you able to figure out to synthesize someone else's voice?

**Comment by PedroDKE** [comment]
@vinamramunot-tech  i'm not trying to synthesis someones else's voice, just trying to train a model on a dataset i scraped myself, but for now i'm trying to use the thorsten dataset loader for mine

@dathudeptrai  (sorry for the tag) i tried to preprocess some files using the thorsten configuration, this worked fine for most but at some point i get the following value error that can be seen bellow, any idea why i get this error? (i looked into it and all my files should be atleast 1s long and have a sr of 22050)

```
tensorflow-tts-preprocess --rootdir ./set_train --outdir ./dump_train --config preprocess/thorsten_preprocess.yaml --dataset thorsten --test_size 0.000000000001
2021-01-30 20:13:16.243799: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda/extras/CUPTI/lib64
2021-01-30 20:13:16.243820: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-01-30 20:13:24,703 (preprocess:373) INFO: Selected 'thorsten' processor.
2021-01-30 20:13:24,771 (preprocess:412) INFO: Training items: 15835
2021-01-30 20:13:24,771 (preprocess:413) INFO: Validation items: 1
[Preprocessing train]:   3%|██▋                                                                                 | 500/15835 [00:52<30:53,  8.28it/s]2021-01-30 20:14:18,230 (preprocess:291) WARNING: 23-00026-f000026 causes clipping. It is better to reconsider global gain scale value.
[Preprocessing train]:   4%|███                                                                                 | 573/15835 [01:02<38:22,  6.63it/s]2021-01-30 20:14:27,025 (preprocess:291) WARNING: 23-00028-f000025 causes clipping. It is better to reconsider global gain scale value.
[Preprocessing train]:  46%|█████████████████████████████████████▉                                             | 7227/15835 [13:33<11:15, 12.74it/s]2021-01-30 20:26:58,677 (preprocess:291) WARNING: 23-00019-f000150 causes clipping. It is better to reconsider global gain scale value.
[Preprocessing train]:  60%|██████████████████████████████████████████████████▏                                | 9579/15835 [17:49<06:09, 16.91it/s]2021-01-30 20:31:14,168 (preprocess:291) WARNING: 10-00002-f000084 causes clipping. It is better to reconsider global gain scale value.
[Preprocessing train]:  71%|██████████████████████████████████████████████████████████▌                       | 11307/15835 [20:55<09:33,  7.89it/s]2021-01-30 20:34:19,925 (preprocess:291) WARNING: 23-00019-f000139 causes clipping. It is better to reconsider global gain scale value.
[Preprocessing train]:  84%|████████████████████████████████████████████████████████████████████▋             | 13262/15835 [24:17<06:02,  7.10it/s]2021-01-30 20:37:43,317 (preprocess:291) WARNING: 23-00003-f000094 causes clipping. It is better to reconsider global gain scale value.
[Preprocessing train]:  88%|███████████████████████████████████████████████████████████████████████▊          | 13858/15835 [25:18<00:46, 42.35it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/thesis/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/anaconda3/envs/thesis/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/user/anaconda3/envs/thesis/lib/python3.8/site-packages/tensorflow_tts/bin/preprocess.py", line 193, in gen_audio_features
    assert np.abs(audio).max() <= 1.0, f"{utt_id} is different from 16 bit PCM."
  File "/home/user/anaconda3/envs/thesis/lib/python3.8/site-packages/numpy/core/_methods.py", line 30, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/thesis/bin/tensorflow-tts-preprocess", line 8, in <module>
    sys.exit(preprocess())
  File "/home/user/anaconda3/envs/thesis/lib/python3.8/site-packages/tensorflow_tts/bin/preprocess.py", line 446, in preprocess
    for result, mel, energy, f0, features in train_map:
  File "/home/user/anaconda3/envs/thesis/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/user/anaconda3/envs/thesis/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
ValueError: zero-size array to reduction operation maximum which has no identity
[Preprocessing train]:  88%|███████████████████████████████████████████████████████████████████████▊          | 13869/15835 [25:20<03:35,  9.12it/s]
```

**Comment by pranavpawar3** [comment]
@PedroDKE Hi, were you able to complete the custom training? If so, please share inputs on the preprocessing of a custom dataset. I have scraped the LivingAudioDataset - https://github.com/Idlak/Living-Audio-Dataset/tree/master/en, and trying to train fastspeech2 on the same.
