### ISSUE TITLE
getting error while training data

### ISSUE THREAD

**Issue by rustam** [TensorSpeech/TensorFlowTTS#480]
getting following error while training data by using tacotron2

_Traceback (most recent call last):
  File "examples/tacotron2/train_tacotron2.py", line 513, in <module>
    main()
  File "examples/tacotron2/train_tacotron2.py", line 505, in main
    resume=args.resume,
  File "/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 999, in fit
    self.run()
  File "/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 103, in run
    self._train_epoch()
  File "/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 129, in _train_epoch
    self._check_eval_interval()
  File "/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 166, in _check_eval_interval
    self._eval_epoch()
  File "/lib/python3.7/site-packages/tensorflow_tts/trainers/base_trainer.py", line 897, in _eval_epoch
    f"(Steps: {self.steps}) Finished evaluation "
 UnboundLocalError: local variable 'eval_steps_per_epoch' referenced before assignment_

**Comment by dathudeptrai** [comment]
@rustam can you pull the newest code ?. BTW, you can check by urself this line of code (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/trainers/base_trainer.py#L903) to see what is the problem, i do not see any bug here. @ZhaoZeqing did you get this problem ?

**Comment by rustam** [comment]
I checked the code , following part of the code in bold , shouldn't be included by for loop?


`    def _eval_epoch(self):
        """Evaluate model one epoch."""
        logging.info(f"(Steps: {self.steps}) Start evaluation.")

        # calculate loss for each batch
        for eval_steps_per_epoch, batch in enumerate(
            tqdm(self.eval_data_loader, desc="[eval]"), 1
        ):
            # eval one step
            self.one_step_evaluate(batch)

            **if eval_steps_per_epoch <= self.config["num_save_intermediate_results"]:
                # save intermedia
                self.generate_and_save_intermediate_result(batch)**

        **logging.info(
            f"(Steps: {self.steps}) Finished evaluation "
            f"({eval_steps_per_epoch} steps per epoch)."**
        )`

**Comment by rustam** [comment]
checked the code before submit issue . 
shouldn't the following part be included to for loop? 

`            if eval_steps_per_epoch <= self.config["num_save_intermediate_results"]:
                # save intermedia
                self.generate_and_save_intermediate_result(batch)

        logging.info(
            f"(Steps: {self.steps}) Finished evaluation "
            f"({eval_steps_per_epoch} steps per epoch)."`

**Comment by dathudeptrai** [comment]
I think a code is correct and that code did not change a long time ago so everything should fine ?. Can you try to debug ?

**Comment by rustam** [comment]
i tried, got error until i have change the script as i described above. 

change following part :
```
        for eval_steps_per_epoch, batch in enumerate(
            tqdm(self.eval_data_loader, desc="[eval]"), 1
        ):
            # eval one step
            self.one_step_evaluate(batch)

            if eval_steps_per_epoch <= self.config["num_save_intermediate_results"]:
                # save intermedia
                self.generate_and_save_intermediate_result(batch)

        logging.info(
            f"(Steps: {self.steps}) Finished evaluation "
            f"({eval_steps_per_epoch} steps per epoch)."
        )
```
to :

```
        for eval_steps_per_epoch, batch in enumerate(
            tqdm(self.eval_data_loader, desc="[eval]"), 1
        ):
            # eval one step
            self.one_step_evaluate(batch)
            if eval_steps_per_epoch <= self.config["num_save_intermediate_results"]:
                # save intermedia
                self.generate_and_save_intermediate_result(batch)

            logging.info(
                f"(Steps: {self.steps}) Finished evaluation "
                f"({eval_steps_per_epoch} steps per epoch)."
            )
```

**Comment by dathudeptrai** [comment]
@rustam hmm, i think you should keep an old code and remove this line of code:

```
f"({eval_steps_per_epoch} steps per epoch)."
```

**Comment by rustam** [comment]
@dathudeptrai  thank you as you suggested remove above line is enough. rerun the training comment out the suggested line without error .

**Comment by ZhaoZeqing** [comment]
@dathudeptrai I have not got this error in the newst code:)

**Comment by rustam** [comment]
@ZhaoZeqing have you waited till the steps done which configured for eval_interval_steps, in example the value is 500. in my case just after finished 500th step , the error come out.

**Comment by ZhaoZeqing** [comment]
> @ZhaoZeqing have you waited till the steps done which configured for eval_interval_steps, in example the value is 500. in my case just after finished 500th step , the error come out.

@rustam Yes, I have trained after the eval_interval_steps, it was ok :)

**Comment by edwin-19** [comment]
I encountered this issue before just wanted to say something even though this issue is closed, but you should check your batch size for the validation dataloader.

This happens because your total amount of data is less than your batch size.

Hope this helps to clarify

**Comment by Sean-NS** [comment]
reply in 2023.

That variable is just for counting, but the scope of that variable is just limited in for statement.
But from the logic, that variable is needed after the for statement.

So I assigned that just before the for statement

```
       # pre-assignment
       eval_steps_per_epoch = 0

       for eval_steps_per_epoch, batch in enumerate(
            tqdm(self.eval_data_loader, desc="[eval]"), 1
        ):
            # eval one step
            self.one_step_evaluate(batch)

            if eval_steps_per_epoch <= self.config["num_save_intermediate_results"]:
                # save intermedia
                self.generate_and_save_intermediate_result(batch)

        logging.info(
            f"(Steps: {self.steps}) Finished evaluation "
            f"({eval_steps_per_epoch} steps per epoch)."
        )

```
For me, this try worked like a charm.
