### ISSUE TITLE
No speech in audio file

### ISSUE THREAD

**Issue by JohnWalker-dev** [TensorSpeech/TensorFlowTTS#481]
First of all I am really thankful for this repository. I guess my spectogram is quite okay, since it is very similar to the actual spectogram of audio. For vocoder I am using a multiband wavegan universal vocoder. 
But I am getting a void (no sound) audio of only 1 second for every sentence. I would like to know, where I am doing wrong. Any help will be appreciated.

**Comment by JohnWalker-dev** [comment]
![image](https://user-images.githubusercontent.com/78144006/106119889-8678d380-6177-11eb-8fc4-61604eb30c21.png)
Here is the screen shot of my spectogram. And here is the array returned by fastspeech2 inference (masked_mel_after value). 

<tf.Tensor: shape=(1, 15, 80), dtype=float32, numpy=
array([[[-6.1786294 , -6.0646076 , -6.1002197 , ..., -6.6326623 ,
         -6.6525187 , -6.690618  ],
        [-6.158462  , -6.0820107 , -6.1079926 , ..., -6.6315594 ,
         -6.6585283 , -6.6750116 ],
        [-1.0029715 , -1.2349578 , -1.275165  , ..., -0.98656493,
         -0.96316147, -0.9930181 ],
        ...,
        [-6.04207   , -5.9514933 , -5.8613653 , ..., -6.5080605 ,
         -6.5390887 , -6.5960116 ],
        [-6.174239  , -6.0726    , -6.026902  , ..., -6.70455   ,
         -6.727611  , -6.7578816 ],
        [-6.225495  , -6.124037  , -6.1218934 , ..., -6.694069  ,
         -6.740127  , -6.7748923 ]]], dtype=float32)>

And here are my duration_outputs:
<tf.Tensor: shape=(1, 194), dtype=int32, numpy=
array([[0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>



Here is my audio after using melgan :
<tf.Tensor: shape=(3840,), dtype=float32, numpy=
array([ 0.6335543 , -0.15024835,  0.49361414, ..., -0.7396296 ,
        0.05870018, -0.3182526 ], dtype=float32)>

But when I import it using 
sf.write('./audio_after.wav', audio_after, 22050, "PCM_16")
It gives an empty sound file of only 0.8 second

**Comment by JohnWalker-dev** [comment]
@dathudeptrai @erogol @candlewill @cclauss @mapledxf Any bit of insight from you guys will be a never-ending favor for me.

**Comment by dathudeptrai** [comment]
@JohnWalker-dev do not tag everyone :))). you just need create issue :))).
