### ISSUE TITLE
Fine tuning questions

### ISSUE THREAD

**Issue by JohnWalker-dev** [TensorSpeech/TensorFlowTTS#482]
Thankyou so much for an amazing repository.

I would really appreciate response from any one for the questions below:
1) During fine tuning our fastspeech2 model, what is the criteria to stop. If we are fine tuning a data set on LJ speech weights. What would be the iterations to tune it with a data of ~30 minutes?
2) I am using a universal decoder. But the problem is that model is able to give a good audio for the words available in my (30 minutes data set). But on unseen words, its performance is not much good. 
3) The last words of the sentence are missed in some audios. What could be the reason for that ?

**Comment by ZDisket** [comment]
@JohnWalker-dev 
1. Based on my experience I'd stop training at about 20-30k when finetuning on LJSpeech data.
2. Then that's a problem with your text2mel, not the vocoder
3. Again, bad performance on your FS2.

**Comment by JohnWalker-dev** [comment]
I need to know how our melgan vocoder can support long audios formation? My FS2 is giving a correct spectogram but the vocoder is not been able to convert last characters.
