### ISSUE TITLE
possible to see fastspeech2 metrics in TensorBoard ?

### ISSUE THREAD

**Issue by PedroDKE** [TensorSpeech/TensorFlowTTS#488]
Is there a way so see the training metrics/losses of fastspeech2 in TensorBoard?

**Comment by dathudeptrai** [comment]
@PedroDKE just need:

`tensorboard --logdir PATH`.

**Comment by PedroDKE** [comment]
does the basetrainer also save the file needed for tensorboard when the model gets saved after a keyboard interupt or only after the completion of the full training steps?

**Comment by dathudeptrai** [comment]
> @dathudeptrai does the basetrainer also save the file needed for tensorboard when the model gets saved after a keyboard interupt or only after the completion of the full training steps?
> 
> I'm using tensorboard 2.4.1, stopped my training after 10k steps with a keyboard interupt but tensorboard can not seem to find my log files (the path i give in is the same ad my outdir argument)

the tensorboard file saved in `outdir` for sure.

**Comment by PedroDKE** [comment]
yes, found it. It seemed that it didn't safe correctly on my first try. But it did in my second. Thank you!
