### ISSUE TITLE
Duration alignments

### ISSUE THREAD

**Issue by CaoNguyen-audio** [TensorSpeech/TensorFlowTTS#489]
Xin chào. What an amazing repository. I am working on an open source project, where I am using this project. I am using a pre-trained LJspeech model. But I want to know how can I get duration of each word in the audio. I see that in text2mel_model.inference function, you guys are returning a duration too. But I am confused what this duration is representing ? Can you please be kind enough to guide me on how can I get duration of each word spoken in the audio

**Comment by CaoNguyen-audio** [comment]
Any insights @ZDisket @dathudeptrai. Your two words answer will be a valuable source of information for me.

**Comment by ZDisket** [comment]
@CaoNguyen-audio The durations returned are for every character or phoneme, depending on what you're using as input. Let's assume char, so if you input "hello bye" and the durations look like [20, 10, 15, 30, 25, 10, 30, 25]. So, to get per word durations you'd have to figure out based on your input which parts belong to certain words, then split and sum them up. 
In our example input the first 5 durations belong to the word "hello" and the last 3 to "bye", so [20, 10, 15, 30, 25] and [10, 30, 25] respectively. So the duration of the word hello is 100 and bye is 65.

**Comment by CaoNguyen-audio** [comment]
Thank you so much.
