### ISSUE TITLE
Why there are two speaker embeddings in tacotron

### ISSUE THREAD

**Issue by zhouyong64** [TensorSpeech/TensorFlowTTS#490]
One speaker embedding in TFTacotronEmbeddings. Another one in the Encoder. Why need two?

**Comment by dathudeptrai** [comment]
@zhouyong64 can you point out the code ?

**Comment by zhouyong64** [comment]
In TFTacotronEncoder.call(), the inputs go through TFTacotronEmbeddings, which contains a speaker embedding. Then in the same call(), the output of biLISM is combined with another speaker embedding (Line 262).

**Comment by dathudeptrai** [comment]
@zhouyong64 `TFTacotronEmbeddings` include `charactor_embedding` and `speaker_embedding`. We also use `speaker_embeddings` for `attention` and `decoder` module by adding it into outout of `biLSTM`.
