### ISSUE TITLE
padding value for speaker_id

### ISSUE THREAD

**Issue by zhouyong64** [TensorSpeech/TensorFlowTTS#491]
In tacotron2 code, the padding value for speaker_id is 0. Could this be wrong, since 0 is the first valid speaker id? As I understand it, input_mask is used to ignore padded values. However, there are two speaker emdeddings in current implementation, one in TFTacotronEmbeddings and another in Encoder. Input_mask only work on the first speaker embedding, because the second speaker embedding comes after the use of input_mask. Anything I miss here, please point them out.

**Comment by dathudeptrai** [comment]
@zhouyong64 a shape of `speaker_id` is `batch_size`, padding value won't affect anything here, we do not use padding speaker id :D.

**Comment by zhouyong64** [comment]
Thanks for explaining.

**Comment by zhouyong64** [comment]
Thanks for explaining.
