### ISSUE TITLE
Inference for Tactron2 using other language 

### ISSUE THREAD

**Issue by Amels404** [TensorSpeech/TensorFlowTTS#499]
Hello! 
I have trained the tactotron2 model on an Arabic language. The problem is that I have an error when decoding for inference. 

Versions: 
TensorflowTTS=0.11 
TensoflowGPU= 2.3.0/2.4.0
TensorflowAddons=0.12.0
Error: 
Trying to access element 77 in a list with 77 elements.

Thank you for you help! 

![inferencetactron2](https://user-images.githubusercontent.com/71659848/108057050-60e23a00-7052-11eb-8422-8cce75da06c2.png)

**Comment by ahmedalbahnasawy** [comment]
@Amels404 could you provide more details ? Are you able to generate spectrogram without using decode_tacotron2.py ? like using this colab 
https://github.com/TensorSpeech/TensorFlowTTS/blob/master/notebooks/tacotron2_inference.ipynb

**Comment by Amels404** [comment]
Thank you very much for getting back. 

Actually, No, I can't generate the spectrogram,  I tried it out, but I got an error to save the PB:
'tf.saved_model.save(tacotron2, "./test_saved", signatures=tacotron2.inference)'  
I was unable to save the model, you can find the error in the screenshot below. 

For more details, I have converted my dataset to the data format needed for the train, I changed the  AutoProcessor to accept the Arabic language, I also changed the train_tactron2 and the tacotron_dataset files to meet the needs for the Arabic dataset. 

I have, also,  try=ied to do the inference using tacotron2 and MultiBand MelGan for the generator as indicated in this notebook: https://colab.research.google.com/drive/1ybWwOS5tipgPFttNulp77P6DAB5MtiuN?usp=sharing
but I did not get a good response. 

As for the first error, it happens when I try the decode_tacotron2.py file. 

Thnak you! 

![error screenshot](https://user-images.githubusercontent.com/71659848/108187243-8d5b8c00-710e-11eb-9212-ec80e327429a.PNG)

**Comment by ahmedalbahnasawy** [comment]
@Amels404 I see. Well, Before you save the model you need to fit random input to the model (TF2 related). then load_weights and save it.

**Comment by Amels404** [comment]
Yes, I see, thank you for your time!
