### ISSUE TITLE
 Are there any plans to add other vocoders？

### ISSUE THREAD

**Issue by PeijiYang** [TensorSpeech/TensorFlowTTS#503]
Do you have any plans to add other vocoders, like lpcnet, wavernn etc.

**Comment by dathudeptrai** [comment]
if you know another interesting vocoder, let me know :D.

**Comment by manmay-nakhashi** [comment]
https://arxiv.org/pdf/2011.12985.pdf

**Comment by dathudeptrai** [comment]
> https://arxiv.org/pdf/2011.12985.pdf

it's really hard to implement this model :D.
