### ISSUE TITLE
HifiGAN resblocks are applied sequentially.

### ISSUE THREAD

**Issue by hccho2** [TensorSpeech/TensorFlowTTS#504]
https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/models/hifigan.py#L162

```
  for j in range(config.stacks):
      layers += [
          TFHifiResBlock(
              kernel_size=config.stack_kernel_size[j],
              filters=config.filters // (2 ** (i + 1)),
              dilation_rate=config.stack_dilation_rate[j],
              use_bias=config.use_bias,
              nonlinear_activation=config.nonlinear_activation,
              nonlinear_activation_params=config.nonlinear_activation_params,
              is_weight_norm=config.is_weight_norm,
              initializer_seed=config.initializer_seed,
              name="hifigan_resblock_._{}._._{}".format(i, j),
          )
      ]
```

![image](https://user-images.githubusercontent.com/26861167/109168022-c3110c80-77c1-11eb-9987-dc8dd337f1b2.png)

HifiGAN resblocks should be applied in parallel.

**Comment by dathudeptrai** [comment]
@hccho2 i need to read paper again to check this :D.

**Comment by dathudeptrai** [comment]
@hccho2 here is an original implementation (https://github.com/jik876/hifi-gan/blob/master/models.py#L106-L110). Still sequential ?. Anyway, I agree that apply parallel resblock should improve latency much :D.

**Comment by machineko** [comment]
XLA should "possibly" make it parallel after compilation let's check that first

**Comment by hccho2** [comment]
@dathudeptrai 
The issue I'm talking about isn't the efficient side of the computation.


origin implementation:
```
xs=None
for j in range(config.stacks):
    if xs is None:
        xs = resblocks[j](x)
    else:
        xs += resblocks[j](x)
```

this repo:
```
for j in range(config.stacks):
        x = resblocks[j](x)
```

**Comment by dathudeptrai** [comment]
@hccho2 I know it, but I think it does not affect a result much. I will fix an implementation in the next release. I will also check if the model inference faster or not :D .

**Comment by hccho2** [comment]
@dathudeptrai 
Ok. thanks.

**Comment by machineko** [comment]
@dathudeptrai 
If u want to debug if code will be properly dispatched on gpu -> [tf-profiler](https://www.tensorflow.org/guide/profiler) its handy tool :)
