### ISSUE TITLE
In C++ , how to inference  duration_outputs?

### ISSUE THREAD

**Issue by zhangsanfeng86** [TensorSpeech/TensorFlowTTS#505]
Hello  @ZDisket， 

In Python, it can inference  duration_outputs,as follow:
![image](https://user-images.githubusercontent.com/73547638/109170238-8f32e880-77bb-11eb-8151-6b0a511f101d.png)

how to inference  duration_outputs in C++？

**Comment by ZDisket** [comment]
I haven't figured out a way yet. Technically the exported model has multiple outputs that could be extracted with C++, but trying to get something other than the first one results in a bunch of bizarre errors.
My guess is that you'll have to mess with how the model is exported.

**Comment by zhangsanfeng86** [comment]
Thank you  for your reply :)
