### ISSUE TITLE
Missing Duration files 

### ISSUE THREAD

**Issue by holianh** [TensorSpeech/TensorFlowTTS#509]
Hi every one,
I try to train fastspeech2 on ljspeech as example folder.
I faced the problems: missing duration files, the steps i did:
1. download ljspeech dataset from [here](https://keithito.com/LJ-Speech-Dataset/) to local
2. install tensorFlowTTS:
```bash
$ git clone https://github.com/TensorSpeech/TensorFlowTTS.git
$ cd TensorFlowTTS
$ pip install .
```
3. Run processing:
```bash
tensorflow-tts-preprocess --rootdir ./ljspeech --outdir ./data_dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech

tensorflow-tts-normalize --rootdir ./dump_ljspeech --outdir ./data_dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
```
4. follow example of training fastspeech2 instructions:
in this step, I faced the problem: how to create duration files? I see the similar procedure in [tacotron2](https://github.com/dathudeptrai/TensorflowTTS/tree/master/examples/tacotron2#step-4-extract-duration-from-alignments-for-fastspeech), but tacotron2 and fastspeech2 are difference (in structure, checkpoint step,...). So, what should I do to get accurate duration for fastspeech2 to train the ljspeech and to train a new language from scratch?

Because, without duration files, [Step 2: Training from scratch](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2#step-2-training-from-scratch) of Fastspeech cannot run.
My last question is: how do I do to train a new language without errors?
Thank you in advance!

**Comment by ZDisket** [comment]
You either train Tacotron2 on your dataset then use that to extract durations or use a forced aligner like MFA. There's an example for doing this with LibriTTS here: https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2_libritts, although I can't help with it that much because I use different scripts in my fork.
