### ISSUE TITLE
pretrain model of melgan

### ISSUE THREAD

**Issue by gaoyu1983** [TensorSpeech/TensorflowTTS#51]
Hi, I tried to use run melgan on your pretrained model, but I found there is no ckpt data, only discriminator and generator's h5 files.
I read the train_melgan.py, found it needs --resume parameter, but I think it needs ckpt file to get steps and epochs. 
Could you upload the ckpt files along with the pre-trained model or is there other way to do it ?

Thank you for your awesome repo. It is really well constructed and I can't wait to see its performance.

**Comment by dathudeptrai** [comment]
@gaoyu1983 hi, sorry for this confusion :(. --resume is "Resume" the model and continue to training. While the h5 file is the weight is used as "Pretrained" weight to fine-tune for other datasets, in this case we don't need ckpt file. I think i will add --pretrained flag to solve this confution.
