### ISSUE TITLE
where define the tensor name

### ISSUE THREAD

**Issue by zhangsanfeng86** [TensorSpeech/TensorFlowTTS#514]
Hello @ZDisket，

where define the tensor name in FastSpeech2.cpp
such as:  "serving_default_input_ids"  ,   "serving_default_energy_ratios" ,"StatefulPartitionedCall"

![image](https://user-images.githubusercontent.com/73547638/110412483-40dcee00-80c7-11eb-8ba2-3b20ea6ac092.png)

**Comment by OnceJune** [comment]
you can print the op name in python first
