### ISSUE TITLE
Processor API

### ISSUE THREAD

**Issue by ariG23498** [TensorSpeech/TensorFlowTTS#515]
I am creating a libritts processor like this:
```python
processor = AutoProcessor.from_pretrained(
    pretrained_path="/content/TensorFlowTTS/tensorflow_tts/processor/pretrained/libritts_mapper.json"
)
```

After I have the processor I am using the `text_to_sequence` function to transform a `str` into a list of `ids`. I have been getting key errors for quite some time now. Did not find a good documentation to help resolve my problem. At a later stage found another method `inference_text_to_seq`. I would love for the maintainers to guide me to better documentation of the classes and methods. 😄

**Comment by machineko** [comment]
Give me ur discord/gitter info so I can ping u later and answer ur questions 👍🏻

**Comment by ariG23498** [comment]
Discord: Aritra#8047
Thanks for the reply 😄

**Comment by shachar-ug** [comment]
@ariG23498 how did you end up resolving it?
