### ISSUE TITLE
Zoneout in Tacotron2

### ISSUE THREAD

**Issue by ZhaoZeqing** [TensorSpeech/TensorFlowTTS#517]
Hi~~

I added zoneout in Tacotron2 like this:
```Python
def _zoneout(self, states, new_states, rate, training):
        if training:
            return states + (1 - rate) * tf.nn.dropout((new_states - states), rate)
        else:
            return rate * states + (1 - rate) * new_states
            # return new_states
```
It's ok when return **rate * states + (1 - rate) * new_states** at inference time, when I only return **new_states** at inference time, voice quality is better than the former but speak more faster. A little question about this.

**Comment by OnceJune** [comment]
so is that used to tune speak speed? where to add the code?

**Comment by dathudeptrai** [comment]
> A little question about this.

zoneout makes a generated speech faster is an existential issue for a long time and i do not know how to fix :D.

**Comment by ZhaoZeqing** [comment]
> so is that used to tune speak speed by adding `rate`

@OnceJune I tried to make **rate** equal to  1, 0.05, 0.1, the speech speed changed from fast to normal.

**Comment by ZhaoZeqing** [comment]
> > A little question about this.
> 
> zoneout makes a generated speech faster is an existential issue for a long time and i do not know how to fix :D.

Oh! So it's an existential problem. Thanks!
