### ISSUE TITLE
Questions on FastSpeech2 implementation

### ISSUE THREAD

**Issue by Mercurise** [TensorSpeech/TensorFlowTTS#519]
Hi,

Thanks for your great works. Just some general questions regarding the fast-speech2 implementation. 

1. In the codes, the model outputs **mel_before**, and **mel_after**. Could you let me know why we need two outputs here? Is it better to only have one Mel-spectrogram instead of two, especially for TFLite's version as it's simpler running on the edge? 

2. Another question on the notebook that conducts TTS with **Fastspeech2** and **MelGAN**. Is there any preference using MelGAN instead of Parallel Wave GAN as the original fast-speech2 paper?

3. Is it possible to provide some baseline losses/performance on FastSpeech2, MelGAN, or other TTS models for reference?

Thanks

**Comment by luan78zaoha** [comment]
Show some losses results.
- Tacotron2
![tacotron](https://user-images.githubusercontent.com/32391999/111260197-5cae3a00-865b-11eb-9ff8-e701bff32219.png)
- Fastspeech2
![fsp2](https://user-images.githubusercontent.com/32391999/111260206-6041c100-865b-11eb-9f1e-67ed787f465d.png)
- MB-MelGan
![melgan](https://user-images.githubusercontent.com/32391999/111260211-6172ee00-865b-11eb-86d5-4220d2e1f7de.png)

**Comment by Mercurise** [comment]
thanks that's quite helpful, will close the issue now.
