### ISSUE TITLE
Request: Streaming output

### ISSUE THREAD

**Issue by StuartIanNaylor** [TensorSpeech/TensorFlowTTS#522]
Does it have or is it possible to have a streaming output to reduce sentence latency.

The examples I have seen save complete sentence to file.

I was wondering if a 2 stage buffer could be used where an output pool buffer feeds a callback buffer that is similar to say [pyaudio](http://people.csail.mit.edu/hubert/pyaudio/docs/#example-callback-mode-audio-i-o)  or [sounddevice](https://python-sounddevice.readthedocs.io/en/0.4.1/usage.html#callback-streams)  callbacks, where chunks are delivered to create a stream?

**Comment by StuartIanNaylor** [comment]
I got the fastspeech2/melgan-tfl running Pi400 2.0Ghz.

run time 8.952440023422241 wave duration 11.133968 x1.24
run time 7.136162042617798 wave duration 8.870023 x1.24

Of the 2 example text inputs using audio_after

I had a problem on run with scikitlearn `It seems that scikit-learn has not been built correctly.` but `export LD_PRELOAD=libgomp.so.1 python3` fixes that.

Streaming that output would be such a great feature.
Is it because its a 2 stage pass of faststream then melgan and even if 'chunked' the process swap would still cause delay?

**Comment by maozhiqiang** [comment]
how to convert melgan to streaming outputs!

**Comment by dathudeptrai** [comment]
@manmay-nakhashi

**Comment by manmay-nakhashi** [comment]
@maozhiqiang @StuartIanNaylor 
1. generate mel(fastspech2) till first delimiter.
2. send it to melgan(take a chunk size of 32 or 64) and send it to audio player 
3. to make it more faster on edge device you can train your models for 40 mel.(it gives decent output).
4. my model size for fastspeech2 is ~7 mb and melgan is ~1 mb with 40 mel.

**Comment by StuartIanNaylor** [comment]
Also I have no idea guys but when I was looking I noticed librosa.
I have been playing with https://github.com/google-research/google-research/tree/master/kws_streaming of late and found the tf.signal math libs to be faster than librosa.

Is there any reason why librosa or is it just historical?

**Comment by manmay-nakhashi** [comment]
@dathudeptrai i have this older script can you modify it according to current version and push it for example ?.
```
import numpy as np
import tensorflow as tf
from tensorflow_tts.processor import LJSpeechProcessor
from tensorflow_tts.processor.ljspeech import symbols, _symbol_to_id

import asyncio
import scipy.io.wavfile
import time
import sys
import math
import pyaudio
punctuations = ['.', '?', '!']
# from multiprocessing import Pool
from multiprocessing.dummy import Pool
split_punctuations = [',', '.', '-', '?', '!', ':', ';']

#fastspeech Get input and output tensors.
interpreter = tf.lite.Interpreter(model_path='tflite_models/fastspeech_quant.tflite')
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
#melgan Get input and output tensors.
mel_interpreter = tf.lite.Interpreter(model_path="tflite_models/mb_melgan_quant.tflite")
mel_input_details = mel_interpreter.get_input_details()
mel_output_details = mel_interpreter.get_output_details()
#initialize text processor
processor = LJSpeechProcessor(None, "english_cleaners")

def generate_sample(ob, preview=True):
    print("* Generating sample...")
    tone_out = ob

    if preview:
        print("* Previewing audio file...")

        bytestream = tone_out.tobytes()
        pya = pyaudio.PyAudio()
        stream = pya.open(format=pya.get_format_from_width(width=4), channels=1, rate=22050, output=True)
        stream.write(bytestream)
        stream.stop_stream()
        stream.close()
        pya.terminate()
        print("* Preview completed!")
        
    else:
        write('sound.wav', SAMPLE_RATE, tone_out)
        print("* Wrote audio file!")


def custom_splitter(text):
  if "{" in text and "}" in text:
    acc = []
    split = text.split("}")
    for word in split:
      if "{" in word:
        acc.append(word + "}")
      else:
        acc.append(word)
    return acc
  else:
    return text.split()

def add_punctuation(text):
  if len(text) < 1:
    return text
  if len(text) < 10:
    if text[-1] in punctuations:
      if text[-1] != ".":
        return text[:-1] + "."
  if text[-1] not in punctuations:
    text += '.'
  return text

def break_chunks(l, n):
  """Yield successive n-sized chunks from l."""
  for i in range(0, len(l), n):
    yield " ".join(l[i:i + n])

def split_by_threshold(text, threshold):
  text_list = text.split()
  
  if len(text_list) <= threshold:
    return [text]

  if threshold < len(text_list) < (threshold*2):
    return list(break_chunks(
        text_list,
        int(math.ceil(len(text_list) / 2))
    ))
  elif (threshold*2) < len(text_list) < (threshold*3):
    return list(break_chunks(
        text_list,
        int(math.ceil(len(text_list) / 3))
    ))
  elif (threshold*3) < len(text_list) < (threshold*4):
    return list(break_chunks(
        text_list,
        int(math.ceil(len(text_list) / 4))
    ))
  else:
    return list(break_chunks(
        text_list,
        int(math.ceil(len(text_list) / 4))
    ))

def synthesize_helper(text, threshold=4):
    text_list = text.split()
    if len(text_list) <= threshold*1.3:
      decoder_output_tflite, mel_output_tflite = infer(text)
      mel_interpreter.resize_tensor_input(mel_input_details[0]['index'], tf.shape(decoder_output_tflite))
      mel_interpreter.allocate_tensors()
      mel_interpreter.set_tensor(mel_input_details[0]['index'],decoder_output_tflite)
      mel_interpreter.invoke()
      audio = mel_interpreter.get_tensor(mel_output_details[0]['index']).squeeze()
      outdir = "results/"
      generate_sample(audio)
      scipy.io.wavfile.write(outdir+input_text+".wav",22050,audio)
      return

    split_by_punc = None
    if len(text_list) >= threshold:
      for punc in split_punctuations:
        if punc in text:
          split_by_punc = text.split(punc)
          break

    chunks = []
    if split_by_punc:
      for sentence in split_by_punc:
        sentence = sentence.strip()
        chunk = split_by_threshold(sentence, threshold)
        chunks += split_by_threshold(sentence, threshold)
    else:
      chunks += split_by_threshold(text, threshold)

    # loop = asyncio.get_event_loop()
    pool = Pool(processes=1)
    combined_wav = np.array([], dtype = 'float32')
    for idx, chunk in enumerate(chunks):
      if len(chunk) > 0:
        text = add_punctuation(chunk)
        decoder_output_tflite, mel_output_tflite = infer(text)
        mel_interpreter.resize_tensor_input(mel_input_details[0]['index'], tf.shape(decoder_output_tflite))
        mel_interpreter.allocate_tensors()
        mel_interpreter.set_tensor(mel_input_details[0]['index'],decoder_output_tflite)
        mel_interpreter.invoke()
        audio = mel_interpreter.get_tensor(mel_output_details[0]['index']).squeeze()
        # loop.run_until_complete(generate_sample(audio)) 
        pool.apply_async(generate_sample, [audio])
        time.sleep(0.9)
        combined_wav = np.concatenate((combined_wav,audio))
    # loop.close()
    outdir = "results/"
    scipy.io.wavfile.write(outdir+input_text+".wav",22050,combined_wav)



# Prepare input data.
def prepare_input(input_ids):
  input_ids = tf.expand_dims(tf.convert_to_tensor(input_ids, dtype=tf.int32), 0)
  return (input_ids,
          tf.convert_to_tensor([1.0], dtype=tf.float32))

# Test the model
def infer(input_text):
  input_ids = processor.text_to_sequence(input_text.lower())
  interpreter.resize_tensor_input(input_details[0]['index'], 
                                  [1, len(input_ids)])
  interpreter.allocate_tensors()
  input_data = prepare_input(input_ids)
  for i, detail in enumerate(input_details):
    input_shape = detail['shape']
    interpreter.set_tensor(detail['index'], input_data[i])

  interpreter.invoke()

  # The function `get_tensor()` returns a copy of the tensor data.
  # Use `tensor()` in order to get a pointer to the tensor.
  return (interpreter.get_tensor(output_details[0]['index']),
          interpreter.get_tensor(output_details[1]['index']))

for _ in range(1):
  start_time = time.time()
  input_text = sys.argv[1]
  speaker_id = tf.convert_to_tensor([0.0], dtype=tf.float32)
  synthesize_helper(input_text)
  end_time = time.time()

  print(end_time-start_time)
```

**Comment by StuartIanNaylor** [comment]
hey guys many thanks its a great TTS :) So good to have such a great sounding offline TTS on something like a Pi

**Comment by dathudeptrai** [comment]
@manmay-nakhashi sure, let me take a look :D.

**Comment by StuartIanNaylor** [comment]
PS is there a model trained with n_mel=40?

`ValueError: Shapes (384, 40) and (384, 80) are incompatible`

**Comment by maozhiqiang** [comment]
hi @manmay-nakhashi @dathudeptrai ！ thanks for your reply,  My point is, How to use melgan to streaming generation for real mels ?

**Comment by maozhiqiang** [comment]
> PS is there a model trained with n_mel=40?
> 
> `ValueError: Shapes (384, 40) and (384, 80) are incompatible`

you can modify config file to to, and Re extracting audio features

**Comment by StuartIanNaylor** [comment]
I would have to retrain a model though wouldn't I as current one is with 80 n_mel.
Just wondering if there is a demo model completed with 40 n_mel as my 1050ti might not be up for the job :)


PS dunno if any interest but this is the tensorflow audio_ops.audio_spectrogram vs librosa

```
import tensorflow.compat.v1 as tf
from tensorflow.python.ops import gen_audio_ops as audio_ops
import sounddevice as sd
import numpy as np
import threading
import os

rec_duration = 0.020
sample_rate = 16000
num_channels = 1

def get_mfcc(waveform):
        # Run the spectrogram and MFCC ops to get a 2D audio: Short-time FFTs
        # background_clamp dims: [time, channels]
        sample_rate = 16000

        spectrogram = audio_ops.audio_spectrogram(
            waveform,
            window_size=320,
            stride=160)
        # spectrogram: [channels/batch, frames, fft_feature]

        # extract mfcc features from spectrogram by audio_ops.mfcc:
        # 1 Input is spectrogram frames.
        # 2 Weighted spectrogram into bands using a triangular mel filterbank
        # 3 Logarithmic scaling
        # 4 Discrete cosine transform (DCT), return lowest dct_coefficient_count
        mfccs = audio_ops.mfcc(
            spectrogram=spectrogram,
            sample_rate=sample_rate,
            upper_frequency_limit=7600,
            lower_frequency_limit=60,
            filterbank_channel_count=40,
            dct_coefficient_count=13)
        # mfcc: [channels/batch, frames, dct_coefficient_count]
        # remove channel dim
        mfccs = tf.squeeze(mfccs, axis=0)
        return mfccs



def sd_callback(rec, frames, time, status):
    
    # Notify if errors
    if status:
        print('Error:', status)
    mfcc = get_mfcc(rec)
    #print(mfcc)
    print(os.getloadavg())

# Start streaming from microphone
with sd.InputStream(channels=num_channels,
                    samplerate=sample_rate,
                    blocksize=int(sample_rate * rec_duration),
                    callback=sd_callback):
    threading.Event().wait()
```
Gives an av of `(0.2, 0.2, 0.38)`
But with librosa
`(0.3, 0.29, 0.27)`
Guess not huge but the TF math does seem to be faster

```
import sounddevice as sd
import numpy as np
import librosa
import threading
import os

rec_duration = 0.020
sample_rate = 16000
num_channels = 1
sd.default.never_drop_input= False
sd.default.latency= ('high', 'high')
sd.default.dtype= ('float32', 'float32')



def get_mfcc(audio):
    audio = np.squeeze(audio, 1)    
    mfccs = librosa.feature.mfcc(y=audio, n_mfcc=13, sr=sample_rate, n_fft=320, hop_length=160, n_mels=40, fmin=60.0, fmax=76000.0, htk=False )
    return mfccs

def sd_callback(rec, frames, time, status):

    # Notify if errors
    if status:
        print('Error:', status)
    mfcc = get_mfcc(rec)
    #print(mfcc)
    print(os.getloadavg())
# Start streaming from microphone
with sd.InputStream(channels=num_channels,
                    samplerate=sample_rate,
                    blocksize=int(sample_rate * rec_duration),
                    callback=sd_callback):
    threading.Event().wait()
    ```
    
    That is with MFCC but thinks generally its the same.

**Comment by OnceJune** [comment]
@maozhiqiang you can make frame and samples overlapped

**Comment by maozhiqiang** [comment]
hi @OnceJune ! how to set overlapped size, my result is bad to use frame syntheis

**Comment by OnceJune** [comment]
@maozhiqiang what about feed by chunk, 50 frames a time maybe, which outputs 50*hop_size samples. the you play 45 frames' audio, and next run you got another 50*hop_size samples, just ola the 5*hop_size samples from last run and the first 5*hop_size samples from new run, and play 50 frames' audio(5 frames prev, 45 frames new, and you got 5 frames left for next run), and output all in the last chunk.

**Comment by manmay-nakhashi** [comment]
@maozhiqiang i am using buffering plus overlapping chunking to meet the requirement 
1. first chunk make it 25% of the audio send it for mel generation 
2. meanwhile take 64 slice of mel and overlap of 10 each side and keep streaming

**Comment by manmay-nakhashi** [comment]
@StuartIanNaylor you can also trim the model params if you are using 40 mel . because data complexity is less now

**Comment by StuartIanNaylor** [comment]
I am not all that sure how to do that, still very much a tensorflow noob :)
Its OK I changed the parameter Yaml and obviously the input shape is now wrong.
It was just curiosity with a Pi4 as last time I tested this level of TTS it was very much a GPU affair.

I think I will take a back seat and sit in awe at the fantastic work of others as really didn't think this type of edge quality would be possible.
I was just interested at what the lowest load possibility sounded like.

But if anyone wants to make a streaming interface with maybe some so of callback method please do.
In fact thinking about it a streaming object is likely to have the callback but all is need is like you say is a buffer that can err out on underflow if the models lags the stream.

**Comment by manmay-nakhashi** [comment]
@dathudeptrai i have english 40 mel model where should i upload it ?

**Comment by StuartIanNaylor** [comment]
email? stuartiannaylor@outlook.com I will share it from my google drive and put a link up here.
I have no idea how to let you upload to me drive.

**Comment by maozhiqiang** [comment]
hi @manmay-nakhashi @OnceJune Thank you for your warm help！ @manmay-nakhashi would you tell me how to use queue to smooth voice streaming ! thanks again!

**Comment by manmay-nakhashi** [comment]
@maozhiqiang are you using python, java or c++?

**Comment by maozhiqiang** [comment]
> @maozhiqiang are you using python, java or c++?

python

**Comment by manmay-nakhashi** [comment]
@maozhiqiang did you try above script which i posted ?(you have to change LJprocessor according to current branch) , 
for queue implementation you can refer https://docs.python.org/3/library/queue.html , i don't have python code implemented.

**Comment by maozhiqiang** [comment]
@manmay-nakhashi thanks , I will try!

**Comment by StuartIanNaylor** [comment]
How did it go with the streaming output guys? Also @manmay-nakhashi did you ever find the n_mel=40 model?
