### ISSUE TITLE
TensorFlowTTS_Tacotron2_with_TFLite.ipynb import error

### ISSUE THREAD

**Issue by StuartIanNaylor** [TensorSpeech/TensorFlowTTS#524]
```
    from tensorflow_tts.processor.ljspeech import symbols, _symbol_to_id
ImportError: cannot import name 'symbols' from 'tensorflow_tts.processor.ljspeech'
```

Hi I am trying to run the copied jupyter code locally which presume should work as long as the paths are correct.
The above import fails has there been a naming/structure change ?

Thanks

**Comment by dathudeptrai** [comment]
@StuartIanNaylor change `symbols` to `LJSPEECH_SYMBOLS`

**Comment by StuartIanNaylor** [comment]
Many apols

```
    from tensorflow_tts.processor.ljspeech import LJSPEECH_SYMBOLS, _symbol_to_id
ImportError: cannot import name '_symbol_to_id' from 'tensorflow_tts.processor.ljspeech'
```

**Comment by dathudeptrai** [comment]
@StuartIanNaylor i will fix it :D

**Comment by StuartIanNaylor** [comment]
I think its just my setup as ran the fastvoice one on colab for me.
I would hazard a guess that jupyter doesn't seem to like to run from the venv I have setup.
