### ISSUE TITLE
Voice cloning

### ISSUE THREAD

**Issue by TarasevichArtem** [TensorSpeech/TensorFlowTTS#525]
Can I clone my voice? Can I use the already trained model in this case? If possible, how big is the dataset needed for further training? Are there any examples of such training (maybe in a colab)?

**Comment by ZDisket** [comment]
@TarasevichArtem Yes, and you can use already trained model as pretrained checkpoint for finetuning. For that, you want at least 30 minutes of data. I've managed both Tacotron2 and FastSpeech2 with less, but the general rule is that 30 minutes is a safe minimum.

**Comment by PeijiYang** [comment]
> @TarasevichArtem Yes, and you can use already trained model as pretrained checkpoint for finetuning. For that, you want at least 30 minutes of data. I've managed both Tacotron2 and FastSpeech2 with less, but the general rule is that 30 minutes is a safe minimum.

I try tacotron and fs2 finetuned with 2 hours of data, the result is not very well. is it need to turn down the learning rate when finetuning?

**Comment by ZDisket** [comment]
@PeijiYang If the result is bad only due to low quality audio and you can't immediately see anything wrong with the mel spectrograms then it's probably the vocoder. I don't usually turn down the learning rate when finetuning, but it may work in your case.

**Comment by PeijiYang** [comment]
> @PeijiYang If the result is bad only due to low quality audio and you can't immediately see anything wrong with the mel spectrograms then it's probably the vocoder. I don't usually turn down the learning rate when finetuning, but it may work in your case.

how many steps you usually set when you finetune?

**Comment by ZDisket** [comment]
@PeijiYang Almost all of the time I stop at 30k with default learning rate config.

**Comment by PeijiYang** [comment]
> @PeijiYang Almost all of the time I stop at 30k with default learning rate config

Maybe i finetune it too many steps.. :D

**Comment by krigeta** [comment]
> Can I clone my voice? Can I use the already trained model in this case? If possible, how big is the dataset needed for further training? Are there any examples of such training (maybe in a colab)?

Hello, are you to find any solution to your problem because I also want to clone voice using a colab notebook.

**Comment by juunnn** [comment]
@ZDisket do you train the whole fastspeech2 model or just a specific part like in `var_train_expr: "embeddings|encoder|decoder"`?

**Comment by ZDisket** [comment]
@juunnn 
Whole model

**Comment by juunnn** [comment]
So, I tried to adapt fastspeech2 model with my existing model. I did the preprocessing same as I trained my existing model. But when I trying to execute the training this is happened.
```
2021-04-23 14:56:39.517277: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-04-23 14:56:39.517872: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2099980000 Hz
Traceback (most recent call last):
  File "trainer/train_fastspeech2.py", line 417, in <module>
    main()
  File "trainer/train_fastspeech2.py", line 409, in main
    resume=args.resume,
  File "/home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow_tts/trainers/base_trainer.py", line 852, in fit
    self.run()
  File "/home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow_tts/trainers/base_trainer.py", line 101, in run
    self._train_epoch()
  File "/home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow_tts/trainers/base_trainer.py", line 123, in _train_epoch
    self._train_step(batch)
  File "/home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow_tts/trainers/base_trainer.py", line 666, in _train_step
    self.one_step_forward(batch)
  File "/home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Incompatible shapes: [16,90,384] vs. [16,101,384]
	 [[node tf_fast_speech2/add_1 (defined at /home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow_tts/models/fastspeech2.py:181) ]]
	 [[cond_4/else/_182/cond_4/Greater/_532]]
  (1) Invalid argument:  Incompatible shapes: [16,90,384] vs. [16,101,384]
	 [[node tf_fast_speech2/add_1 (defined at /home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow_tts/models/fastspeech2.py:181) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference__one_step_forward_26157]

Errors may have originated from an input operation.
Input Source operations connected to node tf_fast_speech2/add_1:
 tf_fast_speech2/encoder/layer_._3/mul (defined at /home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow_tts/models/fastspeech.py:391)

Input Source operations connected to node tf_fast_speech2/add_1:
 tf_fast_speech2/encoder/layer_._3/mul (defined at /home/jun/vcloning/fs2/venv/lib/python3.6/site-packages/tensorflow_tts/models/fastspeech.py:391)

Function call stack:
_one_step_forward -> _one_step_forward
```
The command that I use is something like this
```
python trainer/train_fastspeech2.py --train-dir ./dataset/clean/M20002/train \
--dev-dir ./dataset/clean/M20002/valid \
--use-norm 1 \
--f0-stat ./dataset/clean/M20002/stats_f0.npy \
--energy-stat ./dataset/clean/M20002/stats_energy.npy \
--outdir ./ckpt/M20002 \
--config ./conf/adapt.yaml \
--pretrained ./model/base.h5 
```
pretty much the same with the config I train the base model.

**Comment by dathudeptrai** [comment]
@juunnn there is something wrong with ur training samples, you need to figure out what sample cause this problem by this simple script:

```
for data in tqdm(train_dataset):
    # test 1 step forward pass
    model(**data)
```

let use batch_size = 1 :D

**Comment by juunnn** [comment]
yeah, I figured out that my preprocessing is different from the base model. Thank you.

**Comment by davidesalvi** [comment]
> > Can I clone my voice? Can I use the already trained model in this case? If possible, how big is the dataset needed for further training? Are there any examples of such training (maybe in a colab)?
> 
> Hello, are you to find any solution to your problem because I also want to clone voice using a colab notebook.

Hi, did you manage to solve this problem? I'm also interested in it
