### ISSUE TITLE
Noise problem in generating audio mute position

### ISSUE THREAD

**Issue by tts-nlp** [TensorSpeech/TensorFlowTTS#536]
hi , when training using mb_melgan config, the generator audio appear noise in end of blank! how to solve this

![b'000641'](https://user-images.githubusercontent.com/58066364/113952979-5de11a00-9849-11eb-977e-5c19d7209cef.png)
[00641.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/6275295/00641.zip)

**Comment by dathudeptrai** [comment]
@tts-nlp it is not a problem, you can get a real length of ur audio from the mel generated.
