### ISSUE TITLE
Double Decoder Consistency for Tacotron 2

### ISSUE THREAD

**Issue by ZDisket** [TensorSpeech/TensorFlowTTS#54]
Hi, I found this [interesting post](https://erogol.com/solving-attention-problems-of-tts-models-with-double-decoder-consistency/) while regularly checking up on erogol's blog. Any chances of having it here? Having a Tacotron 2 that is practically immune to alignment problems sounds very state of the art.
For reference, Mozilla/TTS has it.

**Comment by dathudeptrai** [comment]
@ZDisket training tacotron-2 take too much time for me but i will consider. There are many paper solve alignment problem and training very fast such as glow-tts, flow-tts, aligntts. I don't think we really need tacotron-2 because fastspeech2 can produce comparable results and alignTTS can learn very good alginment with serveral hours. So the problem is, if we can find a model can be inference real-time, training time < 1 day and learn very good alignment with serveral hours, do we need tacotron-2 anymore ?

**Comment by ZDisket** [comment]
@dathudeptrai I know that too. If you get any of these working well (or FastSpeech2 without teacher model) then just ignore my suggestion.

**Comment by dathudeptrai** [comment]
Yeah :))) fastspeech2 without anh external aligner is comming :))) be patient

**Comment by dathudeptrai** [comment]
BTW, to: @erogol is "Double Decoder" training slower than original Tacotron-2 ? cc: @ZDisket

**Comment by erogol** [comment]
@dathudeptrai it makes training only for 5% slower. And it definitely is worth it. It solves to attention problems once for all at least for my runs. 

The problem with FastSpeech it requires initial alignments (from an aligner or a teacher model). Therefore to make the whole process easier and more accessible to everyone, I still believe targeting Tacotron like attention models is a worthy effort. 

Even you like to train FastSpeech you can use DDC to generate even better attention alignments labels for your FS training.

**Comment by erogol** [comment]
> 
> 
> Yeah :))) fastspeech2 without any external aligner is comming :))) be patient

you mean align-TTS?

**Comment by dathudeptrai** [comment]
@erogol flow-tts :D

**Comment by dathudeptrai** [comment]
@ZDisket i will read erogol's blog then i will consider to implement here but maybe you need training by urself :(. Tell me if it's ok ;v

**Comment by erogol** [comment]
I can try a PR but I need at least one day being 48 hours :)

**Comment by dathudeptrai** [comment]
@erogol what do you mean :)), one day cann't being 48 hours :))).

**Comment by erogol** [comment]
not in Mars :)

**Comment by dathudeptrai** [comment]
@erogol decoder (fine) is still 2 LSTM layers as normal and decoder (coarse) is 1 LSTM layers, am i right?

**Comment by erogol** [comment]
no the architecture is the same bur reduction rate is larger. But its a good idea to use even less layers.

**Comment by ZDisket** [comment]
@dathudeptrai I can train it from scratch myself although I estimate it'll take a week.

**Comment by ZDisket** [comment]
@dathudeptrai 
> So the question is, if we can find a model can be inference real-time, training time < 1 day and learn very good alignment with serveral hours, do we need tacotron-2 anymore ?

Does MFA-extracted duration FastSpeech2 now fit that description?
