### ISSUE TITLE
TFlite example fastspeech&melgan with TF 2.4.1

### ISSUE THREAD

**Issue by StuartIanNaylor** [TensorSpeech/TensorFlowTTS#542]
```
Traceback (most recent call last):
  File "tfl-test.py", line 67, in <module>
    decoder_output_tflite, mel_output_tflite = infer(input_text)
  File "tfl-test.py", line 54, in infer
    interpreter.invoke()
  File "/home/stuart/TensorFlowTTS/venv/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 540, in invoke
    self._interpreter.Invoke()
RuntimeError: tensorflow/lite/kernels/reshape.cc:58 stretch_dim != -1 (0 != -1)Node number 83 (RESHAPE) failed to prepare.
```
Works with 2.3.1 tensorflow-gpu but above fails with above.
It works but just for info

**Comment by StuartIanNaylor** [comment]
Anyone got any ideas as can be a bit of a pain finding correct wheels as just trying the the intel optimised tensorflow but no 2.3.1 whl unless compile.

**Comment by dathudeptrai** [comment]
> ```
> Traceback (most recent call last):
>   File "tfl-test.py", line 67, in <module>
>     decoder_output_tflite, mel_output_tflite = infer(input_text)
>   File "tfl-test.py", line 54, in infer
>     interpreter.invoke()
>   File "/home/stuart/TensorFlowTTS/venv/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 540, in invoke
>     self._interpreter.Invoke()
> RuntimeError: tensorflow/lite/kernels/reshape.cc:58 stretch_dim != -1 (0 != -1)Node number 83 (RESHAPE) failed to prepare.
> ```
> 
> Works with 2.3.1 tensorflow-gpu but above fails with above.
> It works but just for info

did you use tf-nightly ?

**Comment by StuartIanNaylor** [comment]
Nope tf-nightly is now far ahead of when the examples where created which is going to be tf2.5.0-rc1.

I am guessing part of the tensorflow-gpu of 2.3.1 is used that upstream is no longer the same also tensorflow 2.3.1 does the same.
From memory in 2.4 things got changed around with tensorflow being the all-in package and then a new package of tensorflow-cpu being just the cpu version.

I could use the current tf-nightly but I would wager a strong bet its going to do the same.

**Comment by dathudeptrai** [comment]
@StuartIanNaylor seems this is a bug of tf 2.4.1, tf2.3.1 or tf-nightly work well :(

**Comment by StuartIanNaylor** [comment]
Doubt it will try but unlikely the api changes have reverted upstream
