### ISSUE TITLE
How to fine-tune speaker embedding in multi-speaker FastSpeech2

### ISSUE THREAD

**Issue by guoyang94** [TensorSpeech/TensorFlowTTS#543]
A multi-speaker FastSpeech2 was trained. How to fine-tune speaker embedding part for another one target speaker. Or how to get speaker embedding for another one target speaker.  

I do not understand.

**Comment by dathudeptrai** [comment]
@guoyang94 what do you mean ?

**Comment by guoyang94** [comment]
> @guoyang94 what do you mean ?
In TensorflowTTS，we use tf.keras.layers.Embedding to get speaker embedding for each speaker in training dataset. 

tf.keras.layers.Embedding(
                config.n_speakers,
                config.encoder_self_attention_params.hidden_size）

config.n_speakers is the number of speakers in training dataset. Is right?

I want to fine tune multi-speaker FT2 to another target speaker for few-shot.

So, I need to fine-tune speaker embedding in multi-speaker FT2 to get speaker embbeding for another target speaker.

I do't konw how to get it.

**Comment by guoyang94** [comment]
tf.keras.layers.Embedding(
config.n_speakers,
config.encoder_self_attention_params.hidden_size）

config.n_speakers is the number of speakers in training dataset. Is right?

I want to fine tune multi-speaker FT2 to another target speaker for few-shot.

So, I need to fine-tune speaker embedding in multi-speaker FT2 to get speaker embbeding for another target speaker.

I do't konw how to get it.

**Comment by guoyang94** [comment]
We ues tf.keras.layers.Embedding to get speaker embedding for each speaker in training dataset.
tf.keras.layers.Embedding(config.n_speakers,config.encoder_self_attention_params.hidden_size）

config.n_speakers is the number of speakers in training dataset. Is right?

I want to fine tune multi-speaker FT2 to another target speaker for few-shot.

So, I need to fine-tune speaker embedding in multi-speaker FT2 to get speaker embbeding for another target speaker.

I do't konw how to get it.
