### ISSUE TITLE
tf 2.4.1 bugs

### ISSUE THREAD

**Issue by tts-nlp** [TensorSpeech/TensorFlowTTS#544]
when training using tf 2.4.1 , 

training code
`CUDA_VISIBLE_DEVICES=0 python examples/multiband_melgan/train_multiband_melgan.py \
  --train-dir ./dump/train/ \
  --dev-dir ./dump/valid/ \
  --outdir ./examples/multiband_melgan/exp/train.multiband_melgan.v1/ \
  --config ./examples/multiband_melgan/conf/multiband_melgan.v1.yaml \
  --use-norm 1 \
`
The following error occurred

`2021-04-20 13:30:56.974771: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:656] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_3"
op: "FlatMapDataset"
input: "TensorDataset/_1"
input: "Const/_2"
attr {
  key: "Targuments"
  value {
    list {
      type: DT_STRING
    }
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_flat_map_fn_31"
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        unknown_rank: true
      }
      shape {
        unknown_rank: true
      }
      shape {
        unknown_rank: true
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_STRING
      type: DT_STRING
      type: DT_STRING
    }
  }
}
. Consider either turning off auto-sharding or switching the auto_shard_policy to DATA to shard this dataset. You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via `dataset.with_options(options)`.
2021-04-20 13:30:56.997978: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:656] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_3"
op: "FlatMapDataset"
input: "TensorDataset/_1"
input: "Const/_2"
attr {
  key: "Targuments"
  value {
    list {
      type: DT_STRING
    }
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_flat_map_fn_538"
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        unknown_rank: true
      }
      shape {
        unknown_rank: true
      }
      shape {
        unknown_rank: true
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_STRING
      type: DT_STRING
      type: DT_STRING
    }
  }
}
. Consider either turning off auto-sharding or switching the auto_shard_policy to DATA to shard this dataset. You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via `dataset.with_options(options)`.`

**Comment by dathudeptrai** [comment]
@tts-nlp pls use tf 2.3.1 :)), i did not test our code with tf 2.4.1 yet :D .

**Comment by tts-nlp** [comment]
@dathudeptrai thanks for your suggestion , but tensorflow 2.3.1 not support cuda11, my new GPU only support cuda 11 for training!

**Comment by k-grygiel** [comment]
Did you try turning off sharding?

options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = AutoShardPolicy.OFF
dataset = dataset.with_options(options)

**Comment by tts-nlp** [comment]
hi @k-grygiel , 
According to your suggestion, modify as follows
`    def create(
            self,
            allow_cache=False,
            batch_size=1,
            is_shuffle=False,
            map_fn=None,
            reshuffle_each_iteration=True,
    ):
        """Create tf.dataset function."""
        output_types = self.get_output_dtypes()

        datasets = tf.data.Dataset.from_generator(
            self.generator, output_types=output_types, args=(self.get_args())
        )
        options = tf.data.Options()
        options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.OFF
        datasets = datasets.with_options(options)
        if allow_cache:
`

but the error still exists

**Comment by k-grygiel** [comment]
Try adding this in audio_mel_dataset.py

**Comment by tts-nlp** [comment]
@k-grygiel Still can't solve this error

**Comment by tts-nlp** [comment]
@k-grygiel thanks! the bugs fixed !

**Comment by dathudeptrai** [comment]
@tts-nlp can you make a pull request to fix this problem in tf 2.4.1 ?

**Comment by tts-nlp** [comment]
@dathudeptrai ok
