### ISSUE TITLE
hifigan InvalidArgumentError:Paddings must be non-negative: 0 -8980

### ISSUE THREAD

**Issue by Livjxbill993** [TensorSpeech/TensorFlowTTS#546]
Excuese me. when i run train_hifigan.py.  The following error occurs when training to  5000 steps
How to solve this problem?

tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -8980
	 [[{{node cond_4/else/_38/cond_4/Pad}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]

**Comment by dathudeptrai** [comment]
@Livjxbill993 there is something wrong with ur input data. To debug this, you should check what sample cause this error by bellow simple script:

```
for data in tqdm(train_dataloader):
    # print anything you want to found the error sample here. 
```

**Comment by zheng-xing** [comment]
> Excuese me. when i run train_hifigan.py. The following error occurs when training to 5000 steps How to solve this problem?
> 
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -8980 [[{{node cond_4/else/_38/cond_4/Pad}}]] [[MultiDeviceIteratorGetNextFromShard]] [[RemoteCall]]

Hi @Livjxbill993, did you figure out why? I have met the same problem @ 5000 step when evaluation starts. At first I suppose the val set data has some problem so I use the train set data to evaluation step but the same problem appears. It's weird the same data works for training step but fails at evaluation step.
