### ISSUE TITLE
hifigan v1 gradient explosion ？

### ISSUE THREAD

**Issue by unparalleled-ysj** [TensorSpeech/TensorFlowTTS#547]
The number of training steps can be seen from the figure
![2](https://user-images.githubusercontent.com/39238619/115490275-57629180-a290-11eb-8e80-d8be8e071d8f.png)
![1](https://user-images.githubusercontent.com/39238619/115490289-5df10900-a290-11eb-9751-58db61b9cce9.png)
![3](https://user-images.githubusercontent.com/39238619/115490382-909b0180-a290-11eb-933e-3f07ee45f1b3.png)

Some data will also appear a straight line after 100k in the v2 version. Do you have any suggestions?

**Comment by ZDisket** [comment]
There was a similar issue a bit ago and I replied with this: https://github.com/TensorSpeech/TensorFlowTTS/pull/387#issuecomment-813606701. Have you tried it?

**Comment by unparalleled-ysj** [comment]
> There was a similar issue a bit ago and I replied with this: [#387 (comment)](https://github.com/TensorSpeech/TensorFlowTTS/pull/387#issuecomment-813606701). Have you tried it?

Okay, let me test it. By the way, should the parameter discriminator_train_start_steps be set to 100k or set to 0 like you

**Comment by ZDisket** [comment]
@unparalleled-ysj Try 0 first.

**Comment by jarred1989** [comment]
@ZDisket @unparalleled-ysj Any good news? I ran into the same problem, so I changed the optimizer and  set discriminator_train_start_steps to 0 according to #387, the synthesized waveforms are no longer silence, but they are even worse than mb-melgan.

**Comment by ZDisket** [comment]
@jarred1989 A while back I came into the conclusion that there is just something wrong with TensorflowTTS HiFi-GAN that can't be alleviated with simple optimizer or config changes, so I settled with adding the MPD to MB-MelGAN, which trains slower but helps increase multispeaker performance, and may make it possible to successfully finetune another model to adapt it to a target speaker, as I am testing out.

**Comment by jarred1989** [comment]
@ZDisket  Thanks for your opinion, I may try it out later.

**Comment by chenht2010** [comment]
make learning rate smaller will be good. I tried on two corpus male and female, use default config, failed; smaller the lr, the result is good.

**Comment by ZDisket** [comment]
@chenht2010 What learning rate did you use?

**Comment by chenht2010** [comment]
only changed the generator:
`generator_optimizer_params:`
`values: [0.000125, 0.000125, 0.000625, 0.000625, 0.0000625, 0.00003125, 0.000015625, 0.000001]`

**Comment by dathudeptrai** [comment]
> only changed the generator:
> `generator_optimizer_params:`
> `values: [0.000125, 0.000125, 0.000625, 0.000625, 0.0000625, 0.00003125, 0.000015625, 0.000001]`

can you make a pull request to change the default config for better training :D ?

**Comment by chenht2010** [comment]
> 
> 
> > only changed the generator:
> > `generator_optimizer_params:`
> > `values: [0.000125, 0.000125, 0.000625, 0.000625, 0.0000625, 0.00003125, 0.000015625, 0.000001]`
> 
> can you make a pull request to change the default config for better training :D ?

sure

**Comment by Ellie1013** [comment]
@ZDisket Hi, I run hifiGAN with smaller lr, but the gradient exploded at 200K.
So, I tried to run with your source, but I got none value error.
Do you know the cause of the error, and your result is successful?
The error is like ..

lib/python3.8/site-packages/tensorflow_tts/trainers/base_trainer.py:300 _one_step_forward  *
        per_replica_losses = self._strategy.run(
/lib/python3.8/site-packages/tensorflow_tts/trainers/base_trainer.py:436 _one_step_forward_per_replica  *
        self._gen_optimizer.apply_gradients(
/lib/python3.8/site-packages/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py:710 apply_gradients  **
        return distribution_strategy_context.get_replica_context().merge_call(

...

lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:339 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:264 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py:281 _constant_impl
        tensor_util.make_tensor_proto(
/lib/python3.8/site-packages/tensorflow/python/framework/tensor_util.py:445 make_tensor_proto
        raise ValueError("None values not supported.")

    ValueError: None values not supported.
