### ISSUE TITLE
Error opening './LJSpeech-1.1/wavs/LJ047-0223.wav': System error.

### ISSUE THREAD

**Issue by Echidonasan** [TensorSpeech/TensorFlowTTS#548]
I got this error when I tried to run !tensorflow-tts-preprocess on colab

![image](https://user-images.githubusercontent.com/59184604/115492153-15950500-a216-11eb-88a2-7ca64d49702e.png)

this is my colab: https://colab.research.google.com/drive/1VC5ZoFEoz4ry0lI2caA9SfoR496o_UHQ#scrollTo=AQDBmpInYI0G

How to fix it?

**Comment by ZDisket** [comment]
Can you set your Colab link so that anyone with it can view?
