### ISSUE TITLE
Trying install on Windows and conflicting dependencies.

### ISSUE THREAD

**Issue by AjaxFB** [TensorSpeech/TensorFlowTTS#549]
`ERROR: Cannot install tensorflowtts==0.11, tensorflowtts==0.7, tensorflowtts==0.8, tensorflowtts==0.9 and tensorflowtts==1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    tensorflowtts 1.1 depends on tensorflow-gpu==2.3.1
    tensorflowtts 0.11 depends on tensorflow-gpu>=2.3.1
    tensorflowtts 0.9 depends on tensorflow-gpu>=2.3.0
    tensorflowtts 0.8 depends on tensorflow-gpu>=2.2.0
    tensorflowtts 0.7 depends on tensorflow-addons>=0.9.1`
    
    Someone can give me a tip?

**Comment by krkv** [comment]
Have you figured out what is the issue?
