### ISSUE TITLE
Can I add extra speakers to the pre-trained single speaker model?

### ISSUE THREAD

**Issue by JH-lee95** [TensorSpeech/TensorFlowTTS#551]
I want to convert the existing single speaker model to multi speaker model by adding some extra speakers. Is this possible? If it is, where do I have to modify?

**Comment by dathudeptrai** [comment]
@JH-lee95 you need to fine-tune a model after resizing speaker embeddings. To resize a speaker embedding you just need re-define speaker_embedding, here is an example to do that:

```
model = TFFastSpeech2(...)
model.embeddings.encoder_speaker_embeddings = [NEW_SPEAKER_EMBEDDING_LAYER]
model.decoder.decoder_speaker_embeddings =  [NEW_SPEAKER_EMBEDDING_LAYER]
```

**Comment by JH-lee95** [comment]
@dathudeptrai 
[NEW_SPEAKER_EMBEDDING_LAYER] <- This must be same with number of speakers, am I right?

**Comment by dathudeptrai** [comment]
> @dathudeptrai
> [NEW_SPEAKER_EMBEDDING_LAYER] <- This must be same with number of speakers, am I right?

you can modify the number of speakers here.

**Comment by JH-lee95** [comment]
Thank you sir!
