### ISSUE TITLE
'tensorflow-tts-preprocess' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by serrunlee** [TensorSpeech/TensorFlowTTS#556]
Please help me, I am studying usage TensorFlowTTS, 
from https://github.com/TensorSpeech/TensorFlowTTS

I finished all installed. After that I used this command.

`
tensorflow-tts-preprocess --rootdir ./ljspeech --outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
`

But I found the problem

```
'tensorflow-tts-preprocess' is not recognized as an internal or external command,
operable program or batch file.
```

How should I fix it?

**Comment by dathudeptrai** [comment]
@serrunlee are u using window ?

**Comment by serrunlee** [comment]
I can solve the problem
Use this command

```
git pull
pip install --upgrade .
```
