### ISSUE TITLE
Does it support the latest version of TensorFlow 2.5.0-rc3?

### ISSUE THREAD

**Issue by rgzn-aiyun** [TensorSpeech/TensorFlowTTS#559]
The latest version of TensorFlow 2.5.0-rc3 supports cpu acceleration:

oneAPI Deep Neural Network Library (oneDNN)
CPU performance optimizations from
Intel-optimized TensorFlow
are now available in the official x86-64 Linux and Windows builds.

They are off by default. Enable them by setting the environment variable
TF_ENABLE_ONEDNN_OPTS=1.
We do not recommend using them in GPU systems, as they have not been
sufficiently tested with GPUs yet.

**Comment by rgzn-aiyun** [comment]
@dathudeptrai

**Comment by dathudeptrai** [comment]
@rgzn-aiyun not test yet but it should work :D
