### ISSUE TITLE
Unable to load .ckpt file while resuming Tacotron2 training because of missing .h5 file

### ISSUE THREAD

**Issue by samuel-lunii** [TensorSpeech/TensorFlowTTS#561]
Hi ! 
I am trying to resume training from a checkpoint I saved.
Here is the command I used (python 3.7 & TF 2.3.1): 

python train_tacotron2 --config examples/tacotron2/conf/tacotron2.v1.yaml --train-dir /opt/ml/input/data/training/train/ --dev-dir /opt/ml/input/data/training/valid/ --model_dir s3://sagemaker-XXXX/test_job/model --outdir s3://sagemaker-XXXX/tac2-LJ-test-6/ --resume s3://sagemaker-XXXX/tac2-LJ-test-6/checkpoints/ckpt-18000 

First, I get these Warnings : 
```
WARNING: Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING: Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING: Unresolved object in checkpoint: (root).optimizer.decay
WARNING: A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit.
```

Then I get this error message : 
`OSError: Unable to open file (unable to open file: name = 's3://sagemaker-XXXX/tac2-LJ-test-6/checkpoints/model-18000.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

The thing is that I could not find any .h5 file in that folder, only ckpt. Are .h5 supposed to be saved during training ? And Where ? Should not ckpt files be enough to resume training ? About the warnings, is this a normal behaviour ?

Thanks !

**Comment by dathudeptrai** [comment]
@samuel-lunii there should be a .h5 file in checkpoint folder (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/trainers/base_trainer.py#L959-L962). You need debug by yourself why the h5 file isn't save correctly. A `save_weights` method here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/utils/utils.py#L48-L69). Pls modify `save_interval_steps` to small number first :D (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/conf/tacotron2.v1.yaml#L76).

**Comment by samuel-lunii** [comment]
Ok Thanks for quick reply ! 
There should be, indeed :) 
I will try to understand why they are not saved and will let you know.

**Comment by samuel-lunii** [comment]
alright got it :) 
`s3://` paths are not taken into account by the `_path_requires_gfile()` method in `utils.py`. 
I know my path is always going to be an `s3://` so I just disabled the condition in the `save_weights()` method.
Thanks a lot !
