### ISSUE TITLE
Pip install requires additional library

### ISSUE THREAD

**Issue by patrickvonplaten** [TensorSpeech/TensorFlowTTS#567]
Hey,

Thanks a lot for the great library. 

When installing *TensorFlowTTS* via pip it seems like a dependency is missing, *e.g.*, the following commands fails:

```bash
!pip install TensorFlowTTS
```

```python
from tensorflow_tts.inference import AutoConfig
from tensorflow_tts.inference import TFAutoModel
from tensorflow_tts.inference import AutoProcessor
```

because the package: `german_transliterate` can't be found. Only when doing 

```bash
!pip install TensorFlowTTS
!pip install git+https://github.com/repodiac/german_transliterate
```

```python
from tensorflow_tts.inference import AutoConfig
from tensorflow_tts.inference import TFAutoModel
from tensorflow_tts.inference import AutoProcessor
```

It works. It seems that `german_transliterate` is a necessary dependency to me -> should this maybe be installed automatically so that users can just do `pip install TensorFlowTTS` ? :-) 

[Here](https://colab.research.google.com/drive/1ixdhZqE_4yNmB27rd7HWyvtAQEqxtIru?usp=sharing) a colab to reproduce the problem.

cc @osanseviero

**Comment by dathudeptrai** [comment]
@patrickvonplaten Actually we can remove german_transliterate dependency in a `setup.py` in the next release of TensorFlowTTS :)). For users who want to use german TTS, they should install `german_transliterate` by themselves since there is no `german_transliterate` package in pypi :))).

**Comment by oliverguhr** [comment]
A little hint would be great, that you need to install this dependency by yourself.
