### ISSUE TITLE
Fastspeech 2 design question

### ISSUE THREAD

**Issue by PedroDKE** [TensorSpeech/TensorFlowTTS#568]
The original paper proposes the following variance predictor:
![image](https://user-images.githubusercontent.com/43861296/118535634-fcb33d00-b74a-11eb-8814-f9d871f8f113.png)

here it seems to me that the output of the lenght regulator is being used for pitch and energy prediction and not the output of the encoder as in this repo's implementation.
this repo's implementation's logic (line 162-189 of FS2 model) looks more like this to me:
![image](https://user-images.githubusercontent.com/43861296/118536860-87486c00-b74c-11eb-9c18-c5db3a58af3c.png)
(red are deleted connections and black is the current flow of how i understand it)
Here the output of the encoder is  used to predict the pitch and energy. These are then summed and then [encoder_state+energy_embedding+pitch_embedding] and the duration are going through the Length Regulator. and this is then your output for the variance adaptor.

Is there a reason for this adaptation or did i got something wrong from the implementation/original paper?

**Comment by dathudeptrai** [comment]
@PedroDKE https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2#whats-difference-

**Comment by PedroDKE** [comment]
Aah i see, seems like I missed that part :D thank you!
