### ISSUE TITLE
Porting to Tensorflow.js

### ISSUE THREAD

**Issue by kylejmorris** [TensorSpeech/TensorFlowTTS#575]
Hey there, love this project! I'm interested in doing a port of tacotron2 to tensorflow.js, wondering if anyone here has made any similar progress porting TfTTS models to TF.js. 

**Main unknowns**
- How long it'd take to setup a pipeline config and exporter (similar to existing tensorflow libs like [https://github.com/tensorflow/models/blob/master/research/object_detection/exporter_main_v2.py](url)
- are there any constraints on tf.js (model size limits, latency limits) preventing a port?
- How much room is there to improve existing voice quality once ported? Google posted a great demo of tacotron2 but I haven't seen any opensource meet that quality bar yet. I suppose its either an architecture constraint or we need better training data.

**Comment by dathudeptrai** [comment]
@kylejmorris I added `help wanted` tag :D, let see if anyone else can help :D.
