### ISSUE TITLE
Model overfit?

### ISSUE THREAD

**Issue by titipakorn** [TensorSpeech/TensorFlowTTS#577]
Here is the training logs of Tacotron-2.
![messageImage_1622093966318](https://user-images.githubusercontent.com/22910644/119773183-733e0080-beea-11eb-89e2-7445d80ec211.jpg)
![messageImage_1622093986554](https://user-images.githubusercontent.com/22910644/119773189-75a05a80-beea-11eb-97d1-4e854f6918e6.jpg)
My model can only speak sentences mostly in the training set but when I tried test sentences, the model can't speak it correctly.

What's wrong with my model?

In the attached picture, the old model are the orange one with 100k epochs and I used the old one to train the blue one.

My corpus is 5 hr and 25 mins with single speaker. The number of sentences are 2710. I trained the model with phonetic approach.

The results are still the same as I said.

**Comment by dathudeptrai** [comment]
@titipakorn could you attach an alignment figure?

**Comment by ZDisket** [comment]
@titipakorn 5 hours with 2710 utterances is insufficient time for training a Tacotron2 model from scratch (although it can vary depending on how monotone or emotional it is, and the quality). I did manage one with 8 hours but it had many misspellings. Can you attach some audio samples with alignment figures on test sentences? 
For small amounts of data I recommend first training a large, open-source corpus (like LJSpeech for English), then finetuning said model on your data.

**Comment by titipakorn** [comment]
> @titipakorn 5 hours with 2710 utterances is insufficient time for training a Tacotron2 model from scratch (although it can vary depending on how monotone or emotional it is, and the quality). I did manage one with 8 hours but it had many misspellings. Can you attach some audio samples with alignment figures on test sentences?
> For small amounts of data I recommend first training a large, open-source corpus (like LJSpeech for English), then finetuning said model on your data.

Actually this model was fine-tuning from LJSpeech. Do you have any ideas to augment my original data since my language data are scarce. 

Here is the alignment figure of testing sentences.

Test sentence 1
![test_sentence_s1](https://user-images.githubusercontent.com/22910644/119961474-49f7a000-bfd0-11eb-9a75-9113e9dae446.png)


Test sentence 2
![test_sentence_s2](https://user-images.githubusercontent.com/22910644/119961483-4d8b2700-bfd0-11eb-943d-6855f60b80de.png)

Here is training sentences.

![train_sentence_s1](https://user-images.githubusercontent.com/22910644/119961670-84613d00-bfd0-11eb-88cf-7d312894431a.png)


![train_sentence_s2](https://user-images.githubusercontent.com/22910644/119961674-86c39700-bfd0-11eb-8f03-cace7108217f.png)

I can't upload the sound in this comment so here is the link to them. https://drive.google.com/drive/folders/191EHXPi-X5HM8qV7nA01q6-sOtJ1Rd3A?usp=sharing

I still don't understand the perfect alignment that it should be.

**Comment by dathudeptrai** [comment]
@titipakorn those alignments took from training folder or you got it when doing a real inference?

**Comment by titipakorn** [comment]
> @titipakorn those alignments took from training folder or you got it when doing a real inference?

from real inference .

**Comment by dathudeptrai** [comment]
@titipakorn I heard a generated audio and it sounds ok, so the problem is about pronunciation?

**Comment by titipakorn** [comment]
> @titipakorn I heard a generated audio and it sounds ok, so the problem is about pronunciation?

Yes, it is. So I'm not sure it is about the size of training set or my grapheme-to-phoneme.

**Comment by dathudeptrai** [comment]
@titipakorn you can train with character to check if the problem is ur G2P or not. Pronunciation problem mainly caused by the size of the training set, I think :D.

**Comment by titipakorn** [comment]
> @titipakorn you can train with character to check if the problem is ur G2P or not. Pronunciation problem mainly caused by the size of the training set, I think :D.

Thanks for your help!

**Comment by dathudeptrai** [comment]
@titipakorn let train with character and check if the problem still exists :D.

**Comment by titipakorn** [comment]
> @titipakorn let train with character and check if the problem still exists :D.

I would take a lot of time since I have to train two models and each training time is about 7 days. 😔

**Comment by dathudeptrai** [comment]
> > @titipakorn let train with character and check if the problem still exists :D.
> 
> It would take a lot of time since I have to train two models and each training time is about 7 days.

hmmm, try to use the weight from model trained with G2P then fintune with charactor =))).

**Comment by titipakorn** [comment]
> > > @titipakorn let train with character and check if the problem still exists :D.
> > 
> > 
> > It would take a lot of time since I have to train two models and each training time is about 7 days.
> 
> hmmm, try to use the weights from the model trained with G2P then fintune with charactor =))).

I see. Thank you!
