### ISSUE TITLE
MelGAN model not found :/

### ISSUE THREAD

**Issue by ARFR2** [TensorSpeech/TensorFlowTTS#580]
**hello**
I tried to test this on _colab_, but i couldn't load MelGAN models.
for example for 'MelGAN Original' i got this error: 
`HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/melgan-1M6.h5/resolve/main/model.h5`
and for the others too.

**Comment by dathudeptrai** [comment]
@ARFR2 I will update all colab now :D. But u can try: 

```
from tensorflow_tts.inference import TFAutoModel

melgan = TFAutoModel.from_pretrained("tensorspeech/tts-melgan-ljspeech-en")
```

**Comment by ARFR2** [comment]
Thank you. 
but now I get another error on 
`from tensorflow_tts.inference import TFAutoModel`
error: ImportError: No module named german_transliterate.core

**Comment by dathudeptrai** [comment]
@ARFR2 
```
pip install git+https://github.com/repodiac/german_transliterate.git#egg=german_transliterate
```

**Comment by ARFR2** [comment]
Thank you.
