### ISSUE TITLE
h5py issue !

### ISSUE THREAD

**Issue by ARFR2** [TensorSpeech/TensorFlowTTS#583]
hi
on colab,
I get this error `AttributeError: 'str' object has no attribute 'decode'`.
when i run `tacotron2 = TFAutoModel.from_pretrained("tensorspeech/tts-tacotron2-ljspeech-en", name="tacotron2")`.

I searched, and found [This issue on h5py github](https://github.com/h5py/h5py/issues/1732).
this error caused by h5py > 3.0.0

**Comment by fengwang** [comment]
I solved this problem by degrading h5py to 2.10
