### ISSUE TITLE
following arguments are required 

### ISSUE THREAD

**Issue by twister11211** [TensorSpeech/TensorFlowTTS#589]
hi I enter all arguments in the instructions but still get error messages saying

train_tacotron2.py: error: the following arguments are required: --outdir, --config

TensorFlowTTS> python examples/tacotron2/train_tacotron2.py \--train-dir ./dump/train/ \--dev-dir ./dump/valid/ \--outdir ./examples/tacotron2/exp/train.tacotron2.v1/ \--config ./examples/tacotron2/conf/tacotron2.v1.yaml \--use-norm 1 \--mixed_precision 0 \--resume ""

the end of log 
usage: train_tacotron2.py [-h] [--train-dir TRAIN_DIR] [--dev-dir DEV_DIR] [--use-norm 
                                         USE_NORM] --outdir OUTDIR
                                         --config CONFIG [--resume [RESUME]] [--verbose VERBOSE]
                                         [--mixed_precision MIXED_PRECISION] [--pretrained 
                                         [PRETRAINED]]
train_tacotron2.py: error: the following arguments are required: --outdir, --config

I'm new to programing and this is giving me a hard time I would really appreciate any help I could get with this thanks

**Comment by twister11211** [comment]
I figured it out rookie mistake

**Comment by LxtteDev** [comment]
> I figured it out rookie mistake

What was the fix? I have this exact issue.

**Comment by twister11211** [comment]
Remove the / sepirating the arguments and put them on the same line

**Comment by LxtteDev** [comment]
> Remove the / sepirating the arguments and put them on the same line

I am doing that

**Comment by LxtteDev** [comment]
I already was separating the arguments, and it looks like you were too. If you still have the command somewhere, can you post it? I would like to try and figure out what you did.

**Comment by twister11211** [comment]
python examples/tacotron2/train_tacotron2.py --train-dir ./dump/train/ --dev-dir ./dump/valid/ --outdir ./examples/tacotron2/exp/train.tacotron2.v1/ --config ./examples/tacotron2/conf/tacotron2.v1.yaml --use-norm 1 --mixed_precision 0 --resume ""

**Comment by LxtteDev** [comment]
Thank you! Posting the command gave me the required brain cells to find out its because of the quotation marks.
