### ISSUE TITLE
How can I fix this error?

### ISSUE THREAD

**Issue by bear19782002** [TensorSpeech/TensorFlowTTS#595]
When I run the following code in colab, an error occurs.
However, it works fine in windows or docker environment.
It seems that this error did not occur in r0.7

import os
!git clone https://github.com/TensorSpeech/TensorFlowTTS.git
os.chdir("TensorFlowTTS")
!pip install .
os.chdir("..")
import sys
sys.path.append("TensorFlowTTS/")

from examples.multiband_melgan.train_multiband_melgan import main

**Comment by dathudeptrai** [comment]
@bear19782002 a Korean colab is fixed now.
