### ISSUE TITLE
Tacotron2 inference fails, but training evaluation seems fine

### ISSUE THREAD

**Issue by ihshareef** [TensorSpeech/TensorFlowTTS#597]
I'm training a Tacotron2 to perform duration extraction so that I can train FastSpeech2. I have a 5-hour custom non-English dataset that I prepared like LJSpeech (used default preprocessing). I'm training from scratch.

The alignments and the spectrograms generated during training seem fine, and so does the tensorboard outputs, as can be seen as follows:
![evaluation_alignment](https://user-images.githubusercontent.com/7621646/121739110-98e71e80-cb14-11eb-9ddb-19236995f80a.png)
The spectrograms, though from 1,500 steps, have not deteriorated at 16,000 steps.
![evaluation_spectrogram](https://user-images.githubusercontent.com/7621646/121739143-a1d7f000-cb14-11eb-84d3-f1ced7294f2b.png)
![tensorboard_values](https://user-images.githubusercontent.com/7621646/121739154-a6040d80-cb14-11eb-95a6-f6c38e7e424e.JPG)

However, I get terrible results when I download a model (16,000 iterations) and perform inference. I created a Google Colab notebook for inference: https://colab.research.google.com/drive/1JLkncs27HaMo7dj05-T4cNW4u2nYAVWv?usp=sharing

The alignments and the spectrogram produced are as follows:
![inference_alignment](https://user-images.githubusercontent.com/7621646/121739215-bb793780-cb14-11eb-8efe-5eba2d71aabc.JPG)
![melspectrogram](https://user-images.githubusercontent.com/7621646/121739410-02672d00-cb15-11eb-87c3-e45ad7493bb7.JPG)

In the AutoProcessor, I used the `ljspeech_mapper.json` that I got from the `dump_ljspeech` folder. I used the `tacotron2.v1.yml` file that I found in the `examples` folder, as well. 

As per what I understand from [here](https://github.com/TensorSpeech/TensorFlowTTS/issues/581#issuecomment-856550695), should I ignore this and keep training until 50k and then use the model to extract durations for FastSpeech2?

**Comment by dathudeptrai** [comment]
@ihshareef you need training tacotron2 atleast 50k steps.

**Comment by ihshareef** [comment]
Thanks for the quick response. Will continue until 50k and check if it persists.

**Comment by ihshareef** [comment]
Closing issue until I check things again with 50k iterations. Will update progress.

**Comment by ihshareef** [comment]
Just as an update:
I guess that the dataset that I had used (~5,000 speech samples, total of 8 hours) was insufficient for the Tacotron to learn properly. I used the pretrained LJSpeech model and fine-tuned it on my dataset, and now I'm able to generate speech from Tacotron without using teacher-forcing.

**Comment by dathudeptrai** [comment]
> Just as an update:
> I guess that the dataset that I had used (~5,000 speech samples, total of 8 hours) was insufficient for the Tacotron to learn properly. I used the pretrained LJSpeech model and fine-tuned it on my dataset, and now I'm able to generate speech from Tacotron without using teacher-forcing.

Thanks for the report :D, it's a good new since our pretrained models are valuable :dagger:
