### ISSUE TITLE
Nan loss while training the tacotron2 model:/ 

### ISSUE THREAD

**Issue by NoCodeAvaible** [TensorSpeech/TensorFlowTTS#601]
Hey @dathudeptrai,
when I start the training of the tacotron2 model I immediately get a nan loss.  
I've already tried to resolve this problem by following the steps of [this issue](https://github.com/TensorSpeech/TensorFlowTTS/issues/563). 
At first it worked well but as I tried to start the training today I ended up getting the old nan problem I was facing before following the instructions on how to solve this problem in the issue I've linked.

What I am using:
Tensorflow = 2.4.0/2.3.0 also worked for me
Cuda = 11.0
Cudnn = 8.0

What I've tried before I followed the instructions:
Tensorflow = 2.2.0
Cuda = 10.0
Cudnn = 8.0

My gpu:
nvidia rtx 3080 

Picture of training:
![nan_loss](https://user-images.githubusercontent.com/77166330/122974673-e1170400-d392-11eb-93e2-bcae09d2630b.JPG)

Pictures of the system variables to make sure Cuda was installed the right way:
![sysv1](https://user-images.githubusercontent.com/77166330/122973832-f5a6cc80-d391-11eb-93d9-3b6a6322c77a.JPG)

![sysv2](https://user-images.githubusercontent.com/77166330/122973849-f9d2ea00-d391-11eb-8817-b077937a7193.JPG)

Picture of the `nvcc -V` command if Cuda was installed the right way:
![commandpromt](https://user-images.githubusercontent.com/77166330/122974434-97c6b480-d392-11eb-95db-01237c399726.JPG)

Thank's for every suggestion and help in advance:)

**Comment by Rashi2011** [comment]
I am also facing the same issue 
cuda 10.1
cudnn 7.6.5
tensorflow              2.2.0
tensorflow-addons       0.11.2
tensorflow-estimator    2.2.0
tensorflow-gpu          2.2.1

driver version  465.27

**Comment by CracKCatZ** [comment]
Hey @Rashi2011 which graphics card are you using?

**Comment by Rashi2011** [comment]
I changed them to
cuda  11.0                      
cudnn   8                                   
tensorflow 2.4.1                         
tensorflow-gpu   2.5
and it worked

**Comment by CracKCatZ** [comment]
Hey @Rashi2011, 

thank's for your fast response:)
Are you really using cuda version 11.0 and cudnn version 8.0 or are you using for example a little higher version of cuda and cudnn for example cuda 11.3. 0 and cuda v8.2.0

Thanks for your response in advance:)

**Comment by Rashi2011** [comment]
Hii @CracKCatZ ,
No,  I am using cuda 11.0 and cudnn 8.0 only.
