### ISSUE TITLE
Help needed regarding conversion of tactron2 and melgan model into TFlite

### ISSUE THREAD

**Issue by FatimaZulfiqar** [TensorSpeech/TensorFlowTTS#603]
Hi, I am unable to convert tacotron2 and melgan model with the help of the "TensorFlowTTS_Tacotron2_with_TFLite" notebook. I am facing issues while importing a library. Can anybody please help me and tell me exact way to convert into TFLite?

**Comment by dathudeptrai** [comment]
@FatimaZulfiqar what is ur tf version ?

**Comment by FatimaZulfiqar** [comment]
Oh um, I am running on Colab and I think it's TensorFlow 2.6

**Comment by dathudeptrai** [comment]
@FatimaZulfiqar i think you can try tf 2.3.1

**Comment by FatimaZulfiqar** [comment]
> @FatimaZulfiqar i think you can try tf 2.3.1

Okay thank you so by downgrading tensorflow version into 2.3.1 d I still need to install tensorflow-nightly? 

Also my Google Colab notebook keeps on crashing due to unknown reasons whenever I execute a cell for an inference of tflite tacotron2 model. I can't quite figure out the issue

**Comment by FatimaZulfiqar** [comment]
![notebook crashes](https://user-images.githubusercontent.com/81231619/123507314-292f7280-d682-11eb-9994-1fb00c5f5b70.png)
 

That's the part where the notebook keep on crashing

**Comment by FatimaZulfiqar** [comment]
![log](https://user-images.githubusercontent.com/81231619/123507392-7d3a5700-d682-11eb-8ab5-547562a38125.jpeg)

and that's a runtime log
