### ISSUE TITLE
Failed to run processing 

### ISSUE THREAD

**Issue by khainh3101** [TensorSpeech/TensorFlowTTS#605]
Hello guys, when i run command : $pip install TensorFlowTTS, then my console show "Fail to build pyword". I try to install pyworld by: pip install pyword and it has been installed. After all, i run on terminal:  
tensorflow-tts-preprocess --rootdir ./ljspeech --outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
And console show:"tensorflow-tts-preprocess: command not found"
Please help me pass this part, thank you

**Comment by ziyigit** [comment]
> Hello guys, when i run command : $pip install TensorFlowTTS, then my console show "Fail to build pyword". I try to install pyworld by: pip install pyword and it has been installed. After all, i run on terminal:
> tensorflow-tts-preprocess --rootdir ./ljspeech --outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
> And console show:"tensorflow-tts-preprocess: command not found"
> Please help me pass this part, thank you

You can try to install **Visual Studio** , select **desktop development with c++**, after reboot run pip install .

**Comment by TheHonestBob** [comment]
> Hello guys, when i run command : $pip install TensorFlowTTS, then my console show "Fail to build pyword". I try to install pyworld by: pip install pyword and it has been installed. After all, i run on terminal:
> tensorflow-tts-preprocess --rootdir ./ljspeech --outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
> And console show:"tensorflow-tts-preprocess: command not found"
> Please help me pass this part, thank you

You have to python setup.py if you want to use command tensorflow-tts-preprocess, you also can use python preprocess.py just change a little code
