### ISSUE TITLE
emotions in speech

### ISSUE THREAD

**Issue by luantunez** [TensorSpeech/TensorFlowTTS#607]
Hello and thank you for sharing your work!
I was wondering if it would be possible have an emotional TTS with these tools.
Are there any pretrained models or suggestions on how to do so?
Thank you very much in advance!

**Comment by ZDisket** [comment]
If you have a large enough dataset (12+ hours total) split by emotion, you can assign IDs to every emotion and modify the dataloader to load them as `speaker_id`, so in the final model you'll be able to control the emotion by using speaker IDs.

**Comment by iamanigeeit** [comment]
I am actually working on this, because i want to disentangle speaker and emotion information.

**Comment by luantunez** [comment]
Great! Do you have any time estimation? 
Thank you!

**Comment by iamanigeeit** [comment]
I need to finish my current experiments by Mid-Aug, so it won't be earlier than that... are you looking for a pretrained model? If you need something soon, i have written a preprocessor for the ESD dataset (https://github.com/HLTSingapore/Emotional-Speech-Data) that you can use for training.

**Comment by luantunez** [comment]
Thank you very much! I will do that! Could you please give an update when you are able to release your ETTS so I can compare results?

**Comment by iamanigeeit** [comment]
Let me know how i can contact you. Thanks!

**Comment by luantunez** [comment]
luantunez95@gmail.com 😁
