### ISSUE TITLE
Enabling mixed_precision for training

### ISSUE THREAD

**Issue by jun-danieloh** [TensorSpeech/TensorflowTTS#61]
Hi, I would like to turn on mixed_precision setting for training so set "1" for the command below, but mixed_precision is still False after that. Do I miss something?

```
2020-06-25 06:58:32,264 (train_tacotron2:413) INFO: mixed_precision = False
```

```
CUDA_VISIBLE_DEVICES=0 python3 examples_models/tacotron2/train_tacotron2.py \
  --train-dir ./dump_lisa/train/ \
  --dev-dir ./dump_lisa/valid/ \
  --outdir ./examples_models/tacotron2/exp_lisa/train.tacotron2.v2_mixed_precision/ \
  --config ./examples_models/tacotron2/conf/tacotron2.v1.yaml \
  --use-norm 1
  --mixed_precision 1 \
  --resume ""
```

**Comment by dathudeptrai** [comment]
@jun-danieloh i don't know :)) maybe you need explicit set is_mixed_precision = True in Tacotron2Trainer Class, but i failed to enable mixed precision training for tacotron-2 :)), that is a tensorflow-related bug. FastSpeech is still ok :)).
