### ISSUE TITLE
No diagonal alignment and guided attention loss - Tacotron2

### ISSUE THREAD

**Issue by abaddon-moriarty** [TensorSpeech/TensorFlowTTS#611]
Hi, 
I'm having trouble when training my tacotron2 model on a French dataset.

My guided attention loss after going down keeps going back up, and from what I saw on the expected learning curves ([here](https://github.com/tensorspeech/TensorFlowTTS/tree/master/examples/tacotron2#learning-curves)), it should not get higher.
![image](https://user-images.githubusercontent.com/56978503/124584793-f0975200-de54-11eb-90d7-945e404d3dc1.png)

In the important notes on tacotron2 ([here](https://github.com/tensorspeech/TensorFlowTTS/tree/master/examples/tacotron2#learning-curves)) it is explained that the guided attention should be disabled after 15 to 25k steps, after the diagonal alignement has been made, however my model has still not reached a diagonal alignment.

This is my alignment at 30k steps.. they all look like that.
![image](https://user-images.githubusercontent.com/56978503/124586057-48828880-de56-11eb-9b70-3568ee5989d6.png)

It did have somewhat of a diagonal alignement around 8k steps, which is why I started over a few times from that point, but they lost it every time.
![image](https://user-images.githubusercontent.com/56978503/124586426-b464f100-de56-11eb-8bbe-ca9363ea09b3.png)

Is there a parameter I should change to help the model get the diagonal alignment?
Thank you for your answers!

**Comment by dathudeptrai** [comment]
@abaddon-moriarty the tensorboard curve is ok. You need to keep training the model up to 50-80k steps, 30k is not enough to make tacotron2 be able to use in the inference.

**Comment by abaddon-moriarty** [comment]
@dathudeptrai , thank you for your answer. I have continued training up to 100'000 iterations.
Here are my tensorboard and my diagonal alignment.
![image](https://user-images.githubusercontent.com/56978503/125104060-45e59480-e0dd-11eb-80da-54ddcd01cca0.png)

Should I keep the training going to get results?

**Comment by abaddon-moriarty** [comment]
I have managed to get the diagonal alignement, the problem wasn't a lack of training, but the text to seq part.
When I fed ids input directly and not text, it worked well, now I have resolved the text2seq problem. The model works great!
