### ISSUE TITLE
spoken audio not clear after multiple runs

### ISSUE THREAD

**Issue by get2abhi** [TensorSpeech/TensorFlowTTS#616]
The spoken audio slowly becomes gibberish after 1st/2nd use.

**Comment by dathudeptrai** [comment]
@get2abhi can you pass ur script to reproduce ur bug here ?

**Comment by get2abhi** [comment]
It happens with the android out of box example.  

Steps to reproduce:

Run the android example and change the speed from fast to slow. The voice output will become gibberish
