### ISSUE TITLE
weight incompatible for German TTS

### ISSUE THREAD

**Issue by neso613** [TensorSpeech/TensorFlowTTS#618]
Hi, I am trying to get german tts model but got this error while assigning weight to architecture(Tacotron2)
ValueError: Cannot assign to variable encoder/embeddings/character_embeddings/weight:0 due to variable shape (149, 512) and value shape (156, 512) are incompatible

**Comment by dathudeptrai** [comment]
@neso613 can you pass ur script here ?

**Comment by natapon-lyve** [comment]
I am also get this error. I have just clone the model from huggingface and comment the line `dataset: thorsten`. When load model from pretrained model. I also got the warning.

My code is in this [colab](https://colab.research.google.com/drive/16mWwAW37vKJ3fsGsNVQu5izZQjbhBVGt?usp=sharing)

**Comment by neso613** [comment]
any update ?
