### ISSUE TITLE
Getting an used before assigned error

### ISSUE THREAD

**Issue by Geigerkind** [TensorSpeech/TensorFlowTTS#621]
Following line is the culprit:
https://github.com/TensorSpeech/TensorFlowTTS/blob/eec964d8142636c008311f26ff15ca90c5a41b2d/tensorflow_tts/trainers/base_trainer.py#L139

Also I needed to install the german transliterate myself, dont think it should throw an error If im not even using german input.

**Comment by ZDisket** [comment]
@Geigerkind How many files are in your train set? This can happen when the batch size is larger than the amount of actual files.

**Comment by Geigerkind** [comment]
Not many at all, just recorded a few to test it. Where can I view the batch size?

**Comment by Geigerkind** [comment]
Works with a larger amount of files!
Sorry to bother!
