### ISSUE TITLE
OOM witch batch_size=16

### ISSUE THREAD

**Issue by CracKCatZ** [TensorSpeech/TensorFlowTTS#625]
Hey guys,

when training the tacotron model I am getting an OOM with a batch size of 16.
But I don't understand how this is even possible because I have a gpu with 11 gigs of vram and my pc is not running other processes while training. When reducing the batch size to 8 everything works fine but only 5 gigs of my vram is used while training and the training is actually pretty slow(7.50it/s).

So I am wondering if I made something wrong with my cuda/cudnn setup and how I can fix this problem.

Thanks for every help and suggestion in advance:)

**Comment by dathudeptrai** [comment]
@CracKCatZ the maximum training samples should be <= 12s, pls check that :D.

**Comment by ZDisket** [comment]
@CracKCatZ In your log, check the max_mel_length, it should've gotten printed. You probably got some very long sample(s)

**Comment by CracKCatZ** [comment]
Hey @dathudeptrai and @ZDisket ,

thanks for your guys fast response and help:)
I will check it:)

**Comment by NoCodeAvaible** [comment]
Hey @dathudeptrai and @ZDisket ,
I am using the english ljspeech dataset but I checked the training samples anyway and noticed that none of the samples were longer than 12 seconds or very long.
Is there maybe something else that could be wrong?

**Comment by CracKCatZ** [comment]
Hey @dathudeptrai and @ZDisket ,
I am using the english ljspeech dataset but I checked the training samples anyway and noticed that none of the samples were longer than 12 seconds or very long.
Is there maybe something else that could be wrong?

**Comment by dathudeptrai** [comment]
> Hey @dathudeptrai and @ZDisket ,
> I am using the english ljspeech dataset but I checked the training samples anyway and noticed that none of the samples were longer than 12 seconds or very long.
> Is there maybe something else that could be wrong?

the maximum mel frames for training should be <= 850, pls check that.

**Comment by krkv** [comment]
Could you advise on how to exclude training samples which are too long?
