### ISSUE TITLE
Can I use a pretrained model and "teach" it to use my voice?

### ISSUE THREAD

**Issue by Geigerkind** [TensorSpeech/TensorFlowTTS#626]
Hello,
I would like to have a model that can output my voice.
However, I don't have the time to record 24h of my voice, I probably need for a single hour several months.

So my question is, can I use a shortcut and apply my voice to one of the pretrained models?

If so, how much training data would I need for that?

**Comment by dathudeptrai** [comment]
@Geigerkind i think around 4-5 hours :)).

**Comment by Geigerkind** [comment]
@dathudeptrai 
"So my question is, can I use a shortcut and apply my voice to one of the pretrained models?"
I saw that tactotron has some sort of pretrained general model that I can use.

Can I even further reduce the training time and required data if I would use the pretrained ljspeech model?

**Comment by ZDisket** [comment]
@Geigerkind You can do with as little as 30 minutes, although I would recommend up to 2 hours, if you train your voice by finetuning one of the pretrained models in the same language (so English would be LJSpeech). It also depends on what model you're training. FastSpeech2 is less data-demanding than Tacotron2.

**Comment by Geigerkind** [comment]
Okay, so I could use the pretrained ljspeech model to train the for example multiband melgan model with my data and I should get in theory a solid generator with my voice?

Also I dont yet understand the difference between the tactotron model and the multiband melgan in general. To generate speech I seem to need two models, but what their difference is I didnt understand yet.
