### ISSUE TITLE
Automatically generate voice data sets

### ISSUE THREAD

**Issue by rgzn-aiyun** [TensorSpeech/TensorFlowTTS#627]
Use Google or Microsoft Synthetic Platform to generate voice data sets?
Who tested it?
@dathudeptrai

**Comment by rgzn-aiyun** [comment]
Appropriate data sets have been a major obstacle to studying speech synthesis, and the ability to generate the corresponding data sets by relying on major speech synthesis platforms has been a significant advance in studying speech synthesis.

**Comment by dathudeptrai** [comment]
@rgzn-aiyun i don't know what you want to ask :D

**Comment by ZDisket** [comment]
@rgzn-aiyun I mean, you definitely could, but why? This TTS is for generating good human voices, you'd just be copying someone else's already blatantly synthetic voice. Also, with finetuning, you can use way smaller datasets, as I've experimented.

**Comment by rgzn-aiyun** [comment]
> @rgzn-aiyun i don't understand what you want to ask :D

What I'm trying to say is that it is proposed to add multilingual speech synthesis.

**Comment by rgzn-aiyun** [comment]
> @rgzn-aiyun I mean, you definitely could, but why? This TTS is for generating good human voices, you'd just be copying someone else's already blatantly synthetic voice. Also, with finetuning, you can use way smaller datasets, as I've experimented.

You're right, single-language synthesizing sounds are good, but there's a gap in the achievement of language!
