### ISSUE TITLE
Why my training data is so slow

### ISSUE THREAD

**Issue by yukikazenanodesu** [TensorSpeech/TensorFlowTTS#629]
i use 4 NIVDIA TELESLA 100P to train the tacotron2 modle is so slow only 3s/its  be similar to my notebook divice rtx2070 what reasion couse it ？
this is my sever 4 NIVDIA TELESLA 100P
![image](https://user-images.githubusercontent.com/31941796/126624196-38eb03c2-4171-4916-a205-5a024024fb25.png)
this is my notebook rtx2070
![image](https://user-images.githubusercontent.com/31941796/126624486-0dca8c81-e2b4-4557-8702-b91591e5b09d.png)

**Comment by dathudeptrai** [comment]
@yukikazenanodesu because tacotron2 is a sequence2sequence model, and a decode is run sequentially.

**Comment by yukikazenanodesu** [comment]
thanksalot
