### ISSUE TITLE
config length of the melspectrogram input

### ISSUE THREAD

**Issue by linhld0811** [TensorSpeech/TensorflowTTS#63]
When i training tacotron2 model with my own data, some of mel-spetrogram has timestep  > 2000 so I always get this error:

> tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [16,2000,80] vs. [16,2023,80]

I dkn that where to set the timestep to higher value to adapt my data.
Thanks

**Comment by azraelkuan** [comment]
check this： https://github.com/dathudeptrai/TensorflowTTS/blob/493dae65b8b9979b507d87ae8330f956fa5176df/tensorflow_tts/models/tacotron2.py#L723

**Comment by linhld0811** [comment]
I set that to another number but still got this error with timestep = 2000

**Comment by dathudeptrai** [comment]
@linhld0811 try comment out https://github.com/dathudeptrai/TensorflowTTS/blob/master/tensorflow_tts/models/tacotron2.py#L723, it could solve the problem. BTW, i think > 2000 steps is too long, maybe you need consider to move it into evaluation folder if you set "use_fixed_shapes=True" or you can set "use_fixed_shapes=False" to training with dynamic shape, but i'm not sure if dynamic faster than fixed shape (refer https://github.com/dathudeptrai/TensorflowTTS/issues/34#issuecomment-642309118).
