### ISSUE TITLE
from_pretrained() func cannot load local pretrained repo.

### ISSUE THREAD

**Issue by Pavel-Sara** [TensorSpeech/TensorFlowTTS#632]
When I have already downloaded the models and want to load it locally, but the function 'from_pretrained' only tries to download from internet.

**Comment by Pavel-Sara** [comment]
need more testing without internet.

**Comment by dathudeptrai** [comment]
@Pavel-Sara https://github.com/TensorSpeech/TensorFlowTTS/blob/master/test/test_auto.py#L68-L78
