### ISSUE TITLE
How to adjust the speaking speed of tacotron + mb-melgan? Fastspeech2 can be in speed_ Ratios is adjusted here, but where is tacotron adjusted?

### ISSUE THREAD

**Issue by yukikazenanodesu** [TensorSpeech/TensorFlowTTS#634]
![image](https://user-images.githubusercontent.com/31941796/127469669-6cdd4d95-f023-4a76-8e3d-85be25c844c7.png)
![image](https://user-images.githubusercontent.com/31941796/127469703-79a078a2-404d-4010-a8c0-7bff4658e042.png)

**Comment by yukikazenanodesu** [comment]
I didn't find a place to adjust its parameters with tacotron2 ？

**Comment by ZDisket** [comment]
@yukikazenanodesu Tacotron2 doesn't have speed controls. You're gonna have to either use FastSpeech2 or speed up the resulting waveform with audio editing.

**Comment by TheHonestBob** [comment]
> I didn't find a place to adjust its parameters with tacotron2 ？

you can use sonic, but you have to package it if you use python
