### ISSUE TITLE
Tacotron2 does not work for multi-speaker

### ISSUE THREAD

**Issue by iamanigeeit** [TensorSpeech/TensorFlowTTS#638]
I've tried doing inference on multi-speaker data and it fails for any `speaker_id != 0`. The `mel_outputs` terminates early and no audio is produced.

    decoder_output, mel_outputs, stop_token_prediction, alignment_history = tacotron2.inference(
            tf.expand_dims(tf.convert_to_tensor(input_ids, dtype=tf.int32), 0),
            tf.convert_to_tensor([len(input_ids)], tf.int32),
            tf.convert_to_tensor([speaker_id], dtype=tf.int32)  # anything other than 0 will fail
    )

On `speaker_id = 0`, the audio is averaged over all speakers and doesn't reflect the speaker's voice.

The only thing i note is that the norm of the speaker embeddings is much bigger for speaker 0 than all the other speakers (1.8+ vs 0.3+). For comparison, norms of the character embeddings are all between 3 to 4.

From what i can see in `tacotron_dataset.py`, in `_load_data()`, you've hard-coded `speaker_id: 0`, so multi-speaker training data will not work.

**Comment by ZDisket** [comment]
@iamanigeeit That's correct. You need to modify the dataloader to load your data and provide a `speaker_id`. Here's an [example](https://github.com/ZDisket/TensorflowTTS/blob/tac2msv2/examples/tacotron2/tacotron_dataset.py).

**Comment by iamanigeeit** [comment]
@ZDisket Thanks for this! Writing a separate file containing 1 `speaker_id` for each utterance seems like overkill, so i will likely just put everything in a single file.

**Comment by ZDisket** [comment]
@iamanigeeit Yes, it is. At the time it was a quick and dirty solution, but do feel free to do better.
