### ISSUE TITLE
About resampled ljspeech

### ISSUE THREAD

**Issue by ttsking** [TensorSpeech/TensorFlowTTS#648]
I have a customized dataset like ljspeech, except the sampling-rate is 24000.

for the preprocess configuration based on ljspeech_preprocess.yaml, besides modifying sampling_rate from 22500 to 24000, should i modify hop_size from 256 to 300, and how about fft_size. I' m new for tacotron, i didn't find any reference content on this.

**Comment by ZDisket** [comment]
There is already a preprocessing config for 24KHz: https://github.com/TensorSpeech/TensorFlowTTS/blob/master/preprocess/libritts_preprocess.yaml
Yes, `hop_size` to 300. FFT size remains the same.

**Comment by ttsking** [comment]
Ok, thanks for your quick responds. I have tested the config provided. It's work. Thanks you two again.
