### ISSUE TITLE
speech voice speed

### ISSUE THREAD

**Issue by jialesmu** [TensorSpeech/TensorFlowTTS#649]
thanks for the project, I tried the demo and seems the voice speed is a little bit too fast, is there any way to control the voice speed?

**Comment by dathudeptrai** [comment]
@jialesmu what is a model you are using ?

**Comment by jialesmu** [comment]
> @jialesmu what is a model you are using ?

tensorspeech/tts-tacotron2-baker-ch

this one~

**Comment by dathudeptrai** [comment]
@jialesmu it's not easy to control speed in tacotron2, if you want to do this, let use FS2 that supports control speed through `speed_ratios`.

**Comment by jialesmu** [comment]
Thanks for your help~
