### ISSUE TITLE
Train Multi-speaker  Fastspeech2  with same transcription

### ISSUE THREAD

**Issue by zhangsanfeng86** [TensorSpeech/TensorFlowTTS#650]
Hi @dathudeptrai,
There are 5000 transcriptions,and speak by 5 speakers.
Then record 25000 wavs.  The transcriptions of each speaker are the same.
When feed them into FS2 training, got a error.  
I guess the "same transcription" cause the error
How could I solve this problem?
The error as follow:
![image](https://user-images.githubusercontent.com/73547638/129925186-a583355c-e8aa-4761-a2b7-5589947d6822.png)

**Comment by zhangsanfeng86** [comment]
If only feed data of one speaker  into FS2, due to all the transcriptio are different ,the training process is OK.

**Comment by zhangsanfeng86** [comment]
@dathudeptrai  Could help to check : the "outputs" and "repeat_encoder_hidden_states"  in shape 1 is different.

https://github.com/TensorSpeech/TensorFlowTTS/blob/acf3dac1301958431e17ba6f3616dbcaa522ee1c/tensorflow_tts/models/fastspeech.py#L705

**Comment by dathudeptrai** [comment]
@zhangsanfeng86 The shape is different because the duration is wrong, you must ensure that sum(duration) == len(mel) for each sample.

**Comment by zhangsanfeng86** [comment]
@dathudeptrai Thank you for your quick reply!
1. I have check the sum for duration and len of mel, it equal. the code as follow
2. 
`  1 import numpy as np
  2 import os
  3 
  4 wav_list = os.listdir("norm-feats/")
  5 dur_list = os.listdir("durations")
  6 for i in wav_list:
  7     wavs = np.load("norm-feats/" + i)
  8     dur = np.load("durations/" + i[:6] + "-durations.npy")
  9     if np.sum(dur)!=len(wavs):
 10         print(i)
 11         print(i[:6])
 12         break
 13 
`
it print nothing.

2.  where should I insert your code to check the wrong sample?

**Comment by dathudeptrai** [comment]
@zhangsanfeng86 here, before training https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/fastspeech2/train_fastspeech2.py#L402

**Comment by zhangsanfeng86** [comment]
it got an error,as follow:
![image](https://user-images.githubusercontent.com/73547638/130318286-d9aee699-b6b6-4b5a-8f8a-f465c555fbe6.png)


![image](https://user-images.githubusercontent.com/73547638/130318279-8193c945-79a9-47c4-8697-c8220ad63aea.png)

**Comment by dathudeptrai** [comment]
@zhangsanfeng86 the code above is just an example code :D. The exactly code should be 

```
fastspeech2(**data, training=True)
```

**Comment by zhangsanfeng86** [comment]
@dathudeptrai Thank you!
