### ISSUE TITLE
Colab notebook not working

### ISSUE THREAD

**Issue by TarasevichArtem** [TensorSpeech/TensorFlowTTS#653]
When trying to run the main demo in Colaboratory (https://colab.research.google.com/drive/1akxtrLZHKuMiQup00tzO2olCaN-y3KiD?usp=sharing), I get an error importing tensorflow.
ImportError                               Traceback (most recent call last)
<ipython-input-5-06a1fb1092f3> in <module>()
----> 1 import tensorflow as tf
      2 
      3 import yaml
      4 import numpy as np
      5 import matplotlib.pyplot as plt

5 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/__init__.py in <module>()
    172 
    173 # Normalization layers.
--> 174 from tensorflow.python.keras.layers.normalization import LayerNormalization
    175 from tensorflow.python.keras.layers.normalization_v2 import SyncBatchNormalization
    176 

ImportError: cannot import name 'LayerNormalization' from 'tensorflow.python.keras.layers.normalization' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/normalization/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by ZDisket** [comment]
@TarasevichArtem 
It's a fairly recent bug with Google Colaboratory, looks like the environment doesn't take kindly to having its Tensorflow version replaced anymore. Thankfully, we can infer (and train) just fine with Tensorflow 2.6.0, the latest release. I don't have write access to the original E2E notebook, but here's my copy that you can use for now: https://colab.research.google.com/drive/1FKru64jgtkCuSavlGO3YdQtzLG7Qpbcb?usp=sharing

**Comment by dathudeptrai** [comment]
@ZDisket i can upgrade the pip requirements to install latest tf version if someone confirm that it work just fine :D

**Comment by ZDisket** [comment]
@dathudeptrai While maintaining training and testing notebooks for a community I tested both fastspeech2 with mixed precision, multi band melgan with hifigan discriminator train and infer on tf 2.6.0, all works fine, only that it gives some warnings. I haven't tested tacotron2 train but I am 99.99% sure there shouldn't be a problem

**Comment by dathudeptrai** [comment]
@ZDisket okay, i will upgrade to tf2.6 in the next release and if there is a bug , i will fix =))
