### ISSUE TITLE
pretained model saving path

### ISSUE THREAD

**Issue by jialesmu** [TensorSpeech/TensorFlowTTS#654]
thanks for your help, I tried the demo and saw some downloading while 
`fastspeech2 = TFAutoModel.from_pretrained("tensorspeech/tts-fastspeech2-ljspeech-en")`
this run, however I can't find the download's saving path, it seems downloads a model and loaded it
where does the model saved with these downloads?
thanks !

**Comment by dathudeptrai** [comment]
@jialesmu the pretrained model in `home/.cache/tensorflow_tts/`. BTW, after loads model, you can save its pretrained then reload it as the code here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/test/test_auto.py#L72-L78)

**Comment by jialesmu** [comment]
> @jialesmu the pretrained model in `home/.cache/tensorflow_tts/`. BTW, after loads model, you can save its pretrained then reload it as the code here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/test/test_auto.py#L72-L78)

thank you very much~ It solves my problem!
