### ISSUE TITLE
how to add clipnorm in the multiband melgan training ?

### ISSUE THREAD

**Issue by yingfenging** [TensorSpeech/TensorFlowTTS#657]
Hello, when I run the multiband melgan, I add the clipnorm in the "gen_optimizer", like this
```
        gen_optimizer = tf.keras.optimizers.Adam(
            learning_rate=generator_lr_fn,
            amsgrad=config["generator_optimizer_params"]["amsgrad"],
           clipnorm=1.0,
        ) 
```
it  report error  as blow
_Gradient clipping in the optimizer (by setting clipnorm or clipvalue) is currently unsupported when using a distribution strategy._

I check my code, and the GPU's number is 1, and "STRATEGY = tf.distribute.OneDeviceStrategy(device="/gpu:0")".

How can I add the clipnorm in the training ?
Thanks in advance.

**Comment by dathudeptrai** [comment]
@yingfenging I do not know but Tacotron2/FastSpeech2 can be applied clipnorm without any problems. See here (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/optimizers/adamweightdecay.py#L124)

**Comment by yingfenging** [comment]
@dathudeptrai   ok，thanks. I will try it.
