### ISSUE TITLE
Can't  save  the SavedModel of FastSpeech2

### ISSUE THREAD

**Issue by tongtianchedi** [TensorSpeech/TensorFlowTTS#661]
Hi, experts,
when I try to save the SavedModel of FastSpeech2, I modified both parts of the code:

In the script of fastspeech2.py:
```
class TFFastSpeech2(TFFastSpeech):
    ...
    @tf.function 
    def call(
        self,
        input_ids,
        speaker_ids,
        duration_gts,
        f0_gts,
        energy_gts,
        training=False,
        **kwargs,
    ):
    ...
```

In the script of train_fastspeech2.py:
```
...
 trainer.compile(model=fastspeech, optimizer=optimizer)
    try:
        trainer.fit(
            train_dataset,
            valid_dataset,
            saved_path=os.path.join(config["outdir"], "checkpoints/"),
            resume=args.resume,
        )
        tf.saved_model.save(fastspeech,'cpu_saved_model', signatures=fastspeech.call.get_concrete_function([ #add
                tf.TensorSpec(shape=[None, None], dtype=tf.int32, name="input_ids"),
                tf.TensorSpec(shape=[None,], dtype=tf.int32, name="speaker_ids"),
                tf.TensorSpec(shape=[None,], dtype=tf.float32, name="speed_ratios"),
                tf.TensorSpec(shape=[None,], dtype=tf.float32, name="f0_ratios"),
                tf.TensorSpec(shape=[None,], dtype=tf.float32, name="energy_ratios")
            ]))
 ...
```

but error occurs:

Traceback (most recent call last):
  File "examples/fastspeech2/train_fastspeech2.py", line 442, in <module>
    main()
  File "examples/fastspeech2/train_fastspeech2.py", line 421, in main
    tf.saved_model.save(fastspeech,'cpu_saved_model', signatures=fastspeech.call.get_concrete_function([
AttributeError: 'function' object has no attribute 'get_concrete_function'

How can I do? Could you help me?
Thank you very much.

**Comment by dathudeptrai** [comment]
https://github.com/TensorSpeech/TensorFlowTTS/blob/master/notebooks/fastspeech2_inference.ipynb
