### ISSUE TITLE
how to fine tune on unseen speakers small dataset?

### ISSUE THREAD

**Issue by Pydataman** [TensorSpeech/TensorFlowTTS#663]

**Comment by ZDisket** [comment]
@Pydataman I recommend formatting your dataset in the same format that one of the built in processors takes (like LJSpeech), then starting training of your preferred models with the` --pretrained` argument

**Comment by Pydataman** [comment]
> @Pydataman I recommend formatting your dataset in the same format that one of the built in processors takes (like LJSpeech), then starting training of your preferred models with the` --pretrained` argument and a pretrained .h5 weights file

@ZDisket  thx,   Is it fine tune on any speaker ID?
