### ISSUE TITLE
extract duration for fastspeech2

### ISSUE THREAD

**Issue by karrdy89** [TensorSpeech/TensorFlowTTS#664]
Hello.
Thanks for the great repo.
I am trying to train a pre-trained fastspeech2 model(kss).
It seems that a duration is needed for learning, which can be extracted by training a tacotron.
I have a question here. isn't the duration necessary for learning tacotron2? also, how many epoch is required for accurate extraction?

**Comment by dathudeptrai** [comment]
@karrdy89 you need training tacotron2 to extract duration for fs2. Around 50k-80k is good enough for extract duration.

**Comment by karrdy89** [comment]
I get it.
Thanks for the reply :)

**Comment by Pydataman** [comment]
> @karrdy89 you need training tacotron2 to extract duration for fs2. Around 50k-80k is good enough for extract duration.

if there is small unseen speaker data, hot to extract duration info?

**Comment by zheng-xing** [comment]
> @karrdy89 you need training tacotron2 to extract duration for fs2. Around 50k-80k is good enough for extract duration.

Hi @dathudeptrai, I have a question, if I understand correctly, the fs2 paper suggest it does not require a teacher model to extract durations as fs1 do, right?
