### ISSUE TITLE
Question for chinese text to voice

### ISSUE THREAD

**Issue by jialesmu** [TensorSpeech/TensorFlowTTS#666]
First of all, thanks again for your amazing work.
I tried several models, and there is one problem when I deal with Chinese words.
The polyphone characters will produce same pronunciation in result which it should give different pronunciation, is there any way to fix this problem?
for example,word 乐, can pronounced like 'le' means happy; however this word also can pronounced like 'yue' means music.
Thanks

**Comment by dathudeptrai** [comment]
@azraelkuan

**Comment by dathudeptrai** [comment]
@azraelkuan

**Comment by OnceJune** [comment]
sounds like your frontend gives wrong pronunciation prediction, can you print the network input?

**Comment by azraelkuan** [comment]
@jialesmu, in this repo, we do not have a polyphone model to judge this, because we do not have such data.
if u want to train a  polyphone  model, u can buy data from databaker and train a model like [g2pM](https://github.com/kakaobrain/g2pM).

**Comment by jialesmu** [comment]
> @jialesmu, in this repo, we do not have a polyphone model to judge this, because we do not have such data.
> if u want to train a polyphone model, u can buy data from databaker and train a model like [g2pM](https://github.com/kakaobrain/g2pM).

Thanks for your suggestion, I will try g2pM~
