### ISSUE TITLE
LibriTTS out-of-box produces incoherent speech

### ISSUE THREAD

**Issue by shachar-ug** [TensorSpeech/TensorFlowTTS#667]
Using out of the box training produces results that are not forming coherent words.
Initially running prepare_libri.ipnb with 20 speakers, then running as MFA instructed, I encountered size mismatches, to which I saw running tacotron's extract_duration.py should resolve - and it has.

So running

``` 
    bash ttsexamples/mfa_extraction/scripts/prepare_mfa.sh
    python ttsexamples/mfa_extraction/run_mfa.py --corpus_directory ./libritts --output_directory ./mfa/parsed --jobs 8
    python ttsexamples/mfa_extraction/txt_grid_parser.py \
  --yaml_path ttsexamples/fastspeech2_libritts/conf/fastspeech2libritts.yaml \
  --dataset_path ./libritts \
  --text_grid_path ./mfa/parsed \
  --output_durations_path ./libritts/durations \
  --sample_rate 24000 

    tensorflow-tts-preprocess --rootdir ./libritts \
  --outdir ./dump_libritts \
  --config preprocess/libritts_preprocess.yaml \
  --dataset libritts
    
    tensorflow-tts-normalize --rootdir ./dump_libritts \
  --outdir ./dump_libritts \
  --config preprocess/libritts_preprocess.yaml \
  --dataset libritts

```
-> running the MFA since it generates the train.txt required later

and then extracting durations (for train and valid)
```
CUDA_VISIBLE_DEVICES=0 python ttsexamples/tacotron2/extract_duration.py \
  --rootdir ./dump_libritts/train/ \
  --outdir ./dump_libritts/train/durations/ \
  --checkpoint ./ttsexamples/tacotron2/exp/train.tacotron2.v1/checkpoints/model-120000.h5 \
  --use-norm 1 \
  --config ./ttsexamples/tacotron2/conf/tacotron2.v1.yaml \
  --batch-size 32 \
  --win-front 3 \
  --win-back 3

```

and finally running

`bash ttsexamples/fastspeech2_libritts/scripts/train_libri.sh`

This ultimately does not generate proper speech, testing with the libritts pretrained vocoder (nor other vocoders)

```
config = AutoConfig.from_pretrained("../pretrained/mbvocs24k/multiband_melgan.v1_24k.yaml")
mb_melgan = TFAutoModel.from_pretrained(
    config=config, 
    pretrained_path='../pretrained/mbvocs24k/libritts_24k.h5', # "../examples/fastspeech2/checkpoints/model-150000.h5",
    name="melgan"
)
```
Notes: I've changed the hop size to 300 in the yaml configurations according to previous issues.

Would appreciate any hint on what is going on/what's wrong.
Would love to upload and contribute a generated model at the end

**Comment by shachar-ug** [comment]
@OscarVanL , I saw you had some success with it?

**Comment by ZDisket** [comment]
@shachar-ug What Tacotron2 model are you using for extracting durations? It has to match the exact same dataset you're trying to train it on.

**Comment by shachar-ug** [comment]
@ZDisket That's a good pointer, thanks

I donwloaded from the [link](https://drive.google.com/drive/folders/1FQG8XC5c5JJ0jpCUl7Oqu5u2fC8IarP3) in the [tacotron2 page](https://github.com/TensorSpeech/TensorFlowTTS/blob/ba46b472f99b09bbdfc6b9261626c10fb2f2be14/examples/tacotron2/README.md)

which I now see is trained for LJspeech. 

So my questions would be 

1. Is there one trained for LibriTTS or do I need to train it?
2. Shouldn't mfa extraction suffice? Asking as using it, and trying to run, there were size mismatches errors in training

**Comment by shachar-ug** [comment]
@ZDisket since I see no libritts-tacotron2 in this repo, I figured I might as well train my own

if I'm not missing anything, I just generated tacotron2.libritts.v1.yaml with tacotron2_params: dataset: libritts parameter and then ran

`CUDA_VISIBLE_DEVICES=0,1 python ttsexamples/tacotron2/train_tacotron2.py   --train-dir ./dump_libritts/train/   --dev-dir ./dump_libritts/valid/   --outdir ./ttsexamples/tacotron2/exp/train.tacotron2.libritts.v1/   --config ./ttsexamples/tacotron2/conf/tacotron2.libritts.v1.yaml   --use-norm 1   --mixed_precision 0   --resume ""
`
with 2 V100 gpus

This is of course, after running the libri experiment ipynb notebook to generate the dump folder in the first place. 

Am I missing anything?
