### ISSUE TITLE
Which vocoder for training multi-speaker dataser?

### ISSUE THREAD

**Issue by ymzlygw** [TensorSpeech/TensorFlowTTS#668]
Hi , I  see many vocoder implementation in your project. 
I want to train a vocoder on **multi-speaker dataset,** which vocoder can be used for it?
 And the mel-files (containing **audio.npy and mels.npy, mels.npy is generated by Tacotron** )in dataset that I want to  use is from RTVC-project:https://github.com/CorentinJ/Real-Time-Voice-Cloning.

**Comment by dathudeptrai** [comment]
@ymzlygw you can use multiband melgan for training multi-speaker :D

**Comment by ymzlygw** [comment]
> @ymzlygw you can use multiband melgan for training multi-speaker :D

Thanks for your suggestion. How about Mel-GAN? Could you tell me why use MB-MelGAN not Mel-GAN ?

**Comment by ZDisket** [comment]
@ymzlygw Use HiFi-GAN for multispeaker. The MPD is very helpful in that regard (or you can combine mb-melgan with hifi-gan discriminator)
>How about Mel-GAN? Could you tell me why use MB-MelGAN not Mel-GAN ?

MB-MelGAN is preferable to MelGAN simply because it is faster and better. But if you're using multispeaker or want your model to be finetuneable HiFi-GAN's training strategy works much better.

**Comment by ymzlygw** [comment]
> @ymzlygw Use HiFi-GAN for multispeaker. The MPD is very helpful in that regard (or you can combine mb-melgan with hifi-gan discriminator)
> 
> > How about Mel-GAN? Could you tell me why use MB-MelGAN not Mel-GAN ?
> 
> MB-MelGAN is preferable to MelGAN simply because it is faster and better. But if you're using multispeaker or want your model to be finetuneable HiFi-GAN's training strategy works much better.

**Thanks!   And Could you help me with followings two questions?**
1.   Because I have preprocessed the data and can get the  **wav.npy path** and corresponding **mel.npy path** from metadata by index, so in config["format"] , I just need to change the audio_query and mel_query to the path, right?

if config["format"] == "npy":
        audio_query = "*-wave.npy"
        mel_query = "*-raw-feats.npy" if args.use_norm is False else "*-norm-feats.npy"
        audio_load_fn = np.load
        mel_load_fn = np.load
    else:
        raise ValueError("Only npy are supported.")

2. How can I know if my generated  mel.npy is **use_norm** or **raw**? It's just from the output of Tacotron and saved to .npy

**Comment by ymzlygw** [comment]
@ZDisket  Could you please tell me about this ?
'Generator function should return [audio, mel]'----Here **'audio'** means raw audio wav file with npy format, and **'mel'** means mel-gta.npy that  generated from tts model , not from ground truth of audio file. Right?

**Comment by ZDisket** [comment]
@ymzlygw Normally it's ground truth mel, but if you have GTA mels (or postnets, as I call them) then it's better to use them.

**Comment by ymzlygw** [comment]
> @ymzlygw Normally it's ground truth mel, but if you have GTA mels (or postnets, as I call them) then it's better to use them.

OK, Thanks !
