### ISSUE TITLE
The outliers are replaced by max, not by mean in outliers.py

### ISSUE THREAD

**Issue by yanglin187** [TensorSpeech/TensorFlowTTS#669]
In the file: utils/outliers.py

    # replace by mean f0.
    x[indices_of_outliers] = np.max(x)

all the outliers are replaced by max, not by mean ?

**Comment by dathudeptrai** [comment]
@yanglin187 seems it is a bug, but i think it doesn't affect the general performance so I will keep it for backward compatibility.
