### ISSUE TITLE
Can I do based on TensorFlow with DirectML to work with AMD video cards?

### ISSUE THREAD

**Issue by pin240** [TensorSpeech/TensorFlowTTS#671]
Сan I do it on the basis of Tensorflow with DirectML to work with AMD graphics cards? CPUs are slow and Nvidia cards are almost unavaimable.
I have 3 AMD graphics cards (2pcs - R9 Nano and Vega64) and a big 19GB set.(audio)
I'm even willing to give it up for common use.
As I understood, you need a video card with CUDA for training, but I do not have one. A lot of rummaging through the Internet and ran into an article
https://docs.microsoft.com/en-us/windows/ai/directml/gpu-tensorflow-windows
Is it difficult to remake for it and train the model?
How to train a model for Russian language?

**Comment by dathudeptrai** [comment]
@pin240 I don't know, not try yet :D

**Comment by pin240** [comment]
@dathudeptrai  
Sad (  
I hope in the future you will have free time to do this.
