### ISSUE TITLE
The Chinese model does not break sentences

### ISSUE THREAD

**Issue by crystal-lee** [TensorSpeech/TensorFlowTTS#678]
I deployed a TTS service according to this document 
```
https://colab.research.google.com/drive/1YpSHRBRPBI7cnTkQn1UcVTWEQVbsUm1S?usp=sharing#scrollTo=hKTW94-bWK8O
```
but it does not break sentences and does not speak letters and numbers。

who can help me ? Give me a perfect Chinese model, or teach me how to train such a model。

thanks!!!

**Comment by dathudeptrai** [comment]
@azraelkuan
