### ISSUE TITLE
Does hop_size in tacotron2 conf have any impact?

### ISSUE THREAD

**Issue by iamanigeeit** [TensorSpeech/TensorFlowTTS#679]
I see that in `baker_preprocess.yaml` the hop size is 300, but in `tacotron2.baker.v1.yaml` the hop size is 256. My understanding is the hop size in `preprocess` should be adjusted according to sample rate, but should we also change the tacotron conf? I cannot find anywhere that uses the tacotron conf hop size.

**Comment by dathudeptrai** [comment]
@iamanigeeit the hop_size in Tacotron2 conf doesn't have any impact

**Comment by ZDisket** [comment]
@iamanigeeit From what I've been told, `hop_size` in Tacotron2 changes horizontal resolution of the spectrogram. Lower = higher quality, but more compute heavy. This is in relation to `hop_size` of the vocoder (which has to be adjusted for sampling rate); if it is equal, then it's the standard 12.5ms. So 256 hop size vocoder with 256 hop_size Tacotron2 is the same as 512 hop size vocoder with 512 hop_size Tacotron2

**Comment by iamanigeeit** [comment]
@ZDisket Thanks for the reply, but since Tacotron2 only outputs the spectrogram and does not have a vocoder, can i assume `hop_size` is merely to inform vocoders of the horizontal resolution? That is, it has no function in the Tacotron code?
