### ISSUE TITLE
No module named 'german_transliterate'

### ISSUE THREAD

**Issue by Sahanaka** [TensorSpeech/TensorFlowTTS#682]
**from tensorflow_tts.inference import AutoProcessor**

This line fails due to the Error **No module named 'german_transliterate'**

**Comment by dathudeptrai** [comment]
pip install git+https://github.com/repodiac/german_transliterate.git#egg=german_transliterate @Sahanaka

**Comment by Sahanaka** [comment]
> pip install git+https://github.com/repodiac/german_transliterate.git#egg=german_transliterate @Sahanaka

@dathudeptrai thank you for your help. But shouldn't TensorSpeech get rid of this dependency? From the looks of it, this package  (german_transliterate) is not properly maintained.

**Comment by yangboz** [comment]
> pip install git+https://github.com/repodiac/german_transliterate.git#egg=german_transliterate

 File "/home/xibaoda/anaconda3/envs/py37metaavatar/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py", line 361, in __init__
    len(labels), name, description, *labels)
  File "/home/xibaoda/anaconda3/envs/py37metaavatar/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
any idea?

**Comment by Sahanaka** [comment]
What is your TensorFlow version? I used TensorFlow 2.6.0, it resolved the issues I faced

**Comment by yangboz** [comment]
> What is your TensorFlow version? I used TensorFlow 2.6.0, it resolved the issues I faced

maybe 2.8.0， and I tried reinstall again  and it works now

**Comment by Sahanaka** [comment]
You mean it worked for tf version 2.8.0?

**Comment by yangboz** [comment]
> You mean it worked for tf version 2.8.0?

yes tensorflow==2.8.0

**Comment by Sahanaka** [comment]
> 

That is good to know I think the version issues are now resolved then :)

**Comment by yangboz** [comment]
> > 
> 
> That is good to know I think the version issues are now resolved then :)

to be verified.

**Comment by zhenyucui11** [comment]
what is wrong?

> pip install git+https://github.com/repodiac/german_transliterate.git#egg=german_transliterate @Sahanaka
Collecting german_transliterate
  Cloning https://github.com/repodiac/german_transliterate.git to c:\users\409\appdata\local\temp\pip-install-t80tsgyc\german-transliterate_c74ae3c675ce4d65b65ac20bc15d7ba6
  Running command git clone --filter=blob:none --quiet https://github.com/repodiac/german_transliterate.git 'C:\Users\409\AppData\Local\Temp\pip-install-t80tsgyc\german-transliterate_c74ae3c675ce4d65b65ac20bc15d7ba6'
  fatal: unable to access 'https://github.com/repodiac/german_transliterate.git/': Failed to connect to 127.0.0.1 port 6590 after 2049 ms: Couldn't connect to server
