### ISSUE TITLE
Preprocessing German multi-speaker dataset for training FastSpeech2

### ISSUE THREAD

**Issue by Mareike-RTY** [TensorSpeech/TensorFlowTTS#683]
Hi, I would like to train the FastSpeech2 model on a German multi-speaker dataset (4 speakers, 13 hours of audio material for now). Following [this](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2_libritts) guide, I have triggered preprocessing using `thorsten_preprocess.yaml` as config and the `libritts` processor as `--dataset` argument. For this purpose, I have adjusted the `libritts.py` processor based on the `thorsten.py` processor because of my German-language dataset. 

When triggering preprocessing with this command:
```
%cd /home/mp/TensorFlowTTS/
!tensorflow-tts-preprocess --rootdir /home/mp/TensorFlowTTS/tftts_data/train_val \
--outdir ./dump \
--config preprocess/thorsten_preprocess.yaml \
--dataset libritts
```

I get the following KeyError:
```
/home/mp/TensorFlowTTS
2021-10-01 10:19:49.692503: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-10-01 10:19:50,957 (preprocess:373) INFO: Selected 'libritts' processor.
2021-10-01 10:19:50,976 (preprocess:412) INFO: Training items: 6481
2021-10-01 10:19:50,976 (preprocess:413) INFO: Validation items: 342
[Preprocessing train]:   0%|                           | 0/6481 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/tensorflow/bin/tensorflow-tts-preprocess", line 8, in <module>
    sys.exit(preprocess())
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow_tts/bin/preprocess.py", line 446, in preprocess
    for result, mel, energy, f0, features in train_map:
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/opt/anaconda3/envs/tensorflow/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
KeyError: '@Solange'
```
 
However, when I use the `thorsten` processor as `--dataset` argument, the preprocessing runs perfectly well, but it's not set up for multi-speaker from what I understand (and afterwards, the duration file is missing in the `dump` folder so that I would have to train Tacotron2 to extract the durations.)

Could you please point me in the right direction and tell me, for example, if using the `thorsten` processor is fine despite a multi-speaker dataset, or is adjusting the `libritts` processor the right thing to do (and if so, what might cause the error? I can't find the error's cause in the scripts listed in the above error message). 

Thank you very much for any help!

**Comment by dathudeptrai** [comment]
@monatis can you help ?

**Comment by ZDisket** [comment]
@Mareike-RTY `thorsten `processor is okay for multi-speaker, but you need to modify dataloader to load your `speaker_id `from files you must manually create: https://github.com/TensorSpeech/TensorFlowTTS/blob/cd3a5e1f9915fa7dd646771fd50fe6fef94fe9fc/examples/fastspeech2/fastspeech2_dataset.py#L176

**Comment by Mareike-RTY** [comment]
@ZDisket Thank you very much for your guidance. I will do so!
