### ISSUE TITLE
License question -> Follow-up

### ISSUE THREAD

**Issue by albertswiecicki** [TensorSpeech/TensorFlowTTS#689]
Dear creators,
I work in a multinational company, and I write to you on behalf of my team. 
We would like to use and contribute to TensorflowTTS, but we cannot due to a non-standard license.
I saw that a similar question #279  was asked over a year ago, and I wonder if something has changed since then.

We believe that we are not the only ones interested in using and contributing to this repository that are constrained by the license.

**Comment by dathudeptrai** [comment]
@albertswiecicki i will change the license soon :D
