### ISSUE TITLE
install error  (llvmlite error)

### ISSUE THREAD

**Issue by lianghongyi** [TensorSpeech/TensorFlowTTS#690]
I tried to install this project on window10, I have tried to install this on two different machine.But this problem always happen.
what can I do?

![image](https://user-images.githubusercontent.com/812418/137911251-3540392d-30ef-47f4-8854-c90147199d33.png)

**Comment by lianghongyi** [comment]
still have no clue....

**Comment by yorkshiremaster** [comment]
I had the same issue with python 3.9.
Finally, I downgrade python to 3.7.4 to fix it.
