### ISSUE TITLE
Not able to generate train.txt file to run multi-speaker libritts for FastSpeach 2 

### ISSUE THREAD

**Issue by hasnin24** [TensorSpeech/TensorFlowTTS#696]
I tired to use MFA based extraction for FastSpeech2 on Windows 10 but I kept getting:

    OSError: [WinError 193] %1 is not a valid Win32 application 

    when running:
      python examples/mfa_extraction/run_mfa.py \
        --corpus_directory ./libritts \
        --output_directory ./mfa/parsed \
        --jobs 8
I was wondering what is the format for train.txt. In the comments  section for /examples/fastspeech2_libritts says the format should be like this:  

    Wav Path | Text | Speaker Name
    Wav Path2 | Text | Speaker Name

however, no matter what I do I keep getting an error when I preprocess my data using this command: 

     tensorflow-tts-preprocess --rootdir ./libritts --outdir ./dump_libritts --config preprocess/libritts_preprocess.yaml --dataset 
     libritts --n_cpus 16

The error when I run the above command: 

      File "c:\users\user\anaconda3\envs\tts\lib\multiprocessing\pool.py", line 867, in next
          raise value
      KeyError: '@he'

sample of the train.txt I created following the recommended format:  

    55/LJ001-0002 | in being comparatively modern | 55
    22/LJ048-0006 | or to the vice president, end quote | 22

**Comment by ZDisket** [comment]
@hasnin24 I see you're using Windows, you should try Linux.

**Comment by hasnin24** [comment]
> @hasnin24 I see you're using Windows, you should try Linux.

I was able to run it on google colab!!! Thanks for replying. I do have one quick question, is there any way I add a new voice to an existing one for FB2 if so is there any docs to follow? thanks again.
