### ISSUE TITLE
How to reduce the complexity of melgan's model and accelerate the inference of the model?

### ISSUE THREAD

**Issue by X-CCS** [TensorSpeech/TensorFlowTTS#699]
+ Hi! I transferred `fs2 + melgan` to `tflite` model and deployed it to mobile devices. I found that the inference of `melgan` model was too complex and occupied too much `CPU` resources.I'd like to ask you what can reduce the complexity of `melgan` model.
+ I think it should be summarized into the following points
    + (1).Without affecting the effect, can we remove some network layers of `melgan` and look at the model structure and don't know which layers can be removed?
    + (2).Are there other tools that can further compress the `tflite` model?
    + (3).Is there any other better `vocoder` that can be applied to the mobile terminal?

**Comment by dathudeptrai** [comment]
@X-CCS maybe you need try float16 or int8 for melgan model ?. In my case, melgan is fast (actually MB-melgan), and the CPU resources needed are low.

**Comment by X-CCS** [comment]
+ thank you！ @dathudeptr 
+ I tried the `float16` method. Although it has been reduced a lot, I expect it to be smaller. Now I'm trying to do it in the `int8` way. I refer to [this scheme](https://www.tensorflow.org/lite/performance/post_training_integer_quant) to convert the`.h5` model into `int8` model, and the generation is always unsuccessful. Would you like to ask if you have a ready-made scheme for reference: convert the`.h5` model to the `int8` model of tflite?
