### ISSUE TITLE
training fastspeech2 from scratch on a new dataset

### ISSUE THREAD

**Issue by MostafaAlaviyan** [TensorSpeech/TensorFlowTTS#701]
hi
thanks for the valuable repository.
I want to train fastspeech2 from scratch on a Persian dataset, but it is expressed that  ''Right now we only support ljspeech, kss, baker, libritts, thorsten and synpaflex for dataset argument. In the future, we intend to support more datasets.'' on the main page of the repo.
now, how can I train the model on my dataset?
best regards
@ZDisket

**Comment by ZDisket** [comment]
@MostafaAlaviyan 
It only supports those datasets out of the box, but you can add your own by analyzing how they're implemented and adding your own. I trained on a Spanish dataset, it's easy.

**Comment by MostafaAlaviyan** [comment]
thanks a lot, can u  explain the way of defining a new dataset to the main repo clearly? where do I add the dataset? and how to add it?
@ZDisket

**Comment by v-nhandt21** [comment]
Hi @ZDisket , do you know any publish Spanish dataset for training TTS?
