### ISSUE TITLE
The result of training fs2 + mb_melgan on baker and LJspeech is not good.

### ISSUE THREAD

**Issue by TheHonestBob** [TensorSpeech/TensorFlowTTS#702]
I have tried to train fs2+mb_melgan on baker and LJspeech at the same time, baker speaker id is 0 and LJspeech speaker id is 1. my conf is follow: sampling_rate: 22050, fft_size: 2048, hop_size: 300, win_length: 1200, MFA create duration file，speaker 0 or speaker 1 is good at chinese or english, I want speaker 0 or speaker 1 to be good at english or chinese, can I train a good model by this way? I hope to get some suggestions， thanks a lot.

**Comment by ZDisket** [comment]
@TheHonestBob You're training a two-speaker, two language model, and you want both speakers to be good at the two languages despite only speaking one language per speaker? Not sure whether it'll work out.

**Comment by TheHonestBob** [comment]
Thank you for your reply，I’m not sure whether conf has effect，I'll try
