### ISSUE TITLE
Support Voice-Clone for multi-speaker dataset?

### ISSUE THREAD

**Issue by ymzlygw** [TensorSpeech/TensorFlowTTS#705]
HI, Thanks for your work and , could you please tell me if you have any implementation for voice-clone using multi-speaker dataset? Or some advice about how to merge your work with the synthesizer in [Real-Time-Voice-Cloning](https://github.com/CorentinJ/Real-Time-Voice-Cloning). I aims to convert  a voice-clone model to tflite and test the performence.
Really thanks and waiting for your reply!

**Comment by ymzlygw** [comment]
> https://github.com/clovaai/voxceleb_trainer

Thanks, so it means need to change the structure of tacotron2 by adding a speaker embedding layer? Is there any doc about how to change it?

**Comment by TheHonestBob** [comment]
> > https://github.com/clovaai/voxceleb_trainer
> 
> Thanks, so it means need to change the structure of tacotron2 by adding a speaker embedding layer? Is there any doc about how to change it?

I think that ur just modify inference func by tf.add() or other way.
