### ISSUE TITLE
 "from tensorflow_tts.inference" -> AlreadyExistsError: Another metric with the same name already exists.

### ISSUE THREAD

**Issue by SinaArdehali** [TensorSpeech/TensorFlowTTS#706]
@samuel-lunii  I cannot run the french colab file "E2E-TensorflowTTS-Synpaflex.ipynb", since the imports "from tensorflow_tts.inference " create the error:

AlreadyExistsError: Another metric with the same name already exists.

After searching on the web, it seems like this is a version error, but i cannot manage to solve it.

**Comment by zb121** [comment]
You can go to the setup.py file,change the line 25 `tensorflow-gpu==2.6.0`  to `tensorflow-gpu==2.6.2` ,and I only change this config and then the AlreadtExistsError disappear.

**Comment by godspirit00** [comment]
Or `pip install keras==2.6.0`
