### ISSUE TITLE
how to set the mbmelgan's parameters

### ISSUE THREAD

**Issue by hertz-pj** [TensorSpeech/TensorFlowTTS#710]
if i want to train by the wav with "sampling_rate=16k, hop_size=200，win_size=800"。
The mbmelgan's parameters i set upsampling_scale=[2,5,5].
Do i need to set downsample_scale=[2,5,5]？
Or keep [4,4,4] unchanged?

**Comment by ZDisket** [comment]
@hertz-pj 
I've trained mb-melgan on many different sampling rates and got good results without changing the downsample scales, so I believe you should keep it as-is. But if you do have the spare time and compute feel free to experiment; who knows, you might just discover something!
