### ISSUE TITLE
training mb_melgan with baker gets noise at the end of sample

### ISSUE THREAD

**Issue by ttsking** [TensorSpeech/TensorFlowTTS#713]
when i train the mb_melgan with baker dataset (offical or my own dataset), i found if there has silence at the end of sample, then the result become noise.

for example:
![b'7094'-marked](https://user-images.githubusercontent.com/74232385/144259231-dfd780d2-3d20-4dec-8d3e-618edd757a3b.png)
and:
![b'7849'-marked](https://user-images.githubusercontent.com/74232385/144259232-feb6f53a-0e8b-4f7a-abf4-a4a9dac79acd.png)

This issue won't affact the silence in middle:
![b'6887'](https://user-images.githubusercontent.com/74232385/144259290-cea610c6-362f-41ff-ab96-2a2620c801e1.png)

i use the standard baker_preprocess.yaml with "trim_silence: true"
Is there any thing can be done to improve the results?

**Comment by dathudeptrai** [comment]
@ttsking It is not a problem in a real inference process since you know the length of the mel then you know exactly the length of audio generated then you can remove these noises at the end (the noise you hear corresponding to a padding mel in training)

**Comment by ttsking** [comment]
Ok, Thanks for your comments.
