### ISSUE TITLE
Install Error (Could not build wheels for pyworld wich use PEP 517 and cannot be installed directly)

### ISSUE THREAD

**Issue by NiklasBrandstaeter** [TensorSpeech/TensorFlowTTS#718]
I have tried to install TensorFlowTTS on Ubunutu 18.04 with Python 3.7. But I got the Error from the topic.
I have also tried to install TensorFlowTTS on Ubuntu 20.04 with Python 3.8. After installing and importing tensorflow, the process finished with exit code 132 (interrupted by signal 4: SIGILL).

**Comment by dathudeptrai** [comment]
@ZDisket do you have any idea ?
