### ISSUE TITLE
Spanish models

### ISSUE THREAD

**Issue by nahuelproietto** [TensorSpeech/TensorFlowTTS#722]
Hello, I tried the _default english pre-trained model_ on cpptflite example and sounds fine, really nice work.
I want to know if any of you has trained some spanish dataset to tell me about the experience. Thanks!

**Comment by dathudeptrai** [comment]
@nahuelproietto we have not trained any Spanish model before

**Comment by dathudeptrai** [comment]
@nahuelproietto we have not trained any Spanish model before

**Comment by ZDisket** [comment]
@nahuelproietto I have trained a few Spanish models, the process is simple but I haven't made time to formally contribute it.

**Comment by nahuelproietto** [comment]
sounds good. I'm going to try it.
