### ISSUE TITLE
Debian 11 Installation

### ISSUE THREAD

**Issue by Hierosme** [TensorSpeech/TensorFlowTTS#727]
Hello,

pip install Instructions not work at all due to llvm installation and unfortunally after one hour of researh i simply not understand how install TensorFlowTTS.

LLVM version... 11.0.1
....
RuntimeError: Building llvmlite requires LLVM 7.0+ Be sure to set LLVM_CONFIG to the right executable path.
Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

I have follow llvm installation instruction without succes

Anyone have test installation on Debian 11 ?
Someone know if  documentation better as a simple 'pip install' exist ?

TensorFlowTTS installation look ultra complexe and the documentation don't reflet that ....

Regards

**Comment by psalajka** [comment]
Hello,

I'd like to report the same issue with Ubuntu 21.10 . It looks like the main problem is that there are no pre-compiled `llvmlite` binaries for Python 3.9 (current default) and `llvmlite==0.31` needs LLVM==8 for compilation, which is not available (9 and 13 are).

I Installed **Python 3.8** (by [this recipe](https://askubuntu.com/questions/1261775/why-i-cant-install-python-3-8)) and everything looks OK again.
I still need to test a few more things but it looks promising.

See below the installation recipe I used last time.

------------------------------------------------------------------------------------------------------------------------------------
From my readme:

## Installation

Install the package with the following command. This way, you'll have
all useful "binaries" (e.g. `tensorflow-tts-preprocess`) and any changes
to the code will take effect immediately as well.
```
pip install --upgrade --editable .
```

Continue with installing `german_transliterate` (from `dockerfile`):
```
pip install git+https://github.com/repodiac/german_transliterate.git#egg=german_transliterate
```

Then, I only needed to fix `numpy` and `h5py` versions:
```
pip install --upgrade numpy~=1.19.2
pip install --upgrade h5py~=3.1.0
```
