### ISSUE TITLE
Extract duration from tacotron2 model

### ISSUE THREAD

**Issue by linhld0811** [TensorSpeech/TensorflowTTS#73]
I don't send any issue to this comment. Following to the tutorial in training model fastspeech2, we have to extract the duration from alignment of tacotron2 model( on function get_duration_from_alignment on file extract_duration.py).
I just want to know what exactly of this term "duration". Anyone help me to figure out this definition?!

**Comment by l4zyf9x** [comment]
Character and Mel-spectrogram have different lengths, len(character)< len(mel). In fast speech, we mapping from characters to mel so each character will represent for a chunk mel and length of this chunk,  we call duration.

**Comment by linhld0811** [comment]
I have a question: Can i use time alignment( duration in ms of each phoneme which is extracted by kaldi) for transform to duration format that you use for training fastspeech?!

**Comment by azraelkuan** [comment]
@linhld0811 yes, but you should use the same phoneme in tts as you use in kalid.
