### ISSUE TITLE
Italian models

### ISSUE THREAD

**Issue by grausof** [TensorSpeech/TensorFlowTTS#730]
Hello, I'm trying to train the model also for Italian language and I would like to use the [MLS dataset](http://www.openslr.org/94/) which always derives from LibriVox. My question is whether I have to use a single speaker in the dataset, or can I use more than one. Also I ask you if you have already tried this dataset! Thanks

**Comment by ZDisket** [comment]
@grausof You probably want to try single speaker first. You can try multiple speakers but you'll have to modify the dataloader and Tacotron2 multispeaker seems broken, as it failed to learn attention at all during all my experiments, which I think is the fault of adding speaker embeddings to both encoder and decoder, keith ito's implementation only has them on the encoder.
