### ISSUE TITLE
preprocessing

### ISSUE THREAD

**Issue by xxoospring** [TensorSpeech/TensorflowTTS#74]
why it loop again and again?
this is the command line i use as the readme instruction:
```
tensorflow-tts-preprocess --rootdir /workspace/proj/FastSpeech-exp/data/LJSpeech --outdir ./dump/ --conf preprocess/ljspeech_preprocess.yaml --n_cpus 1
```
![image](https://user-images.githubusercontent.com/21218850/86208494-3fa40a80-bba3-11ea-967b-0324023369a5.png)
when processed about 20%， it seems loop back and start from scratch again

**Comment by dathudeptrai** [comment]
@xxoospring because i use multi-processing :))), so the visualize looks a bit confuse haha :D but it's right behavior =)).

**Comment by xxoospring** [comment]
> @xxoospring because i use multi-processing :))), so the visualize looks a bit confuse haha :D but it's right behavior =)). I found that even you set n_cpu = 1 it's still use all CPU =))))))), that is a bug of the multiprocess library :(

Thanks for your quick reply. So, when should I stop?, or just ignore it and wait till the process finish?

**Comment by dathudeptrai** [comment]
@xxoospring wait till the process finish :)))
