### ISSUE TITLE
Fastspeech Data preparation--- How to extract duration (duration_query (str): Query to find duration files in root_dir.)

### ISSUE THREAD

**Issue by jeevan-revaneppa-hirethanad** [TensorSpeech/TensorFlowTTS#746]
I'm unable to understand how to get **'duration_query (str): Query to find duration files in root_dir',** while **preparing data** for training a **fast speech** model. It would be helpful if someone could suggest me how to proceed.

**Comment by ttsking** [comment]
you should first train a model of Tacotron2. then use the script of  [extract_duration.py] (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/extract_duration.py) to generate duration files
