### ISSUE TITLE
tensorflow-tts-preprocess: command not found

### ISSUE THREAD

**Issue by JHuang251998** [TensorSpeech/TensorFlowTTS#747]
Hello all, I have the ljspeech dataset and I want to run it through the preprocessing step, but whenever I run the tensorflow-tts-preprocess command it shows that the command is not found. Can someone help me? 

Thank you in advance!

**Comment by neso613** [comment]
@JHuang251998  tensorflow-tts-preprocess maps with tensorflow_tts/bin/preprocess.py

You can use commands -
`python3 tensorflow_tts/bin/preprocess.py--rootdir ./ljspeech --outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
`

**Comment by 912602337** [comment]
> [@JHuang251998](https://github.com/JHuang251998) tensorflow-tts-preprocess 与 tensorflow_tts/bin/preprocess.py 映射
> 
> 您可以使用命令 - `python3 tensorflow_tts/bin/preprocess.py--rootdir ./ljspeech --outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech `

tensorflow-tts-normalize: command not found
