### ISSUE TITLE
Bad cases or artifacts for Tacotron2 + Melgan vocoder, Any suggestions?

### ISSUE THREAD

**Issue by GuangChen2016** [TensorSpeech/TensorFlowTTS#753]
I have trained a Melgan vocoder using my own data, but when its used for end-to-end TTS, some of the synthesized results (about 3% utterances）has some artifacts (noise). In details, the mel-spectrum in corresponding ares discontinuous, shown as follows:
![LEEGHJGKZO(@0@F51_LO$XL](https://user-images.githubusercontent.com/23181283/159263605-8a380b78-ba29-4524-bb26-8e8ccbbda895.png)
Any suggestions to improve the this?

**Comment by dathudeptrai** [comment]
@GuangChen2016 can you share your model training config and your data information?

**Comment by GuangChen2016** [comment]
I use default config with upsample_scales of [8 8 2 2], stacks number 4 and set weight norm to be false for both generator and discriminator. 
And I use multi-resoluation stft loss for generator. 
Data: samplerate 24Khz, hopsize 256.
