### ISSUE TITLE
如何添加停顿？

### ISSUE THREAD

**Issue by watersoft123** [TensorSpeech/TensorFlowTTS#758]
我在CSDN上看到一篇文章，通过链接找到这里。文章提到为了使音频人性化，可以添加#3停顿。请问这个是手动添加，还是有一个类似字典的文件自动添加？是否有示例可供参考？谢谢！

**Comment by MichalKrass** [comment]
哪篇CSDN文章发一下？

**Comment by watersoft123** [comment]
> 哪篇CSDN文章发一下？

我也忘了地址了，不过那篇文章写的就是你的这个TTS，我按着文章里的链接才找到Github。你也可以看看https://zhuanlan.zhihu.com/p/319978933

**Comment by MichalKrass** [comment]
> 我在CSDN上看到一篇文章，通过链接找到这里。文章提到为了使音频人性化，可以添加#3停顿。请问这个是手动添加，还是有一个类似字典的文件自动添加？是否有示例可供参考？谢谢！

This module is missing, you need to add it yourself
