### ISSUE TITLE
Fastspeech2 training error : Not found any mels files in $./dump_ljspeech/train/.

### ISSUE THREAD

**Issue by neso613** [TensorSpeech/TensorFlowTTS#759]
Hi all,
I have just started learning TTS model building. I am trying to train fastspeech2 model using ljspeech dataset.
For that, I have donwloaded ljspeech dataset and run folllowing commands  -
`tensorflow-tts-preprocess --rootdir ./ljspeech --outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
`
![image](https://user-images.githubusercontent.com/31642462/166681715-bc3fdeb7-fd03-4be7-b8c8-c1cd285677bd.png)

`tensorflow-tts-normalize --rootdir ./ljspeech --outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
`
![image](https://user-images.githubusercontent.com/31642462/166681806-2220adfd-1521-49c9-b7ee-aa6a3228713c.png)

> norm-feats folder created but have no items in it.

Following commands used to start training -
`CUDA_VISIBLE_DEVICES=0 python examples/fastspeech2/train_fastspeech2.py \
>   --train-dir ./dump_ljspeech/train/ \
>   --dev-dir ./dump_ljspeech/valid/ \
>   --outdir ./examples/fastspeech2/exp/train.fastspeech2.v1/ \
>   --config ./examples/fastspeech2/conf/fastspeech2.v1.yaml \
>   --use-norm 1 \
>   --f0-stat ./dump_ljspeech/stats_f0.npy \
>   --energy-stat ./dump_ljspeech/stats_energy.npy \
>   --mixed_precision 1 \
>   --resume ""
`
But end up with this error-

![image](https://user-images.githubusercontent.com/31642462/166682378-2514de3b-f19c-4275-81ca-fc2f97a4a8d0.png)

Why training is failing? @dathudeptrai @ZDisket

**Comment by neso613** [comment]
looking forward to hearing from the team and community.

**Comment by neso613** [comment]
@dathudeptrai can you pls share your thoughts on this.

**Comment by neso613** [comment]
@machineko @erogol pls help me in this regard.

**Comment by mmseerrttt** [comment]
@neso613 I also encountered the same problem, but with tacotron2. have you solved it.

**Comment by mmseerrttt** [comment]
you can try 
```
tensorflow-tts-preprocess --rootdir ./ljspeech --outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
tensorflow-tts-normalize --rootdir ./dump_ljspeech --outdir ./dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
```
