### ISSUE TITLE
A couple of questions regarding pre-processing.

### ISSUE THREAD

**Issue by jun-danieloh** [TensorSpeech/TensorflowTTS#76]
1. Could you add short details regarding for each directories? What's ids, raw-feats and so on? Also, could you point any references regarding these if you have any?
```
|   |- train/
|       |- ids/
|           |- LJ001-0001-ids.npy
|           |- ...
|       |- raw-feats/
|           |- LJ001-0001-raw-feats.npy
|           |- ...
|       |- raw-f0/
|           |- LJ001-0001-raw-f0.npy
|           |- ...
|       |- raw-energies/
|           |- LJ001-0001-raw-energy.npy
|           |- ...
|       |- norm-feats/
|           |- LJ001-0001-norm-feats.npy
|           |- ...
|       |- wavs/
|           |- LJ001-0001-wave.npy
```

2. I am running tacotron2 with my own wav files. My own metadata.csv has only two columns as below. Text are normalized so there are no numbers.
```
filename | text
```
However, I noticed that metadata.csv of LJSpeech has 3 columns as below. Is 2nd column(unnormalized text) of metadata.csv used while pre-processing?
```
filename | unnormalized text | text
```

Thanks in advance!

**Comment by azraelkuan** [comment]
for 1:
check https://github.com/TensorSpeech/TensorflowTTS/blob/cabca9f9d656928e580c156718a6f655e987766e/tensorflow_tts/bin/preprocess.py#L279-L307
ids : text id
raw-feats: acoustic feature like mel spec
norm-feats: normliazed feature like mean-std norm
 energies and f0: please check fastspeech2 paper

for 2:
we should use normalized text: check here: https://github.com/TensorSpeech/TensorflowTTS/blob/cabca9f9d656928e580c156718a6f655e987766e/tensorflow_tts/processor/ljspeech.py#L136
u can use `awk` to add a fake text to your metadata: filename | fake text | normlized text | or just modify the code

**Comment by jun-danieloh** [comment]
You are awesome! Thanks :)
