### ISSUE TITLE
Getting requirements to build wheel did not run successfully

### ISSUE THREAD

**Issue by ADNDiouf** [TensorSpeech/TensorFlowTTS#761]
Hi everybody, 
I'm trying to install TensorFlowTTS usiing pip and git clone however I'm encountering a problem and I don't know how to solve it !
Can you help me please ?
<img width="761" alt="problem_tensorflowtts" src="https://user-images.githubusercontent.com/72380431/168256652-3bc8a395-c28b-4cca-b2ae-bbc05e6fffab.PNG">

**Comment by XsNizx** [comment]
try to run  `apt-get install cmake`

**Comment by DiniMuhd7** [comment]
Try running pip install wheel setuptools pip --upgrade
