### ISSUE TITLE
Longer Chinese sentences use fastspeech2 to synthesize exceptions

### ISSUE THREAD

**Issue by lawo123** [TensorSpeech/TensorFlowTTS#771]
Longer Chinese sentences use fastspeech2 to synthesize exceptions.
TEXT:在一个拥有 2500 万人口的不发达且以孤立着称的国家，绝大多数人被认为没有接种疫苗，它有可能成为一场规模巨大的人道主义灾难，威胁到几乎任何政府的权力控制 在世界上。
WAVE：[2.zip](https://github.com/TensorSpeech/TensorFlowTTS/files/9138051/2.zip)

@dathudeptrai

**Comment by qxde01** [comment]
1、例子中的baker没有做标点断句等处理，需要自己修改baker.py
2、baker数据句子都不长，对于长句的位置向量效果不佳，需做额外的后处理

**Comment by lawo123** [comment]
感谢您的回复。那长句的位置向量效果不好怎么做后处理解决这个问题呢？

**Comment by qxde01** [comment]
@lawo123 要把#1#2#3韵律以及标点加进去训练，简单的后处理先切分句子合成再语音拼接

**Comment by Tian14267** [comment]
请问你有用aishell3做训练和合成吗？我出来的结果很差哎。请问你们效果如何
