### ISSUE TITLE
Ukrainian TTS

### ISSUE THREAD

**Issue by egorsmkv** [TensorSpeech/TensorFlowTTS#772]
Hello.

If I will publish a high-quality dataset (around 8 hours of speech) for Ukrainian, then you can make a processor for it?

**Comment by hlp-ai** [comment]
Processor is highly related to speech corpus. So, in order to preserve generality, the project would implement the processors for those common datasets. A simple way is to make your dataset compatible with those common datasets, and you can directly make use of the existing processors.

**Comment by egorsmkv** [comment]
I have seen code for processors and in my opinion it's easy to write own one. 

Your advice about common format is right, fully support it.

**Comment by egorsmkv** [comment]
The dataset is here - https://github.com/egorsmkv/ukrainian-tts-datasets/tree/main/lada
