### ISSUE TITLE
not working with large text.

### ISSUE THREAD

**Issue by avraamya** [TensorSpeech/TensorFlowTTS#777]
i want to use large text with fastspeech, but as i understand in need to change the configs. i not able to find the exact place to make change in order to make in work. i try to change some parameter in configs files, but it not working for me. which file and which parameter exactly i need to change?

mels, audios = do_synthesis(input_text, fastspeech, mb_melgan, "FASTSPEECH", "MB-MELGAN")

but i got error:

InvalidArgumentError: indices[0,2048] = 2049 is not in [0, 2049)
[[node decoder/position_embeddings/Gather
(defined at /usr/local/lib/python3.7/dist-packages/tensorflow_tts/models/fastspeech.py:76)
]] [Op:__inference__inference_63215]

Errors may have originated from an input operation.
Input Source operations connected to node decoder/position_embeddings/Gather:
In[0] decoder/position_embeddings/Gather/resource:
In[1] mul_1 (defined at /usr/local/lib/python3.7/dist-packages/tensorflow_tts/models/fastspeech.py:872)

**Comment by francis-ohara** [comment]
Also facing the same issue. Would appreciate if it were fixed.
