### ISSUE TITLE
Support Arabic Language

### ISSUE THREAD

**Issue by Muhammad-Abdelsattar** [TensorSpeech/TensorFlowTTS#781]
Are you open to support Arabic language? you can use Dr.Nawar Halabi dataset :https://www.kaggle.com/datasets/bc297d8ca0753cd21cdcacd7bd324c0c607361a14471c801f09b028a1ecb098e

**Comment by ahmedalbahnasawy** [comment]
@Muhammad-Abdelsattar Its easy to support Arabic language. I got an Arabic model but not Nawar Halbi. If you could prepare the data and clean i can start the Training (Tacotron + FS2)
