### ISSUE TITLE
Preprocessing error with ljspeech

### ISSUE THREAD

**Issue by LxtteDev** [TensorSpeech/TensorFlowTTS#786]
When preprocessing, I am getting a new error: `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`. I dont think the error has nothing to do with an amount of files. I removed some .wav's and also tried adding some to no avail. I am using the **preprocess\ljspeech_preprocess.yaml** config and **ljspeech** dataset.

**Comment by ahmedalbahnasawi** [comment]
what version of numpy you using? i think upgrading numpy would solve the issue.

**Comment by LxtteDev** [comment]
I am using numpy `1.21.6` but I dont want to upgrade because I am using tensorflow `2.6`. If I upgrade, tensorflow also gets upgraded.

**Comment by LxtteDev** [comment]
I tried upgrading it. Nothing changed. Still getting the same error.

**Comment by ahmedalbahnasawi** [comment]
`pip install TensorFlowTTS==1.8`
i am using tf-gpu 2.6 and numpy 1.19.5. let me know if it works ?

**Comment by DannyP0** [comment]
@LxtteDev  use pyworld < 0.3.2, e.g pip install pyworld==0.3.1
