### ISSUE TITLE
Android release as TTS engine

### ISSUE THREAD

**Issue by paolo-caroni** [TensorSpeech/TensorFlowTTS#792]
I have seen that there is an Android example release, on android API there is [TTS engine](https://developer.android.com/reference/android/speech/tts/TextToSpeech), so every app can use a specific engine selected by the user.
FOSS TTS engine on Android actually are eSpeak-ng and (only for less languages) RHVoice, that sounds very robotic.
The default TTS engine on most device is [Google TTS (actually Speech Services by Google)](https://play.google.com/store/apps/details?id=com.google.android.tts) that send text to google and receive vocal message (so orrible for privacy).
The provided android axample crash at start on my emulator and also is NOT listed as TTS engine.
Since there is [Common Voice Dataset](https://www.tensorflow.org/datasets/catalog/common_voice?hl=en) (I cooperate on it for my mother language) your project can change considerably the situation of TTS engine on Android.
There is any plan to release an app that run as TTS engine on Android?
Would you consider it?

Cheers,
Paolo

**Comment by inconnu26** [comment]
Dear Paolo, I agree completely. Having this easily implementable on Android is very important, especially with the arrival of GPT Models. Hopefully you will get a reply.

**Comment by mapledxf** [comment]
The Android TTS Engine is a system App. You cannot replace it unless you have the root permission.

**Comment by paolo-caroni** [comment]
> The Android TTS Engine is a system App. You cannot replace it unless you have the root permission.

Please @mapledxf don't spread incomplete/incorrect information.
It is possible install multiple tts engine app on android and set what to use, I'm using espeak-ng at the moment, that is a user installed app and not an system app.
I don't have rooted nothing obviously.

**Comment by paolo-caroni** [comment]
Just to clarify to @mapledxf what I mean.

![Screenshot_20230627_135000](https://github.com/TensorSpeech/TensorFlowTTS/assets/2750264/adadc533-a699-4161-bbf8-daf3dee5a586)

**Comment by mapledxf** [comment]
yeah, my bad. i did some research. just make the apk as a service should be work. :)

**Comment by paolo-caroni** [comment]
> yeah, my bad. i did some research. just make the apk as a service should be work. :)

To me it seems not simple, as specified on my first post the example app crash on my emulator, also make the apk as a service will change the code somewhere. I'm not an android developer, I can help with testing, donate my voice, design icon or (if asked) giving pocket money to who write and maintain the code.
