### ISSUE TITLE
Train with another dataset

### ISSUE THREAD

**Issue by GitVHV** [TensorSpeech/TensorFlowTTS#793]
How to create dataset for training. Can you give more detailed instructions? Looking forward to your feedback. Thank u so much.

**Comment by paolo-caroni** [comment]
Hi, I've not tried yet,
but it seems pretty simple to me, see [prepare dataset](https://github.com/TensorSpeech/TensorFlowTTS#prepare-dataset).
As mentioned is a [LJSpeech-like](https://keithito.com/LJ-Speech-Dataset/) format.
