### ISSUE TITLE
What do you think about FastPitch ?

### ISSUE THREAD

**Issue by Yablon** [TensorSpeech/TensorflowTTS#91]
I found that NVIDIA released a paper named [FastPitch: Parallel Text-to-speech with Pitch Prediction](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/FastPitch).

Do you have any plan to try and release some samples to compare with tacotron based models and fastspeech ?

**Comment by dathudeptrai** [comment]
@Yablon samples here https://tensorspeech.github.io/TensorflowTTS/. FastSpeech2 ~ Tacotron2

**Comment by Yablon** [comment]
@dathudeptrai Thank you for your quick relpy !

**Comment by dathudeptrai** [comment]
@Yablon i think u have trained some **FastPitch** model, hope you can make some comments after hear our samples :). Note that nvidia use **Waveglow** which is much lower and larger compared with our **Mb-Melgan**.

**Comment by Yablon** [comment]
@dathudeptrai Yes, I have trained the FastPitch model using NVIDIA repo and its recommended parameters, here are some audio samples. The vocoder is their pretrained WaveGlow.
[wavs_devset10-150.zip](https://github.com/TensorSpeech/TensorflowTTS/files/4876889/wavs_devset10-150.zip)

Following is audio samples from this repo,
[fastspeech2.100k.zip](https://github.com/TensorSpeech/TensorflowTTS/files/4876896/fastspeech2.100k.zip)

Both of the two models are trained on same LJSpeech Dataset. Sample rate is the same, 22050Hz.

I think that FastPitch samples is better than FastSpeech2 in the sense of audio quality. The shortage may come from the difference of the WaveGlow and MelGan vocoder. 

What is your opinion ?

**Comment by dathudeptrai** [comment]
@Yablon yeah, waveglow is better than mb-melgan. It's much larger and much slower too. BTW, can you generate **FastPitch + Waveglow** samples same as my samples on my demo page ? (https://tensorspeech.github.io/TensorflowTTS/) (pls see the FastSpeech-2 samples (BBC news) section)

**Comment by Yablon** [comment]
@dathudeptrai Okay, I will generate them later.

**Comment by dathudeptrai** [comment]
@Yablon can you update :))

**Comment by Yablon** [comment]
@dathudeptrai Oh，I will update today

**Comment by Yablon** [comment]
[wavs_tts_1500.zip](https://github.com/TensorSpeech/TensorflowTTS/files/4929189/wavs_tts_1500.zip)

Finally I got this. 

The model was trained with code of this [repo](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/FastPitch) for 1500 epochs using LJSpeech-1.1 data as the repo recommended.

**Comment by dathudeptrai** [comment]
@Yablon thanks, i think it's comparable. Seem that FastSpeech2 produce better mel than FastPitch but waveglow reconstruct audio better than mb-melgan.
