### ISSUE TITLE
Extract Durations Tacotron2 with reduction_factor > 1

### ISSUE THREAD

**Issue by vikrantsharma7** [TensorSpeech/TensorflowTTS#92]
Facing `AssertionError: different between sum_durations and len_mel` when using `reduction_factor` > 1.
[https://github.com/TensorSpeech/TensorflowTTS/blob/master/examples/tacotron2/extract_duration.py#L179](https://github.com/TensorSpeech/TensorflowTTS/blob/master/examples/tacotron2/extract_duration.py#L179)
Although it works fine with `reduction_factor` = 1.
Are there any changes to be made for the same?
Thanks.

**Comment by dathudeptrai** [comment]
@vikrantsharma7 hi you cann't do that, duration is extracted from alignment which produces from Tacotron-2 with reduction_factor=1.

**Comment by vikrantsharma7** [comment]
@dathudeptrai thanks for the quick reply.
