### ISSUE TITLE
Unnecessary lines in example inference Colab notebook

### ISSUE THREAD

**Issue by ZDisket** [TensorSpeech/TensorflowTTS#94]
I found these two lines in the [official E2E demo](https://colab.research.google.com/drive/1akxtrLZHKuMiQup00tzO2olCaN-y3KiD?usp=sharing#scrollTo=mT1B4yaVfR-V) that are unnecessary, in the setup cell:
```
!pip install samplerate pysndfx
!apt install sox
```
As shown in [my notebook](https://colab.research.google.com/drive/109UhmWq00XaNN1gZuiHEybp1AlZfdb-d?usp=sharing), which I assume they were copied from, those installations are for post-processing of the audio output. By upsampling to 48k and treble boosting the output we can get it to sound clearer.

But I see no such step in the official notebook, so there they're just wasting time. The notebook works just fine without them.

**Comment by dathudeptrai** [comment]
thanks :D, you are right :D
