### ISSUE TITLE
 max_mel_length = tf.reduce_max(mel_length) if self.config["use_fixed_shapes"] is False else [                 self.config["max_mel_length"]]

### ISSUE THREAD

**Issue by Hongpeng1992** [TensorSpeech/TensorflowTTS#95]
max_mel_length = tf.reduce_max(mel_length) if self.config["use_fixed_shapes"] is False else [                 self.config["max_mel_length"]]

Hi,  in config ,  did not get  max_mel_length 

Thank you!

**Comment by dathudeptrai** [comment]
@Hongpeng1992 https://github.com/TensorSpeech/TensorflowTTS/blob/master/examples/tacotron2/train_tacotron2.py#L513-L514. It will compute max mel/char length automatically base on ur dataset then update it into config.

**Comment by Hongpeng1992** [comment]
Thank you !
