### ISSUE TITLE
pad() missing 1 required positional argument: 'mode'

### ISSUE THREAD

**Issue by Mingrg** [TensorSpeech/TensorflowTTS#96]
In examples/fastspeech2/fastspeech2_dataset.py, line 33.

> durs_cum = np.cumsum(np.pad(durs, (1, 0)))

I got an error like：

> pad() missing 1 required positional argument: 'mode'

Seem like I used the wrong version of numpy or something? How should I pad in this situation?
My numpy version is 1.16.4.

**Comment by dathudeptrai** [comment]
my numpy version is 1.18.1

**Comment by MingRuigang** [comment]
> my numpy version is 1.18.1

thx! I found that in version 1.18, "mode" uses "constant" by default.

I changed the code to:

> durs_cum = np.cumsum(np.pad(durs, (1, 0), mode='constant'))

In numpy version 1.16.4 and it wored.
