### ISSUE TITLE
preprocess input

### ISSUE THREAD

**Issue by linhld0811** [TensorSpeech/TensorflowTTS#97]
I have a question about the preprocess of input for training fastspeech2.
as i know, for improve performance of tacotron2 model(based on the implement of NVIDIA), the text need add the character BOS(begin of sentences), EOS(end of sentences) and the wav(after strim silence) adding 5 frame to the end.
In your implement, i don't find anywhere you add that on text or wav?!
In the symbols, i find the character _eos = "~", but i do not see that again. What is the clue for model can use for predict end of the sentences?!

**Comment by dathudeptrai** [comment]
@linhld0811 https://github.com/TensorSpeech/TensorflowTTS/blob/master/examples/tacotron2/tacotron_dataset.py#L198-L199. Everything is on generator function.

**Comment by linhld0811** [comment]
Sorry for my shortcoming. Can i delete the character space ( 11th in ur symbols) when convert input_text to idx for training?!

**Comment by dathudeptrai** [comment]
@linhld0811 no, you can't delete space charactor.

**Comment by linhld0811** [comment]
i wonder why fastspeech2 model dont need the eos character. maybe due to that fastspeech2 is non-autoregressive, is that right?!

**Comment by dathudeptrai** [comment]
yes
